### ISSUE TITLE
始终没搞懂这个的原理

### ISSUE THREAD

**Issue by buzai** [shadowsocks/ShadowsocksX-NG#1003]
我的理解 ss-ng 启动后就可以对所有的 流量监控了，swift 是ui层，ss-local是代理协议层，但是如何hook系统的流量的呢还是说 ss-local 已经有了这个能力了呢，那ss-local是如何实现的呢，可以提供一下关键字么我去查查。

**Comment by ygmyth** [comment]
看一眼你网络设置--高级--代理

**Comment by buzai** [comment]
@ygmyth 谢谢
通过你的提示，我查到wiki 代理自动配置（英语：Proxy auto-config，简称PAC）是一种网页浏览器技术，用于定义浏览器该如何自动选择适当的代理服务器来访问一个网址。这个看解释是对 浏览器 ，它对普通软件也是这么生效的么

**Comment by ygmyth** [comment]
并不是 "ss-ng 启动后就可以对所有的 流量监控了", ss只是'被动'监听流量. '被动'的意思是其他应用软件配置了代理,把流量'主动'给ss.
你再看看ss-ng--偏好设置--高级 中的端口和地址, 打开PAC文件第一行,对比一下

**Comment by buzai** [comment]
@ygmyth 🙏谢谢我懂了
