### ISSUE TITLE
VPS疑似被ISP和运营商和谐了

### ISSUE THREAD

**Issue by dasonchan** [shadowsocks/ShadowsocksX-NG#1005]
大家好，新人一个，首先要感谢各位对SS的辛勤付出。

不知道各位有没有遇过类似的问题：
我和朋友共享一个VPS，我们都使用同样的设备（iPhone和MacBook）和服务器配置（我配置完直接分享给他）。唯一的区别就是运营商，他使用联通4g和电信宽带，而我是移动4g和广电宽带。
虽然他至今为止没有遇到什么问题，这两个星期以来我手机端（4G和WIFI）基本用不了，电脑端可以用一下但是不能持续很久，特别是在线看视频的时候很快就会被和谐了。

我尝试了新建VPS，更换端口都没有办法彻底解决。

请问各位对于这个问题有什么看法吗？先谢过大家了。

**Comment by lingan1996** [comment]
我也遇到类似的情况。我之前搭了一个ss，用的好好的，这两天来广州后就用不了，手机电脑都用不了。但在别的省市的同学还是可以使用我的ss，而且我使用别人的ss账号也能上google！但就是不能自己连上自己的vps。可以ping通，ip没被封。
有人知道这是什么原因吗

**Comment by shuijingy** [comment]
不用疑似；实锤。

**Comment by zhaipanyu** [comment]
> 不用疑似；实锤。换加密协议，端口号多试试。

现在shadowsocks官方网站都打不开了...怎么看个人信息哦

**Comment by fxtxz2** [comment]
https://shadowsocks.org/en/index.html

**Comment by yangnaihua** [comment]
确实是，之前朋友自己的也说用不了，结果过了几天，我自己的也用不了了。。。。。

**Comment by luvvien** [comment]
用 [vultr](https://vien.tech/article/114) ，被封就删服务器重新建就能换ip，现在还限时注册送50刀

**Comment by asheroin** [comment]
坐标广东，vultr的vps，实测教育网（有线）能ping通ip，搭建的ss，电脑端跟手机端都正常使用

但是切换到移动4g连接时，手机无法使用ss，电脑连接手机热点时，无法ping通上述的ip
