### ISSUE TITLE
Batch import from URLs/JSONs?

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/ShadowsocksX-NG#1007]
ShadowsocksX-NG currently seems to only support importing from a single URL at a time. This addition would be nice to share several servers at once.

**Comment by qiuyuzhou** [comment]
It support import multiple urls from clipboard from v1.8.0

Example:
```
ss://Y2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTpvcmRBaXRIYXMy@127.209.1.145:8088/?plugin=v2ray-plugin;#moon-v2ray
ss://YWVzLTEyOC1nY206dmF0WmVIYXJ2NA==@47.1.1.42:6443/?#HK
ss://YWVzLTEyOC1jZmI6dmF0WmVIYXJ2NA==@47.1.1.42:7443/?#HK-cfb
```

**Comment by qiuyuzhou** [comment]
I may add an import window with an input text box in future.

**Comment by gen** [comment]
I would like to request importing via JSON upload.

if importing via clipboard, is the format documented anywhere?

**Comment by Mygod** [comment]
It doesn't seem to work with shadowsocks-android exported URLs. Got `Not found valid shadowsocks server urls`.

**Comment by Mygod** [comment]
Actually it only works if only one server is added at a time, so I consider this issue not fixed at all.
