### ISSUE TITLE
运行无反应问题

### ISSUE THREAD

**Issue by chitonqd** [shadowsocks/ShadowsocksX-NG#1009]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by chitonqd** [comment]
不出现图形配置界面

**Comment by luvvien** [comment]
为什么不直接下载打包好的。。。 这是买的吗？推荐自己搭一个：[小白一键ss教程](https://vien.tech/article/122)  文章底部提供了各种下载方式
