### ISSUE TITLE
间歇性无法使用，过两分钟又好了

### ISSUE THREAD

**Issue by cuiguohua** [shadowsocks/ShadowsocksX-NG#1012]
**Describe the bug**
在PAC模式下（别的模式不清楚），有时会无法连接，差不多2分钟就又好了。

(手机上用的小火箭正常可用，说明节点是正常的)

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 10.14 Beta (18A365a)
 - Version 1.8.2 (1)

**Comment by dansaka** [comment]
我也要这个问题 同问

**Comment by misparking** [comment]
up

**Comment by dansaka** [comment]
我这个问题好了 不是shadowsocksX-Ng的问题，我之前用的是vultr外网服务器  我换一个外网服务器就好了，不用vultr了

**Comment by George520** [comment]
我也是，我用的是搬瓦工，换了个节点就好了

**Comment by cuiguohua** [comment]
很迷，我的节点是在Google Cloud上部署，之前提这个issue时：
mac上无法使用，但是手机上正常。
我也不知道是哪里出了原因，最近新增了一个ssr节点，使用了不常用的协议，似乎连不上的情况少了一些。
先这样吧。
