### ISSUE TITLE
Please upgrade the version of KCPTUN Client

### ISSUE THREAD

**Issue by hectorguo** [shadowsocks/ShadowsocksX-NG#1014]
I am using the docker container (https://hub.docker.com/r/mritd/shadowsocks) to host the shadowsocks and kcptun on the server side. But it seems that the version on the client side cannot match the one on docker. 

The latest version of kcptun is [v20190109](https://hub.docker.com/r/mritd/shadowsocks)
But the version of this client is [v20170718](https://github.com/shadowsocks/ShadowsocksX-NG/blob/aabdc77c3c4cb1187b2511d7fb239dcaf926c090/ShadowsocksX-NG/LaunchAgentUtils.swift#L12)

Please help to upgrade the version. Otherwise, it will not work with kcptun.

**Comment by tkisme** [comment]
#967 closed

**Comment by qiuyuzhou** [comment]
Already upgraded, release soon.

**Comment by zoulux** [comment]
@hectorguo kcptun is OK？
