### ISSUE TITLE
vps没有被河蟹但是mac无法fanqiang windows可以

### ISSUE THREAD

**Issue by coderloveryan** [shadowsocks/ShadowsocksX-NG#1019]
默认	14:19:27.336803 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.
错误	14:20:00.570009 +0800	ShadowsocksX-NG	Task <3771BF27-43AD-45ED-9231-3A3B2DCF7488>.<1> finished with error - code: -1001
默认	14:20:00.575037 +0800	ShadowsocksX-NG	TIC TCP Conn Cancel [1:0x600003e180c0]
默认	14:20:00.575137 +0800	ShadowsocksX-NG	[C1 Hostname#9b14e281:443 tcp, url: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, tls] cancel
错误	14:20:00.575129 +0800	ShadowsocksX-NG	Task <3771BF27-43AD-45ED-9231-3A3B2DCF7488>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-1001 "请求超时。" UserInfo={_kCFStreamErrorCodeKey=-2102, NSUnderlyingError=0x6000005668e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, _NSURLErrorFailingURLSessionTaskErrorKey=<private>, _NSURLErrorRelatedURLSessionTaskErrorKey=<private>, NSLocalizedDescription=请求超时。, NSErrorFailingURLStringKey=<private>, NSErrorFailingURLKey=<private>, _kCFStreamErrorDomainKey=4} [-1001]
默认	14:20:00.575184 +0800	ShadowsocksX-NG	[C1 Hostname#9b14e281:443 tcp, url: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, tls] cancelled
默认	14:20:00.575208 +0800	ShadowsocksX-NG	0.000s [C1 <private> Hostname#9b14e281:443 proxy] path:start
默认	14:20:00.575224 +0800	ShadowsocksX-NG	0.000s [C1 <private> Hostname#9b14e281:443 proxy] path:satisfied
默认	14:20:00.575242 +0800	ShadowsocksX-NG	0.000s [C1 <private> Hostname#9b14e281:443 proxy] proxy:start_process
默认	14:20:00.575257 +0800	ShadowsocksX-NG	0.000s [C1 <private> Hostname#9b14e281:443 proxy] proxy:finish_process
默认	14:20:00.575273 +0800	ShadowsocksX-NG	0.000s [C1 <private> Hostname#9b14e281:443 proxy] proxy:start_resolve
默认	14:20:00.575288 +0800	ShadowsocksX-NG	0.010s [C1 <private> Hostname#9b14e281:443 proxy] proxy:finish_resolve
默认	14:20:00.575403 +0800	ShadowsocksX-NG	0.010s [C1.1 <private> Hostname#9b14e281:443 resolver] path:start
默认	14:20:00.575471 +0800	ShadowsocksX-NG	0.010s [C1.1 <private> Hostname#9b14e281:443 resolver] path:satisfied
默认	14:20:00.575557 +0800	ShadowsocksX-NG	0.010s [C1.1 <private> Hostname#9b14e281:443 resolver] resolver:start_dns
默认	14:20:00.575592 +0800	ShadowsocksX-NG	0.075s [C1.1 <private> Hostname#9b14e281:443 resolver] resolver:receive_dns
默认	14:20:00.576464 +0800	ShadowsocksX-NG	0.075s [C1.1.1 <private> 192.168.0.134:50007<->IPv4#5444bdfb:443 socket-flow] path:start
默认	14:20:00.576519 +0800	ShadowsocksX-NG	0.075s [C1.1.1 <private> 192.168.0.134:50007<->IPv4#5444bdfb:443 socket-flow] path:satisfied
默认	14:20:00.576560 +0800	ShadowsocksX-NG	0.076s [C1.1.1 <private> 192.168.0.134:50007<->IPv4#5444bdfb:443 socket-flow] flow:start_connect
默认	14:20:00.576592 +0800	ShadowsocksX-NG	60.003s [C1] path:cancel
默认	14:20:00.576987 +0800	ShadowsocksX-NG	nw_endpoint_flow_protocol_disconnected [C1.1.1 IPv4#5444bdfb:443 cancelled socket-flow (null)] Output protocol disconnected
默认	14:20:00.577129 +0800	ShadowsocksX-NG	nw_connection_report_state_with_handler_locked [C1] reporting state cancelled
错误	14:20:00.577581 +0800	ShadowsocksX-NG	Task <3771BF27-43AD-45ED-9231-3A3B2DCF7488>.<1> HTTP load failed (error code: -999 [1:89])
默认	14:20:26.641992 +0800	ShadowsocksX-NG	Task <7A23E35F-1E58-4FAB-AD2E-C6CF05683C70>.<2> resuming, QOS(0x21)
默认	14:20:26.643293 +0800	ShadowsocksX-NG	Task <7A23E35F-1E58-4FAB-AD2E-C6CF05683C70>.<2> {strength 1, tls 8, ct 0, sub 0, sig 0, ciphers 1, bundle 0, builtin 0}
默认	14:20:26.643605 +0800	ShadowsocksX-NG	TIC Enabling TLS [2:0x600003e2de00]
默认	14:20:26.643670 +0800	ShadowsocksX-NG	TIC TCP Conn Start [2:0x600003e2de00]
默认	14:20:26.643841 +0800	ShadowsocksX-NG	[C2 Hostname#9b14e281:443 tcp, url: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, tls] start
默认	14:20:26.645223 +0800	ShadowsocksX-NG	nw_connection_report_state_with_handler_locked [C2] reporting state preparing
默认	14:20:26.645932 +0800	ShadowsocksX-NG	Task <7A23E35F-1E58-4FAB-AD2E-C6CF05683C70>.<2> setting up Connection 2
默认	14:20:26.646338 +0800	ShadowsocksX-NG	Sending CFNA PAC query
默认	14:20:26.647183 +0800	ShadowsocksX-NG	Received CFNA PAC response
默认	14:20:26.783476 +0800	ShadowsocksX-NG	nw_socket_handle_socket_event [C2.1.1:3] Socket received CONNECTED event
默认	14:20:26.783624 +0800	ShadowsocksX-NG	nw_endpoint_flow_protocol_connected [C2.1.1 IPv4#d850fa1c:443 in_progress socket-flow (satisfied)] Transport protocol connected
默认	14:20:26.785760 +0800	ShadowsocksX-NG	TIC TLS Event [2:0x600003e2de00]: 1, Pending(0)
默认	14:20:26.786000 +0800	ShadowsocksX-NG	TIC TLS Event [2:0x600003e2de00]: 2, Pending(0)
默认	14:20:26.904044 +0800	ShadowsocksX-NG	TIC TLS Event [2:0x600003e2de00]: 2, Pending(0)
默认	14:20:26.904165 +0800	ShadowsocksX-NG	TIC TLS Event [2:0x600003e2de00]: 11, Pending(0)
默认	14:20:26.904385 +0800	ShadowsocksX-NG	TIC TLS Event [2:0x600003e2de00]: 14, Pending(0)
默认	14:20:26.915892 +0800	ShadowsocksX-NG	System Trust Evaluation yielded status(0)
默认	14:20:26.922431 +0800	ShadowsocksX-NG	TIC TLS Trust Result [2:0x600003e2de00]: 0
默认	14:20:27.040498 +0800	ShadowsocksX-NG	nw_endpoint_flow_protocol_connected [C2.1.1 IPv4#d850fa1c:443 in_progress socket-flow (satisfied)] Output protocol connected
默认	14:20:27.040742 +0800	ShadowsocksX-NG	nw_connection_report_state_with_handler_locked [C2] reporting state ready
默认	14:20:27.041537 +0800	ShadowsocksX-NG	TIC TLS Event [2:0x600003e2de00]: 20, Pending(0)
默认	14:20:27.041646 +0800	ShadowsocksX-NG	TIC TCP Conn Connected [2:0x600003e2de00]: Err(16)
默认	14:20:27.041908 +0800	ShadowsocksX-NG	TIC TCP Conn Event [2:0x600003e2de00]: 1
默认	14:20:27.041999 +0800	ShadowsocksX-NG	TIC TCP Conn Event [2:0x600003e2de00]: 8
默认	14:20:27.042027 +0800	ShadowsocksX-NG	TIC TLS Handshake Complete [2:0x600003e2de00]
默认	14:20:27.042318 +0800	ShadowsocksX-NG	Task <7A23E35F-1E58-4FAB-AD2E-C6CF05683C70>.<2> now using Connection 2
默认	14:20:27.042541 +0800	ShadowsocksX-NG	nw_endpoint_flow_protocol_connected [C2.1.1 IPv4#d850fa1c:443 ready socket-flow (satisfied)] Output protocol connected
默认	14:20:27.042728 +0800	ShadowsocksX-NG	Task <7A23E35F-1E58-4FAB-AD2E-C6CF05683C70>.<2> sent request, body N
默认	14:20:27.156830 +0800	ShadowsocksX-NG	Task <7A23E35F-1E58-4FAB-AD2E-C6CF05683C70>.<2> received response, status 200 content K
默认	14:20:27.420055 +0800	ShadowsocksX-NG	Task <7A23E35F-1E58-4FAB-AD2E-C6CF05683C70>.<2> response ended
默认	14:20:27.420161 +0800	ShadowsocksX-NG	Task <7A23E35F-1E58-4FAB-AD2E-C6CF05683C70>.<2> done using Connection 2
默认	14:20:58.041041 +0800	ShadowsocksX-NG	TIC TCP Conn Cancel [2:0x600003e2de00]
默认	14:20:58.041147 +0800	ShadowsocksX-NG	[C2 Hostname#9b14e281:443 tcp, url: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, tls] cancel
默认	14:20:58.041298 +0800	ShadowsocksX-NG	[C2 Hostname#9b14e281:443 tcp, url: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt, tls] cancelled
	[C2.1.1 <private> 192.168.0.134:50037<->IPv4#d850fa1c:443]
	Connected Path: satisfied (Path is satisfied), interface: en5, ipv4, dns
	Duration: 31.397s, DNS @0.005s took 0.010s, TCP @0.018s took 0.121s, TLS took 0.257s
	bytes in/out: 75998/681, packets in/out: 54/3, rtt: 0.118s, retransmitted packets: 0, out-of-order packets: 0
默认	14:20:58.041349 +0800	ShadowsocksX-NG	0.000s [C2 <private> Hostname#9b14e281:443 proxy] path:start
默认	14:20:58.041377 +0800	ShadowsocksX-NG	0.000s [C2 <private> Hostname#9b14e281:443 proxy] path:satisfied
默认	14:20:58.041401 +0800	ShadowsocksX-NG	0.001s [C2 <private> Hostname#9b14e281:443 proxy] proxy:start_process
默认	14:20:58.041422 +0800	ShadowsocksX-NG	0.001s [C2 <private> Hostname#9b14e281:443 proxy] proxy:finish_process
默认	14:20:58.041443 +0800	ShadowsocksX-NG	0.001s [C2 <private> Hostname#9b14e281:443 proxy] proxy:start_resolve
默认	14:20:58.041464 +0800	ShadowsocksX-NG	0.003s [C2 <private> Hostname#9b14e281:443 proxy] proxy:finish_resolve
默认	14:20:58.041502 +0800	ShadowsocksX-NG	0.004s [C2.1 <private> Hostname#9b14e281:443 resolver] path:start
默认	14:20:58.041525 +0800	ShadowsocksX-NG	0.004s [C2.1 <private> Hostname#9b14e281:443 resolver] path:satisfied
默认	14:20:58.041546 +0800	ShadowsocksX-NG	0.005s [C2.1 <private> Hostname#9b14e281:443 resolver] resolver:start_dns
默认	14:20:58.041567 +0800	ShadowsocksX-NG	0.015s [C2.1 <private> Hostname#9b14e281:443 resolver] resolver:receive_dns
默认	14:20:58.041684 +0800	ShadowsocksX-NG	0.015s [C2.1.1 <private> 192.168.0.134:50037<->IPv4#d850fa1c:443 socket-flow] path:start
默认	14:20:58.041719 +0800	ShadowsocksX-NG	0.016s [C2.1.1 <private> 192.168.0.134:50037<->IPv4#d850fa1c:443 socket-flow] path:satisfied
默认	14:20:58.041773 +0800	ShadowsocksX-NG	0.018s [C2.1.1 <private> 192.168.0.134:50037<->IPv4#d850fa1c:443 socket-flow] flow:start_connect
默认	14:20:58.041853 +0800	ShadowsocksX-NG	0.139s [C2.1.1 <private> 192.168.0.134:50037<->IPv4#d850fa1c:443 socket-flow] flow:finish_transport
默认	14:20:58.041896 +0800	ShadowsocksX-NG	0.139s [C2.1 <private> Hostname#9b14e281:443 resolver] flow:finish_transport
默认	14:20:58.041952 +0800	ShadowsocksX-NG	0.139s [C2 <private> Hostname#9b14e281:443 proxy] flow:finish_transport
默认	14:20:58.042056 +0800	ShadowsocksX-NG	0.396s [C2.1.1 <private> 192.168.0.134:50037<->IPv4#d850fa1c:443 socket-flow] flow:finish_connect
默认	14:20:58.042094 +0800	ShadowsocksX-NG	0.396s [C2.1 <private> Hostname#9b14e281:443 resolver] flow:finish_connect
默认	14:20:58.042151 +0800	ShadowsocksX-NG	0.396s [C2 <private> Hostname#9b14e281:443 proxy] flow:finish_connect
默认	14:20:58.042221 +0800	ShadowsocksX-NG	0.397s [C2.1.1 <private> 192.168.0.134:50037<->IPv4#d850fa1c:443 socket-flow] flow:changed_viability
默认	14:20:58.042314 +0800	ShadowsocksX-NG	0.397s [C2.1 <private> Hostname#9b14e281:443 resolver] flow:changed_viability
默认	14:20:58.042402 +0800	ShadowsocksX-NG	0.397s [C2 <private> Hostname#9b14e281:443 proxy] flow:changed_viability
默认	14:20:58.042457 +0800	ShadowsocksX-NG	31.397s [C2] path:cancel
默认	14:20:58.043173 +0800	ShadowsocksX-NG	nw_endpoint_flow_protocol_disconnected [C2.1.1 IPv4#d850fa1c:443 cancelled socket-flow (null)] Output protocol disconnected
默认	14:20:58.043585 +0800	ShadowsocksX-NG	nw_connection_report_state_with_handler_locked [C2] reporting state cancelled
错误	14:21:10.236686 +0800	ShadowsocksX-NG	Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
错误	14:21:10.236817 +0800	ShadowsocksX-NG	Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
错误	14:31:43.923640 +0800	ShadowsocksX-NG	Unable to load Info.plist exceptions (eGPUOverrides)
默认	14:31:53.923986 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.

**Comment by nitafloooq** [comment]
我说来学习如何---,我的win  爬出去了, 用mac os 爬不出去. 请问是wifi 高级-socks代理输入端口127.0.0.1-1080  还是要偏好设置,监听设置下     有没有人帮助下

**Comment by Kunchao** [comment]
> 我说来学习如何---,我的win 爬出去了, 用mac os 爬不出去. 请问是wifi 高级-socks代理输入端口127.0.0.1-1080 还是要偏好设置,监听设置下 有没有人帮助下

我的也是win爬出去了，但是macos爬不出去，不知道该怎么设置

**Comment by nitafloooq** [comment]
是版本问题吧，我下载的shadowsockx-ng-r8版本解决了问题

**Comment by qiuyuzhou** [comment]
ShadowsocksX-NG is not support SSR server.

**Comment by liaozd** [comment]
btw, what is the SSR server?
