### ISSUE TITLE
HTTP代理设置问题

### ISSUE THREAD

**Issue by angelsinklowcn** [shadowsocks/ShadowsocksX-NG#102]
版本 1.3.1 (1)中设置HTTP代理，地址改完无法保存不管改成0.0.0.0还是我本地局域网地址都会变成127.0.0.1 而且端口监听也没看到打开

**Comment by qiuyuzhou** [comment]
改完先点下其他输入框，就会保存。

**Comment by qiuyuzhou** [comment]
输入框bind需要启用：continuously updates value
