### ISSUE TITLE
突然不能用了

### ISSUE THREAD

**Issue by yudongyy** [shadowsocks/ShadowsocksX-NG#1021]
之前可以用的，突然不能用了，这是为何，服务器是没有问题的

**Comment by antimonyGu** [comment]
me too.同一个服务器在ios能用，mac上不行。我快疯了

**Comment by antimonyGu** [comment]
curl --socks5 127.0.0.1:1086 ip.gs    
curl: (52) Empty reply from server
➜  ~ lsof -i :1086                     
COMMAND   PID      USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
ss-local  563 guzhizhou    6u  IPv4 0x813961cff0a81bd      0t0  TCP localhost:cplscrambler-lg (LISTEN)
ss-local 7396 guzhizhou    6u  IPv4 0x813961d021de4bd      0t0  TCP localhost:cplscrambler-lg (LISTEN)
ss-local 7396 guzhizhou    7u  IPv4 0x813961ce67a5b8d      0t0  UDP localhost:cplscrambler-lg
➜  ~ plutil -p ~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist | grep "ServerHost\|Password\|Method\|ServerPort\|ShadowsocksOn\|ShadowsocksRunningMode\|LocalSocks5"
  "LocalSocks5.EnableUDPRelay" => 1
  "LocalSocks5.EnableVerboseMode" => 1
  "LocalSocks5.ListenAddress.Old" => "127.0.0.1"
  "LocalSocks5.ListenPort.Old" => 1086
      "Method" => "aes-256-gcm"
      "Password" => "OGIyOWIxNT"
      "ServerHost" => "67.216.207.142"
      "ServerPort" => 443
      "Method" => "aes-256-cfb"
      "Password" => "TumFJB2b5w"
      "ServerHost" => "67.216.207.142"
      "ServerPort" => 8379
➜  ~ lsof -i :1086                                                  
COMMAND    PID      USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
ss-local   563 guzhizhou    6u  IPv4 0x813961cff0a81bd      0t0  TCP localhost:cplscrambler-lg (LISTEN)
Google    6885 guzhizhou   52u  IPv4 0x813961cfd8c04bd      0t0  TCP localhost:62068->localhost:cplscrambler-lg (ESTABLISHED)
ss-local  7396 guzhizhou    6u  IPv4 0x813961d021de4bd      0t0  TCP localhost:cplscrambler-lg (LISTEN)
ss-local  7396 guzhizhou    7u  IPv4 0x813961ce67a5b8d      0t0  UDP localhost:cplscrambler-lg
ss-local  7396 guzhizhou   10u  IPv4 0x813961d021957bd      0t0  TCP localhost:cplscrambler-lg->localhost:62068 (ESTABLISHED)

**Comment by uduse** [comment]
同问

**Comment by nullopp** [comment]
今天也是突然不能用了 卸载原来1.6.1的新装了最新版 OK了

**Comment by antimonyGu** [comment]
> > me too.同一个服务器在ios能用，mac上不行。我快疯了
> 
> 请问你现在搞定了吗？

没有，在路由上翻墙了，放弃折腾了。

**Comment by zhenghamu** [comment]
> > > me too.同一个服务器在ios能用，mac上不行。我快疯了
> > 
> > 
> > 请问你现在搞定了吗？
> 
> 没有，在路由上翻墙了，放弃折腾了。

要怎么做到……我的天，刚买了的一个ssxng突然就不能用了

**Comment by Aijunwei** [comment]
官网都打不开了https://portal.shadowsocks.ch/

**Comment by DOTANEIL** [comment]
Is it reliable to purchase service from portal.shadowsocks.ch?

**Comment by Justsoos** [comment]
你们这种没头没脑的提问方式，换成你，你想让别人怎么回答你？
