### ISSUE TITLE
内置的Privoxy 配置问题

### ISSUE THREAD

**Issue by zhuleilei** [shadowsocks/ShadowsocksX-NG#1025]
Mac上安装了额ShadowsocksX-NG ,开启了内置的HTTP代理,使用手动模式.

这时希望HTTP代理忽略一些域名的代理转发,所以在配置文件里加入了 
```
forward *.xxx.com/ .
```
但是,privoxy.conf 这个文件似乎是程序主动生成的,重启ShadowsocksX-NG 配置文件会重新生成,偏好设置中关闭开启HTTP代理,也会重新生成配置文件,那我如何在手动模式下,来对内置的Privoxy进行自定义的配置呢?

**Comment by qiuyuzhou** [comment]
Implementation in 79f5d8be5bd7b48f6233d20f51e9b663175826bc.
Release it later.
