### ISSUE TITLE
维护者放个支付宝二维码吧，这样修bug也有动力了

### ISSUE THREAD

**Issue by qingping209** [shadowsocks/ShadowsocksX-NG#1026]
有收费版的吗

**Comment by csc-EricWu** [comment]
怕是不敢放把， 怕被追踪啊

**Comment by KSMASTERS** [comment]
不敢放啊，这玩意一旦国内涉及到商业用途就完了

**Comment by SSSEN** [comment]
钓鱼的吧，放比特币地址都比这靠谱

**Comment by coooliang** [comment]
会被查水表

**Comment by michaelzhye** [comment]
> 钓鱼的吧，放比特币地址都比这靠谱

BTC只要涉及出入金或OTC一樣會被Tracking，除非放XMR之類的crypto currency才能保障安全，最作者或所有的committer注意安全。
