### ISSUE TITLE
global mode not working on Chrome running on Mac OS X 10.13.6

### ISSUE THREAD

**Issue by fenrei** [shadowsocks/ShadowsocksX-NG#1027]
**Describe the bug**
i'm on Mac OS X 10.13.6
simple thing, when i switch to Global mode, any website won't open on the Chrome browser.
but all website works fine on Safari

**To Reproduce**
fully setup ShasowsocksX-NG, switch to Global Mode
open Chrome and go to www.google.com

**Expected behavior**
i expected google.com appears.

**Screenshots**
no screenshots needed

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: mac os x 10.13.6
 - Version  1.4.4-R8 (1)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by weixie4** [comment]
echo here
