### ISSUE TITLE
并没有更新最新的gfwlist

### ISSUE THREAD

**Issue by longdeqidao** [shadowsocks/ShadowsocksX-NG#103]
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist - GET 404

**Comment by longdeqidao** [comment]
shoud be this link https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by qiuyuzhou** [comment]
代码里缺省值是这个地址：https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
可以在高级配置里自行修改。
