### ISSUE TITLE
这个工具是不是已经不再维护了？

### ISSUE THREAD

**Issue by sd4324530** [shadowsocks/ShadowsocksX-NG#1042]
这个工具是不是已经不再维护了？

**Comment by xiebruce** [comment]
同问，不止是这个，shadowsocks是不是也凉凉了？6月初，一大批ip被关进了小黑屋，据说是用了ss的就被关，据说是特征被识别了，谁知道具体情况吗？

**Comment by sd4324530** [comment]
> 同问，不止是这个，2.6.8是不是也凉凉了？6月初，一大批IP被关进了小黑屋，据说是用了SS的就被关，据说是特征被识别了，谁知道具体情况吗？

我的服务器倒是没事，我现在主要就是担心这个工具不再维护，之后操作系统升级，会不会有兼容性的问题，还没找到其他可以替代的工具

**Comment by xiebruce** [comment]
替代工具当然有，v2ray
