### ISSUE TITLE
shadowsocks官网登不上

### ISSUE THREAD

**Issue by callmenana** [shadowsocks/ShadowsocksX-NG#1048]
5月17日在SS官网上购买了年度入门版。5月31日晚在寝室能正常使用，6月1日把电脑带回家后，不管是连Wi-Fi还是热点都用不了。曾经的购买链接也都点不开了。

只有进入官网登录我的账号，才能看到二维码配置。现在登不上SS，请问怎么办？

**Comment by archer-black** [comment]
@callmenana 查看你注册的邮箱，会发邮件给你可用地址的 :)

**Comment by juggle586** [comment]
> @callmenana查看你注册的邮箱，会发邮件给你可用地址的:)

现在突然不能用了？

**Comment by archer-black** [comment]
@callmenana 是的啊，官网说特殊时期大部分都不能用。我试了所以的都挂了...

**Comment by PhilipTang** [comment]
@archer-black ，这两天怎么啦 有啥情况？

**Comment by archer-black** [comment]
@PhilipTang 不知道啊，我先换别的用了

**Comment by iamlintao** [comment]
全国都这样了，等等吧

**Comment by mxclover** [comment]
那几天快到了(特殊日子)

**Comment by notomorow** [comment]
看来TG想封还是能封的，平时不封就是留个窗口给大家透透气。

**Comment by callmenana** [comment]
> @callmenana 查看你注册的邮箱，会发邮件给你可用地址的 :)

邮件里的地址链接也打不开
