### ISSUE TITLE
之前一直正常使用，今天所有的服务都无法正常使用

### ISSUE THREAD

**Issue by songyule** [shadowsocks/ShadowsocksX-NG#1049]

**Comment by juggle586** [comment]
我也是 不知道什么原因

**Comment by wjbianjason** [comment]
+1

**Comment by jinhyhenry** [comment]
官网都上不了了~是不是卷钱跑路了~

**Comment by yun0926** [comment]
+1

**Comment by yaonanjiang** [comment]
the same problem as you met

**Comment by hp-wangjie** [comment]
+1

**Comment by zhanglinbo** [comment]
+1

**Comment by dancewhale** [comment]
+1 到底啥特殊原因呀

**Comment by kidbai** [comment]
不知道是不是特殊日子到了。。我今天也用不了

**Comment by xhurongna** [comment]
+1

**Comment by fangmd** [comment]
+1, bwg 换ip还要钱了。。。😣

**Comment by TaylerTao** [comment]
+1

**Comment by aiwozhe** [comment]
+1

**Comment by berryhsiang** [comment]
+1 什么时候才能恢复啊啊啊啊啊，感觉和世界失联了

**Comment by ZhaoXinNian** [comment]
+1 。

**Comment by lk-timeout** [comment]
看来挂的人很多。。。

**Comment by GoldenArmour** [comment]
+1

**Comment by xk1816** [comment]
挂啊

**Comment by aiwozhe** [comment]
是不是国家网络限制了，手机上也都没法用




| |
孙庆江
|
|
aiwozhe@yeah.net
|

签名由 网易邮箱大师 定制

在2019年06月02日 22:06，xk1816 写道：

挂啊

**Comment by yunlonggmail** [comment]
有知道具体原因的吗？

**Comment by GoldenArmour** [comment]
ip被封了    就算换个ip估计还是要被封

**Comment by tankcong** [comment]
ip封了，这段时间凉凉

**Comment by qinghuazs** [comment]
我的也是

**Comment by iamlintao** [comment]
全国都这样了 等等吧

**Comment by hangzz** [comment]
特殊日子，110.100

**Comment by codeRiding** [comment]
大家都知道，这样会好受点

**Comment by TonyShng** [comment]
+1 唉 难受啊

**Comment by huangbxaaa** [comment]
+1

**Comment by ljwname** [comment]
+1

**Comment by szs00szs** [comment]
有木有替换的方案，求分享一下～

**Comment by ljwname** [comment]
还有其他的科学上网方式吗，求推荐。

**Comment by SleepyCatZz** [comment]
+1

**Comment by chenzi** [comment]
+1

**Comment by ASmartPig** [comment]
凉凉

**Comment by nextisleo** [comment]
as you see,the time of 6.4 is coming;so the GWF is enhanced,my vpn construct on google cloud can`t not user so far;hope someone tell me how to treat this problem;

**Comment by songyule** [comment]
所以，封了就封了，工作人员不给处理一哈的吗😂😂😂

**Comment by jiangfeng0205** [comment]
bwh刚换的ip又被封了！

**Comment by fangmd** [comment]
目前可行方案应该是用飞机场

**Comment by qq29oo** [comment]
bwg也不行了，换了ip被秒封

**Comment by jiangfeng0205** [comment]
这是什么事件导致的呀？

**Comment by whybux** [comment]
bwg +1

**Comment by hujukee** [comment]
Something wrong with my shadowsocks, what happend?

**Comment by LLeung49** [comment]
+1 ios设备还能用 mac不行。。。。

**Comment by hotmaycold** [comment]
> +1 ios设备还能用 mac不行。。。。

shadowrocket 也不行呢

**Comment by liujiede** [comment]
1

**Comment by chenchao6** [comment]
好日子结束了？

**Comment by jiangfeng0205** [comment]
这事情都过去30来年了，没想到对现在还有影响。

**Comment by sunmouse** [comment]
+1

**Comment by YcSaber** [comment]
有什么可替换方案么最近。

**Comment by LiuZiqi-dual** [comment]
不知道v2ray有没有被破

**Comment by jiangfeng0205** [comment]
> 不知道v2ray有没有被破

v2也好多被封的，等过了这两天再说吧。上面的说需要过了6号。等等看吧，别往枪口上撞，到时候欧普请去喝茶就不至于了。

**Comment by xuanquanzhi** [comment]
64学潮吧

**Comment by loveuforever999** [comment]
+1

**Comment by desmax** [comment]
how about you speak international language?

**Comment by jiangfeng0205** [comment]
> how about you speak international language?
what's wrong with you?

**Comment by loveuforever999** [comment]
> > 不知道v2ray有没有被破
> 
> v2也好多被封的，等过了这两天再说吧。上面的说需要过了6号。等等看吧，别往枪口上撞，到时候被请去喝茶就不至于了。

真的会被请去喝茶嘛

**Comment by po1arbear** [comment]
> 特殊日子，110.100
有谁知道啥时候解封吗，都过去好几天了

**Comment by hackrflov** [comment]
Still not working...

**Comment by openfe-openfe** [comment]
10天了,还不能访问啊

**Comment by LiuZiqi-dual** [comment]
> > 特殊日子，110.100
> > 有谁知道啥时候解封吗，都过去好几天了

封了的不存在解封只有换IP，寄希望于中共不追封你换了的新IP

**Comment by libfox** [comment]
vultr ip 被封，销毁重建ip不刷新了，还是原来的ip，怎么破？

**Comment by TonyShng** [comment]
我这里把端口号换了后是可以了，可以先ping一下，能ping通修改端口号试试

**Comment by whybux** [comment]
哈哈哈，搬瓦工vps解禁了。
