### ISSUE TITLE
可否考虑在启动时默认启用ss呐

### ISSUE THREAD

**Issue by oufumihiko** [shadowsocks/ShadowsocksX-NG#105]
否则每次重启都要点一下
![screen shot 2016-10-20 at 11 36 36 pm](https://cloud.githubusercontent.com/assets/8544939/19566782/0f8723e4-971e-11e6-82a8-bd7a5a53c0b1.png)

**Comment by uhy** [comment]
是的，或者增加一个可选项，是否开启启动 ss 功能

**Comment by qiuyuzhou** [comment]
merge pull request引入的bug，
已经修复，等待发布新版
