### ISSUE TITLE
macos mojave  版本1014.5  配置好了 ，完全没看到生效呀，用不了

### ISSUE THREAD

**Issue by brianlaibaoqin** [shadowsocks/ShadowsocksX-NG#1052]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior
<img width="493" alt="屏幕快照 2019-06-04 下午2 17 37" src="https://user-images.githubusercontent.com/34622645/58855811-8ccd5880-86d3-11e9-994c-0a58a5ef4dfe.png">

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by callmenana** [comment]
从六一开始就用不了，之前能用，不知道为什么，SS官网登不上了，无法获取配置二维码

**Comment by LiuZiqi-dual** [comment]
你先看看你的vps还能不能ping通，6月1日中共封了大量vps的ip段

**Comment by Bohan-Song** [comment]
6月17后恢复

**Comment by zhangcanfeng612** [comment]
> 6月17后恢复

你怎么知道的嘞？

**Comment by callmenana** [comment]
官方解释：

针对"特殊"原因造成的中国内地客户无法连接节点的问题，我们已恢复日本 JP1、JP2、JP3 美国 US1 US2 US3 荷兰 NL1 德国 DE1 澳洲 AU1 和香港 HK3 节点，并为高级版和旗舰版客户新加入的 SZ 深港专线节点。

由于 DNS 地址生效需要 24-48 小时，在此期间，您可以将上述节点服务器地址放入 https://ping.sb/ 网站中搜索框，取消 China Mainland 选项，点击右边开始 Start，使用返回的地址 Respond IP 作为服务器地址，填入您的 Shadowsocks 程序中的服务器地址栏中进行连接。如果仍无法正常使用，您需要耐心等待您的网络提供商，接受我们宣告的路由，这可能会在 24-48 内生效。

对于此次不可抗力因素为您带来的不便，敬请谅解，待全部节点恢复后，我们会为您双倍补偿受影响的时间。

**Comment by callmenana** [comment]
日本 JP1、JP2、JP3 美国 US1 US2 US3 荷兰 NL1 德国 DE1 澳洲 AU1 和香港 HK3 可以用

**Comment by brianlaibaoqin** [comment]
> 你先看看你的vps还能不能ping通，6月1日中共封了大量vps的ip段

我的MAC重新装了系统，就可以用了，不知道怎么回事。

**Comment by brianlaibaoqin** [comment]
我的MAC重新装了系统，就可以用了，不知道怎么回事，可能系统有问题吧
