### ISSUE TITLE
Next release plan?

### ISSUE THREAD

**Issue by colachg** [shadowsocks/ShadowsocksX-NG#1054]
**Describe the solution you'd like**
I see the v2ray plugin is merged, so I want to know when to release new version?Or how can I build my self to use it. Thank you guys :)
@lkebin  @qiuyuzhou

**Comment by lkebin** [comment]
@colachg Open .xcworkspace file and build the project in Xcode.

**Comment by GainSury** [comment]
here is the news commit version.
[ShadowsocksX-NG.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/3269409/ShadowsocksX-NG.zip)

**Comment by colachg** [comment]
@GainSury Thanks a lot. I think docker is a good solution :)

**Comment by jiangangli69** [comment]
> here is the news commit version.
> [ShadowsocksX-NG.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/3269413/ShadowsocksX-NG.zip)

It seems that cannot download it, can you share it again? Many thanks.

**Comment by GainSury** [comment]
> > here is the news commit version.
> > [ShadowsocksX-NG.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/3269413/ShadowsocksX-NG.zip)
> 
> It seems that cannot download it, can you share it again? Many thanks.

add proxy to download it, Github is banned in Mainland China somewhere
