### ISSUE TITLE
什么时候发布新版本？

### ISSUE THREAD

**Issue by hugbio** [shadowsocks/ShadowsocksX-NG#1055]
我想了解下。什么时候又新的版本发布？能否在图标上加服务器连接状态变化？这很方便

**Comment by zhenghamu** [comment]
请问一下可以救一下技术小白吗？需要翻……但是不会……我是mac……之前都是点打开就好了现在不行了

**Comment by Antisunny** [comment]
感觉UI是否可以优化一下 edit servers弹窗的输入框、下拉框什么的真的不甚好看

**Comment by qiuyuzhou** [comment]
@hugbio 考虑最近一个月发布新版。不存在服务器连接状态这种事，具体原理请去google一下shadowsocks的实现原理。
@Antisunny 这个项目的目的只是以最低成本提供一个mac上可用的ss GUI客户端，不会考虑UI是否好看这种事。
