### ISSUE TITLE
请问为啥ShadowsocksX-NG可以连上但是依然上不了网

### ISSUE THREAD

**Issue by yeru130** [shadowsocks/ShadowsocksX-NG#1057]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by Bohan-Song** [comment]
这几天¥¥吧  可能过几天就好了

**Comment by yeru130** [comment]
希望吧，日本，香港、美国的都连不上，搜个东西也搜不出来很不方便啊

**Comment by yeru130** [comment]
> 这几天¥¥吧 可能过几天就好了

你的今天也登录不上吗

**Comment by Jiangchenglin521** [comment]
> > 这几天¥¥吧 可能过几天就好了
> 
> 你的今天也登录不上吗

都快一周了，不能用了。。。。。

**Comment by pz9042** [comment]
日本一这个服务器能连，不过速度有点慢

**Comment by Bohan-Song** [comment]
过几天就好了，这段时间各大视频网站弹幕都封杀了  你觉得为啥？。。。

**Comment by pz9042** [comment]
> 过几天就好了，这段时间各大视频网站弹幕都封杀了 你觉得为啥？。。。

应该是6.4事件，就是89年6.4事件

**Comment by Bohan-Song** [comment]
@pz9042   。。。别说出来 命不要了？
