### ISSUE TITLE
Mac没法连接了

### ISSUE THREAD

**Issue by longertime** [shadowsocks/ShadowsocksX-NG#1059]
从上个月开始就无法连接了。。。。。

**Comment by ppker** [comment]
我也是 连不上了 真JB 服了

**Comment by Coco-Wiz** [comment]
官网越来月坑了,解决方法直接让换新的,我也是呵呵了!

**Comment by qiuyuzhou** [comment]
官网是https://shadowsocks.org/ 仅提供软件，所有卖ss服务器的都跟官网无关。
有关ss服务器提供商的事不要到这边开源软件github上来讨论。
