### ISSUE TITLE
ss 到底还能不能用了,难道要换 VPN 了?这都等了快半个月了,官网说是端午前后,难道凉凉了?

### ISSUE THREAD

**Issue by Coco-Wiz** [shadowsocks/ShadowsocksX-NG#1062]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by vesperisdead** [comment]
同问

**Comment by TomorrowIsAnOtherDay** [comment]
+1

**Comment by fanweiguo** [comment]
充钱没多久呀，太坑爹了

**Comment by Seechai47** [comment]
政治敏感期

**Comment by yd23** [comment]
我一个历史悠久资费极地的服务器 居然ip被ban了，sigh，被动消费升级了。 现在有啥魔高一尺的宝物吗。。。

**Comment by tcc123** [comment]
现在是不能用了吗

**Comment by CHENLOLA** [comment]
代码是开源的；
生饭菜不会自己煮一下嘛。

**Comment by maxfong** [comment]
@CHENLOLA 来秀智商的？看清楚人家问题

**Comment by maxfong** [comment]
今天发现IP解封了，可以看下自己的是否解封
