### ISSUE TITLE
Mac Mojave: cannot connect to app store and software update failed issue.

### ISSUE THREAD

**Issue by antidb** [shadowsocks/ShadowsocksX-NG#1064]
Recently, I cannot connect to the app store and software update failed.

I searched the web, and followed lots of "solutions", like delete Caches, Preferences, Keychain access etc, nothing worked.

And I found it is OK when I use my Shadowsocks in Global Mode, but in OFF mode or Auto mode, it can't connect. So I think it might be the system network configuration problem, but I did delete Preferences, but it isn't work.

The recent move I did maybe I add a line about "apple.com/us" in Shadowsocks user rule configuration file to bypass GFW.

Any help here? Appreciated.

**Comment by qiuyuzhou** [comment]
Sometime the appstore block by GFW. It's not an issue of ShadowsocksX-NG.
