### ISSUE TITLE
现在手机端是可以正常访问的，但是在mac上无法访问

### ISSUE THREAD

**Issue by lhuafmaof** [shadowsocks/ShadowsocksX-NG#1068]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by JerryCui** [comment]
我的也是这样

**Comment by Wendy1209** [comment]
我的Mac 谷歌都上不去

**Comment by coooliang** [comment]
我也是啊！！！！手机一样的配置OK的。但不管是windows还是mac都不行哦。

**Comment by jackyzou226** [comment]
我也试过，我的做法是重新安装mac

Lion <notifications@github.com> 于2019年8月12日周一 下午2:13写道：
