### ISSUE TITLE
安装的 Kcptun 版本为: 20190611 无法加速客户端连不上

### ISSUE THREAD

**Issue by meteorice** [shadowsocks/ShadowsocksX-NG#1069]
**Describe the bug**
安装的 Kcptun 版本为: 20190611 无法加速客户端连不上

**To Reproduce**

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.14.5]
 - Version [e.g. 版本 1.8.2 (1)]

**ss-local.log**
 2019-06-26 02:11:22 INFO: plugin "plugins/kcptun" enabled
 2019-06-26 02:11:22 INFO: initializing ciphers... aes-256-cfb
 2019-06-26 02:11:22 INFO: listening at 127.0.0.1:2086
 2019-06-26 02:11:22 INFO: tcp port reuse enabled
test2019/06/26 02:11:22 version: 20170718
2019/06/26 02:11:22 listening on: 127.0.0.1:58422
2019/06/26 02:11:22 encryption: aes
2019/06/26 02:11:22 nodelay parameters: 1 20 2 1
2019/06/26 02:11:22 remote address: *.*.*.*:28003
2019/06/26 02:11:22 sndwnd: 128 rcvwnd: 1024
2019/06/26 02:11:22 compression: true
2019/06/26 02:11:22 mtu: 1350
2019/06/26 02:11:22 datashard: 10 parityshard: 3
2019/06/26 02:11:22 acknodelay: false
2019/06/26 02:11:22 dscp: 0
2019/06/26 02:11:22 sockbuf: 4194304
2019/06/26 02:11:22 keepalive: 10
2019/06/26 02:11:22 conn: 1
2019/06/26 02:11:22 autoexpire: 60
2019/06/26 02:11:22 scavengettl: 600
2019/06/26 02:11:22 snmplog: 
2019/06/26 02:11:22 snmpperiod: 60
2019/06/26 02:11:22 connection: 192.168.31.225:61943 -> *.*.*.*:28003
2019/06/26 02:11:25 stream opened
2019/06/26 02:11:25 stream closed
2019/06/26 02:11:30 stream opened
2019/06/26 02:11:30 stream closed
**Application log**

**Crash Log**

**Additional context**

**Comment by Vale-sail** [comment]
我也遇到了 我使用 https://github.com/shadowsocks/kcptun 里面的kcp client 就可以正常连接使用 但是使用ss 就不行

**Comment by meteorice** [comment]
> 我也遇到了 我使用 https://github.com/shadowsocks/kcptun 里面的kcp client 就可以正常连接使用 但是使用ss 就不行

你是用 https://github.com/shadowsocks/kcptun/blob/shadowsocks/Dockerfile 启动的？

**Comment by Vale-sail** [comment]
不是 我直接启动的

**Comment by Vale-sail** [comment]
> > 我也遇到了 我使用 https://github.com/shadowsocks/kcptun 里面的kcp client 就可以正常连接使用 但是使用ss 就不行
> 
> @Vale-sail
> 
> 你是用 https://github.com/shadowsocks/kcptun/blob/shadowsocks/Dockerfile 启动的？

我的可以了  因为我的密码里面有一个符号需要转义 但是 kcp 安装脚本给出key 没有进行转义导致错误

**Comment by qiuyuzhou** [comment]
Make sure to use right plugin opts format.
Something like: `crypt=aes;mode=fast`
