### ISSUE TITLE
今天又无法使用了吗？

### ISSUE THREAD

**Issue by lrhddzyj** [shadowsocks/ShadowsocksX-NG#1072]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by berryhsiang** [comment]
是的，我所有服务器都用不起。自从六月那啥之后恢复了也总觉得不稳定、很慢……能不能救救孩子，没vpn学都习不了，真实崩溃

**Comment by fgcui1204** [comment]
@berryhsiang 注册google cloud账号，免费一年服务器使用

**Comment by ZoeShaw101** [comment]
同无法使用
