### ISSUE TITLE
mojave无法使用shadowsocksX-NG的看过来

### ISSUE THREAD

**Issue by hd2210** [shadowsocks/ShadowsocksX-NG#1073]
到系统偏好设置->安全性和隐私->完全磁盘访问中将shadowsocksX-NG赋予完整磁盘访问即可。

**Comment by CoderWeiLee** [comment]
问一下 是直接跑起来在pac自动模式下就能翻墙访问google了吗  我试了一下  发现没有什么效果哇

**Comment by hd2210** [comment]
是啊，你先确定你的shadowsocks服务器没问题？同时看下~/Library/Logs/ss-local.log里面有没有什么报错。如果还是不行，就查下监听端口是否被占用了，如果是则修改到其他端口再重启shadowsocksX-NG

**Comment by ITTroy** [comment]
我在Windows 上能上，Mac 上自从更新了majave后就用不了了

**Comment by Four5Fire** [comment]
since update to the catalina of version, my ssr is unable to use chrome.

**Comment by sontekliu** [comment]
可以参考 #855

**Comment by Four5Fire** [comment]
Greateful，thank you very much，I solved the problem.




------------------ 原始邮件 ------------------
发件人: "Javaliu"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 下午2:31
收件人: "shadowsocks/ShadowsocksX-NG"<ShadowsocksX-NG@noreply.github.com>; 
抄送: "javacao"<942558046@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [shadowsocks/ShadowsocksX-NG] mojave无法使用shadowsocksX-NG的看过来 (#1073)




可以参考 #855

**Comment by Four5Fire** [comment]
> since update to the catalina of the version, my ssr is unable to use chrome.

I solved the problem. My "ggfwzs" prompts proxy permission conflicts, so, I delete the library of the chrome and close “ggfwzs” after reinstall the chrome.
