### ISSUE TITLE
官网打不开，无法续费

### ISSUE THREAD

**Issue by hswlxc** [shadowsocks/ShadowsocksX-NG#1075]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wanghongli1991** [comment]
https://order.shadowsocks.se

**Comment by Xarriors** [comment]
不要把ss技术官网和普通的提供ss服务的公司的官网搞混淆了
参考
https://crifan.github.io/scientific_network_summary/website/shadowsocks_intro/ss_official_site.html
其他参考：
https://crifan.github.io/scientific_network_summary/website/server_client_mode/ss_server/self_build_ss_server.html
