### ISSUE TITLE
v1.3.1在10.11.6下无法使用

### ISSUE THREAD

**Issue by Fengxq2014** [shadowsocks/ShadowsocksX-NG#108]
没有报错，pac模式和全局模式都不能用，用老版本的shadowsocksX就可以

**Comment by BaranWang** [comment]
10.12 一样的问题，是设置的有问题吗？

**Comment by mrbeann** [comment]
我这边也运行不了。10.12 感觉设置改了改也没啥用？

**Comment by 512557852** [comment]
同样无法使用

**Comment by Fengxq2014** [comment]
![image](https://cloud.githubusercontent.com/assets/8519834/19691938/a3886e66-9b08-11e6-93cb-562089502b67.png)

**Comment by NapoleonAlexandre** [comment]
同样无法使用

**Comment by heartinfei** [comment]
我的也无法使用了！重启也不行！

**Comment by chenhouwu** [comment]
我的也无法使用了！重启也不行！

**Comment by cani1see** [comment]
楼上的可以看看服务器选中了没有

**Comment by chenhouwu** [comment]
我的可以了。把 *单次验证* 关掉就行了。

**Comment by mickeydonkey** [comment]
这边同样有问题，@chenhouwu 可以截个图说明一下吗？谢谢

**Comment by chenhouwu** [comment]
@mickeydonkey 在服务器设置中，不要check `启用OTA`

**Comment by jnuc093** [comment]
我是 10.11.6。X-NG 版本 1.3.8-R8 (3) 也无法使用。问下单次验证在哪设置?
