### ISSUE TITLE
无法扫描二维码

### ISSUE THREAD

**Issue by zXwilt** [shadowsocks/ShadowsocksX-NG#1081]
**Describe the bug**
扫描桌面二维码没有任何反应。观察到console里成功打印了相应的SSR连接，复制之后用从剪贴板倒入URL也不成功，该URL在手机上能成功导入。

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**
添加一个节点

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.14.5]
 - Version [e.g. 18.2]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by qiuyuzhou** [comment]
Not support SSR.

**Comment by with021** [comment]
cant use qr-code scan , mac os big sur. please help, ss 1.9.4
