### ISSUE TITLE
global mode not woking on Mojave

### ISSUE THREAD

**Issue by videni** [shadowsocks/ShadowsocksX-NG#1084]
# system  level netwoking configuration

![image](https://user-images.githubusercontent.com/4058341/61604497-51cbb800-ac74-11e9-8b93-754a3960618b.png)

shadowscoket-NG is switched to global mode,  this doesn't work.

here are what I do

1. switch to global mode
2. add http_proxy environment variable to terminal.
3. ping www.google.com  in terminal
```
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
```
# browser proxy, such as SwitchyOmega

![image](https://user-images.githubusercontent.com/4058341/61604537-80e22980-ac74-11e9-9280-b48ca545fdf6.png)

it works for browser  as expected  .

**Comment by lilunxm12** [comment]
CLI Apps doesn't work with system SOCKS5 proxies. Use http proxies instead
```
export http_proxy=socks5://127.0.0.1:1087
export https_proxy=socks5://127.0.0.1:1087
```
Or use something like ProxyChains-NG if you really want SOCKS5

**Comment by videni** [comment]
@lilunxm12 , thanks for your help.  as I show above, I have added http_proxy environment variable to terminal. in my case , it is 
```
export http_proxy=socks5://127.0.0.1:1086
export https_proxy=socks5://127.0.0.1:1086
```
this doesn't help. I also tried ProxyChains-NG,  still the same.

**Comment by lilunxm12** [comment]
Your screenshot shows 1086 is for SOCKS proxy, not http/https.

**Comment by lilunxm12** [comment]
I just realized you can't use any proxy with ping but http proxy should be good for most CLI applications.

**Comment by videni** [comment]
@lilunxm12,  I see,  works now, thanks.
