### ISSUE TITLE
MAC shadowsocks 不能使用

### ISSUE THREAD

**Issue by DreamDemoD** [shadowsocks/ShadowsocksX-NG#1089]
今天突然不能使用了,账号是对的,现在开了全局国内网络也上不去

**Comment by jackyzou226** [comment]
ip能ping通吗

DreamDemoD <notifications@github.com>于2019年8月5日 周一18:54写道：

**Comment by DreamDemoD** [comment]
不能啊

**Comment by jackyzou226** [comment]
估计被封了，换一台vps

DreamDemoD <notifications@github.com>于2019年8月5日 周一19:22写道：

**Comment by DreamDemoD** [comment]
我试试看(●◡●)ﾉ

**Comment by DreamDemoD** [comment]
现在ip可以ping成功了，可是还是不能翻

**Comment by jackyzou226** [comment]
手机可以吗？

DreamDemoD <notifications@github.com> 于2019年8月5日周一 下午8:11写道：

**Comment by y1324** [comment]
我也是，手机正常mac不行了

**Comment by wantr01** [comment]
有解决办法吗？
