### ISSUE TITLE
mac shadowsocks-NG cannot work by wired network

### ISSUE THREAD

**Issue by ltang320** [shadowsocks/ShadowsocksX-NG#1098]
Recently, my mac cannot use the shadowsocks-NG according to the wired network.
I have already ping my ipv6 network. I can ping it by myself. And my wireless network can use these setup of shadowscks.
However, after I turn on the shadowsocks in the wired network, it cannot connect.

Could everyone can give me some suggestions to fix this problem?

![屏幕快照 2019-08-23 18 20 55](https://user-images.githubusercontent.com/11830693/63586047-0d18a100-c5d3-11e9-8efa-0762aacc72f4.png)
![屏幕快照 2019-08-23 18 23 34](https://user-images.githubusercontent.com/11830693/63586090-24578e80-c5d3-11e9-8f39-eecd66deec8b.png)

 - OS Version: 10.14
 - Version 6

**Comment by qiuyuzhou** [comment]
Select the interfaces by yourself in here.
![image](https://user-images.githubusercontent.com/2310221/64453356-f3bb3d00-d11a-11e9-9f92-e9fd7dc3c736.png)
