### ISSUE TITLE
能实现多个SS服务器自动切换么？

### ISSUE THREAD

**Issue by xqiushi** [shadowsocks/ShadowsocksX-NG#11]
windwos 上有一个变体版的。https://github.com/breakwa11/shadowsocks-rss
可以多个服务器故障切换和负载均衡，MacOS上实现有难度么？

**Comment by qiuyuzhou** [comment]
有难度
目前实现，未与ss-local进行深度整合，ss-local作为后台服务运行。
GUI只负责控制配置文件和开关后台服务。
如果shadowsocks-libev的ss-local支持这些功能，GUI就可以对其进行相应配置。

shadowsocks-libev的ss-local目前实现到什么程度，我还太清楚，需要抽时间去了解。

**Comment by xqiushi** [comment]
谢谢亲，所做的一切！

**Comment by omaidb** [comment]
@xqiushi @qiuyuzhou 比如定时测速，哪个服务器速度最快自动切换过去
