### ISSUE TITLE
Password saves incorrectly in ss-local-config.json.

### ISSUE THREAD

**Issue by behzadsh** [shadowsocks/ShadowsocksX-NG#1104]
**Describe the bug**
Seems like app escapes slashes `/` before saving it in `ss-local-config.json`.

**To Reproduce**
Add a password that contains `/` and gets an invalid password message in logs.
After checking logs for finding the reason why my shadowsocks is not working, I checked `ss-local-config.json` and see that `/` in my password was escaped. I removed escaping back-slash and check the connection and it was fine.

**Expected behavior**
Slashes should not be escaped before saving in `ss-local-config.json`.

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 10.14.6
 - Version 1.8.2

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

```
...
 2019-09-02 21:34:02 ERROR: invalid password or cipher
 2019-09-02 21:34:03 ERROR: invalid password or cipher
 2019-09-02 21:34:04 ERROR: invalid password or cipher
 2019-09-02 21:34:04 ERROR: invalid password or cipher
 2019-09-02 21:34:04 ERROR: invalid password or cipher
 2019-09-02 21:34:04 ERROR: invalid password or cipher
 2019-09-02 21:34:05 ERROR: invalid password or cipher
...
```

**Comment by qiuyuzhou** [comment]
This is NSJSONSerialization.dataWithJSONObject that likes to insert additional backslashes.
Escaped forward slashes is also valid json. May be `ss-local` hasn't handle it correctly.

Need a workaround.
