### ISSUE TITLE
macOS Mojave版本10.14.6，如何设置加密方式为none?现在报错ERROR: invalid cipher name: none

### ISSUE THREAD

**Issue by Firewall-Tomohisa** [shadowsocks/ShadowsocksX-NG#1107]
在安装shadowsocks服务端的时候，加密方式选择的none，Windows上使用没有任何问题。但是现在mac无法设置加密方式为none，也就是不选择任何加密方式。这个服务器的配置是从Windows的json文件导入的，所以有none加密方式，但是启动时日志一直报错。那请问有什么方法将mac的SS加密方式设置为none？
When installing the shadowsocks service, the encryption method is selected as none, and there are no problems with using it on Windows.But now the MAC can't set the encryption mode to none, which means it doesn't choose any encryption mode.This server is configured to be imported from a json file on Windows, so there is none encryption, but the log keeps reporting errors at startup.Is there any way to set MAC SS encryption to none?
<img width="417" alt="QQ图片20190910094757" src="https://user-images.githubusercontent.com/51064238/64577991-9fc98600-d3b0-11e9-8963-23b1ee108db8.png">

**Comment by qiuyuzhou** [comment]
`shadowsocks-libev` which NG depend on, does not support encrypt method `none`

**Comment by Firewall-Tomohisa** [comment]
问题解决了，使用的shadowsocksX-NG-R，它支持none加密方法，同时它的配置和Windows客户端的SS是一样的😄，谢谢！

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Qiu Yuzhou <notifications@github.com&gt;
发送时间: 2019年9月10日 10:46
收件人: shadowsocks/ShadowsocksX-NG <ShadowsocksX-NG@noreply.github.com&gt;
抄送: Firewall-Tomohisa <1986532190@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[shadowsocks/ShadowsocksX-NG] macOS Mojave版本10.14.6，如何设置加密方式为none?现在报错ERROR: invalid cipher name: none (#1107)




shadowsocks-libev which NG depend on, does not support encrypt method none
