### ISSUE TITLE
端口傻傻分不清= =

### ISSUE THREAD

**Issue by YaphetSFiS** [shadowsocks/ShadowsocksX-NG#1109]
好多个端口- -根本搞不明白，想问该怎么去设置这几个端口
用的是shadowsocksX-NG-2
![image](https://user-images.githubusercontent.com/17846296/64588704-ca7a0580-d3d5-11e9-8e6c-d5b2f5ed1d00.png)
![image](https://user-images.githubusercontent.com/17846296/64588725-d796f480-d3d5-11e9-8924-697d6ffbfea7.png)
本地socks监听地址：
本地socks监听端口：

本地PAC服务器监听地址：
本地PAC服务器监听端口：

HTTP代理监听地址：
HTTP代理监听端口：

**Comment by qiuyuzhou** [comment]
去搜索引擎搜索
