### ISSUE TITLE
Launch At login with default on

### ISSUE THREAD

**Issue by imsoso** [shadowsocks/ShadowsocksX-NG#111]
原来的每次启动都会自动开启ss，现在启动是启动了，打开浏览器才发现没开

**Comment by huangdou0204** [comment]
我也正为此事苦恼。怎么才能开机自动打开？ 自启动是没问题的

**Comment by wilsli** [comment]
App是随登录启动了，但是Shadowsocks没有开启 :-(

**Comment by qiuyuzhou** [comment]
1.3.2已经修复

**Comment by brallow** [comment]
OS X 10.12.2
Shadowsocks NG 1.4（3）
存在同样的问题
