### ISSUE TITLE
我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？

### ISSUE THREAD

**Issue by kshq1996** [shadowsocks/ShadowsocksX-NG#1114]
我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
封了吗？
还有什么替代品么。

**Comment by Jiangchenglin521** [comment]
应该是和70周年有关吧。3天崩了两次了。。。。。

**Comment by kshq1996** [comment]
> 应该是和70周年有关吧。3天崩了两次了。。。。。

我换了朋友的结点了，确认不是软件问题，是服务器结点问题，但是能ping通不能上网是什么意思

**Comment by lzhgostudy** [comment]
应该是了，再加上香港那边的动荡，无疑就是国家信息局做事了。我之前在阿里购买的香港服务器做跳板，相安无事的用了半年，3天前就发现不好使了，ping不通，一直提示timeout。后来我在阿里重新购买了一台香港服务器，试了一下，可以ping通，然后开开心心的部署shadowsocks环境，接着我打开YouTube，页面也可以正常显示，但是几秒钟后，马上无法访问，ping也不通，提示超时。呵呵！

**Comment by chaiyuyi** [comment]
从哪里能买的别的节点啊，没了Google 我如同一个瞎子

**Comment by Alan201601** [comment]
哎，难受，不能用了，我要怎么学习。

**Comment by althyman** [comment]
香港的ECS服务器只要挂了VPN的全部被关停了。。。精准检测。。。。

**Comment by kshq1996** [comment]
> 从哪里能买的别的节点啊，没了Google 我如同一个瞎子

https://www.cordcloud.org/auth/register1  
只接受邀请码，你可以试试我朋友用的
邀请码
U3Is0ZLCYYtgrhE1rSafJNjvQtQccEj7

**Comment by kshq1996** [comment]
> 哎，难受，不能用了，我要怎么学习。

重新买节点吧。。

**Comment by kshq1996** [comment]
> 应该是了，再加上香港那边的动荡，无疑就是国家信息局做事了。我之前在阿里购买的香港服务器做跳板，相安无事的用了半年，3天前就发现不好使了，ping不通，一直提示timeout。后来我在阿里重新购买了一台香港服务器，试了一下，可以ping通，然后开开心心的部署shadowsocks环境，接着我打开YouTube，页面也可以正常显示，但是几秒钟后，马上无法访问，ping也不通，提示超时。呵呵！

新加坡的好像可以用

**Comment by kshq1996** [comment]
> 香港的ECS服务器只要挂了VPN的全部被关停了。。。精准检测。。。。

好牛逼，全部崩了

**Comment by strategist922** [comment]
邀请码无效耶

Mr.KeAng <notifications@github.com> 於 2019年9月19日 週四 下午2:27寫道：

**Comment by kshq1996** [comment]
> 邀请码无效耶 Mr.KeAng <notifications@github.com> 於 2019年9月19日 週四 下午2:27寫道：
> […](#)

重新编辑了 一个邀请码只能用一次

**Comment by chaosVoid** [comment]
> > 应该是了，再加上香港那边的动荡，无疑就是国家信息局做事了。我之前在阿里购买的香港服务器做跳板，相安无事的用了半年，3天前就发现不好使了，平不通，一直提示超时。后来我在阿里重新购买了一台香港服务器，试了一下，可以ping通，然后开开心心的部署2.6.8环境，接着我打开YouTube的页面也可以正常显示，但是几秒钟后，马上无法访问，平也不通，提示超时。呵呵！
> 
> 新加坡的好像可以用

前天和今天2个新加坡的也跪了

**Comment by zongmingwei** [comment]
> > 邀请码无效耶 Mr.KeAng [notifications@github.com](mailto:notifications@github.com) 於 2019年9月19日 週四 下午2:27寫道：
> > […](#)
> 
> 重新编辑了 一个邀请码只能用一次

还有邀请码吗，好多天了还是上不去= =

**Comment by kshq1996** [comment]
> > > 邀请码无效耶 Mr.KeAng [notifications@github.com](mailto:notifications@github.com) 於 2019年9月19日 週四 下午2:27寫道：
> > > […](#)
> > 
> > 
> > 重新编辑了 一个邀请码只能用一次
> 
> 还有邀请码吗，好多天了还是上不去= =

不好意思，我已经没有了，有另外一家的，你们要用的话，试试吧：
http://cp.dawangidc.com/aff.php?aff=2731
估计需要借一下梯子才能上去，去查一下结点。

**Comment by bsback** [comment]
换了几个服务器，都是刚开始OK，很快就不行了，小众的偏远的都一样，换个端口可以，然后很快又不行了，估计是一直监测着

**Comment by 960208781** [comment]
搬瓦工的也是挂掉了

**Comment by real-kjk76** [comment]
换了好多服务器都是很快就不行了，小众的，偏远国家的都一样，换个端口可以，然后很快又不行了，应该是一直监控着，直到世界上IP地址都耗光。好多次看个youtube视频看到一半就不行了

**Comment by sky3hao** [comment]
只想说一句:CNM, 狗G 人类的毒瘤

**Comment by ChaoSection** [comment]
我的搬瓦工直接关机了，买了这家的机场撑过去这段时间再说

**Comment by ChaoSection** [comment]
http://sssru.pw/auth/register?code=hiQaqXxaLaNiryDyOMNgMF8QhiQB07tN

**Comment by kshq1996** [comment]
> http://sssru.pw/auth/register?code=hiQaqXxaLaNiryDyOMNgMF8QhiQB07tN
这个邀请码或者链接能用几次？

**Comment by ChaoSection** [comment]
没有次数限制，通过链接注册会赠送一元用于购买试用套餐

**Comment by btsome** [comment]
我也发现这个问题了，PAC模式智能上国内的，切换成全局所有网络都不可以上了。

**Comment by kshq1996** [comment]
推荐v2ray了，我换了v2ray好稳定，小火箭老是不行，
iPhone 用 小火箭
Android 用 v2rayNG
Mac 用 v2rayU
Windows没研究过，看看吧
http://cp.dawangidc.com/aff.php?aff=2731

**Comment by gbm777** [comment]
别折腾了，ssr换端口能活10分钟，之后秒封。

**Comment by xudongyi** [comment]
> 我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
> 封了吗？
> 还有什么替代品么。

ssr基本上已经都不能用了,还是推荐使用v2ray进行代理

**Comment by DLsunset** [comment]
> 我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
> 封了吗？
> 还有什么替代品么。

试试换个端口。我的一开始也是这样，换个端口就好了

**Comment by followztx** [comment]
ss流量已经被识别了，目前tor配合ss,可以规避。已经ping不通的结点，通过tor可连上了。
教程链接：https://www.imtrq.com/archives/738

**Comment by zongmingwei** [comment]
> > 我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
> > 封了吗？
> > 还有什么替代品么。
> 
> ssr基本上已经都不能用了,还是推荐使用v2ray进行代理
我下载了v2ray还是不行= =是节点有问题么

**Comment by zongmingwei** [comment]
> > 我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
> > 封了吗？
> > 还有什么替代品么。
> 
> ssr基本上已经都不能用了,还是推荐使用v2ray进行代理

我下载了v2ray还是不行。。。是节点有问题么

**Comment by kshq1996** [comment]
> > > 我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
> > > 封了吗？
> > > 还有什么替代品么。
> > 
> > 
> > ssr基本上已经都不能用了,还是推荐使用v2ray进行代理
> 
> 我下载了v2ray还是不行。。。是节点有问题么

你买的结点是v2的么？

**Comment by zongmingwei** [comment]
> > > > 我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
> > > > 封了吗？
> > > > 还有什么替代品么。
> > > 
> > > 
> > > ssr基本上已经都不能用了,还是推荐使用v2ray进行代理
> > 
> > 
> > 我下载了v2ray还是不行。。。是节点有问题么
> 
> 你买的结点是v2的么？

不是，是shadowsocks的，但我刚刚发现shadowsocks又突然能用了。。。v2的节点要在哪里买啊？？？？

**Comment by kshq1996** [comment]
> > > > > 我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
> > > > > 封了吗？
> > > > > 还有什么替代品么。
> > > > 
> > > > 
> > > > ssr基本上已经都不能用了,还是推荐使用v2ray进行代理
> > > 
> > > 
> > > 我下载了v2ray还是不行。。。是节点有问题么
> > 
> > 
> > 你买的结点是v2的么？
> 
> 不是，是shadowsocks的，但我刚刚发现shadowsocks又突然能用了。。。v2的节点要在哪里买啊？？？？

http://cp.dawangidc.com/aff.php?aff=2731

**Comment by kshq1996** [comment]
点

> > > > > 我的小火箭能ping通结点，挂了节点连不上，是不是软件问题？还是70周年警告？
> > > > > 封了吗？
> > > > > 还有什么替代品么。
> > > > 
> > > > 
> > > > ssr基本上已经都不能用了,还是推荐使用v2ray进行代理
> > > 
> > > 
> > > 我下载了v2ray还是不行。。。是节点有问题么
> > 
> > 
> > 你买的结点是v2的么？
> 
> 不是，是shadowsocks的，但我刚刚发现shadowsocks又突然能用了。。。v2的节点要在哪里买啊？？？？

挂全局代理或者非中国结点
http://cp.dawangidc.com/aff.php?aff=2731

**Comment by mqliutie** [comment]
关键点在于手机连接可以, PC连接不可以不是么...  同样的节点, 就在当时严打情况我手机都可以 但是到电脑上就不行

**Comment by jack80342** [comment]
我重写了大部分功能。https://github.com/jack80342/ShadowsocksX-NG-R

**Comment by FreeSlaver** [comment]
想都不用想，gfw给你精准封锁了，重新找个老牌的实力强的机场，<a href="https://user.by.ltd/aff.php?aff=17672">bywave</a>。
