### ISSUE TITLE
Mac OS 下kcptun 插件不工作

### ISSUE THREAD

**Issue by yorkwang** [shadowsocks/ShadowsocksX-NG#1115]
查看sslog 如下：

 2019-09-19 16:07:17 INFO: using tcp fast open
 2019-09-19 16:07:17 INFO: initializing ciphers... aes-256-cfb
 2019-09-19 16:07:17 INFO: listening at 127.0.0.1:1080
 2019-09-19 16:07:17 INFO: tcp port reuse enabled
 2019-09-19 16:09:55 INFO: plugin "plugins/kcptun" enabled
 2019-09-19 16:09:55 INFO: using tcp fast open
 2019-09-19 16:09:55 INFO: initializing ciphers... aes-256-cfb
 2019-09-19 16:09:55 INFO: listening at 127.0.0.1:1080
 2019-09-19 16:09:55 INFO: tcp port reuse enabled
Incorrect Usage. flag provided but not defined: -fast-open

NAME:
   kcptun - client(with SMUX)

USAGE:
   kcptun [global options] command [command options] [arguments...]

VERSION:
   20190910

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --localaddr value, -l value      local listen address (default: ":12948")
   --remoteaddr value, -r value     kcp server address (default: "vps:29900")
   --key value                      pre-shared secret between client and server (default: "it's a secrect") [$KCPTUN_KEY]
   --crypt value                    aes, aes-128, aes-192, salsa20, blowfish, twofish, cast5, 3des, tea, xtea, xor, sm4, none (default: "aes")
   --mode value                     profiles: fast3, fast2, fast, normal, manual (default: "fast")
   --conn value                     set num of UDP connections to server (default: 1)
   --autoexpire value               set auto expiration time(in seconds) for a single UDP connection, 0 to disable (default: 0)
   --scavengettl value              set how long an expired connection can live(in sec), -1 to disable (default: 600)
   --mtu value                      set maximum transmission unit for UDP packets (default: 1350)
   --sndwnd value                   set send window size(num of packets) (default: 128)
   --rcvwnd value                   set receive window size(num of packets) (default: 512)
   --datashard value, --ds value    set reed-solomon erasure coding - datashard (default: 10)
   --parityshard value, --ps value  set reed-solomon erasure coding - parityshard (default: 3)
   --dscp value                     set DSCP(6bit) (default: 0)
   --nocomp                         disable compression
   --sockbuf value                  per-socket buffer in bytes (default: 4194304)
   --smuxbuf value                  the overall de-mux buffer in bytes (default: 4194304)
   --keepalive value                seconds between heartbeats (default: 10)
   --snmplog value                  collect snmp to file, aware of timeformat in golang, like: ./snmp-20060102.log
   --snmpperiod value               snmp collect period, in seconds (default: 60)
   --log value                      specify a log file to output, default goes to stderr
   --quiet                          to suppress the 'stream open/close' messages
   --tcp                            to emulate a TCP connection(linux)
   -c value                         config from json file, which will override the command from shell
   --help, -h                       show help
   --version, -v                    print the version
 2019-09-19 16:09:55 ERROR: plugin service exit unexpectedly

**Comment by yorkwang** [comment]
shoadowsocks 和kcptun用的最新版本

**Comment by HBSpy** [comment]
+1
同
Aye
The same
ncorrect Usage. flag provided but not defined: -fast-open

**Comment by qiuyuzhou** [comment]
请导出诊断信息，发出来。

**Comment by ice6** [comment]
-----------------------------------
{
  "LSUIElement" : true,
  "CFBundleName" : "ShadowsocksX-NG",
  "LSMinimumSystemVersion" : "10.11",
  "CFBundleExecutable" : "ShadowsocksX-NG",
  "CFBundleSupportedPlatforms" : [
    "MacOSX"
  ],
  "CFBundleIconFile" : "AppIcon",
  "CFBundleIdentifier" : "com.qiuyuzhou.ShadowsocksX-NG",
  "NSMainNibFile" : "MainMenu",
  "CFBundleDevelopmentRegion" : "en",
  "CFBundleVersion" : "1",
  "DTCompiler" : "com.apple.compilers.llvm.clang.1_0",
  "CFBundleInfoDictionaryVersion" : "6.0",
  "DTXcodeBuild" : "10G8",
  "CFBundlePackageType" : "APPL",
  "LSApplicationCategoryType" : "public.app-category.utilities",
  "BuildMachineOSBuild" : "18G95",
  "NSHumanReadableCopyright" : "Copyright © 2016-2019 qiuyuzhou. All rights reserved. License GPLv3.",
  "DTPlatformVersion" : "GM",
  "NSPrincipalClass" : "SWBApplication",
  "DTPlatformBuild" : "10G8",
  "CFBundleSignature" : "????",
  "DTXcode" : "1030",
  "DTSDKBuild" : "18G74",
  "CFBundleShortVersionString" : "1.9.2",
  "CFBundleURLTypes" : [
    {
      "CFBundleTypeRole" : "Viewer",
      "CFBundleURLIconFile" : "menu_icon@2x",
      "CFBundleURLSchemes" : [
        "ss"
      ],
      "CFBundleURLName" : "shadowsocks"
    }
  ],
  "CFBundleNumericVersion" : 16809984,
  "DTSDKName" : "macosx10.14",
  "CFBundleIconName" : "AppIcon"
}
-----------------------------------
Preferences:
ShadowsocksOn=1
ShadowsocksRunningMode=auto
LocalSocks5.ListenPort=1086
LocalSocks5.ListenAddress=127.0.0.1
PacServer.ListenAddress=127.0.0.1
PacServer.ListenPort=1089
LocalSocks5.Timeout=60
LocalSocks5.EnableUDPRelay=0
LocalSocks5.EnableVerboseMode=0
GFWListURL=https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
LocalHTTP.ListenAddress=0.0.0.0
LocalHTTP.ListenPort=1087
LocalHTTPOn=1
LocalHTTP.FollowGlobal=0
ProxyExceptions=127.0.0.1, localhost, 192.168.0.0/16, 10.0.0.0/8, FE80::/64, ::1, FD00::/8
-----------------------------------
Active server profile: 
ServerHost=***********
ServerPort=8989
Method=aes-256-gcm
Password=****************
Plugin=
PluginOptions=
-----------------------------------
$ ls -l ~/Library/Application Support/ShadowsocksX-NG/
total 16
drwxr-xr-x   3 bing  staff   96 Dec 16  2017 kcptun_20170322
lrwxr-xr-x   1 bing  staff   85 Dec 16  2017 kcptun_client -> /Users/bing/Library/Application Support/ShadowsocksX-NG/kcptun_20170322/kcptun_client
drwxr-xr-x   3 bing  staff   96 Jul 25 07:52 kcptun_v20170718
drwxr-xr-x   3 bing  staff   96 Sep 21 16:56 kcptun_v20190905
drwxr-xr-x   6 bing  staff  192 Sep 21 16:56 plugins
lrwxr-xr-x   1 bing  staff   85 Dec 16  2017 privoxy -> /Users/bing/Library/Application Support/ShadowsocksX-NG/privoxy-3.0.26.static/privoxy
drwxr-xr-x   3 bing  staff   96 Dec 16  2017 privoxy-3.0.26.static
-rw-r--r--   1 bing  staff  434 Sep 21 17:02 privoxy.config
drwxr-xr-x   3 bing  staff   96 Jul 25 07:52 simple-obfs-0.0.5_1
drwxr-xr-x   9 bing  staff  288 Dec 16  2017 ss-local-3.0.5
drwxr-xr-x  12 bing  staff  384 Sep 21 16:48 ss-local-3.2.0
drwxr-xr-x  12 bing  staff  384 Sep 21 16:59 ss-local-3.2.5
-rw-r--r--   1 bing  staff  191 Sep 21 17:02 ss-local-config.json
lrwxr-xr-x   1 bing  staff   70 Sep 21 16:59 ss-local-latest -> /Users/bing/Library/Application Support/ShadowsocksX-NG/ss-local-3.2.5
drwxr-xr-x   3 bing  staff   96 Sep 21 16:56 v2ray-plugin_1.1.0
-----------------------------------
$ ls -l ~/Library/LaunchAgents/
total 80
-rw-r--r--  1 bing  staff   697 Mar  2  2018 com.adobe.AAM.Updater-1.0.plist
-rw-r--r--  1 bing  staff   687 Jan 30  2018 com.adobe.GC.Invoker-1.0.plist
-rw-r--r--  1 bing  staff  1664 Sep  8 19:00 com.github.facebook.watchman.plist
-rw-r--r--  1 bing  staff   730 Jan 24  2018 com.macpaw.zh.CleanMyMac3.Scheduler.plist
-rw-r--r--  1 bing  staff   727 Sep 21 17:02 com.qiuyuzhou.shadowsocksX-NG.http.plist
-rw-r--r--  1 bing  staff   930 Jul 17 10:20 com.qiuyuzhou.shadowsocksX-NG.kcptun.plist
-rw-r--r--  1 bing  staff  1045 Sep 21 17:02 com.qiuyuzhou.shadowsocksX-NG.local.plist
-rw-r--r--  1 bing  staff   543 Nov 21  2018 homebrew.mxcl.mysql.plist
-rw-r--r--  1 bing  staff   823 May 25  2018 homebrew.mxcl.redis.plist
-rw-r--r--@ 1 bing  staff   677 Aug  2 20:41 org.virtualbox.vboxwebsrv.plist
-----------------------------------
$ ls -l ~/.ShadowsocksX-NG/
total 712
-rw-r--r--  1 bing  staff  165256 Sep 21 16:57 gfwlist.js
-rw-r--r--@ 1 bing  staff  189845 Sep 21 16:57 gfwlist.txt
-rw-r--r--@ 1 bing  staff      95 May  2  2017 user-rule.txt
-----------------------------------
$ ls -l /Library/Application Support/ShadowsocksX-NG/
total 112
-rwsr-sr-x@ 1 root  admin  54816 Sep 21 16:56 proxy_conf_helper
-----------------------------------
$ lsof -PiTCP -sTCP:LISTEN
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
nginx       311 bing    7u  IPv4 0x36874a9ca91dee79      0t0  TCP *:80 (LISTEN)
nginx       311 bing    8u  IPv4 0x36874a9ca91e0ba1      0t0  TCP *:443 (LISTEN)
nginx       311 bing    9u  IPv4 0x36874a9ca91de4c1      0t0  TCP *:60 (LISTEN)
nginx       312 bing    7u  IPv4 0x36874a9ca91dee79      0t0  TCP *:80 (LISTEN)
nginx       312 bing    8u  IPv4 0x36874a9ca91e0ba1      0t0  TCP *:443 (LISTEN)
nginx       312 bing    9u  IPv4 0x36874a9ca91de4c1      0t0  TCP *:60 (LISTEN)
nginx       313 bing    7u  IPv4 0x36874a9ca91dee79      0t0  TCP *:80 (LISTEN)
nginx       313 bing    8u  IPv4 0x36874a9ca91e0ba1      0t0  TCP *:443 (LISTEN)
nginx       313 bing    9u  IPv4 0x36874a9ca91de4c1      0t0  TCP *:60 (LISTEN)
nginx       314 bing    7u  IPv4 0x36874a9ca91dee79      0t0  TCP *:80 (LISTEN)
nginx       314 bing    8u  IPv4 0x36874a9ca91e0ba1      0t0  TCP *:443 (LISTEN)
nginx       314 bing    9u  IPv4 0x36874a9ca91de4c1      0t0  TCP *:60 (LISTEN)
nginx       315 bing    7u  IPv4 0x36874a9ca91dee79      0t0  TCP *:80 (LISTEN)
nginx       315 bing    8u  IPv4 0x36874a9ca91e0ba1      0t0  TCP *:443 (LISTEN)
nginx       315 bing    9u  IPv4 0x36874a9ca91de4c1      0t0  TCP *:60 (LISTEN)
nginx       316 bing    7u  IPv4 0x36874a9ca91dee79      0t0  TCP *:80 (LISTEN)
nginx       316 bing    8u  IPv4 0x36874a9ca91e0ba1      0t0  TCP *:443 (LISTEN)
nginx       316 bing    9u  IPv4 0x36874a9ca91de4c1      0t0  TCP *:60 (LISTEN)
nginx       317 bing    7u  IPv4 0x36874a9ca91dee79      0t0  TCP *:80 (LISTEN)
nginx       317 bing    8u  IPv4 0x36874a9ca91e0ba1      0t0  TCP *:443 (LISTEN)
nginx       317 bing    9u  IPv4 0x36874a9ca91de4c1      0t0  TCP *:60 (LISTEN)
nginx       318 bing    7u  IPv4 0x36874a9ca91dee79      0t0  TCP *:80 (LISTEN)
nginx       318 bing    8u  IPv4 0x36874a9ca91e0ba1      0t0  TCP *:443 (LISTEN)
nginx       318 bing    9u  IPv4 0x36874a9ca91de4c1      0t0  TCP *:60 (LISTEN)
Shadowsoc 35974 bing   11u  IPv4 0x36874a9ce59271e9      0t0  TCP *:1089 (LISTEN)
Shadowsoc 35974 bing   12u  IPv6 0x36874a9cb8c497d9      0t0  TCP *:1089 (LISTEN)
privoxy   35998 bing    3u  IPv4 0x36874a9cd2a5f799      0t0  TCP *:1087 (LISTEN)
ss-local  36105 bing    6u  IPv4 0x36874a9cd34b7799      0t0  TCP localhost:1086 (LISTEN)
redis-ser 87891 bing    6u  IPv4 0x36874a9cb8baab09      0t0  TCP localhost:6379 (LISTEN)
redis-ser 87891 bing    7u  IPv6 0x36874a9cb8c4d299      0t0  TCP localhost:6379 (LISTEN)
mysqld    88102 bing   38u  IPv4 0x36874a9cb4a7c1e9      0t0  TCP *:3306 (LISTEN)
mysqld    88102 bing   41u  IPv6 0x36874a9cb8c4a979      0t0  TCP *:33060 (LISTEN)
Adobe\x20 88116 bing   13u  IPv4 0x36874a9ce9b008c9      0t0  TCP localhost:15292 (LISTEN)
phpstorm  97066 bing  200u  IPv4 0x36874a9cd2a13f11      0t0  TCP localhost:6942 (LISTEN)
phpstorm  97066 bing  382u  IPv4 0x36874a9cd2a11831      0t0  TCP localhost:63342 (LISTEN)
phpstorm  97066 bing  435u  IPv4 0x36874a9cd2a22de1      0t0  TCP *:9001 (LISTEN)
phpstorm  97066 bing  440u  IPv4 0x36874a9cd2a3ff11      0t0  TCP *:10137 (LISTEN)
phpstorm  97066 bing  486u  IPv4 0x36874a9cd0015b09      0t0  TCP *:20080 (LISTEN)
-----------------------------------
$ ifconfig
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 8c:85:90:80:bd:ef 
	inet 10.0.0.3 netmask 0xffffff00 broadcast 10.0.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:3f:ec:07:94:01 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:3f:ec:07:94:00 
	media: autoselect <full-duplex>
	status: inactive
en3: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:3f:ec:07:94:05 
	media: autoselect <full-duplex>
	status: inactive
en4: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	options=460<TSO4,TSO6,CHANNEL_IO>
	ether 82:3f:ec:07:94:04 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 82:3f:ec:07:94:01 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 7 priority 0 path cost 0
	member: en3 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 8 priority 0 path cost 0
	member: en4 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 9 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	options=400<CHANNEL_IO>
	ether 0e:85:90:80:bd:ef 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	options=400<CHANNEL_IO>
	ether 9e:e6:aa:52:dd:59 
	inet6 fe80::9ce6:aaff:fe52:dd59%awdl0 prefixlen 64 scopeid 0xc 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
llw0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether 9e:e6:aa:52:dd:59 
	inet6 fe80::9ce6:aaff:fe52:dd59%llw0 prefixlen 64 scopeid 0xd 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::2c41:a12d:c15:a2ad%utun0 prefixlen 64 scopeid 0xe 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::8f33:a1ef:3415:da99%utun1 prefixlen 64 scopeid 0xf 
	nd6 options=201<PERFORMNUD,DAD>
en5: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether ac:de:48:00:11:22 
	inet6 fe80::aede:48ff:fe00:1122%en5 prefixlen 64 scopeid 0x4 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
-----------------------------------
$ launchctl list | grep com.qiuyuzhou.
35974	0	com.qiuyuzhou.ShadowsocksX-NG.8000
35998	0	com.qiuyuzhou.shadowsocksX-NG.http
-	0	com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
36105	0	com.qiuyuzhou.shadowsocksX-NG.local
-	255	com.qiuyuzhou.shadowsocksX-NG.kcptun
-----------------------------------

**Comment by JoveYu** [comment]
```
 2019-09-23 19:21:41 INFO: plugin "plugins/kcptun" enabled
 2019-09-23 19:21:41 INFO: using tcp fast open
 2019-09-23 19:21:41 INFO: initializing ciphers... chacha20-ietf-poly1305
 2019-09-23 19:21:41 INFO: listening at 127.0.0.1:1080
 2019-09-23 19:21:41 INFO: tcp port reuse enabled
2019/09/23 19:21:41 version: 20190905
2019/09/23 19:21:41 address ::1:65129: too many colons in address
```

**Comment by qiuyuzhou** [comment]
@ice6 

> Active server profile:
> ServerHost=***********
> ServerPort=8989
> Method=aes-256-gcm
> Password=****************
> Plugin=
> PluginOptions=

没有给出你的kcptun 配置

**Comment by qiuyuzhou** [comment]
@JoveYu 

> 2019/09/23 19:21:41 address ::1:65129: too many colons in address

这个日志已经说明了错误.
应该是`[::1]:65129`

**Comment by JoveYu** [comment]
@qiuyuzhou  我知道这是个错误 所以我发给你  我的配置并没有错误  我更换到1.9.1以后一切正常
配置给你参考

```
{
  "local_address" : "127.0.0.1",
  "timeout" : 60,
  "password" : "xxx",
  "server" : "xxx",
  "plugin_opts" : "mode=fast2;crypt=none;key=xxx;nocomp",
  "local_port" : 1080,
  "method" : "chacha20-ietf-poly1305",
  "server_port" : 12345,
  "plugin" : "plugins/kcptun"
}
``` 
看错误描述，跟IPV6环境可能有关系

**Comment by qiuyuzhou** [comment]
@JoveYu 请问你是ipv6网络？

**Comment by JoveYu** [comment]
@qiuyuzhou 是的,内网同时有ipv4和ipv6的IP

**Comment by qiuyuzhou** [comment]
Fixes in v1.9.3

**Comment by Bearljj** [comment]
我的也是启用kcptun插件不正常：
2020-03-08 21:47:23 INFO: plugin "plugins/kcptun" enabled
 2020-03-08 21:47:23 INFO: using tcp fast open
 2020-03-08 21:47:23 INFO: initializing ciphers... chacha20
 2020-03-08 21:47:23 INFO: listening at 127.0.0.1:1086
 2020-03-08 21:47:23 INFO: tcp port reuse enabled
Incorrect Usage. flag provided but not defined: -fast-open

NAME:
   kcptun - client(with SMUX)

USAGE:
   kcptun [global options] command [command options] [arguments...]

VERSION:
   20200226

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --localaddr value, -l value      local listen address (default: ":12948")
   --remoteaddr value, -r value     kcp server address (default: "vps:29900")
   --key value                      pre-shared secret between client and server (default: "it's a secrect") [$KCPTUN_KEY]
   --crypt value                    aes, aes-128, aes-192, salsa20, blowfish, twofish, cast5, 3des, tea, xtea, xor, sm4, none (default: "aes")
   --mode value                     profiles: fast3, fast2, fast, normal, manual (default: "fast")
   --conn value                     set num of UDP connections to server (default: 1)
   --autoexpire value               set auto expiration time(in seconds) for a single UDP connection, 0 to disable (default: 0)
   --scavengettl value              set how long an expired connection can live(in sec), -1 to disable (default: 600)
   --mtu value                      set maximum transmission unit for UDP packets (default: 1350)
   --sndwnd value                   set send window size(num of packets) (default: 128)
   --rcvwnd value                   set receive window size(num of packets) (default: 512)
   --datashard value, --ds value    set reed-solomon erasure coding - datashard (default: 10)
   --parityshard value, --ps value  set reed-solomon erasure coding - parityshard (default: 3)
   --dscp value                     set DSCP(6bit) (default: 0)
   --nocomp                         disable compression
   --sockbuf value                  per-socket buffer in bytes (default: 4194304)
   --smuxver value                  specify smux version, available 1,2 (default: 1)
   --smuxbuf value                  the overall de-mux buffer in bytes (default: 4194304)
   --streambuf value                per stream receive buffer in bytes, smux v2+ (default: 2097152)
   --keepalive value                seconds between heartbeats (default: 10)
   --snmplog value                  collect snmp to file, aware of timeformat in golang, like: ./snmp-20060102.log
   --snmpperiod value               snmp collect period, in seconds (default: 60)
   --log value                      specify a log file to output, default goes to stderr
   --quiet                          to suppress the 'stream open/close' messages
   --tcp                            to emulate a TCP connection(linux)
   -c value                         config from json file, which will override the command from shell
   --help, -h                       show help
   --version, -v                    print the version
 2020-03-08 21:47:23 ERROR: plugin service exit unexpectedly

**Comment by Bearljj** [comment]
Active server profile: 
ServerHost=**************
ServerPort=29900
Method=chacha20
Password=********
Plugin=kcptun
PluginOptions=key=boci2020;crypt=aes;mode=fast2;mtu=1350;sndwnd=512;rcvwnd=512;datashard=10;parityshard=3;dscp=0; autoexpire=900

**Comment by Henry586** [comment]
> Active server profile: ServerHost=************** ServerPort=29900 Method=chacha20 Password=******** Plugin=kcptun PluginOptions=key=boci2020;crypt=aes;mode=fast2;mtu=1350;sndwnd=512;rcvwnd=512;datashard=10;parityshard=3;dscp=0; autoexpire=900

many thanks, finally found this example for plugin options for kcptun!
