### ISSUE TITLE
brew uninstall failed

### ISSUE THREAD

**Issue by guyeu** [shadowsocks/ShadowsocksX-NG#1116]
**Describe the bug**

```bash
$ brew cask upgrade shadowsocksx-ng
==> Upgrading 1 outdated package:
shadowsocksx-ng 1.8.2 -> 1.9.2
==> Upgrading shadowsocksx-ng
==> Satisfying dependencies
==> Downloading https://github.com/shadowsocks/ShadowsocksX-NG/releases/download/v1.9.2/ShadowsocksX-NG.app.1.9.2.zip
Already downloaded: /Users/***/Library/Caches/Homebrew/downloads/a719cd18f5c3aa798ec1428bb0e48387a20dca048df11304820e59f0b453fc06--ShadowsocksX-NG.app.1.9.2.zip
==> Verifying SHA-256 checksum for Cask 'shadowsocksx-ng'.
==> Removing launchctl service com.qiuyuzhou.shadowsocksX-NG.http
==> Removing launchctl service com.qiuyuzhou.shadowsocksX-NG.kcptun
==> Removing launchctl service com.qiuyuzhou.shadowsocksX-NG.local
==> Removing launchctl service com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
==> Running uninstall script /Applications/ShadowsocksX-NG.app/Contents/Resources/proxy_conf_helper
==> Purging files for version 1.9.2 of Cask shadowsocksx-ng
Error: uninstall script /Applications/ShadowsocksX-NG.app/Contents/Resources/proxy_conf_helper does not exist.
```

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 10.14.6 (18G95)
 - Version 1.8.2

**Comment by kshq1996** [comment]
> **Describe the bug**
> 
> ```shell
> $ brew cask upgrade shadowsocksx-ng
> ==> Upgrading 1 outdated package:
> shadowsocksx-ng 1.8.2 -> 1.9.2
> ==> Upgrading shadowsocksx-ng
> ==> Satisfying dependencies
> ==> Downloading https://github.com/shadowsocks/ShadowsocksX-NG/releases/download/v1.9.2/ShadowsocksX-NG.app.1.9.2.zip
> Already downloaded: /Users/***/Library/Caches/Homebrew/downloads/a719cd18f5c3aa798ec1428bb0e48387a20dca048df11304820e59f0b453fc06--ShadowsocksX-NG.app.1.9.2.zip
> ==> Verifying SHA-256 checksum for Cask 'shadowsocksx-ng'.
> ==> Removing launchctl service com.qiuyuzhou.shadowsocksX-NG.http
> ==> Removing launchctl service com.qiuyuzhou.shadowsocksX-NG.kcptun
> ==> Removing launchctl service com.qiuyuzhou.shadowsocksX-NG.local
> ==> Removing launchctl service com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
> ==> Running uninstall script /Applications/ShadowsocksX-NG.app/Contents/Resources/proxy_conf_helper
> ==> Purging files for version 1.9.2 of Cask shadowsocksx-ng
> Error: uninstall script /Applications/ShadowsocksX-NG.app/Contents/Resources/proxy_conf_helper does not exist.
> ```
> 
> **System and Shadowsocksx-NG version: (please complete the following information):**
> 
> * OS Version: 10.14.6 (18G95)
> * Version 1.8.2

**You are not manually deleted the software, you can**
        ` brew cask reinstall shadowsocksx-ng`
**it's will be the lastest version**

**Comment by guyeu** [comment]
thx, it fixed. please close this issue.
