### ISSUE TITLE
Please support chacha20-ietf

### ISSUE THREAD

**Issue by AllenBall** [shadowsocks/ShadowsocksX-NG#112]
I use chacha20-ietf with OTA, but shadowsocks-NG can't support it.

**Comment by AllenBall** [comment]
You can  update ss-local for supporting it.

**Comment by wongsyrone** [comment]
It is provided by libsodium.

**Comment by KyonLi** [comment]
I have create a pull request #114 to support it.

**Comment by qiuyuzhou** [comment]
I have upgrade shadowsocks-libev to 2.5.6 in latest develop branch.
