### ISSUE TITLE
看见有了 v2ray 插件功能，请问可以用吗？怎么用？抱歉我没找到教程。

### ISSUE THREAD

**Issue by smart-z** [shadowsocks/ShadowsocksX-NG#1120]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by qiuyuzhou** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/wiki/SIP003-Plugin

**Comment by smart-z** [comment]
> https://github.com/shadowsocks/ShadowsocksX-NG/wiki/SIP003-P画lugin

哎，您这个教程太高大上了，还是不会用。。。
