### ISSUE TITLE
macOS上用最新版显示on，但是实际上无法翻墙；前人的方法基本上已经尝试了。

### ISSUE THREAD

**Issue by SizheWei** [shadowsocks/ShadowsocksX-NG#1125]
**如题，不能用mac连接吗？**

**Comment by chenjibin** [comment]
我用的最新的 可以翻

**Comment by Aphrodites1995** [comment]
我有同样的问题。显示好使，但是不能翻，IP也是我自己的。

**Comment by chrisyu-chn** [comment]
代理没设置好 或者ip被block了

**Comment by SizheWei** [comment]
> 我用的最新的 可以翻

请问您使用的系统也是macOS， 用的是Shadowsocksx-ng Version 1.9.2 吗？是入门版的还是旗舰版的呀 😂

**Comment by yuqiangit** [comment]
换个ip基本上五分钟就被封了。

**Comment by Aldrich-TB** [comment]
设置没变，更新1.9.2之后就不能用了，kcptun和ss都不行，PC的SS依旧可以用。是更新之后设置规范不一样吗？

**Comment by mouseroser** [comment]
节点被封了

**Comment by SizheWei** [comment]
> 节点被封了

有可能是这样，等过段时间我再试一下，看看是节点的问题还是macOS上支持的问题。

**Comment by SizheWei** [comment]
是的，节点被封了，我在其他地方获得的节点，然后用同样的方法把端口等信息输入进去可以登梯。。。
