### ISSUE TITLE
如何卸载后删除已保存的服务器缓存

### ISSUE THREAD

**Issue by liaokaime** [shadowsocks/ShadowsocksX-NG#1126]
我想卸载并重新安装，但重新安装后仍然存在了卸载前保存的服务器信息，如何完整的卸载并清除缓存？

**Comment by fuzheng1998** [comment]
有一个文件夹`.ShadowsocksX-NG/`里面配置文件删了就行

**Comment by liaokaime** [comment]
> 
> 
> 有一个文件夹`.ShadowsocksX-NG/`里面配置文件删了就行

有比较具体一点的路径吗？

**Comment by fuzheng1998** [comment]
嗯就是当前用户目录下

**Comment by liaokaime** [comment]
我找到了这个文件夹并删除了它，但是重启后，仍然没有清除掉服务器信息，只是清除了gfwlist

**Comment by Aldrich-TB** [comment]
这个文件夹下只有gfwlist和user-rule，没有服务器设置

**Comment by winterbure** [comment]
我和你一样的问题，同求解决办法，不知道你现在解决没有

**Comment by fuzheng1998** [comment]
这里`~/Library/Application Support/ShadowsocksX-NG/`

**Comment by liaokaime** [comment]
> 
> 
> 这里`~/Library/Application Support/ShadowsocksX-NG/`

我试着关闭了shadowsocks，并且删除了`~/Library/Application Support/ShadowsocksX-NG/`这个文件夹，然后再次启动shadowsocks，但是服务器的保存信息仍然没有被清除

**Comment by fuzheng1998** [comment]
可以看看这个[FAQ](https://github.com/shadowsocks/ShadowsocksX-NG/wiki/FAQ)

**Comment by liaokaime** [comment]
> 
> 
> 可以看看这个[FAQ](https://github.com/shadowsocks/ShadowsocksX-NG/wiki/FAQ)

多谢
