### ISSUE TITLE
mac os安装后无法推出

### ISSUE THREAD

**Issue by Holden-Lin** [shadowsocks/ShadowsocksX-NG#1129]
1.  安装后没有传统的tuo拖动图标到“应用程序”完成安装的界面
2. 运行后，在桌面会存在一个宗卷，并且无法推出（不是错别字）
感觉应该没有正确安装？

<img width="605" alt="屏幕快照 2019-09-27 下午10 41 08" src="https://user-images.githubusercontent.com/26894421/65778171-048a2c00-e178-11e9-89ed-62c34fbdcdb9.png">

<img width="162" alt="屏幕快照 2019-09-27 下午10 43 13" src="https://user-images.githubusercontent.com/26894421/65778312-487d3100-e178-11e9-99f8-f26432502c4c.png">

**Comment by qiuyuzhou** [comment]
这有-R8的后缀，这是其他人改的衍生版。这里项目发布只是zip包

**Comment by qiuyuzhou** [comment]
你应该是直接执行镜像里的app，因为正在运行，所以不让推出
