### ISSUE TITLE
OTA功能有问题。header不对

### ISSUE THREAD

**Issue by liaozibo** [shadowsocks/ShadowsocksX-NG#113]
windeows c# 最新版本是有ota功能的，上面的ota也是正确的。
这个mac版本的 ota功能 在我服务器日志上，直接tcp首包 就错误了。
查看python 版本源码是可以看出ota实现的
目前这个版本在我mac上ota是不可用 ，同一个服务器，在我windows上的c#版本是可以用的，而且很好用。

**Comment by liaozibo** [comment]
在未开启ota 的时候 解密后包头 第一个字节 只有可能是
0b00000001 0b00000011 0b00000100 三种情况 分别对应为 ADDRTYPE_IPV4 ADDRTYPE_IPV6 ADDRTYPE_HOST 三种情况。
根据 shadowsocks.org 官网所说：
OTA的标示为：0b00010000 ，开启OTA 后 ，解密后的第一个字节只有可能为 0b00010001 0b00010011 0b00010100
这三种情况，其它的情况均不会通过 第一步header 认证。服务器直接拒绝链接了哦。

**Comment by liaozibo** [comment]
不要意思，我自己选择加密方式 疏忽选错了，OTA 是正常的。不好意思打扰了。

**Comment by wangxufire** [comment]
OTA是干什么用的？

**Comment by liaozibo** [comment]
防止cca攻击用的。请看官网说明

**Comment by liaozibo** [comment]
header 是对了，不过老感觉同一个服务器，同一个 wifi环境下，ng版本的ota功能明显比windows c# 版本的ota慢很多。。。不知道咋的。解包组包不对～？
