### ISSUE TITLE
mac下任何模式都翻不了墙,什么模式都 可以访问国内网站,求指教是为啥怎么都解决不了

### ISSUE THREAD

**Issue by xiaodaiit** [shadowsocks/ShadowsocksX-NG#1132]
![image](https://user-images.githubusercontent.com/16606567/65873396-959a1680-e3b5-11e9-90c9-5e0a112e4180.png)

**Comment by Holden-Lin** [comment]
我的也很不稳定 手机端倒是可以

**Comment by xiaodaiit** [comment]
> 我的也很不稳定 手机端倒是可以

关键是 我的mac就上不了  Windows 和手机都行

**Comment by mrdulin** [comment]
下载了最新版: 版本 1.9.2 (1)
改了ssserver端口配置，mac连上了，打开Youtube看了2分钟，马上不行了。

**Comment by sophiechan512** [comment]
原来我不是一个人，折腾一天了。有知道的大神通知一下，谢谢

**Comment by followztx** [comment]
ss流量已经被识别了，目前tor配合ss,可以规避。已经ping不通的结点，通过tor可连上了。
教程链接：https://www.imtrq.com/archives/738

**Comment by mrdulin** [comment]
@followztx 有没有确凿的证据证明ss流量已经被识别？

**Comment by Holden-Lin** [comment]
v2ray稳定很多

**Comment by followztx** [comment]
> @followztx 有没有确凿的证据证明ss流量已经被识别？
经过大量网友的验证了，

**Comment by xiaodaiit** [comment]
> v2ray稳定很多

这个也不能用  我是服了 就mac不能用

**Comment by xiaodaiit** [comment]
> > @followztx 有没有确凿的证据证明ss流量已经被识别？
> > 经过大量网友的验证了，

这也有点疑问吧  只有mac被识别了吗  其他都没事

**Comment by Jane1587** [comment]
请问有人解决了吗

**Comment by xiaodaiit** [comment]
> 大家都遇到这个问题，并且国庆长假已过，我只能根据自身的使用情况用排除法说明一些情况了：
> 
> 1. 排除特定地区才有这个问题，起初我还以为是甘肃地区（红色根据地）封锁更加严重，国庆放假前在上海
> 2. 排除70周年国庆因素（不能出任何差错，先封为敬）
> 3. 最新版的shadowsocks-ng也使用过，同样的问题
> 4. 稳定使用了一年的虚拟主机，日本东京节点，排除虚拟机的因素，改过ip，端口，使用2分钟，马上不行
> 5. 排除电信网络运营商的问题，网络是没问题的，用v2ray稳定富强
> 
> 已经不知道什么问题了，是作者被收编了，还是要黄了，坐等作者解答
> 
> 期待一篇专业解答的文章，证据确凿，并经过各种实验验证，同学们别怕，有句话叫
> 
> > 道高一尺，魔高一丈

不知道是不是真的所说被识别了ssr

**Comment by followztx** [comment]
> > > @followztx 有没有确凿的证据证明ss流量已经被识别？
> > > 经过大量网友的验证了，
> 
> 这也有点疑问吧 只有mac被识别了吗 其他都没事

ss的流量特征已经能精准识别了，通过meek混淆还能凑合，通过tor双重代理完美解决。

**Comment by followztx** [comment]
解决方案：
浏览器---tor(9150)---ss客户端(1080)---ss服务端--tor中继(3个以上)---被樯的站点
https://www.imtrq.com/archives/738
https://www.torproject.org/dist/torbrowser/8.5.5/TorBrowser-8.5.5-osx64_zh-CN.dmg
