### ISSUE TITLE
请问v2ray怎么用

### ISSUE THREAD

**Issue by GuanHenan** [shadowsocks/ShadowsocksX-NG#1135]
在portal.shadowsocks.club的通知里有一条“我们为所有客户提供了一条 v2ray / vmess 的测试线路，请访问您的服务详情页面查看。 您需要使用支持 vmess 的客户端连接，请在下载中心下载对应支持的客户端。”
请问这个怎么用啊？我下载了v2ray-core v1.4.1，然后扫描了V2Ray [beta]的二维码，依然等不上google，求指点！

**Comment by awenaw** [comment]
这个好像要两台主机做操作

**Comment by zouyuefen** [comment]
core是命令行的，还要下载个GUI程序配合使用就可以了。https://github.com/Cenmrev/V2RayW.git

**Comment by jechtliu** [comment]
> core是命令行的，还要下载个GUI程序配合使用就可以了。https://github.com/Cenmrev/V2RayW.git

mac怎么搞？

**Comment by zouyuefen** [comment]
> > core是命令行的，还要下载个GUI程序配合使用就可以了。https://github.com/Cenmrev/V2RayW.git
> 
> mac怎么搞？

mac的，https://github.com/yanue/v2rayu/

**Comment by qiuyuzhou** [comment]
Please google first

**Comment by zhugw** [comment]
可以参考：https://justmysocks3.net/members/index.php?rp=/knowledgebase/10/How-to-use-Just-My-Socks-on-a-Mac-v2ray.html
