### ISSUE TITLE
mac升级到10.15正式版，google等网页打不开了，升级之前还能打开

### ISSUE THREAD

**Issue by hudingyin** [shadowsocks/ShadowsocksX-NG#1142]
Catalina今天正式发布，第一时间就升级了，升级完成之后就不能打开google系列网页

**Comment by mahuiplus** [comment]
一样，尝试改了端口之后可以，过一会又不行了
然后退出，再打开，又可以了。过一会就又不行了。。。

**Comment by hackeryutu** [comment]
一样

**Comment by fangmd** [comment]
我更新 ss 后可以了

**Comment by micezhao** [comment]
怎么弄啊，大神们，自从国庆节前几天开始到现在，一直不能用啊

**Comment by JianWenJun** [comment]
我也是，大佬怎么弄呀

**Comment by JianWenJun** [comment]
> 一样，尝试改了端口之后可以，过一会又不行了
> 然后退出，再打开，又可以了。过一会就又不行了。。。

尝试更新一下SS软件版本到1.9

**Comment by xiaodaiit** [comment]
是啊 我也遇到了 怎么都不行 我的ss已经是最新版本了

**Comment by gaby77** [comment]
我也是，macOS更新到10.15了，然后就用不了啦，啥情况呢

**Comment by hudingyin** [comment]
我解决了。

我用CleanMymac X 4.4.7卸载shadowsocks，然后再重新安装，就可以用了。之前是直接用扔进废纸篓的方式卸载，（甚至关机重启），再重装，不管是最新版shadowsocks还是老版本，都不行。

**Comment by gaby77** [comment]
我用CleanMyMac卸载了shadowsocks，然后重新安装，还是不行呀

**Comment by Jane1587** [comment]
> Catalina今天正式发布，第一时间就升级了，升级完成之后就不能打开google系列网页

我也是，倒腾了一天了

**Comment by gsp412** [comment]
+1, 升级完后 不稳定，有时能行，有时gg

**Comment by hudingyin** [comment]
bug真是顽固，看来得大神出手了，我用CleanMyMac卸载的解决方法看来不是对所有人有效。我目前为止用着“香港 HKBN A | Netflix”通道，走PAC自动模式，一直很正常。

> 我用CleanMyMac卸载了shadowsocks，然后重新安装，还是不行呀

**Comment by mahuiplus** [comment]
> > 一样，尝试改了端口之后可以，过一会又不行了
> > 然后退出，再打开，又可以了。过一会就又不行了。。。
> 
> 尝试更新一下SS软件版本到1.9

已经1.9.2最新版本了

**Comment by mahuiplus** [comment]
> 我用CleanMyMac卸载了shadowsocks，然后重新安装，还是不行呀

尝试了，一样不行，现在不能用的时候就是改端口，退出，再打开，知道能用，每次过几分钟就又不行了

**Comment by qian-xiaoyang** [comment]
google drive的mac客户端登录不了怎么办，好烦

**Comment by Pudgedd** [comment]
俺也一样，有没有大神有解决方案

**Comment by ldw4033** [comment]
我发现，一会连接正常就不好用，需要关闭，再打开就好用，一会又不好用了

**Comment by gaoyiniy** [comment]
同样升级为10.15后，无论怎么切换都用不了。

**Comment by Crescentz** [comment]
同样不好用

**Comment by smk666** [comment]
> Catalina今天正式发布，第一时间就升级了，升级完成之后就不能打开google系列网页



> 我用CleanMyMac卸载了shadowsocks，然后重新安装，还是不行呀

我也是升级到10.15以后就不能用了，用CleanMyMac卸载了shadowsocks，然后重新安装，也还是不行！

**Comment by micezhao** [comment]
如果你的代理地址填写的是域名的话，可以试着换成对应的ip地址试试

**Comment by zhangzhou1128** [comment]
是Mac最新的Catalina (10.15)版本吗？我升级到这个版本后，也出现这个问题，应该是这个系统的兼容性问题

**Comment by micezhao** [comment]
我也是升级到了10.15 把代理的域名换成ip地址就可以用了

**Comment by zhangzhou1128** [comment]
最新进展：我修改本地默认的http代理、sock5代理的端口（1086/1087/1089这些），就可以了。其他升级到Mac Catalina后，有问题的童鞋，可以试试

**Comment by HeJiaNong** [comment]
> 最新进展：我修改本地默认的http代理、sock5代理的端口（1086/1087/1089这些），就可以了。其他升级到Mac Catalina后，有问题的童鞋，可以试试

虽然能使用，但是这样子就等于开启全局模式了，AppStore都访问不了，只能手动取消系统代理

**Comment by stevenlee87** [comment]
> 我解决了。
> 
> 我用CleanMymac X 4.4.7卸载shadowsocks，然后再重新安装，就可以用了。之前是直接用扔进废纸篓的方式卸载，（甚至关机重启），再重装，不管是最新版shadowsocks还是老版本，都不行。

我尝试了这种方法。一开始是可以的。但是使用一会儿又不行了。
