### ISSUE TITLE
最新源码编译的时候会出现“user-privoxy.config”不存在。"

### ISSUE THREAD

**Issue by zhenio** [shadowsocks/ShadowsocksX-NG#1145]
ShadowsocksX-NG[19772:413594] Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=4 "文件“user-privoxy.config”不存在。"

**Comment by jackfrow** [comment]
兄弟，你这个怎么解决的。

**Comment by sdus007** [comment]
closed？解决方法？

**Comment by Axure** [comment]
手动创建应该就可以了
```
mkdir -p ~/.ShadowsocksX-NG
touch ~/.ShadowsocksX-NG/user-privoxy.config
```
