### ISSUE TITLE
期望切换代理模式的时候只在自动和全局模式之间切换

### ISSUE THREAD

**Issue by Carlis-cpu** [shadowsocks/ShadowsocksX-NG#1147]
习惯了一直以来只有两种模式

更新之后变成了三个模式，每次要多按一次快捷键，而且路过 manual 模式的时候还会断网，特别不方便

感谢！

**Comment by JoveYu** [comment]
手动其实是非常实用的   比如我都是实用手动配置chrome插件来使用，这样不影响系统代理配置

**Comment by Carlis-cpu** [comment]
> 手动其实是非常实用的 比如我都是实用手动配置chrome插件来使用，这样不影响系统代理配置

我以前也是这样做的，但后来自从 Chrome 69 改版了设计 tab height 占据了屏幕太大空间之后就弃掉这个浏览器了。再后来 Safari 升到 13 不能用 extension 了以后，就真的只能零插件手动快捷键切换了……

**Comment by JoveYu** [comment]
@Carlis-cpu 你可以考虑一直开启自动模式   然后使用`编辑PAC用户自定规则`来添加要代理的规则

**Comment by qiuyuzhou** [comment]
Try v1.9.3
