### ISSUE TITLE
mac系统很久都用不了了，各位大神，你们的可以使用吗？

### ISSUE THREAD

**Issue by liuyunchuan** [shadowsocks/ShadowsocksX-NG#1149]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**Diagnoisis file:**

Please first upgrade to the latest version.
Then export the diagnosis file and upload it to here.

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by followztx** [comment]
和系统有啥关系，是你的服务端ip被KO了吧

**Comment by followztx** [comment]
服务端ping不通的解决方案(tor+ss双重代理):
浏览器---tor(9150)---ss客户端(1080)---ss服务端--tor中继(3个以上)---被樯的站点

教程链接：https://www.imtrq.com/archives/738
tor下载：https://www.torproject.org/dist/torbrowser/8.5.5/TorBrowser-8.5.5-osx64_zh-CN.dmg

**Comment by guoziren** [comment]
很久不能用了

**Comment by zhangzhou1128** [comment]
是Mac最新的Catalina (10.15)版本吗？我升级到这个版本后，也出现这个问题，应该是这个系统的兼容性问题

**Comment by liuyunchuan** [comment]
我的操作系统是 10.14.5，软件版本是ShadowsocksX-NG1.6.1(1)，前段时间一直用不了，这几天设置为PAC自动模式，并且选择从GFC List 更新PAC之后暂时能用，但是网速非常慢。

**Comment by Aldrich-TB** [comment]
系统10.15，软件版本1.9.2，kcptun插件使用没问题的

**Comment by chrislone** [comment]
Centos8 装上之后用不了，用 Centos7 装就可以了。
但是一旦装上之后就不能修改密码，不能改端口，如果修改之后就连不上，改回来又可以连上。

**Comment by liuyunchuan** [comment]
可以使用啊，你试试使用PAC自动模式，然后从GFW List更新PAC。
