### ISSUE TITLE
关闭模式下后台监听端口未运行

### ISSUE THREAD

**Issue by FredYuuu** [shadowsocks/ShadowsocksX-NG#115]
NG版本后台未运行在127.0.0.1:1080（我把1081改成了原版的配置1080）上吗？
这样使用proxyOmega时会很困扰
需要如何配置？

**Comment by FredYuuu** [comment]
Sorry 直到我理解了手动模式...

**Comment by py4h0n** [comment]
@FredYuuu  能否解释一下 手动模式，操作了半天没搞明白

**Comment by FredYuuu** [comment]
手动模式就是需要原版ss的关闭状态 ss会在127.0.0.1:1086端口继续运行
