### ISSUE TITLE
升级到1.9.2扫描二维码，可能过长，导致无法选择列表中其他的服务器。

### ISSUE THREAD

**Issue by UncleCatWu** [shadowsocks/ShadowsocksX-NG#1150]
![image](https://user-images.githubusercontent.com/18675524/66636838-7f594980-ec44-11e9-8ffb-304b4d35fc6a.png)

**Comment by UncleCatWu** [comment]
再请问下配置文件的路径在哪儿？

**Comment by lrhddzyj** [comment]
删除备注就好

**Comment by UncleCatWu** [comment]
> 删除备注就好

大佬，在哪儿删除备注呢？

**Comment by JoveYu** [comment]
# 号后面的就是备注

**Comment by ThJoker** [comment]
现在没法改备注了，那个菜单根本就失效了。想问下配置文件在哪里

**Comment by ThJoker** [comment]
配置文件删除后，同样没法选择，菜单上没有变化

**Comment by JoveYu** [comment]
你可以参考 #1151 来删除

**Comment by ThJoker** [comment]
> 你可以参考 #1151 来删除
试了，删除之后重新打开ss，菜单还是没有改变

**Comment by ThJoker** [comment]
> > 你可以参考 #1151 来删除
> > 试了，删除之后重新打开ss，菜单还是没有改变



> 你可以参考 #1151 来删除

试了，删除之后重新打开ss，菜单还是没有改变

**Comment by ThJoker** [comment]
> 你可以参考 #1151 来删除

试了，删除之后重新打开ss，菜单还是没有改变

**Comment by lrhddzyj** [comment]
> > 删除备注就好
> 
> 大佬，在哪儿删除备注呢？
![image](https://user-images.githubusercontent.com/17866623/66805889-bbe4b800-ef58-11e9-8da0-104c3ddfbea2.png)

![image](https://user-images.githubusercontent.com/17866623/66805871-b1c2b980-ef58-11e9-8f5c-3eae30a5cdc6.png)

**Comment by ThJoker** [comment]
> > > 删除备注就好
> > 
> > 
> > 大佬，在哪儿删除备注呢？
> > ![image](https://user-images.githubusercontent.com/17866623/66805889-bbe4b800-ef58-11e9-8da0-104c3ddfbea2.png)
> 
> ![image](https://user-images.githubusercontent.com/17866623/66805871-b1c2b980-ef58-11e9-8f5c-3eae30a5cdc6.png)

现在的问题是，因为过长，根本选不到这个菜单了，直接失效了
