### ISSUE TITLE
有人知道怎么重置1.9.2版本的所有服务器配置吗？急急急~

### ISSUE THREAD

**Issue by UncleCatWu** [shadowsocks/ShadowsocksX-NG#1151]
如题

**Comment by JoveYu** [comment]
可以尝试删除
```
~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist
~/Library/Application Support/ShadowsocksX-NG/
```

**Comment by ThJoker** [comment]
同样的问题，F&Q解决不了

**Comment by qiuyuzhou** [comment]
@JoveYu 的方法是对的
记得先关闭软件
```
rm -f ~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist
```

**Comment by qiuyuzhou** [comment]
或者用xcode编辑~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist

**Comment by ThJoker** [comment]
> 或者用xcode编辑~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist

解决了，必须得用XCODE，原本用sublime打开根本看不懂

**Comment by ThJoker** [comment]
> 或者用xcode编辑~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist

编辑了之后服务器列表依旧失效，没法选择
