### ISSUE TITLE
为什么mac打不开啊？

### ISSUE THREAD

**Issue by ryanwlb** [shadowsocks/ShadowsocksX-NG#1154]
各位大佬问个奇怪问题 
我用公司网络Mac打不开google，偶尔能打开一下，打不开效果类似于网速特别慢那种，不是直接就打不开  其他windows同事用公司网络就可以打开
我用家里网络就可以打开google
好奇怪的问题有人知道为什么么？

**Comment by ryanwlb** [comment]
有人遇到过这个问题么？

**Comment by zhangzhou1128** [comment]
是Mac最新的Catalina (10.15)版本吗？我升级到这个版本后，也出现这个问题，应该是这个系统到兼容性问题

**Comment by liaozd** [comment]
me2

**Comment by bruce2021** [comment]
我这边可以啊。。 系统10.15，客户端1.92
