### ISSUE TITLE
mac系统挂上ssr外网内网都上不去 试过删除重装 没用 

### ISSUE THREAD

**Issue by dancychen028** [shadowsocks/ShadowsocksX-NG#1157]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**Diagnoisis file:**

Please first upgrade to the latest version.
Then export the diagnosis file and upload it to here.

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**
[](url)

**Comment by dancychen028** [comment]
<img width="935" alt="屏幕快照 2019-10-14 上午11 11 54" src="https://user-images.githubusercontent.com/56527177/66727712-8f0aa500-ee73-11e9-80bb-23b7c095baf7.png">

**Comment by zhangzhou1128** [comment]
是Mac最新的Catalina (10.15)版本吗？我升级到这个版本后，也出现这个问题，应该是这个系统的兼容性问题

**Comment by dancychen028** [comment]
> 是Mac最新的Catalina (10.15)版本吗？我升级到这个版本后，也出现这个问题，应该是这个系统的兼容性问题

是10.14的版本

**Comment by zhangzhou1128** [comment]
最新信息：修改本地默认的端口配置，貌似可以了，可能是默认的端口有冲突，你也可以试试
<img width="486" alt="ssx1" src="https://user-images.githubusercontent.com/50696838/66730704-fa5d7280-ee85-11e9-9dc6-d9425ad31d94.png">
<img width="478" alt="ssx2" src="https://user-images.githubusercontent.com/50696838/66730705-faf60900-ee85-11e9-86a2-6f8763d4cf20.png">

**Comment by dancychen028** [comment]
> 最新信息：修改本地默认的端口配置，貌似可以了，可能是默认的端口有冲突，你也可以试试
> <img alt="ssx1" width="486" src="https://user-images.githubusercontent.com/50696838/66730704-fa5d7280-ee85-11e9-9dc6-d9425ad31d94.png">
> <img alt="ssx2" width="478" src="https://user-images.githubusercontent.com/50696838/66730705-faf60900-ee85-11e9-86a2-6f8763d4cf20.png">

改了以后依旧不可以

**Comment by Jane1587** [comment]
> 最新信息：修改本地默认的端口配置，貌似可以了，可能是默认的端口有冲突，你也可以试试
> <img alt="ssx1" width="486" src="https://user-images.githubusercontent.com/50696838/66730704-fa5d7280-ee85-11e9-9dc6-d9425ad31d94.png">
> <img alt="ssx2" width="478" src="https://user-images.githubusercontent.com/50696838/66730705-faf60900-ee85-11e9-86a2-6f8763d4cf20.png">

咋改呀？

**Comment by chxk** [comment]
> 最新信息：修改本地默认的端口配置，貌似可以了，可能是默认的端口有冲突，你也可以试试
> <img alt="ssx1" width="486" src="https://user-images.githubusercontent.com/50696838/66730704-fa5d7280-ee85-11e9-9dc6-d9425ad31d94.png">
> <img alt="ssx2" width="478" src="https://user-images.githubusercontent.com/50696838/66730705-faf60900-ee85-11e9-86a2-6f8763d4cf20.png">

10.15表示相同问题，按你的方法无效...

**Comment by wyfang** [comment]
也不行啊。

**Comment by ctmakro** [comment]
同样遇到此问题。

**Comment by qiuyuzhou** [comment]
不支持SSR协议
