### ISSUE TITLE
Mac这边可以访问了~~

### ISSUE THREAD

**Issue by sexylin** [shadowsocks/ShadowsocksX-NG#1158]
是算法更新了还是国庆结束GFW那边放开管制了？

**Comment by xiaodaiit** [comment]
我的还是不行啊  访问不了

**Comment by 730045** [comment]
我的也不行，求问大佬怎么解决，是需要设置什么东西吗？

**Comment by cpmzwj** [comment]
怎么解决啊，升级后i就使用不了

**Comment by yunlonggmail** [comment]
用1.7ShadowsocksX-NG版本的试试，我使用1.7ShadowsocksX-NG的可以上去，网速比较慢。
多试几个服务器

**Comment by jinhyhenry** [comment]
求portal地址。。。

**Comment by qianbinbin** [comment]
升级Catalina后无法使用，经常断

**Comment by liaozd** [comment]
升级Catalina后无法使用，没有成功过

**Comment by lyc59621** [comment]
升级Catalina后无法使用，手机可以，怎么办
