### ISSUE TITLE
如何配置tls1.2_ticket_auth混淆？插件和插件配置该怎么填？

### ISSUE THREAD

**Issue by ForestZhao** [shadowsocks/ShadowsocksX-NG#1164]

**Comment by reincc** [comment]
用这个吧，这个可以配置混淆和协议
https://github.com/qinyuhang/ShadowsocksX-NG-R/releases/tag/1.4.4-r8

**Comment by ForestZhao** [comment]
> 用这个吧，这个可以配置混淆和协议
> https://github.com/qinyuhang/ShadowsocksX-NG-R/releases/tag/1.4.4-r8

可以了，多谢
