### ISSUE TITLE
shadowsocksX-NG 1.9.2 找不到混淆协议，不支持 SSR 了么？

### ISSUE THREAD

**Issue by fmljjyy** [shadowsocks/ShadowsocksX-NG#1170]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**Diagnoisis file:**

Please first upgrade to the latest version.
Then export the diagnosis file and upload it to here.

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by qiuyuzhou** [comment]
重来不支持SSR，如果你以前的版本支持，那是其他人改过的衍生版本。

**Comment by fmljjyy** [comment]
哦，这样啊，我才仔细看了下，原来是 NG-R，这个分支不是你写的？
