### ISSUE TITLE
从剪贴板导入配置链接时，带的备注不支持中文。

### ISSUE THREAD

**Issue by joy-yu** [shadowsocks/ShadowsocksX-NG#1172]
**Describe the bug**
如题，从剪贴板导入配置链接时，带的备注不支持中文，会直接报错，只能 encodeURI 后导入。
不过通过扫描二维码导入的配置是可以看到中文的，希望可以改善下。

**To Reproduce**
剪贴板导入配置链接时，备注带中文，会直接报错。

**Expected behavior**
导入链接支持中文备注。

**Screenshots**
![image](https://user-images.githubusercontent.com/9348314/67743623-2c5ffe80-fa5a-11e9-97e1-b6942373b84f.png)

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OSX Version: 10.13.2
 - Shadowsocksx-NG: 1.9.2

**Comment by qiuyuzhou** [comment]
按URL的标准，#后的内容必须是URL escaped
应该是你的链接来源没有遵守URL标准。

**Comment by joy-yu** [comment]
> 按URL的标准，#后的内容必须是URL escaped
> 应该是你的链接来源没有遵守URL标准。

我知道编码后导入是没问题的，只是这样看编码后的中文文字实在太不友好了。
