### ISSUE TITLE
服务器列表菜单无法显示

### ISSUE THREAD

**Issue by sunnibfgi** [shadowsocks/ShadowsocksX-NG#1179]
鼠标移动到服务器选项 无法展开显示列表菜单项 另外服务器当前项是乱码模式

**Comment by sunnibfgi** [comment]
<img width="765" alt="截屏2019-10-31上午9 55 43" src="https://user-images.githubusercontent.com/12179856/67918196-4292c980-fbd6-11e9-9ac2-58ddadd15be0.png">

**Comment by qiuyuzhou** [comment]
用最新的1.9.3
