### ISSUE TITLE
v1.9.3让系统变卡并且联网不稳定

### ISSUE THREAD

**Issue by HugoDing** [shadowsocks/ShadowsocksX-NG#1184]
**Describe the bug**
v1.9.3让系统变卡并且不稳定

**To Reproduce**
升级1.9.3版本后，系统变卡，关闭或者降级1.9.2后恢复正常

macOS Catalina 10.15

**Comment by leafjame** [comment]
我的 Catalina 10.15  用 NG 的各个版本都上不了外网啊，请问兄嘚怎么做到的？

**Comment by HugoDing** [comment]
> 我的 Catalina 10.15 用 NG 的各个版本都上不了外网啊，请问兄嘚怎么做到的？

一直能用，没做过特别的修改，只是最新版本有些问题

**Comment by leafjame** [comment]
> > 我的 Catalina 10.15 用 NG 的各个版本都上不了外网啊，请问兄嘚怎么做到的？
> 
> 一直能用，没做过特别的修改，只是最新版本有些问题

好多人都用不了了。。你用的1.9.2嘛？

**Comment by HugoDing** [comment]
> > > 我的 Catalina 10.15 用 NG 的各个版本都上不了外网啊，请问兄嘚怎么做到的？
> > 
> > 
> > 一直能用，没做过特别的修改，只是最新版本有些问题
> 
> 好多人都用不了了。。你用的1.9.2嘛？

是的
