### ISSUE TITLE
1.9.3版本全新下载无法运行

### ISSUE THREAD

**Issue by kevin-lucifer** [shadowsocks/ShadowsocksX-NG#1185]
复现方式：
在从未下载过ss的机器上下载1.9.3版本，放到application中，双击打开。
结果：无反应，进程列表中无ss相关进程。

暂时解决方法：下载旧版1.9.2 运行后，再下载1.9.3，可以正常工作。 

辛苦后续版本解决这个问题。

**Comment by DearTanker** [comment]
额，原来要这样操作。。怪不得直接打不开。。

**Comment by YenBu** [comment]
我这台运行过1.9.2版本的电脑上再用1.9.3，照样时好时坏，上午能用，下午又连不上了

**Comment by YueminHu** [comment]
感谢分享 我今天捣鼓了半天都打不开 原来是这样

**Comment by LiangFuzhi** [comment]
我也是打不开

**Comment by LiangFuzhi** [comment]
无法打开“ShadowsocksX-NG”，因为Apple无法检查其是否包含恶意软件。

**Comment by andylin9404** [comment]
> 无法打开“ShadowsocksX-NG”，因为Apple无法检查其是否包含恶意软件。

打开terminal 命令行工具
输入命令：sudo spctl --master-disable
输入密码即可解决；

**Comment by Jaylee89** [comment]
打开terminal 命令行工具
输入命令：sudo spctl --master-enable
输入密码即可关闭`任何来源`选项

**Comment by Jesse-Fan** [comment]
> > 无法打开“ShadowsocksX-NG”，因为Apple无法检查其是否包含恶意软件。
> 
> 打开terminal 命令行工具
> 输入命令：sudo spctl --master-disable
> 输入密码即可解决；

我是用brew 安装的ng 执行上面命令行 打开了任何来源 但是还是无法打开ng 但是进程能看到shadowsocks

**Comment by zengxs** [comment]
ShadowsocksX-NG 需要读取 `~/.ShadowsocksX-NG/user-privoxy.config` 这个配置文件才能运行，但是 1.9.3 中似乎没有处理该文件不存在的情况。

在这个位置手动一个空文件，1.9.3 就可以正常运行了

在终端中执行下面的命令就可以创建文件：

```sh
mkdir ~/.ShadowsocksX-NG && touch ~/.ShadowsocksX-NG/user-privoxy.config
```

**Comment by Jesse-Fan** [comment]
> ```shell
> mkdir ~/.ShadowsocksX-NG && touch ~/.ShadowsocksX-NG/user-privoxy.config
> ```

可以运行了 谢谢🙏 这个可以提一个pr吧？

**Comment by wyfang** [comment]
新电脑直接下载 1.9.4 无法运行。需要先下载 1.9.2 版本安装运行，然后在替换安装 1.9.4 才可以正常运行。
