### ISSUE TITLE
未设置开机自启，却一直占用监听端口

### ISSUE THREAD

**Issue by learningis1st** [shadowsocks/ShadowsocksX-NG#124]
开机后，未手动开启任何应用程序：

<img width="623" alt="2016-11-03 6 14 08" src="https://cloud.githubusercontent.com/assets/14539571/19962234/ad603578-a1f1-11e6-8018-68fb3c7d7b14.png">

<img width="592" alt="2016-11-03 6 18 37" src="https://cloud.githubusercontent.com/assets/14539571/19962287/f4b048d2-a1f1-11e6-8742-6395ef954bbe.png">

（ShadowsocksX-NG v1.2 运行于 macOS Sierra 10.12.1 (16B2555)）

**Comment by qiuyuzhou** [comment]
正常，看readme
