### ISSUE TITLE
最新版的问题

### ISSUE THREAD

**Issue by py4h0n** [shadowsocks/ShadowsocksX-NG#125]
Shadowsocks-NG与Shadowsocks的区别
我测试发现，Shadowsocks-NG在turn off的情况下，并不在本地监听1080端口，但是shadowsocks在turn off的情况下，仍然可以。Shadowsocks-NG能不能实现turn off的情况下，仍然监听？这样的话，就可以配合proxifier对单个应用进行代理了。
BTY， mac下什么时候可以实现负载均衡？

**Comment by Noisyfox** [comment]
你说的turn off应该是指关闭全局代理吧？

> Added a manual mode which won't configure the system proxy settings. Then you could configure your apps to use socks5 proxy manual.

**Comment by py4h0n** [comment]
@Noisyfox 不是，我说的turn off指的是shadowsocks的状态，跟代理模式（全局还是PAC）没有关系

**Comment by py4h0n** [comment]
@Noisyfox 
我指的是这个
![image](https://cloud.githubusercontent.com/assets/21031426/19995397/40e0cd04-a22d-11e6-92ea-2d87d9ca66ed.png)

**Comment by py4h0n** [comment]
@qiuyuzhou 能不能解答一下？谢谢~

**Comment by qiuyuzhou** [comment]
请用手动模式
ss服务任然在工作，只是不去配置系统代理设置

**Comment by laye0619** [comment]
使用手动模式，应该怎么配置系统代理？还是希望用pac区分国内国外
