### ISSUE TITLE
【推荐】一键搭建ss/ssr服务器教程，简单方便

### ISSUE THREAD

**Issue by corajharris75** [shadowsocks/ShadowsocksX-NG#1331]
[自建ss/ssr服务器教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAss%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B) （含2个一键搭建脚本以及ss/ssr客户端下载）

**Comment by xiaoyu2006** [comment]
这不在本仓库的issue范围里
