### ISSUE TITLE
Is chacha20-ietf supported ?

### ISSUE THREAD

**Issue by yuchenlin** [shadowsocks/ShadowsocksX-NG#135]
Seems not to work

**Comment by yuchenlin** [comment]
Although it doesn't support chacha20-ietf in the config window, we can manually change the .config file in the /Library/Application Support/ShadowsocksX-NG/ss-local-config.json

**Comment by yuchenlin** [comment]
However, it would be better the config windows support manually changes. Also, I found that I cannot build the xcode project in  my Xcode 8.1 (8b62). An error occurs that 

`ld: warning: directory not found for option '-L/Users/yuchenlin/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-ctkkbfihiearsvcpqebeadnsbavz/Build/Products/Debug/BRLOptionParser'
ld: library not found for -lBRLOptionParser
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by qinyuhang** [comment]
reference at https://github.com/shadowsocks/ShadowsocksX-NG/issues/132 and https://github.com/qinyuhang/ShadowsocksX-NG/issues/17

**Comment by qinyuhang** [comment]
Don't build with ShadowsocksX-NG.xcproject, instead U need build with ShadowsocksX-NG.xcworkspace

**Comment by yuchenlin** [comment]
Thank you very much. I'm gonna try again.

**Comment by qiuyuzhou** [comment]
Have added chacha20-ietf in develop branch.
