### ISSUE TITLE
无法打开网页，因为无法与服务器建立安全连接

### ISSUE THREAD

**Issue by bianjunkai** [shadowsocks/ShadowsocksX-NG#138]
您好，安装了NG之后，连接谷歌和facebook都会显示无法打开网页，因为无法与服务器建立安全连接，想请教是怎么回事。
shadowsocks服务器是我自己建的，用Ios端的shadowrocket是可以用的。

**Comment by xiaopangmd** [comment]
我也遇到了这个问题，老的 ShadowsocksX 是能正常使用的

**Comment by klaek** [comment]
Its a small bug. when you scan a qrcode, somethings you get the encrytion is Capital, maybe looks like AES-256-CFB, pls manully change it to aes-256-cfb. little trick n works.
你是不是扫描二维码方式添加的，改一下。

**Comment by Tsahao** [comment]
加密方式没有问题 偶尔会出现一次 等一会就会恢复 很奇怪
