### ISSUE TITLE
打开网页速度很慢

### ISSUE THREAD

**Issue by exxfzc** [shadowsocks/ShadowsocksX-NG#139]
推特基本打不开，动态网要刷新多几次才可以，win下同样用shadowsock速度很快的

**Comment by DeronLee** [comment]
這和客戶端關係不大吧。感覺更像是DNS的問題。你確定Windows和 OS X的網絡設置完全一樣麼？

**Comment by acbetter** [comment]
建议先清空 DNS 缓存。

**Comment by nuomi1** [comment]
ShadowsocksX.app，gfwlist2pac 输出 O(1) 版 PAC，Chrome 很快打开网页，Safari 无法识别。
ShadowsocksX-NG.app，看起来是 gfwlist2pac 输出 ABP 版 PAC，Chrome 还是很快打开网页，Safari 非常慢。

**Comment by exxfzc** [comment]
矛盾了，回家连网，shadowcks上youtube就很快，怎么回事

2016-12-06 22:16 GMT+08:00, nuomi1 <notifications@github.com>:
