### ISSUE TITLE
可否优化下菜单排列顺序？

### ISSUE THREAD

**Issue by Linci** [shadowsocks/ShadowsocksX-NG#141]
<img width="334" alt="1" src="https://cloud.githubusercontent.com/assets/3479164/20422819/a08020fe-ada7-11e6-9a55-82aeef5c6701.png">

**Comment by hulizhen** [comment]
确实这种方式好一点，要不然每次切换代理模式都要进二级菜单，挺麻烦的。

**Comment by qinyuhang** [comment]
对于有很多节点的人来说，这个方式其实很不好。我的节点列表有十几个，如果这样就很不方便。

**Comment by DeronLee** [comment]
是的。我的节点有20个呢。不过如果只是把最常用的2-3个显示在这样的话其实是挺方便的

**Comment by 0x5e** [comment]
代理设置、服务器设置、高级设置、HTTP代理设置，是否也可以整到一起，每个设置一个弹窗。。有点晕啊

**Comment by qinyuhang** [comment]
我也赞同这个，但是如何确定“常用节点”这个标准应该怎么限定呢

DeronLee <notifications@github.com>于2016年11月19日 周六10:22写道：

**Comment by DeronLee** [comment]
這個簡單啊。最簡單的實現就是顯示最後選擇過的2-3個服務器即可。
麻煩一點的實現就是顯示最近一段時間使用次數最多的2-3個服務器。
個人偏向簡單實現即可。

**Comment by acbetter** [comment]
每次切换 PAC自动模式 和 全局模式 都很烦。虽说有快捷键，但是鼠标党表示心很累，以前的 SS 还是很好的，点一下小飞机就可以切换了，而现在只能先进入 代理- 这种二级菜单，然后切换，很影响我的体验。至于一键切换代理服务器，我觉得可以让用户设置最常用的几个代理服务器，切换起来也方便些。

**Comment by myi101** [comment]
我觉得shadowsocksX那个菜单排列就很好，用的很舒服，尤其是从屏幕二维码扫描添加，对新手很友好，我用的都是免费结点，密码每天换的那种，shadowsocksX可以一级菜单就可以扫描，而且动画很友好。切换到这个的唯一好处应该是gfwlist能更新。其他的功能说实话我都用不到太多

**Comment by qiuyuzhou** [comment]
已经优化
