### ISSUE TITLE
能否添加定时重启应用的功能？

### ISSUE THREAD

**Issue by saury** [shadowsocks/ShadowsocksX-NG#142]
由于需要定时刷新ss-local-config.json的密码，发现通过脚本自动更新json文件后需要手动关闭再开启ss服务，能否加入定时重启功能，谢谢

**Comment by qinyuhang** [comment]
脚本本身可以重启应用，通过重载守护进程就可以了。checkout at： https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ShadowsocksX-NG/reload_conf_ss_local.sh

**Comment by saury** [comment]
不好意思，问下是用bash分别跑这两行重载代码吗？似乎没有用，是不是我改错了配置文件？我修改的ss-local-config.json文件在以下路径：
/Library/Application Support/ShadowsocksX-NG/

**Comment by qinyuhang** [comment]
是的。这个并不会杀掉GUI，而是重启SS连接。

**Comment by saury** [comment]
谢谢，发现直接跑reload_conf_ss_local.sh就好了。之前可能异步的关系出了问题
