### ISSUE TITLE
关于ShadowsocksX-NG各个版本的疑问

### ISSUE THREAD

**Issue by unever** [shadowsocks/ShadowsocksX-NG#143]
Hi qiuyuzhou & qinyuhang：

之前一直在使用ShadowsocksX，最近更换节点、服务商等开始使用SSR相关的工具和服务。之前Breakwa11 SSR事件就已经有点晕了，现在看到你的版本，分支更多了一些，加上android客户端的版本，有些混乱，希望能帮忙梳理一下。

目前了解到的版本：

- shadowsocks-rss，项目主页没有做太多介绍，仅从BTSync的文件来看，主要为windows和android客户端，但她的项目主页也推荐了另一个SSR-Android。加上原版shadowsocks，windows2个版本，android3个版本。
- shadowsocksX，很久不更新了，而且shadowsocks官网（所谓的？）推荐的客户端也成了NG版本。
- shadowsocksX-NG，shadowsocksX-NG-R8，shadowsocksX-R，这几个版本有什么不同吗？NG应该是标准版，而其他2个呢？

造成混乱的可能是各种分支较多，而且一些服务商推荐的客户端也不尽相同，所以会有这样的疑问，希望解答一下，谢谢。

更新，原有问题解决，编辑删除了。

**Comment by qinyuhang** [comment]
发错repo了，这个repo的owner是 @qiuyuzhou 不是@qinyuhang。
第三个问题，NG 是 qiuyuzhou 维护的纯SS，后两个版本是根据 NG 修改的支持 SSR 版本。
最后，请使用服务商推荐的就好了，无须而外纠结。

**Comment by unever** [comment]
@qinyuhang 

- - ，竟然不是一个人，没注意，不好意思两位。

还是有问题的，因为同时使用几家服务商，协议也不同，所以想用一个稳定靠谱的通用版本，这样看来，是不是使用shadowsocksX-NG-R8更合适一些？因为通用。

**Comment by qinyuhang** [comment]
如果服务商有支持（或者计划支持）SSR，可以的。

**Comment by unever** [comment]
好的，感谢回复，谢谢

**Comment by Michaelyb520** [comment]
@unever 你用的是shadowsocksX-NG-R8吗？我用的是shadowsocksX-NG-R7版本。我也是正纠结与各个版本的问题。。。。

![image](https://cloud.githubusercontent.com/assets/9857312/21249281/e54f68c6-c377-11e6-98b3-0e1a89c019aa.png)

**Comment by lyqblue** [comment]
mark

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Xiaomi Redmi Note 3 发送_

**Comment by GL8666** [comment]
mark

**Comment by ronghuaxiang** [comment]
windows version how download!

**Comment by Cytusvoid** [comment]
m
