### ISSUE TITLE
能否为切换全局和PAC模式增加全局快捷键？

### ISSUE THREAD

**Issue by hulizhen** [shadowsocks/ShadowsocksX-NG#144]
每次切换代理模式都需要点好几次菜单，如果有了全局快捷的支持会快捷很多。谢谢。

**Comment by Vayn** [comment]
你可以使用我改进的版本: [点击下载](https://github.com/Vayn/ShadowsocksX-NG/releases)
增加了使用快捷键 <kbd>⌃</kbd> + <kbd>⌘</kbd> + <kbd>P</kbd> 进行全局和 PAC 模式的切换

**Comment by qiuyuzhou** [comment]
已经merge pr

**Comment by dustookk** [comment]
@qiuyuzhou 

这个功能兼职太棒了.  感谢作者 👍
