### ISSUE TITLE
关于状态栏显示美化

### ISSUE THREAD

**Issue by OmegaNJU** [shadowsocks/ShadowsocksX-NG#146]
目前在状态栏显示运行模式是通过文字表示，是否可以学习windows版本的ss，win下的ss在开启后小飞机旁边有个上下（表示上传下载）的箭头，而且在自动模式下使用ss时两个箭头会闪烁。而且全局模式下小飞机会变成蓝色。

不知道mac这个状态栏图标允不允许实现这种动态图标，可以的话，我觉得借鉴一下这种挺好的。

**Comment by qiuyuzhou** [comment]
Won't implement it.
