### ISSUE TITLE
最新版本mac系统怎么让终端也走ss的代理

### ISSUE THREAD

**Issue by Insofan** [shadowsocks/ShadowsocksX-NG#147]
如题，很多操作需要终端访问https的网站，网上很多办法新版本也行不通了

**Comment by kiongweidong** [comment]
同一个ss账号，在iPad上可以用，甚至可以看高清视频，但是在Mac端用ng就完全不行！

**Comment by Insofan** [comment]
@kiongweidong mac上可以访问网站和看视频 你换个服务器试试

**Comment by nightire** [comment]
@Insofan 提示：proxifier 或者类似的工具

**Comment by rex-li** [comment]
proxy4chain 似乎有问题，但是proxifier 可以，我正在用。

**Comment by Insofan** [comment]
@nightire @rex-li 解决了 最后用
     `git config --global http.proxy socks5`
解决了

**Comment by obliviosn** [comment]
陪着环境变量，在终端中添加零时环境变量export http_proxy='127.0.0.1:1087'
就可以在终端中使用代理了。
如果想每次终端可以使用，你之间配置全局环境变量即可。

**Comment by denotepython** [comment]
@nightire  我输入了git config --global http.proxy socks5还是不行，现在报错为Failed to connect to socks5 port 1080: Operation timed out，怎么改回去？

**Comment by obliviosn** [comment]
你可以直接覆盖之前设置的即可如，
git config --global ''
用空字符串来覆盖之前设置的。

**Comment by anderc-done** [comment]
ShadowsocksX-NG 可以，右键点小飞机，然后有一个Copy HTTP Proxy Shell Export Line，点击之后会copy命令，可以把命令加在~/.bash_profile里，用的时候终端 source ~/.bash_profile，然后终端就可以翻了

**Comment by Insofan** [comment]
自问自答吧, 没想gayhub这么有爱,这么久了还有人回复, 我用ssr:ShadowsocksX-NG R8 开全局代理 自动终端翻墙

**Comment by MyDinnerIsReady** [comment]
我加进~/.bash_profile然后source了，没用啊。

**Comment by panda020111** [comment]
确实，吧shadowsocks-ng，开成全局代理，终端就可以翻墙了

**Comment by sumtsui** [comment]
之前用Shadowsocks，配合这个[教程](https://blog.csdn.net/shaobo8910/article/details/53908639)里的设置，用polipo，mac终端可以翻墙，换了Shadowsocks-NG之后，终端就翻不了墙了。看前面评论全局设置后就可以，但试了也不行，报错connection timeout。
然后终端里输入export http_proxy='127.0.0.1:1087'，也不行，报错tunneling socket could not be established, cause=connect EHOSTUNREACH

终端翻不了墙无法练习开发，很苦恼啊

**Comment by guanhui07** [comment]
proxifier 这个挺好用

**Comment by gaojinhsu** [comment]
我用Proxifier配合Shadowsocks翻墙能成功，但是配合ShadowsocksNG就不行，我已经在Poxies里设置成127.0.0.1 1086了。
