### ISSUE TITLE
Websites like facebook, youtube, etc. reset connection when using -NG

### ISSUE THREAD

**Issue by ortonomy** [shadowsocks/ShadowsocksX-NG#149]
I use Shadowsocks-NG on my mac + Streisand on DO.

When I connect to my Shadowsocks DO server using SS-NG client, sites like Youtube, Facebook, Google all reset the connection.

This is not the GFW - I use Potatso with my DO SS server on iOS and it works fine. Something in the SS-NG client is causing a problem. How can we troubleshoot this?

**Comment by kiongweidong** [comment]
I have met this problem, but he told me to change a server account. I only have two server accounts ,both of them dosen't work.

**Comment by geligelu** [comment]
Thanks @kiongweidong. So that's two people having this issue - it can't be the server account. Because it works on iOS with Potatso. It's the app!

**Comment by kiongweidong** [comment]
My account can also works on IOS with shadowrocekt

**Comment by geligelu** [comment]
Anyone?!

**Comment by lostcup** [comment]
I also have shadowsocks on DO and it always works fine with ShadowsocksX-NG until I upgrade Mac to 10.12.2. Now it reset connections from time to time. Once I restart ShadowsocksX-NG, it works for a while. But after idle for a few hours, it does not work until I restart it.

**Comment by geligelu** [comment]
@lostcup  - I'm also on Sierra too. Perhaps this is the real source of the bug?

**Comment by lostcup** [comment]
@geligelu It only happens after most recent upgrade with Sierra a few days ago. Before that, Sierra works fine with NG. So my doubt is with changes in 10.12.2 only.

**Comment by geligelu** [comment]
@lostcup - OK, I have to say, I hadn't kept track of whether it was working with Sierra previously to that. Something has definitely broken. When I first set up my server, it worked for like maybe 5 seconds, then stopped working.

Interestingly, my other VPN service, which uses a programatically controlled proxy configuration, also stopped working with Sierra. Perhaps apple changed the way this is controlled.

**Comment by qiuyuzhou** [comment]
Can't use pac url like 'file:///' on 10.12.2
Use new version or global mode.

**Comment by ortonomy** [comment]
I didn't use PAC url?!? I haven't changed any of the settings. What does this mean?
