### ISSUE TITLE
Can't use 1.3.2 and 1.3.1 using my own server

### ISSUE THREAD

**Issue by guanchaoli** [shadowsocks/ShadowsocksX-NG#151]
我之前用的不带NG的老版本，可以连接，然后用了新的1.3.2无法打开网页，再换了1.3.1依然无法打开网页，OSX版本是10.12.1.  服务器设置跟以前是一样的 @qiuyuzhou

**Comment by anyforever** [comment]
同楼上一样的问题。我用的1.3.2，配置和windows上一样，也是打不开。win上没问题。mac os 10.12.1

**Comment by mtndewxu** [comment]
同样的问题。。。google也ping不通。。看了下log也没什么异常。。

**Comment by mtndewxu** [comment]
额我可以上了。。回国后忘记把unblockyouku卸了导致chrome翻不了。。。 stupid me...

**Comment by mark695073649** [comment]
我也是，是设置不对嘛？还是怎么

**Comment by anyforever** [comment]
我的好了，是加密规则选择错了

**Comment by klaek** [comment]
Its a small bug. when you scan a qrcode, somethings you get the encrytion is Capital, maybe looks like AES-256-CFB, pls manully change it to aes-256-cfb. little trick n works.
你是不是扫描二维码方式添加的，改一下。

**Comment by qiuyuzhou** [comment]
I close the old issue.
