### ISSUE TITLE
mac 点击显示日志就彻底完蛋了，永远打不开了，卸载重装都不行

### ISSUE THREAD

**Issue by geekerzhou** [shadowsocks/ShadowsocksX-NG#155]

**Comment by rex-li** [comment]
Have to make sure below files/folders are complete removed:

- /Applicatiuons/Shadowsocks-NG.app
- /Users/****/Library/Application Support/ShadowsocksX-NG
- /Library/Application Support/ShadowsocksX-NG
- /Users/****/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist

After removed above then try reinstall the client and re-config the servers.
