### ISSUE TITLE
[建议] 能同时提供 10.10 版本的吗 ? 

### ISSUE THREAD

**Issue by foobarjohnny** [shadowsocks/ShadowsocksX-NG#157]
对于 10.10 来说, 苹果已经不让升级到 10.11, 而必须直升 10.12 了, 我觉得 10.12 是新出的不稳定, 但是又升不到 10.11, 你能同时提供一个可供 10.10 版本运行的吗 ? 谢谢

**Comment by qiuyuzhou** [comment]
Won't support.

**Comment by cocoahuke** [comment]
Try this https://github.com/cocoahuke/patch_shadowsocksR

**Comment by zisulongkui** [comment]
可行，太感谢了。

**Comment by weiwen1990** [comment]
> 可行，太感谢了。

您好，请问上面git中的Releases是可以直接用吗？
或者需要跑make，生成的文件需要如何放置呢？
多谢！🙏

**Comment by cocoahuke** [comment]
> > 可行，太感谢了。
> 
> 您好，请问上面git中的Releases是可以直接用吗？
> 或者需要跑make，生成的文件需要如何放置呢？
> 多谢！🙏

可以直接用, 🙏 Thank you for your Donation!

**Comment by weiwen1990** [comment]
> > > 可行，太感谢了。
> > 
> > 
> > 您好，请问上面git中的Releases是可以直接用吗？
> > 或者需要跑make，生成的文件需要如何放置呢？
> > 多谢！🙏
> 
> 可以直接用, 🙏 Thank you for your Donation!

好的，感谢您！～
