### ISSUE TITLE
能否优化下 从屏幕扫描二维码添加 

### ISSUE THREAD

**Issue by myi101** [shadowsocks/ShadowsocksX-NG#160]
我是软件产品的产品经理，负责用户研究的，提几个易用性的小建议，也是ShadowsocksX做得比较好的几个地方。
1，菜单名字不太直观，应该显示为：从屏幕扫描二维码添加   会比较直观易懂
2，这个菜单应该显示在一级菜单，ShadowsocksX就是这么做的，能使用到这个软件的人，多数都不是长期固定使用一个服务器，添加服务器还是很常见的。尤其是对很多使用免费服务器的人来说，密码都是一天一换。菜单放在一级菜单，更方便添加。  
3，点击后的扫描动画，严重建议照shadowsocksX，这点做的非常好，它都有扫描动画定位到二维码，然后有确认界面，现在shadowsocksX-NG点击后完全没有确认过程，不清楚到底有没有添加成功，很不友好。
4，既然号称 next-generation Shadowsocks，就希望能站在前辈的基础上做的更好，保留用户友好的地方，这样才对的起下一代这个称号

**Comment by qiuyuzhou** [comment]
1 这个文案可以
2 以前是在外部，后来菜单项太多了，移动到内部。目前不考虑放到外部，但是考虑放到服务器列表上面。
3 没有空做动画。成功添加后，有系统通知提示。
