### ISSUE TITLE
能否增加下确认成功失败的通知显示

### ISSUE THREAD

**Issue by myi101** [shadowsocks/ShadowsocksX-NG#161]
1，点击从GFW list更新PAC，没有通知提示到底更新成功了没有，感觉就像个黑盒子，体验很不好。ShadowsocksX都有提示的；
2，从屏幕扫描二维码，既没有动画，也没有确认操作，也没有成功/失败提示，万一扫描不成功，用户怎么知道呢？ShadowsocksX就会遇到扫描不出来的情况，有提示至少能知道不成功，用户还可以选择手动输入添加。

**Comment by HappyEnd0315** [comment]
更新pac是有通知的
