### ISSUE TITLE
macOS 10.12.2，高级设置与HTTP代理设置无法关闭

### ISSUE THREAD

**Issue by RedDragonFalcon1** [shadowsocks/ShadowsocksX-NG#165]
macOS 10.12.2下，高级设置与HTTP代理设置两个窗口无法关闭

**Comment by qiuyuzhou** [comment]
点左上的x可以关闭呀，我这里可以。

**Comment by Neopallium** [comment]
OSX 10.12.3 with ShadowsocksX-NG 1.4.0 (3).  I have the same problem.  Can't close the advanced settings dialog window clicking the red x doesn't do anything.  I have to quit Shadowsocks and re-open to close the dialog.

**Comment by Neopallium** [comment]
I found the problem.  If the files in the ShadowsocksX-NG.app/Contents/..... do not have read/execute permissions for all users, then the initial install of the "proxy_conf_helper" is done without read/execute permission for all users.

Closing of the advanced settings dialog seems to fail if it can't execute the "proxy_conf_helper".

To fix run:

> sudo chmod a+rx /Library/Application\ Support/ShadowsocksX-NG/proxy_conf_helper

**Comment by qiuyuzhou** [comment]
Thanks. @Neopallium 
I would improve the helper install script.
From
`sudo chmod +s "/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper"`
to
`sudo chmod a+rx "/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper"`
