### ISSUE TITLE
为啥的装的这个版本是1.3.3的？

### ISSUE THREAD

**Issue by Michaelyb520** [shadowsocks/ShadowsocksX-NG#167]
咦。。。什么情况？为嘛我的版本是1.3.3的？
我的也是NG版本。
而现在发布的版本才1.3.2。

![image](https://cloud.githubusercontent.com/assets/9857312/21249162/1abc9a02-c377-11e6-930f-6090c23f0c74.png)

**Comment by SelenGuo** [comment]
哪里下载的？没见到有1.3.3版本

**Comment by qiuyuzhou** [comment]
你这个是其他人维护的衍生版本
