### ISSUE TITLE
增加批量从旧客户端导入服务器列表

### ISSUE THREAD

**Issue by yeliex** [shadowsocks/ShadowsocksX-NG#168]
建议运行批量添加服务器或者从旧客户端导入服务器列表

**Comment by creamidea** [comment]
最近我也遇到了同样的需求。搜索一番之后看到这些 issue: #58 #71 #82 。
也看到了这个 [commit:AppDelegate.swift](https://github.com/shadowsocks/ShadowsocksX-NG/blob/cc342df5b525233265ad39ac756aaed4207881d0/ShadowsocksX-NG/AppDelegate.swift)。
不过目前我还没有看到在 Release 中有相应的版本发布（找不到批量导入的功能，也许是我打开方式不对？望告知）。所以我自己研究了一番，然后我总结在这里，希望对各位有所帮助。

我一次无意中排查其他问题，得知 ShadowsocksX-NG 会把配置写到用户的 default 数据库中。于是，我们只要能够修改数据库中的数据，然后重启客户端，应该就可以满足我们的需求了。
具体操作如下：
```sh
# 首先将现有的配置导出
$ defaults export com.qiuyuzhou.ShadowsocksX-NG config.plist
# 将 plist 二进制转成可读的 json 文件
$ plutil -convert json -o config.json config.plist
# 执行完上面的步骤，你应该可以得到客户端的配置文件了。
# 之后，你对 config.json 文件进行编辑保存。
# 在修改完保存之后，把 json 文件转成 plist 格式的文件
$  plutil -convert xml1 config.json -o config.plist
# 检查 plist 文件是否 OK
$ plutil config.plist
# 当显示 OK 之后就可以将配置导入了
$ defaults import com.qiuyuzhou.ShadowsocksX-NG config.plist
# 之后就是重启客户端。
# 开始享受吧。
```

上面就是我总结出来的一种批量修改配置的方式。如果有什么问题，欢迎随时联系我 :)
以上。

**Comment by qiuyuzhou** [comment]
No plan.

**Comment by xiatian12345** [comment]
现在呢，怎么通过脚本的方式修改服务器配置
