### ISSUE TITLE
能否添加域名或中国IP白名单

### ISSUE THREAD

**Issue by bitweng** [shadowsocks/ShadowsocksX-NG#169]
每个地方的的GFW规则都不大一样。有些域名即使没有完全被墙，也几乎是无法正常访问，而通过代理就嗖嗖快，我自己本地就维护了一长串域名黑名单。
所以，区分境内、境外IP或域名也是个急需的功能。

**Comment by qiuyuzhou** [comment]
请通过用户自定义pac规则去实现

**Comment by JonasGao** [comment]
@bitweng You can use [this client](https://www.plutox.top/)
@qinyuhang In fact, I would like to use [mono_pac](https://github.com/blackgear/mono_pac) on ShadowsocksX-NG. But dont support replacing the full pac file.

**Comment by qiuyuzhou** [comment]
@JonasGao 
mac 上因为是通过socks5代理服务器提供代理，浏览器不会在本地解析域名，域名会在远程服务器解析。
所以浏览器使用pac.js去过滤时是根据域名，根据ip过滤的pac文件不会有用。

**Comment by JonasGao** [comment]
原来
