### ISSUE TITLE
shadowsocks可以用X-NG却用不了

### ISSUE THREAD

**Issue by kiongweidong** [shadowsocks/ShadowsocksX-NG#174]
前两天我的服务器突然就不能用了，在移动端，我的所有的服务器却都可以用，但是在ng上就不能用了，无法打开任何被墙网站，刚开始以为是客户端出了毛病，重新下载安装了过后还是一样不能用，后来换成了shadowsocks过后所有的服务器又都可以用了，但是在ng上还是无法使用！

**Comment by StayTherapy** [comment]
同样的情况，1.3.2 版的NG 在 OSX 10.12 貌似有问题，代理无效，且本地的 http 代理 1087 端口也没打开。

**Comment by leohxj** [comment]
不会吧，昨晚我在 Mac 下还正常使用，建议贴一下 console 信息。

**Comment by huodon** [comment]
今天上午也出问题了, 手机端正常,  
把  /Users/HD/Library/Preferences  里的 `com.qiuyuzhou.ShadowsocksX-NG.plist` 和 /Users/HD/Library/Application Support   里的  `ShadowsocksX-NG/` 删掉居然好了.

**Comment by zzstefan** [comment]
我也是啊，我一直使用的Shadowsocks，但是发现更新不了那个gfwlist，然后今天才看到这个NG的，我就想更新到这个来看看了，结果发现PAC模式上不了任何被墙的网站，只有全局模式才行。

**Comment by Insofan** [comment]
全局模式任何网站都打不开，PAC不能翻墙

**Comment by BIOTONIC** [comment]
@Insofan 和你的一样 简单来说 就是不管用了。。。

**Comment by Insofan** [comment]
@BIOTONIC 我删除了又重装居然好了 要彻底删除配置文件都删掉 怀疑是运营商搞了我

**Comment by BIOTONIC** [comment]
@Insofan X-NG和X-R的Feedback竟然都是这儿 我粉红色的X-R和绿色的X-NG都试了 还是不行 OS10.12.2

**Comment by kiongweidong** [comment]
现在我的ShadowsocksX也用不了了，完全上不去，但是我的服务器在iPad上的Shadowrocket还可以用啊！

**Comment by Insofan** [comment]
@BIOTONIC @kiongweidong 试试换一个ss 帐号 我的一直好使 lantern一直可以用 就是有点慢 翻墙去外面找几个好使的ss帐号

**Comment by yuif37** [comment]
我的 shadowsocksX 和 shadowsocksX NG 都不能用
一开始 GoAgent 可以用 后来就莫名其妙不行了
现在用的 surge 希望不要有一天 surge 也不能用了

**Comment by kiongweidong** [comment]
我今天把ShadowsocksR也下载了下来了，但是还是不能用，几个纸飞机全都用了，每一个可以用的。完全不知道以后该咋收邮件！

**Comment by devXiaoL** [comment]
使用shadowsocksX NG不能上网的可以按照下面的方法 检查一下，shadowsocksX的本地监听端口号是1080，，，shadowsocksX NG的本地监听端口变成了1086，NG的本地监听端口变成了1086，NG的本地监听端口变成了1086，
![image](https://cloud.githubusercontent.com/assets/12447455/23391984/c3840c30-fdb3-11e6-9e09-c1c86bf1e719.png)
![image](https://cloud.githubusercontent.com/assets/12447455/23392067/30e30df8-fdb4-11e6-8d8d-351533d57350.png)

**Comment by dogchild** [comment]
@devXiaoL  端口确实是1086了，那现在要正常使用的话要改成什么？1080吗？

**Comment by sunhb** [comment]
同样的问题，我在配置服务器的时候把Enable OTA 取消勾选之后就可以了。希望对你们有所帮助

**Comment by yudeying918** [comment]
我这里改成1086可以用了
