### ISSUE TITLE
将本地Socks5监听地址改成局域网地址后，127.0.0.1代理失效了。

### ISSUE THREAD

**Issue by Chigogo** [shadowsocks/ShadowsocksX-NG#177]
这导致一个结果，当我在Mac 下把模式调成全局模式的时候，ShadowsocksX-NG在系统代理中依然设置的是127.0.0.1，结果导致代理失效。
希望同时监听局域网和127.0.0.1。

**Comment by yitong-ovo** [comment]
设置监听地址为 0.0.0.0 应该可以达到你所需要的效果。
