### ISSUE TITLE
关于多个PAC的问题

### ISSUE THREAD

**Issue by quietin** [shadowsocks/ShadowsocksX-NG#179]
有将不同地址请求发到不同ss服务器的需求, 比如自动将谷歌的请求发到日本, 而推特的请求发到香港.
亦即多个连接点对应多份PAC文件, 并且在程序启动后, 这些连接点均是可用的, 有没有考虑这样的支持呢?

**Comment by qiuyuzhou** [comment]
This need run multiple ss-local instances.
Won't support it.
