### ISSUE TITLE
更新gfwlist后无法连接

### ISSUE THREAD

**Issue by WhatAKitty** [shadowsocks/ShadowsocksX-NG#181]
更新gfwlist后，无法连接上代理。用shadowsocksX可以。
而且尝试过清空缓存删除配置，发现每次打开后仍旧是原先配置，而且仍旧无法通过xng上外网

**Comment by sunsan05** [comment]
我不知道是不是你这个问题，我之前是好的，然后现在全局模式都不能用了。SS服务器在梅林路由上测试通过，正常使用。

**Comment by WhatAKitty** [comment]
@sunsan05 我全局模式也没法用，不知道哪里出问题了。

**Comment by BIOTONIC** [comment]
同样不管用了
