### ISSUE TITLE
MacOs 10.12.2无法运行

### ISSUE THREAD

**Issue by xylophone21** [shadowsocks/ShadowsocksX-NG#182]
启动后任何方式代理都不能链接。
调试发现ss-local进程没有启动，1086（默认）端口也没有被监听。
手动进入.app启动start-ss-local.sh提示：
/User/xxxx/Library/LaunchAgents/com.xxxxx.shadowsocksX-NG.local.plist: No such file or directory。

查看/User/xxxx/Library/LaunchAgents/目录owner是root，其他用户无写权限，但在另一台升级到10.12.1的机器发现这个目录的owern是用户自己，不确实是否有影响。

**Comment by tianxingvpn** [comment]
我也有同样的问题

**Comment by reancool** [comment]
metoo。。。SwitchyOmega 设置1086...也是不行，软件上的 pingtest 都ok 的。。但是我就是不能用

**Comment by BIOTONIC** [comment]
+1 更新到10.12后就没发使用了

**Comment by transtone** [comment]
cpu 100% , 10.12.2

**Comment by qiuyuzhou** [comment]
@xylophone21 owner是root应该不行
