### ISSUE TITLE
obfs

### ISSUE THREAD

**Issue by jerrylzy** [shadowsocks/ShadowsocksX-NG#184]
能加上对Shadowsocks-libev最新的obfuscate的支持吗？
[https://github.com/shadowsocks/shadowsocks-libev/commit/8cb4f81eba2dde5207f99c0f0b05f30fbb57a497](url)

**Comment by qiuyuzhou** [comment]
目前develop分支的ss-local更新到Shadowsocks-libev的2.5.6版本

**Comment by Kaijun** [comment]
@qiuyuzhou 目前单独使用 ss-local 还需要搭配 obfs-local 吧？可以整合进来吗？和kcptun一样
