### ISSUE TITLE
手动运行 ss-local 提示Invalid config path.

### ISSUE THREAD

**Issue by yuif37** [shadowsocks/ShadowsocksX-NG#187]
打开 shadowsocksX 发现 ss-local 没有运行
![image](https://cloud.githubusercontent.com/assets/3508411/21549557/e163d0ec-ce2d-11e6-88ad-824fe082e1ec.png)
将 ss-local 拖入终端运行提示Invalid config path.
将start_ss_local.sh拖入终端运行提示
/Users/用户名/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist: Service is disabled

**Comment by 8enet** [comment]
很正常啊，执行ss_local需要参数，比如ss-local -c ss-config.json

**Comment by BIOTONIC** [comment]
我这儿10.12.2的系统 运行不了 没找到ss-config.json 是不是因为这个原因 @8enet

**Comment by qiuyuzhou** [comment]
@yuif37 
ss-local是作为后台服务运行的，你的提示Service is disabled已经说明问题了。

**Comment by abners** [comment]
@qiuyuzhou 
![image](https://user-images.githubusercontent.com/7392358/55408554-cfb76680-5592-11e9-883d-813ec86c0153.png)一直报这个错
