### ISSUE TITLE
mac联网后PAC自动模式打不开网页。

### ISSUE THREAD

**Issue by bringtree** [shadowsocks/ShadowsocksX-NG#188]
ShadowsocksX-NG 1.3.2
mac 
客户端机 连上网的时候开PAC自动模式 是打不开网页的， 一定要全局一下 然后打开一个网页 再切回自动模式才可以，有谁遇到这种情况吗？怎么解决？

**Comment by xuweilai** [comment]
我也是这样了 好蛋疼
