### ISSUE TITLE
关于 PAC 文件

### ISSUE THREAD

**Issue by AlbertDu** [shadowsocks/ShadowsocksX-NG#190]
请问在**PAC文件**的两个选项的：
>1. 从 GFW List更新
>2. 编辑 PAC 用户自定规则

这两个的是**合并**之后生效吗，还是2会**覆盖**1？

**Comment by qiuyuzhou** [comment]
合并

**Comment by SendorWang** [comment]
我在PAC用户指定规则，做了如下，却不能生效，我怕写对了吗？
||atlassian.net^
||fabric.io^
