### ISSUE TITLE
自定义 PAC 的格式是怎样的？

### ISSUE THREAD

**Issue by Mysdes** [shadowsocks/ShadowsocksX-NG#191]
参照 https://adblockplus.org/en/filter-cheatsheet 里的格式貌似不生效，拷贝 ShadowsockX的格式貌似也不生效。

**Comment by soldier828** [comment]
参照 https://adblockplus.org/en/filter-cheatsheet格式。
我的需要重启ShadowsocksX-NG生效

**Comment by tonybwb** [comment]
那个格式是有效的。你确定你的pac端口设置对了么？

**Comment by qiuyuzhou** [comment]
原来监控gfwlist.js文件变化的方法在新版macOS上失效了，已经使用新方法实现。
