### ISSUE TITLE
请问是否有开发负载均衡和高可用功能的计划

### ISSUE THREAD

**Issue by baqihg** [shadowsocks/ShadowsocksX-NG#192]
请问是否有开发负载均衡和高可用功能的计划

**Comment by liliass** [comment]
+1

**Comment by qiuyuzhou** [comment]
No plan.

**Comment by yangfeicheung** [comment]
This version has High Availability Mode:

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by linonetwo** [comment]
@ishen7 https://github.com/shadowsocks/ShadowsocksX-NG/issues/391#issuecomment-421769117
