### ISSUE TITLE
pac自定规则需重启ShadowsocksX-NG才生效

### ISSUE THREAD

**Issue by soldier828** [shadowsocks/ShadowsocksX-NG#196]
虽然改完pac，显示PAC rules has been updated，但实际没有生效，需重启ShadowsocksX-NG才生效。
不知道是不是只有我有这样的问题

**Comment by liliass** [comment]
怎么弄都不生效

**Comment by isnine** [comment]
同样，自定义PAC规则无效，我是采取这样设置，不知是否正确
`
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||ip138.com^
`

**Comment by qiuyuzhou** [comment]
Fixed in cb4e6d7f1925070aa2a278f6f58a9ea2bdca611d.

**Comment by baiwei0703** [comment]
添加后，选择“从GFWlist”更新本地PAC  ，然后取消勾选“启用系统代理”，再打开就生效了。。。

**Comment by cfanseal** [comment]
我添加*.baidu.com  然后设置了一个不存在的SS erver ，接着更新PAC，然后关闭，然后再打开，也是不生效的
