### ISSUE TITLE
能不能加个自定义快捷键的功能.

### ISSUE THREAD

**Issue by supermanxiacheng** [shadowsocks/ShadowsocksX-NG#200]
因为买的是付费服务,一共就15g/月
很多网站光靠GWList没用,必须开全局.
然后就一直在全局和自动来回切换,要是有个快捷键,该多好.

尝试过苹果系统的自定义app快捷键,好像对这种bar App,没有什么卵用- -

**Comment by Vayn** [comment]
在作者还没释出最新版前，你可以下载我编译的最新版 https://github.com/Vayn/ShadowsocksX-NG/releases/latest

支持用 cotrol + command + p 切换代理模式

**Comment by qiuyuzhou** [comment]
已经merge PR
