### ISSUE TITLE
Could kcp been support?

### ISSUE THREAD

**Issue by otsukaresama** [shadowsocks/ShadowsocksX-NG#202]
A Simple UDP Tunnel Based On KCP
[https://github.com/xtaci/kcptun](url)

Is it possible that kcptun mentioned above been integrated into the ShadowsocksX-NG?😘

**Comment by qiuyuzhou** [comment]
￼It has been done. In testing.

![screenshot](https://cloud.githubusercontent.com/assets/2310221/21876597/26ac82de-d8bf-11e6-849b-8890ed5fd68d.png)

**Comment by otsukaresama** [comment]
Thank you!

**Comment by Kaijun** [comment]
@qiuyuzhou Still doesn't work on my side. Do you have some kind of instructions how to set it up correctly?
