### ISSUE TITLE
对话框不能关闭

### ISSUE THREAD

**Issue by xmxsuperstar** [shadowsocks/ShadowsocksX-NG#209]
版本： Version 1.3.2 (1)

* Proxy-> Advanced Proxy Preferences 打开的对话框 点击OK 按钮 没有反应

* Advanced Preferences 打开的对话框点击左上角的红色关闭按钮 没有反应

* Http Proxy Preferences 打开的对话框点击左上角的红色关闭按钮 没有反应

**Comment by rizwankce** [comment]
@xmxsuperstar need more info please. Because i could not reproduce your bug with SSx-NG version 1.3.2(1) and macOS 10.2.2

**Comment by qiuyuzhou** [comment]
无法复现。

**Comment by qiuyuzhou** [comment]
duplicate #165

**Comment by qiuyuzhou** [comment]
Have been fixed. For detail #165
