### ISSUE TITLE
Exported server settings JSON does not include KCPTUN related configuration

### ISSUE THREAD

**Issue by maddie** [shadowsocks/ShadowsocksX-NG#211]
## Version
1.4-alpha pre-release

## Steps
1. Click on `Export All Server To Json`
2. Save JSON file
3. Check JSON file content

## What to expect
JSON file should contain kcptun related settings

## What actually happened
Servers with `Enable over kcptun` enabled are exported the same as normal Shadowsocks servers

**Comment by qiuyuzhou** [comment]
@qinyuhang
