### ISSUE TITLE
Low priority: Typo on 'Cancel' button in 'Server Preferences' page

### ISSUE THREAD

**Issue by maddie** [shadowsocks/ShadowsocksX-NG#212]
![image](https://cloud.githubusercontent.com/assets/221872/21994091/eec54142-dc58-11e6-855d-299bad1595aa.png)

The button should be 'Cancel'

**Comment by maddie** [comment]
Also, this should be 'Disable compression'

![image](https://cloud.githubusercontent.com/assets/221872/21994112/0840c024-dc59-11e6-9ec9-b5aad3c4a7b5.png)

**Comment by qiuyuzhou** [comment]
Ok, I have fixed them.
