### ISSUE TITLE
Cannot use kcptun.

### ISSUE THREAD

**Issue by otsukaresama** [shadowsocks/ShadowsocksX-NG#213]
<img width="1064" alt="2017-01-17 2 44 50" src="https://cloud.githubusercontent.com/assets/9023097/22010505/8d488f52-dcc4-11e6-971e-d6580e771e46.png">

<img width="625" alt="2017-01-17 2 45 22" src="https://cloud.githubusercontent.com/assets/9023097/22010452/46e55aa4-dcc4-11e6-860b-f55b34d4662e.png">

This is my configuration on  both server and shadowsocksx-ng.

**Comment by qiuyuzhou** [comment]
信息不足。

请查看下面2个日志文件
~/Library/Logs/kcptun_client.log
~/Library/Logs/ss-local.log

**Comment by otsukaresama** [comment]
Part of the ~/Library/Logs/kcptun_client.log

2017/01/17 15:25:32 version: 20161222
2017/01/17 15:25:32 listening on: 127.0.0.1:8388
2017/01/17 15:25:32 encryption: aes
2017/01/17 15:25:32 nodelay parameters: 1 20 2 1
2017/01/17 15:25:32 remote address: 138.68.17.174:443
2017/01/17 15:25:32 sndwnd: 128 rcvwnd: 1024
2017/01/17 15:25:32 compression: true
2017/01/17 15:25:32 mtu: 1350
2017/01/17 15:25:32 datashard: 10 parityshard: 3
2017/01/17 15:25:32 acknodelay: false
2017/01/17 15:25:32 dscp: 0
2017/01/17 15:25:32 sockbuf: 4194304
2017/01/17 15:25:32 keepalive: 10
2017/01/17 15:25:32 conn: 1
2017/01/17 15:25:32 autoexpire: 0
2017/01/17 15:25:32 snmplog: 
2017/01/17 15:25:32 snmpperiod: 60
2017/01/17 15:25:38 stream opened
2017/01/17 15:25:39 stream opened
2017/01/17 15:25:40 stream closed
2017/01/17 15:25:51 stream opened
2017/01/17 15:25:52 stream opened
2017/01/17 15:25:53 stream closed
2017/01/17 15:25:53 stream opened
2017/01/17 15:25:53 stream closed
2017/01/17 15:25:53 stream closed
2017/01/17 15:25:53 stream opened
2017/01/17 15:25:53 stream closed
2017/01/17 15:25:53 stream opened
2017/01/17 15:25:54 stream opened
2017/01/17 15:25:54 stream closed
2017/01/17 15:25:54 stream opened
2017/01/17 15:26:02 stream closed
2017/01/17 15:26:02 stream closed
2017/01/17 15:26:02 stream closed
2017/01/17 15:26:03 stream opened
2017/01/17 15:26:20 stream opened
2017/01/17 15:26:31 stream opened
2017/01/17 15:26:32 session scavenged
2017/01/17 15:26:33 stream closed
2017/01/17 15:26:33 stream closed
2017/01/17 15:26:33 stream closed
2017/01/17 15:26:33 stream opened
2017/01/17 15:26:50 stream opened

Below is part of the ss-local.log

 2017-01-17 15:25:32 INFO: initializing ciphers... aes-256-cfb
 2017-01-17 15:25:32 INFO: tcp port reuse enabled
 2017-01-17 15:25:32 INFO: listening at 127.0.0.1:1086
 2017-01-17 15:27:32 INFO: initializing ciphers... aes-256-cfb
 2017-01-17 15:27:32 INFO: tcp port reuse enabled
 2017-01-17 15:27:32 INFO: listening at 127.0.0.1:1086

**Comment by qiuyuzhou** [comment]
打开Enable verbose mode，以显示ss-local的详细日志
排查在哪步不通

**Comment by qiuyuzhou** [comment]
看日志，kcptun是有流量联通的。

**Comment by otsukaresama** [comment]
日志好像没有提供更多地信息。打开kcptun选项，访问非pac内网址仍然可以，但是访问其他就不可以了。

2017/01/17 15:36:35 version: 20161222
2017/01/17 15:36:35 listening on: 127.0.0.1:8388
2017/01/17 15:36:35 encryption: aes
2017/01/17 15:36:35 nodelay parameters: 1 20 2 1
2017/01/17 15:36:35 remote address: 138.68.17.174:443
2017/01/17 15:36:35 sndwnd: 128 rcvwnd: 1024
2017/01/17 15:36:35 compression: true
2017/01/17 15:36:35 mtu: 1350
2017/01/17 15:36:35 datashard: 10 parityshard: 3
2017/01/17 15:36:35 acknodelay: false
2017/01/17 15:36:35 dscp: 0
2017/01/17 15:36:35 sockbuf: 4194304
2017/01/17 15:36:35 keepalive: 10
2017/01/17 15:36:35 conn: 1
2017/01/17 15:36:35 autoexpire: 0
2017/01/17 15:36:35 snmplog: 
2017/01/17 15:36:35 snmpperiod: 60
2017/01/17 15:36:36 stream opened
2017/01/17 15:36:38 stream closed
2017/01/17 15:36:38 stream opened
2017/01/17 15:36:41 stream opened
2017/01/17 15:36:44 stream closed
2017/01/17 15:36:59 stream opened
2017/01/17 15:37:05 stream closed
2017/01/17 15:37:05 stream closed
2017/01/17 15:37:15 stream opened
2017/01/17 15:37:29 stream opened
2017/01/17 15:37:35 session scavenged
2017/01/17 15:37:42 stream closed
2017/01/17 15:37:45 stream closed

2017-01-17 15:36:35 INFO: closed gracefully
 2017-01-17 15:36:35 INFO: initializing ciphers... aes-256-cfb
 2017-01-17 15:36:35 INFO: tcp port reuse enabled
 2017-01-17 15:36:35 INFO: listening at 127.0.0.1:1086
 2017-01-17 15:36:36 INFO: connect to live.github.com:443
 2017-01-17 15:36:38 INFO: connect to www.google.com:443
 2017-01-17 15:36:41 INFO: connect to live.github.com:443
 2017-01-17 15:36:59 INFO: connect to live.github.com:443
 2017-01-17 15:37:15 INFO: connect to www.google.com:443
 2017-01-17 15:37:29 INFO: connect to live.github.com:443

**Comment by otsukaresama** [comment]
2017/01/17 15:36:35 version: 20161222

ss-ng内置的客户端版本好像和服务端使用的不一致，sndwnd: 128还有这个选项我在服务端配置成1024（详见最顶端的图），不知道是不是这些原因。

**Comment by qiuyuzhou** [comment]
那是高级设置用缺省值。UI上没有的设置最好不要修改

**Comment by otsukaresama** [comment]
我刚才下载最新版本（20170114)然后手动运行：
./client_darwin_amd64 -r "xx.xx.xx.xx:443" -l ":8388" -mode fast2
这样没有问题。可能是需要版本匹配。

但是好像没有起到加速的作用啊，哈哈。

**Comment by 0xdatou** [comment]
第一张图的443错了, 改为29900.....

**Comment by otsukaresama** [comment]
@0xdatou 谢谢！

**Comment by mayiwei** [comment]
那两处密码分别填什么呢？

**Comment by wuzhidexiaoheizi** [comment]
端口改成29900,地址改为kcptun服务器地址，那还要运行kcptun client干嘛？不是应该连接kcptun client的地址吗？不是很懂，求高手解答

**Comment by wuzhidexiaoheizi** [comment]
是不是ShadowsockX-NG中已经集成了kcptun client。kcptun参数是传给kcptun client启动的参数。我还傻傻的自己启动了一个kcptun client然后ShadowsockX-NG中填的是我自己启动的kcptun client的本地监听地址。以前kcptun和ShadowSocks是分开用的。不知道我理解的对不对。

**Comment by hugojing** [comment]
@wuzhidexiaoheizi 两种方式我都试了一下：1. 直接启用 ShadowsocksX-NG 的 kcptun 功能，正确配置后，是可以正常使用的；2. 自行启动 kcptun client, 然后在 ShadowsocksX-NG 中填写 kcptun client 所在的本地端口，也是可以正常使用的。

我用活动监视器查看，发现打开 ShadowsocksX-NG 时，会出现一个叫 kcptun_client 的进程，关闭时它会消失：

![image](https://user-images.githubusercontent.com/8682847/28401867-5a47e7c6-6d4f-11e7-910f-7c91df1e342d.png)

所以 ShadowsocksX-NG 应该内置了 kcptun_client，已经处理好了这些。我认为你的理解是对的。

**Comment by fatezeronight** [comment]
最好在软件界面加个教程，新手使用起来非常吃力

**Comment by gMan1990** [comment]
@hugojing "所以 ShadowsocksX-NG 应该内置了 kcptun_client，已经处理好了这些。我认为你的理解是对的。"   我电脑怎么木有？？？要怎么开启？

**Comment by gMan1990** [comment]
@qiuyuzhou 没有~/Library/Logs/kcptun_client.log日志，是我打开的方式不对么？
