### ISSUE TITLE
希望自定义快捷键

### ISSUE THREAD

**Issue by ykqmain** [shadowsocks/ShadowsocksX-NG#214]
目前 ctrl+cmd+S 是开关Shadowsocks

但是这个快捷键一般是某些软件的同步快捷键，使用频率很高

所以希望能自定义快捷键

**Comment by qiuyuzhou** [comment]
会先禁用这个功能

**Comment by xpol** [comment]
ctrl+cmd+P 也冲突。希望能：

* 第一步：有选项禁用全部快捷键
* 下一步：有选项禁用单个快捷键
* 最理想：能定制每个快捷键

**Comment by qiuyuzhou** [comment]
已经实现可配置快捷键。
