### ISSUE TITLE
Scaning QRCode from screen still fails since ver 1.4.0

### ISSUE THREAD

**Issue by liheeng** [shadowsocks/ShadowsocksX-NG#215]
As subject, this issue also exists in develop branch.
The cause is the ss url is appended with '\n' character when using base64 to decode. 
I fixed this issue by changing ServerProfile.swift:init:decodeUrl function, to replace '\n' character, it works now.

```swift
        func decodeUrl(url: URL?) -> String? {
            guard let urlStr = url?.absoluteString else {
                return nil
            }
            let index = urlStr.index(urlStr.startIndex, offsetBy: 5)
            let encodedStr = urlStr.substring(from: index)
            guard let data = Data(base64Encoded: padBase64(string: encodedStr)) else {
                return url?.absoluteString
            }
            guard let decoded = String(data: data, encoding: String.Encoding.utf8) else {
                return nil
            }
            
            let d = decoded.replacingOccurrences(of: "\n", with: "")
            
            return "ss://\(d)"
        }
```

Since I am not familiar with swift, I am not sure if my fix has other problem.

**Comment by qiuyuzhou** [comment]
Give me a test case that with \n

**Comment by liheeng** [comment]
Steps to reproduce this issue.
1. open http://www.shadowsocks8.com/ in brower and there are 3 ss QRCodes.
2. scan these 3 QRCodes from screen.

Result:
error happens with "Not found valid qrcode of shadowsocks profile." msg.

**Comment by qiuyuzhou** [comment]
Ok, I can add code to strip the '\n'. But this is a wrong ss url.
```
"rc4-md5:42296216@106.186.116.88:443\n"
```
This is not bug of shadowsocks-ng, but is bug of the generator which generate the qrcode.

**Comment by liheeng** [comment]
@qiuyuzhou, you are right, it actually contains "\n" which doesn't show up when I used online base64 decode tool. 
But this issue doesn't exist only in above url, it also exists in this url http://www.ishadowsocks.mobi/, don't known why they are all wrong. And other SSX app can parse those qr codes normally.

Suggest to enhance for various cases.
