### ISSUE TITLE
新Macbook Pro15不能用

### ISSUE THREAD

**Issue by BusyCat** [shadowsocks/ShadowsocksX-NG#216]
我有两台macbook。一台12寸的，配置shadowsocksx可以正常使用，x-ng不能用。但是后来删了shadowsocksx又可以用了。但是15寸pro是新版的，一模一样的配置无法使用，不知道应该提供什么样的日志给你。很希望能够修复这个问题。版本是1.3.2(1)

**Comment by qiuyuzhou** [comment]
试新版本的，1.4

**Comment by supersu097** [comment]
@qiuyuzhou 现在用10.12.2在mpb2016上也是打不开，在安全设置里面已经允许了。

**Comment by supersu097** [comment]
@qiuyuzhou 不好意思，刚发现打开之后在状态栏里面会有icon，第一次在mac上用ss的GUI client

**Comment by BusyCat** [comment]
使用了1.4，还是不成功。。。。。现在是mbp 2016版本10.12.3

**Comment by aiddroid** [comment]
+1, 新 MacBook pro 13,经常会超时，不太稳定，换回旧版 shadowsocksX 才好使。

**Comment by qiuyuzhou** [comment]
@aiddroid 可能是shadowsocks-libev的新版2.5.6有问题。

**Comment by alex1212112** [comment]
+1,刚更换了新的 MacBook Pro 15, shadowsocksX-NG 不能用，使用 shadowsocksX  没问题

**Comment by alex1212112** [comment]
把 ~/Library/Preferences 里的 com.qiuyuzhou.ShadowsocksX-NG.plist 和 ~/Library/Application Support 里的 ShadowsocksX-NG/ 删掉,又好了. 参考 #174

**Comment by iloooye** [comment]
我这边新款的macbookpro也是用不了 最新的1.5都不行。。
