### ISSUE TITLE
Auto模式不能链接Google， Global模式才行， 没有自带规则吗？

### ISSUE THREAD

**Issue by A1saka** [shadowsocks/ShadowsocksX-NG#219]
Update GFList后也没用

**Comment by luxin88** [comment]
我也是最近这段时间有这个问题，并且用全局模式访问过一次之后，再切换为PAC模式，就又可以了，过一段时间又不行了，怀疑是google内某个资源文件没有在PAC列表中，全局一次加载完了缓存起来 就可以了

**Comment by luxin88** [comment]
怀疑可能是DNS导致。。。不知道有没有强制远程dns的功能

**Comment by ookangzheng** [comment]
我使用libev模式， 在啟動腳本裡面增加
-A -d 8.8.8.8 就可以咯

**Comment by qiuyuzhou** [comment]
I close this.
If still have problems, reopen it
