### ISSUE TITLE
kcptun的 多项基本参数无法使用

### ISSUE THREAD

**Issue by 0xdatou** [shadowsocks/ShadowsocksX-NG#220]
没有看源代码, 单纯想调sndwnd  rcvwnd字段的大小, 手动更改json配置发现重启ss-ng后配置被重置了 , 

建议可以增加  json导入配置的功能

**Comment by qiuyuzhou** [comment]
这种高级参数不打算支持修改

**Comment by hhmob** [comment]
加入kcptun的功能真的很给力，希望能够支持修改，常用的高级配置希望还是可以通过配置文件来导入，界面配置可以不支持修改，你看这样如何？从配置文件里可以修改下面这些参数

"kcptun" : {
    "localaddr": ":12345",
    "remoteaddr": "77.77.77.77:54321",
    "key": "password",
    "crypt": "aes",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 256,
    "rcvwnd": 2048
}

**Comment by cnekol** [comment]
kcptun功能集成确实很方便，不过仍然也希望加入对各项参数编辑的支持。我以为只给一个入口直接编辑jason即可，无需把所有参数展现在gui上。
因为每个人的网络特性不一样，所以不同的参数设置对于速度的影响还是很大的。如果高级参数不能编辑，那kcptun客户端的加入其实没有被充分利用上。想要达到自己网络最好效果就只有单独跑一个kcptun客户端加参数了，这样集成的功能可能会显得利用率偏低。

**Comment by listeng** [comment]
看 $HOME/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.kcptun.plist

**Comment by qiuyuzhou** [comment]
Give a look at v1.5-beta
