### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by JulySnow** [shadowsocks/ShadowsocksX-NG#221]
OS X 10.12 Xcode 8.2.1
已经安装依赖性环境，Debug提示如下
Ld /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug/proxy_conf_helper normal x86_64
cd /Users/JulySnow/Downloads/ShadowsocksX-NG-hotfix-macOS10.12
export MACOSX_DEPLOYMENT_TARGET=10.10
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug -L/Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug/BRLOptionParser -F/Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug -filelist /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper.LinkFileList -mmacosx-version-min=10.10 -Xlinker -object_path_lto -Xlinker /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -lBRLOptionParser -lPods-proxy_conf_helper -Xlinker -dependency_info -Xlinker /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_dependency_info.dat -o /Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug/proxy_conf_helper

ld: warning: directory not found for option '-L/Users/JulySnow/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-cqjnpxjpxbmiowcrphzgbwmjmdxf/Build/Products/Debug/BRLOptionParser'
ld: library not found for -lBRLOptionParser
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by qinyuhang** [comment]
Build with .xcworkspace file PLZ
https://github.com/shadowsocksr/ShadowsocksX-NG/issues/17
JulySnow <notifications@github.com>于2017年1月25日 周三11:28写道：

**Comment by qiuyuzhou** [comment]
最低支持版本10.11，不支持10.10

**Comment by JulySnow** [comment]
在哪里改

**Comment by dalekzhangdong** [comment]
who to
