### ISSUE TITLE
SS账户在ShadowsocksX-NG上无法使用

### ISSUE THREAD

**Issue by starevo** [shadowsocks/ShadowsocksX-NG#223]
搭建的ss+kcp账户在koolshare固件路由上使用正常，手机端shadowrocket也正常，mac端osx10.12.3用老版shadowsocksx正常，不过升级NG1.4后完全不能使用。不知是软件问题还是配置问题，新手求解？非常感谢。

**Comment by mirifem** [comment]
同样的问题。
同一个帐号在iOS、Android、wIndows都能用，两部macbook pro，一部一直能用，另一部10.12从两个月前开始，死活用不了啦，换帐号也不行。老翻墙手，配置绝对没问题，原因肯定出在系统上。

**Comment by blankhang** [comment]
我下载了1.4.1-alpha版本 打开后 新旧全不能用了...
旧版本也连接不上 然后 新版本不支持SSR?

**Comment by qinyuhang** [comment]
这里本来就不支持ssr。ssr移步 https://github.com/shadowsocksr/ShadowsocksX-NG
blankhang <notifications@github.com>于2017年2月3日 周五01:57写道：

**Comment by blankhang** [comment]
抱歉了 = = 就差一个r...我找了一晚上都没找到...
感谢

**Comment by StevenTsao88** [comment]
同样老版本可以用，X-NG不能用，PAC，全局，手动都不能用

**Comment by devXiaoL** [comment]
使用shadowsocksX NG不能上网的可以按照下面的方法 检查一下，shadowsocksX的本地监听端口号是1080，，，shadowsocksX NG的本地监听端口变成了1086，NG的本地监听端口变成了1086，NG的本地监听端口变成了1086，
image
image

**Comment by devXiaoL** [comment]
使用shadowsocksX NG不能上网的可以按照下面的方法 检查一下，shadowsocksX的本地监听端口号是1080，，，shadowsocksX NG的本地监听端口变成了1086，NG的本地监听端口变成了1086，NG的本地监听端口变成了1086，
![image](https://cloud.githubusercontent.com/assets/12447455/23392156/a9ea2b46-fdb4-11e6-9a9e-a84f020c6708.png)
![image](https://cloud.githubusercontent.com/assets/12447455/23392169/bcd80584-fdb4-11e6-8849-407c536b616c.png)

**Comment by Self-heat** [comment]
无法实现代理。shadowsocksX-NG的socks5监听端口默认1086，但是在我这台机器上面，打开ssX-NG时通过terminal发现1086端口并没有进程占用，是不是说明socks5的监听线程没有启动？

**Comment by sadnessleaf** [comment]
@Self-heat 是的，netstat -nat | grep 1086 查看本机1086端口是否listening状态

**Comment by Self-heat** [comment]
@sadnessleaf 已解决，我是Mac端，更新系统版本为Sierra就是。

**Comment by iamwrm** [comment]
@devXiaoL  所以应该把1086改为1080？ 还是把chrome 的设置改为1086？

**Comment by qiuyuzhou** [comment]
这里聚集了各种配置问题的提问。
我关闭issue了

**Comment by yudeying918** [comment]
端口号改成1086可以用了

**Comment by LeeSurelee** [comment]
cooooool，我在我的mbp15上自动代理可行，但 mbp13就不行，设置手动1086就 ok了
