### ISSUE TITLE
用户自定义规则生效问题

### ISSUE THREAD

**Issue by welinkiot** [shadowsocks/ShadowsocksX-NG#224]
用户自定义规定点击确定，提示已经生效，但测试的情况，需要重启代理工具，新加入的代理规则才会真正生效。虽然提示新加入的规则已经更新到PAC，但是工具还是没有应用到这个问题，后面版本是否可以更正一下，不用在手动重启应用来生效规则。

**Comment by wupengshang** [comment]
感觉https的站点并不能直接添加，重启之后感觉也没生效，各位可有这种情况？

**Comment by welinkiot** [comment]
这个问题没有发现，就是需要重启ss就正常了


Eric · 尚科 | 研发工程师 | (86)186 8247 5952
____________________
深圳市联络者科技有限公司
深圳市南山区留仙大道1183南山云谷(一期)综合楼7楼B7&C9
(0086)0755 2660 8130 | www.welink.io <http://www.welink.io/>

**Comment by qiuyuzhou** [comment]
以前有的版本确实有问题，现在应该是好的
