### ISSUE TITLE
Rules by GeoIP

### ISSUE THREAD

**Issue by sdtaheri** [shadowsocks/ShadowsocksX-NG#226]
Would be cool if we could filter traffic by GeoIP.

**Comment by bakso** [comment]
yes

**Comment by qiuyuzhou** [comment]
It's impossible. Why?

Because It proxy the browser by socks5 protocol. When the browser run the pac(proxy auto  configure) file to determine whether use the proxy to connect the endpoint, it's use domain name, not the ip. The dns lookup would run on remote shadowsocks server.

**Comment by leiyangyou** [comment]
It's actually not entirely impossible, PAC files may call dnsResolve to get the IP
