### ISSUE TITLE
1.4-alpha "Launch at login" issue.

### ISSUE THREAD

**Issue by daveoon** [shadowsocks/ShadowsocksX-NG#230]
When the option "Launch at login" is selected, it is working after restart but the menu icon did not appear. Checking the preferences login items, Shadowsocksx-ng is not in the startup item list and need to add in manually to resolve the issue.

**Comment by qiuyuzhou** [comment]
It won't add app to the list with the new approach. But it work. There is no need add it to startup item list manually.

**Comment by daveoon** [comment]
Do you mean "Launch at Login" option is to run in the background and thus, there will be no menu icon as in version 1.3.2? Thanks.

**Comment by qiuyuzhou** [comment]
Yes.
Old approach has been invalid in mac 10.12.3
So I use a new approach to implement this feature.
