### ISSUE TITLE
有个问题一直困扰我很久了，希望作者有空可以解答下。

### ISSUE THREAD

**Issue by definedw** [shadowsocks/ShadowsocksX-NG#231]
shadowsocks-Ng却一直报错，[ERROR]failed to bind.

**Comment by qiuyuzhou** [comment]
高级设置里调整下PAC监听端口，应该是监听端口已经被占用

**Comment by definedw** [comment]
非常感谢你的回复，我在google和百度找了许久这个问题
![1452f4bc-c10d-498d-b620-d74693865e37](https://cloud.githubusercontent.com/assets/21023645/22679556/f652c7c2-ed3d-11e6-85c5-8a08028eb5df.png)
附上控制台截图
![1](https://cloud.githubusercontent.com/assets/21023645/22679572/11e76b64-ed3e-11e6-9a85-0a4823c91f07.png)
按照你的提示修改相关的pac端口，无效。

**Comment by definedw** [comment]
thanks for you help,Thought the problem still unsolved.
