### ISSUE TITLE
ShadowsocksX-NG新版本如何兼容Macos10.10.5? 或者说为什么不能兼容Macos10.10.5?

### ISSUE THREAD

**Issue by cocoahuke** [shadowsocks/ShadowsocksX-NG#233]
在新的版本里带有协议和混淆协议的支持.然后我的SS提供商也更新了这两个协议的支持
我在SS提供商那里购买时这两个协议选了origin, plain 字面上意思应该没有启动新的协议,但是这样做并不兼容旧版本的ShadowSocket
我因为工作原因实在不想更新系统, 一开始是ss-local允许错误因为没有clock_gettime函数,我给补上了
然后是成功运行了, 本地端口也被打开了,但是依然不可以使用,连上后不能翻墙, 可以请教作者为啥不能兼容10.10的版本吗? 而非要10.12 除了clock_gettime这个原因

顺便贴下我替代clock_gettime的代码, 从stackoverflow上找到的,用fishhook替换到ss-local
int my_clock_gettime(int clk_id,struct timespec *tp){
    clock_serv_t cclock;
     mach_timespec_t mts;
     host_get_clock_service(mach_host_self(),REALTIME_CLOCK,&cclock);
     clock_get_time(cclock,&mts);
     mach_port_deallocate(mach_task_self(),cclock);
     tp->tv_sec = mts.tv_sec;
     tp->tv_nsec = mts.tv_nsec;
    return 0;
}

然后非常感谢作者! 对我来说SS比VPN要方便

**Comment by cocoahuke** [comment]
已经解决!  仅仅是clock_gettime的问题,解决之后就可以使用在旧版本的OSX
我仍然无法使用是因为chrome安装了一个插件接管了proxy的控制, 然而在safari上就没问题 
所以卸载插件后 chrome也可以使用了

**Comment by cocoahuke** [comment]
解决办法: https://github.com/cocoahuke/patch_shadowsocksR

**Comment by weiwen1990** [comment]
> 解决办法: https://github.com/cocoahuke/patch_shadowsocksR

您好，请问按照上述方法，是将make后build/目录下生成的内容：hack_clock_gettime.dylib + patch_ss
放入ShadowsocksX-R.app/Contents/Resources/ 目录下即可使用吗？
谢谢
