### ISSUE TITLE
Kernel(AirPortBrcm4360)

### ISSUE THREAD

**Issue by Zerppen** [shadowsocks/ShadowsocksX-NG#234]
default	14:18:15.227694 +0800	kernel	ARPT: 447280.610798: txpkt (MPDU) Complete
default	14:18:15.227705 +0800	kernel	ARPT: 447280.610811: FrameID: 0x660b
default	14:18:15.227707 +0800	kernel	Seq: 0x068b
default	14:18:15.227710 +0800	kernel	TxStatus: 0x0103
default	14:18:15.227716 +0800	kernel	ARPT: 447280.610822: ACK 0 IM 0 PM 0 Suppr 0 (None)
default	14:18:15.227720 +0800	kernel	ARPT: 447280.610826: CNT(rts_tx)=0 CNT(frag_tx_cnt)=15 CNT(cts_rx_cnt)=0
default	14:18:15.227723 +0800	kernel	ARPT: 447280.610829: DequeueTime: 0x03cef048
default	14:18:15.227726 +0800	kernel	LastTxTime: 0xd20dc37d
一开始用的1.3.1的版本，是这个错误。后来换1.4的版本还是这个错误，求指点

**Comment by qiuyuzhou** [comment]
不应该是ss的问题，ss实现不涉及内核。你应该去google 这个问题。
