### ISSUE TITLE
是否考虑增加pac服务的局域网访问

### ISSUE THREAD

**Issue by jichengdu** [shadowsocks/ShadowsocksX-NG#236]
希望ShadowsocksX-NG作为一个局域网内的整体解决方案
让其他设备也能通过访问pac的方式来使用（否则需要另外维护一个http服务器并且手动更新pac）
包括
1.给 pac server 开放访问权限（目前限定本机）
2.修改默认pac生成的代理服务器（目前为127.0.0.1)

**Comment by wdw89** [comment]
同问，这样会比较方便

**Comment by jcx70100** [comment]
希望增加像win下的“允许来自局域网的访问”的功能，在mac下不知道怎么实现，每次都要转到windows下，很麻烦

**Comment by imtyz001** [comment]
@jcx70100 HTTP代理设置就是你需要的功能

**Comment by jcx70100** [comment]
@imtyz001 具体怎么设置呢？在win下，勾选“允许来自局域网的连接”，在其他设备连接共享的wifi后，设置http代理为ip:端口就可以了，在mac下，同样连接共享的wifi后，输入ip：端口不奏效了

**Comment by imtyz001** [comment]
@jcx70100 勾选HTTP代理的设置 监听地址0.0.0.0 端口自己设置 然后连接的设备手动设置HTTP代理就可以了

**Comment by zhuowenli** [comment]
可以结合 Proxifier 来使用，直接把国内的 IP 地址，或者你自己指定某个软件的请求过滤掉，不走代理。

![image](https://cloud.githubusercontent.com/assets/9620783/24575141/6ed22d58-16d0-11e7-9263-cc21646adcd9.png)
![image](https://cloud.githubusercontent.com/assets/9620783/24575158/c2b57ec0-16d0-11e7-9e58-6b8ccf6a19ac.png)

**Comment by LanioHe** [comment]
@imtyz001 这样还是会需要客户端自己设置pac，现在是如果本地pac可以供局域网访问，那设置起来也很方便

**Comment by imtyz001** [comment]
是的，我说的方法局限性比较大

**Comment by yimiaodaren** [comment]
@imtyz001   ss1.5.2 在ss偏好设置 http代理设置 改成0.0.0.0 port:1087 手机端链接wift设置代理到mac笔记本ip 端口 1087 手机还是无法联网

**Comment by dadupi** [comment]
@imtyz001 同问，偏好设置里设置完毕后，手机端还是无法联网

**Comment by imtyz001** [comment]
@dadupi 看看是否是路由器限制了?我这里是可以正常连接的,有的厂商路由器设置里有一个隔离无线AP的选项,那个不能开

**Comment by HaveF** [comment]
可以用。是不是增加一个“允许来自局域网的访问”的菜单会比较方便？当点选这个菜单之后，sockets和http地址都变成`0.0.0.0`, 取消之后再变回`127.0.0.1`

**Comment by huhuang03** [comment]
楼上把话题带偏了。楼主的意思是需要提供一个http的pac文件给手机用。

我也非常需要这个功能，有哪位大神有实现方法可以告诉下我们吗

**Comment by CrazyBunQnQ** [comment]
@tic-toc-developer 请问在哪里勾选 HTTP 代理的设置呀？

**Comment by CrazyBunQnQ** [comment]
@tic-toc-developer 请问在哪里勾选 HTTP 代理的设置呀？
![设置](http://wx2.sinaimg.cn/large/a6e9cb00ly1fu7ukjgxzgj20qe0hw43r.jpg)

**Comment by suojiang** [comment]
mark

**Comment by walkerwzy** [comment]
两年后的mark. pac比http代理有更多优势, 如果代理主机挂了, pac好像可以自动忽略, 而手动设置的就要把代理关了才能访问, 此外, 一挂上http代理, gfwlist就不生效了, 而pac不会. 所以最好能开放pac路径给局域网用

**Comment by Jonnyan404** [comment]
那这个 pac 实现了吗?

**Comment by qiuyuzhou** [comment]
Merged #1056
