### ISSUE TITLE
Cannot scan QR Code on screen for adding a server on macOS 10.12.4 beta

### ISSUE THREAD

**Issue by florianmonfort** [shadowsocks/ShadowsocksX-NG#237]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG 1.4

**Expected behavior:**

When screening from the screen the QR Code for a server, something should happen and the QR Code being displayed on screen should be scanned.

**Actual behavior:**

At the moment nothing happens.

(N/A for feature requests)

**Steps to reproduce:**

- Launch Shadowsocks without any configuration in particular, straight from the latest binary available on GitHub.
- Go to Shadowsocks > Servers > Scan QR Code from Screen...
- Nothing happens.

**How often does this happen?**

Every time I try, and a colleague confirms he has the same issue.

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

 2017-02-09 10:04:43 ERROR: Invalid config path.
 2017-02-09 10:06:39 ERROR: Invalid config path.
 2017-02-09 10:06:49 ERROR: Invalid config path.
 2017-02-09 10:06:59 ERROR: Invalid config path.
 2017-02-09 10:07:09 ERROR: Invalid config path.
 2017-02-09 10:07:19 ERROR: Invalid config path.
 2017-02-09 10:07:29 ERROR: Invalid config path.
 2017-02-09 10:07:39 ERROR: Invalid config path.

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

Searching `Shadowsocksx-NG` did not return any results.

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by steffenix** [comment]
I think it's not an issue with an old mac os version but it's when password has special characters.

**Comment by klaek** [comment]
Its a small bug. when you scan a qrcode, somethings you get the encrytion is Capital, maybe looks like AES-256-CFB, pls manully change it to aes-256-cfb. little trick n works.

**Comment by qiuyuzhou** [comment]
Please try latest version, if still have problems. It work well on my mac with os version 10.12.4
