### ISSUE TITLE
请问kcptun不支持设置端口么？

### ISSUE THREAD

**Issue by otarim** [shadowsocks/ShadowsocksX-NG#240]
如题，没找到设置远程端口的入口

**Comment by starleafs** [comment]
+1 同问，不知道如何设置kcptun,是因为没有办法设置自定义端口么？

**Comment by cnekol** [comment]
因为kcptun在服务端的靶端口是指向shadowsocks的，所以可以直接在上面SS的端口处填写kcptun的端口，就可以直接通过kcptun访问到shadowsoccks端口了。

例，
Address:『服务器IP』：『Kcptun端口』

**Comment by otarim** [comment]
@cnekol 感谢，已经用回命令行
