### ISSUE TITLE
Mac 怎么重置或者清理参数

### ISSUE THREAD

**Issue by bpplpp** [shadowsocks/ShadowsocksX-NG#244]
我尝试删除X，然后打开后原来的参数还在，参数路径在哪里？
因为我是第一次用，想重置

**Comment by mason96112569** [comment]
~/.ShadowsocksX-NG

**Comment by qiuyuzhou** [comment]
`/Users/*/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist`
