### ISSUE TITLE
扫码添加服务器内存增长很快

### ISSUE THREAD

**Issue by welinkiot** [shadowsocks/ShadowsocksX-NG#246]
你好，扫码添加服务器时，程序内存一下子增加到200M多，这个问题是否正常？谢谢

**Comment by qiuyuzhou** [comment]
可能是这个BUG #225

**Comment by qiuyuzhou** [comment]
已经修复，但是还没有发布

**Comment by welinkiot** [comment]
你好，问题情况相同，以为已经修复。另外请教一下，在服务器设置中的
1、启用OTA 的作用是什么？没有看到相关的文档，不知道怎么使用，谢谢
2、enable over kcptun 是需要服务器支持，是吗？如果不支持，就不能开启这个功能
