### ISSUE TITLE
发现个奇怪的问题,打开闪一下就没了

### ISSUE THREAD

**Issue by ljmam** [shadowsocks/ShadowsocksX-NG#247]
我用你的源码编译出来,自己可以运行,发给朋友打开闪一下就没了,是另外需要安装什么么?
我的系统版本是10.12.4 朋友的是10.12.3 在10.11也试过,都一样的问题,在我自己的mbp上是没问题的

**Comment by ivysboy** [comment]
把软件放进应用程序文件夹就不会闪退了

**Comment by ljmam** [comment]
![image](https://cloud.githubusercontent.com/assets/9445372/23060573/3cb24bea-f539-11e6-9848-95036215cdb4.png)
上面是运行日志
放进应用程序文件夹也会闪退,不知道是不是因为我没开发者帐号签名?

**Comment by ljmam** [comment]
知道了,是我自己添加的代码有问题.

请问一下在AppDelegate中的applicationDidFinishLaunching里想弹一个窗口出来,为什么在本机上用showWindow(self)就会闪退呢

具体代码:
var tishis: Tishi!
if tishis != nil{
tishis.close()
}
let ti = Tishi(windowNibName: "Tishi")
tishis = ti
ti.showWindow(self)

新建了一个Tishi.xib窗口

在开发环境中的机器上没问题,用的是xcode 8.2.1(8c1002) SDK是10.12
但是在其它机器上会闪退,把ti.showWindow(self)去掉是可以继续执行的
