### ISSUE TITLE
Auto launch at login is not wok

### ISSUE THREAD

**Issue by zky999** [shadowsocks/ShadowsocksX-NG#249]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG 1.4

**Expected behavior:**

重启系统后菜单栏应该有ShadowsocksX-NG的图标。

**Actual behavior:**

重启系统后菜单栏没有ShadowsocksX-NG的图标，通过ps命令和launchctl查看shadowsocks也已经正常运行，代理也正常工作。

**Steps to reproduce:**

1、正常运行；
2、正常重启；

**How often does this happen?**

总是。

**Comment by brallow** [comment]
OS X 10.12.2
Shadowsocks NG 1.4（3）
存在同样的问题

**Comment by qiuyuzhou** [comment]
Try the new version v1.5.beta.2

**Comment by qiuyuzhou** [comment]
#269
