### ISSUE TITLE
kcptun 设置不好

### ISSUE THREAD

**Issue by hijkzzz** [shadowsocks/ShadowsocksX-NG#250]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG 1.4

KCP Port      : 38989
KCP parameter : --crypt aes --key xxxxxxx --mtu 1350 --sndwnd 128 --rcvwnd 1024 --mode fast2

不知道端口填到哪里，还有sndwnd 之类的也没地方设置，目前无法正常工作
手机客户端复制填参数就行了，这个集成kcptun客户端用不了

**Comment by hijkzzz** [comment]
kcp port 直接填到 ss 端口处，通过 kcptun 访问 ss

**Comment by wanghaifeng** [comment]
[如果设置问题，参见这里](http://imgur.com/a/kavFp)

**Comment by Kaijun** [comment]
@wanghaifeng 这样设置还是不太对。

**Comment by qiuyuzhou** [comment]
不支持设置sndwnd,rcvwnd
请用缺省值

**Comment by benqiu** [comment]
参考了 @wanghaifeng 的配置图 终于解决了 原先我的问题是 上面填写的ss的端口 下面填写了kcptun的端口 搞反了 要是在设置的时候有一些提示就好了。

**Comment by zxq1002** [comment]
dscp也不能设置吗？

**Comment by wanghaifeng** [comment]
设置后还连不上的话，需要查看其它参数是否和server_linux_xxx的启动参数一致，另外检查防火墙是否允许连接kcptun的端口。
