### ISSUE TITLE
通过二维码添加的问题

### ISSUE THREAD

**Issue by wodedajiba** [shadowsocks/ShadowsocksX-NG#251]
通过二维码扫描添加，加密方式为CHACHA20，大写，可以添加成功，但是不能连接，需要手动修改成chacha20，请问是否可以在添加之后过滤一下，将大写或者小写自动转换成，X-NG可以识别的格式，目前X么有这个问题，通过点击SS://XXX可以自动识别为ssx，点击确定就可以添加了。

**Comment by qinyuhang** [comment]
reference to https://github.com/shadowsocksr/ShadowsocksX-NG/issues/98 <https://github.com/shadowsocksr/ShadowsocksX-NG/issues/98>

**Comment by wodedajiba** [comment]
看来多平台兼容是有点蛋疼，有些安卓的机器是CHACHA20。。。

**Comment by wodedajiba** [comment]
还有一个问题，就是刚说的，如果是SS://这样的链接在浏览器总打开，会自动提示是否打开ssx 如果确定就自动添加了这个链接的服务器，但是换成SSX-NG之后点击打开程序就退出了，再次点击就又打开程序了，但是没有添加进去服务器，是不是不支持？@qinyuhang

**Comment by qinyuhang** [comment]
是支持链接打开添加的，但是对于一个链接里面有多个服务器的，暂时还不支持

**Comment by wodedajiba** [comment]
你可以先测试一下，比如 <a href="ss://xxxxx">测试</a> 这样一个链接，只有一个服务器的信息，也不能添加的。如果程序是打开的，那么就会推出，如果是没有打开的，点击 打开之后 没有任何反应。 @qinyuhang

**Comment by wodedajiba** [comment]
`<a href="ss:/xxx">测试</a>`

**Comment by qinyuhang** [comment]
关于 点击 `ss://` url 导致程序退出的bug已经push merge commit 可以等待被merge https://github.com/shadowsocks/ShadowsocksX-NG/pull/253
