### ISSUE TITLE
ss-local不再是后台服务？

### ISSUE THREAD

**Issue by Arrow-Li** [shadowsocks/ShadowsocksX-NG#252]
**10.11.6**
**Version 1.4**

运行ShadowsocksX-NG时ss正常,退出ShadowsocksX-NG后ss-local也被结束了。
原来1.2的时候是退出后ss-local是正常运行的。

**Comment by Arrow-Li** [comment]
func applicationWillTerminate(_ aNotification: Notification) {
        // Insert code here to tear down your application
        StopSSLocal()
        StopKcptun()
        StopPrivoxy()
        ProxyConfHelper.disableProxy()
        if let ref = hotKeyRef { UnregisterEventHotKey(ref) }}

退出时加上ss-local stop了？

**Comment by Arrow-Li** [comment]
<img src="http://p1.bqimg.com/4851/e2fdc172c8dcf094.png">
ShadowsocksX-NG退出时的日志,ss-local应该是start成功了，但是进程里没有

**Comment by qiuyuzhou** [comment]
因为现在pac服务器在app内而不是使用file:///形式的地址，退出后就没有了。所以现在退出app会结束所有的进程。

**Comment by Arrow-Li** [comment]
平时不用pac模式，能考虑改一下么
