### ISSUE TITLE
PAC doesn't match part of url

### ISSUE THREAD

**Issue by clementhk** [shadowsocks/ShadowsocksX-NG#255]
**System and Shadowsocksx-NG version:**

- macOS 10.12.3 (16D32)
- Shadowsocksx-NG Version 1.4.0 (3)

**Expected behavior:**
PAC works with http://www.bbc.com/zhongwen/simp .

**Actual behavior:**
It doesn't work. Global mode works.

".bbc.com/zhongwen" is in 
https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

**Comment by qiuyuzhou** [comment]
It's work at my machine.
Try to click the menu item to update pac file by latest gfwlist.
