### ISSUE TITLE
求增加Ping功能

### ISSUE THREAD

**Issue by evolutionjay** [shadowsocks/ShadowsocksX-NG#256]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG 1.4

有时候有很多服务器，但是不知道哪个服务器挂了，哪个顺畅，所以求一个ping功能。

**Comment by shenyunhuan** [comment]
同求

**Comment by nanacheung** [comment]
同求➕1

**Comment by Fomovet** [comment]
+1

**Comment by ulyssess** [comment]
+1
> 在 2017年3月6日，下午5:12，Fomovet <notifications@github.com> 写道：
> 
> +1

**Comment by omaidb** [comment]
同求+1

**Comment by caizhencang** [comment]
+1

**Comment by flipphos** [comment]
+1
1.4之前的老版本有测试服务器功能的，希望能够保留这个功能，很实用的。谢谢！

**Comment by qinyuhang** [comment]
1.4以前的老版本也没有测速功能，是ssr衍生版本的。

**Comment by flipphos** [comment]
哦哦，原来如此。
我手上有个NG-R8的，估计就是衍生版本了。主版本是 1.3.xx

**Comment by omaidb** [comment]
测试服务器功能很好啊，增加啊

flipphos <notifications@github.com>于2017年3月28日 周二11:33写道：

**Comment by qiuyuzhou** [comment]
duplicate #20
