### ISSUE TITLE
OTA now fully deprecated - what about AEAD

### ISSUE THREAD

**Issue by ortonomy** [shadowsocks/ShadowsocksX-NG#260]
OTA now fully deprecated on Shadowsocks site - does Shadowsocks X NG support ``AEAD ciphers`` out of the box?

http://shadowsocks.org/en/spec/AEAD-Ciphers.html 

if not, when will it?

**Comment by cs17899219** [comment]
+1

**Comment by qiuyuzhou** [comment]
Wait a stable version of shadowsocks-libev.

**Comment by ortonomy** [comment]
http://shadowsocks.org/en/spec/Implementations.html

It says that shadowsocks-libev now support AEAD - is it not stable?

**Comment by qiuyuzhou** [comment]
Have embed latest ss-local in 1.5-beta

**Comment by ortonomy** [comment]
Great. Does this mean AEAD is supported now? It just has to be configured on the server?

**Comment by qiuyuzhou** [comment]
@ortonomy 
Use below encrypt methods:
aes-128-gcm, aes-192-gcm, aes-256-gcm

**Comment by ortonomy** [comment]
@qiuyuzhou - Shadowsocks NG doesn't support aes-xxx-gcm. I just tried adding my new server and these are not available to choose as an encryption method...?

**Comment by qiuyuzhou** [comment]
@ortonomy 
Plz use latest version. From v1.5.beta should have these methods.
The latest version is v1.5.beta.2

**Comment by qiuyuzhou** [comment]
@ortonomy scroll up when open combo.

**Comment by qiuyuzhou** [comment]
Maybe I should change the default encryption method.

**Comment by ortonomy** [comment]
@qiuyuzhou - got it! Thanks for the info :)
