### ISSUE TITLE
can't run telegram with PAC mode

### ISSUE THREAD

**Issue by bringtree** [shadowsocks/ShadowsocksX-NG#263]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 beta (16E144f)
- Shadowsocksx-NG 1.4

**Expected behavior:**

can run telegram with PAC mode

**Actual behavior:**
It only can run with global mode. I want to know how can i do to fix this problem?  Could you help me ？
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by qinyuhang** [comment]
using telegram desktop and set telegram proxy will work
peisong <notifications@github.com>于2017年2月27日 周一21:10写道：

**Comment by bringtree** [comment]
I am using telegram desktop. How can i set telegram proxy will work? i can't find this option.
Telegram Version 2.29.51395 @qinyuhang

**Comment by qinyuhang** [comment]
Go to settings -> proxy; and fill UR proxy config.

**Comment by bringtree** [comment]
In Telegram ?  In Shadowsocks?

**Comment by bringtree** [comment]
ok Thx 👍 @qinyuhang

**Comment by Tsahao** [comment]
@qinyuhang 为什么不能默认 telegram 走代理呢？

**Comment by qinyuhang** [comment]
U may ask the developer of Telegram directly.
