### ISSUE TITLE
Add option to disable shortcut to switch proxy mode

### ISSUE THREAD

**Issue by aihornmac** [shadowsocks/ShadowsocksX-NG#264]
Currently the app supports shortcut to switch proxy mode while lacking option in setting to enable/disable shortcut mode, which sometimes leads to misoperation (even without consciousness). It will be much better if such an option be added.

As usual, thank you for your dedication!

**Comment by qiuyuzhou** [comment]
003727a0fe03304af0ac0f315cfb38250994d02b
