### ISSUE TITLE
Users rule doesn't work no matter I edited it from GUI or directly edited user-rule.txt | user rule无法使用

### ISSUE THREAD

**Issue by GitHub27182818** [shadowsocks/ShadowsocksX-NG#265]
'''
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
|http://ip138.com
'''

version1.3.2

**Comment by balibell** [comment]
Is user-rule.txt used?
I added new rules in preferences > Edit User Rules For PAC... which are not shown in user-rule.txt.

**Comment by qiuyuzhou** [comment]
Have you click the ok button?

Chen Bo <notifications@github.com>于2017年3月11日周六 下午11:45写道：

**Comment by balibell** [comment]
![f17c7845-fdc1-4b98-b5c1-afa888012585](https://cloud.githubusercontent.com/assets/5236078/23828962/9b648072-071d-11e7-8086-f6e756c25675.png)

**Comment by balibell** [comment]
![838cee11-954a-46c5-9617-ec9de3dc6461](https://cloud.githubusercontent.com/assets/5236078/23828975/15e10a32-071e-11e7-8694-c439f2439dd6.png)

**Comment by balibell** [comment]
我想知道真正的PAC文件在哪，很显然 Resources/gfwlist.txt  并不是，我修改它是不会生效的。

**Comment by balibell** [comment]
知道了，访问本地pac文件的地址
http://127.0.0.1:1089/proxy.pac

**Comment by qiuyuzhou** [comment]
`~/.ShadowsocksX-NG/user-rule.txt`
