### ISSUE TITLE
连接后Safari不能连接到服务器

### ISSUE THREAD

**Issue by EEEEElio** [shadowsocks/ShadowsocksX-NG#270]
如标题，前几天还好好的，今天不知道是怎么了，还原了网络设置也重新启动了都没用。。。
![2017-03-05 10 55 34](https://cloud.githubusercontent.com/assets/17145926/23596312/4970be82-01f7-11e7-8937-898c134740e6.jpg)

**Comment by qinyuhang** [comment]
可否按照git issue 的 template 来？提问也要按照基本法呀？

**Comment by qiuyuzhou** [comment]
This doesn't make sense.
