### ISSUE TITLE
Switch to new Go implementation of shadowsocks?

### ISSUE THREAD

**Issue by maddie** [shadowsocks/ShadowsocksX-NG#273]
Consider switching to [the new Go implementation of shadowsocks](https://github.com/shadowsocks/go-shadowsocks2)? Then we can stop worrying about dependencies.

**Comment by qiuyuzhou** [comment]
Good idea. I love go lang. Static link is a killer feature.

maddie <notifications@github.com>于2017年3月12日周日 上午12:45写道：

**Comment by vkings1** [comment]
Yeah good to know. Go they can bypass the isp?

**Comment by maddie** [comment]
@vkings1 It's Shadowsocks. It's the same implementation across languages.

**Comment by vkings1** [comment]
@maddie okay. How to work woth it?
