### ISSUE TITLE
使用了不受支持的协议

### ISSUE THREAD

**Issue by ahlixinjie** [shadowsocks/ShadowsocksX-NG#275]
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。

服务端是shadowsocks-libev 最新版, 客户端是shadowsocksx-ng 1.4 , 浏览器是chrome, 访问墙外网站会出现上述问题
使用老版的shadowsocksX则一切正常, 请问这是什么原因

**Comment by ahlixinjie** [comment]
系统和浏览器的版本都是最新版

**Comment by maddie** [comment]
首先，确保没有使用3.x的AEAD cipher，原本2.x中的aes-xxx-gcm系列cipher已经变成AEAD
其次，确保OTA关闭，3.x已经不再支持OTA

**Comment by snowindy-k** [comment]
@maddie 请问为何不支持 aes-***-gcm系列的cypher了? 如果直接用 `ss-client` 是有这个option的。

**Comment by maddie** [comment]
@snowindy-k 不是不支持，而是从3.x开始aes-xxx-gcm系列cipher变成了AEAD协议，和名字相同的2.x协议不兼容，所以两边(2.x客户端+3.x服务器 or vice versa)就算选上了同样的aes-xxx-gcm cipher，都是不能通讯的

**Comment by snowindy-k** [comment]
@maddie 谢谢。 那是不是需要等`ShadowsocksX-NG`打包3.x的shadow socks-libev?

**Comment by maddie** [comment]
@snowindy-k 暴力一点你可以`brew install shadowsocks-libev`，这样会装最新的3.0.4，把Homebrew的`ss-local`替换掉ShadowsocksX-NG的app bundle里面的`ss-local`来用，按道理没有什么副作用，只是要注意不能选上OTA选项以及用不了新的AEAD cipher例如`chacha20-ietf-poly1305`，因为ShadowsocksX-NG的选项列表里没有

**Comment by ahlixinjie** [comment]
@maddie 取消了OTA之后就正常使用了
