### ISSUE TITLE
无法退出

### ISSUE THREAD

**Issue by maicss** [shadowsocks/ShadowsocksX-NG#282]
**System and Shadowsocksx-NG version:**

- macOS 10.12.3 (16E????)
- Shadowsocksx-NG 1.4

**Expected behavior:**

1， 装上之后，一直链接不上，报这个log
> Mar 21 18:03:52 DSiMac com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.kcptun[50397]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Users/mac/Library/Application Support/ShadowsocksX-NG/: 16D32: xpcproxy + 11211 [1356][286733C4-18D9-396D-B01B-A096BE5B1DC1]: 0x2
Mar 21 18:03:52 DSiMac com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.kcptun): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Mar 21 18:03:52 DSiMac com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[50398]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Users/mac/Library/Application Support/ShadowsocksX-NG/: 16D32: xpcproxy + 11211 [1356][286733C4-18D9-396D-B01B-A096BE5B1DC1]: 0x2
Mar 21 18:03:52 DSiMac com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Mar 21 18:03:52 DSiMac com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[50399]): Service could not initialize: Unable to set current working directory. error = 2: No such file or directory, path = /Users/mac/Library/Application Support/ShadowsocksX-NG/: 16D32: xpcproxy + 11211 [1356][286733C4-18D9-396D-B01B-A096BE5B1DC1]: 0x2
Mar 21 18:03:52 DSiMac com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

2，我删了软件，之后控制台还是一直报这个错，是没有删干净？我top里面也查看了，没有进程了，但是还是有log，这怎么有种百度全家桶的感觉……

3，没找到ss-local.log

**Comment by qiuyuzhou** [comment]
实际服务是以后台服务形式运行的
删除以下服务配置，然后重启
`
~/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.*.plist
`

**Comment by Yufeikang** [comment]
我没有使用的时候为什么会有个后台服务在这里，可以关掉吗
