### ISSUE TITLE
v1.5 alpha，设置模式切换快捷键后，切换时提示信息错误

### ISSUE THREAD

**Issue by nylqd** [shadowsocks/ShadowsocksX-NG#283]
设置了switch mode的shutcuts之后，利用快捷键切换全局和自动模式的时候，提示信息错误，全模式提示提示“auto mode by pac”，自动模式提示为“global mode”，请检查是否提示信息绑定错误？

**Comment by qiuyuzhou** [comment]
Thanks.
更新菜单和应用配置的时机错了。
