### ISSUE TITLE
AEAD - can I use them with Shadowsocks 1.5 alpha for macOS

### ISSUE THREAD

**Issue by ortonomy** [shadowsocks/ShadowsocksX-NG#284]
You've just deprecated OTA - is AEAD inside 1.5 alpha?

**Comment by qiuyuzhou** [comment]
No just a notice.

**Comment by ortonomy** [comment]
'No just a notice.' this doesn't make any sense?

No - just a notice of what?

**Comment by qiuyuzhou** [comment]
Sorry for my poor english.
Just change the label, let the users who see the label to know  they should not use  OTA.

**Comment by ortonomy** [comment]
OK, thanks.
