### ISSUE TITLE
希望能整合最新版的 Kcptun

### ISSUE THREAD

**Issue by Mongkii** [shadowsocks/ShadowsocksX-NG#286]
**System and Shadowsocksx-NG version:**

- macOS 10.12.3
- Shadowsocksx-NG 1.5

Kcptun 作者最近发布了 20170322 版本，优化了 CPU 的使用等，是他力荐的一次升级。
在这里告诉您，同时希望在下一版 Shadowsocksx-NG 能整合最新的 Kcptun，相信这对 Mac 上 SS 的电量消耗与系统占用都会有帮助。辛苦了！

**Comment by qiuyuzhou** [comment]
Ok.
最新的开发分支已经升级了。

**Comment by gMan1990** [comment]
@qiuyuzhou 这个Kcptun要怎么用
