### ISSUE TITLE
菜单栏图标颜色显示过暗

### ISSUE THREAD

**Issue by Sharnodra** [shadowsocks/ShadowsocksX-NG#29]
Mac采用暗色菜单栏并且关闭Shadowsocks后，小飞机颜色相对原版有点太暗了

<img width="58" alt="2016-08-10 7 35 02" src="https://cloud.githubusercontent.com/assets/8577653/17552278/8aa71676-5f31-11e6-898f-fcbbfc68ceef.png">

**Comment by qiuyuzhou** [comment]
不知有没有设计师给换套图标方案？不要用颜色深浅表示开关。

**Comment by bluefo** [comment]
我可以帮忙，请联系我。@qiuyuzhou
然后全局模式和自动模式能否也用图标区分，因为我总是开了全局模式之后忘记改回来。

**Comment by ilessy** [comment]
是的我每次都搞不清楚,我希望用空心和实心的方式来表示开关, 这样就不会搞错了

**Comment by qiuyuzhou** [comment]
Fix in 44c2a2a47bc28935ae72d72da20f2f165887d311

**Comment by qiuyuzhou** [comment]
Same issue #295
