### ISSUE TITLE
macOS 10.12.4 ss-local not run

### ISSUE THREAD

**Issue by Reapor-Yurnero** [shadowsocks/ShadowsocksX-NG#293]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4
- Shadowsocksx-NG 1.4(1.5a)

**Actual behavior:**
ss-local not run.

**Steps to reproduce:**
Just installed it. Bug still occurs after a system restart.

**How often does this happen?**
Always for me.

**ss-local.log**

Since ss-local is not called so there's no ss-local.log

**Application log**

default	09:16:23.658004 +0800	ShadowsocksX-NG	Start ss-local succeeded.
default	09:16:23.722661 +0800	ShadowsocksX-NG	Start privoxy succeeded.
default	09:16:23.722890 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	09:16:23.751462 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2688] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2728] (3,0)
default	09:16:23.752723 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2688] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2728] (3,0)
default	09:16:23.754916 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2688] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2728] (3,0)
default	09:16:23.755779 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2688] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2728] (3,0)
default	09:16:23.757208 +0800	ShadowsocksX-NG	pac proxy set to global

**Comment by J-Liu** [comment]
Ditto, ShadowsocksX-NG working very unstable on macOS 10.12.4.

**Comment by vicsino** [comment]
The same problem, it seems that 1.5 not work well with macOS 10.12.4.

**Comment by J-Liu** [comment]
Is there any working version or will 1.5 be soon released?

**Comment by qiuyuzhou** [comment]
I have received the 10.12.4 update pushing tonight. So I would upgrade os and check the bug tomorrow.

**Comment by qiuyuzhou** [comment]
I have upgraded my mac os to version 10.12.4. The ShadowsocksX-NG working well on my mac.

**Comment by qiuyuzhou** [comment]
If you want my help, need more informations.

**Comment by vicsino** [comment]
```
Dyld Error Message:
  Library not loaded: */libmbedcrypto.0.dylib
  Referenced from: /Users/USER/Library/Application Support/ShadowsocksX-NG/*/ss-local
  Reason: image not found

```
This error make the ss-local crash & crash again.

**Comment by vicsino** [comment]
`brew install mbedtls`
After I installed this, problem disappear.

**Comment by qiuyuzhou** [comment]
@vicsino mbedtls problem has been fix in v1.5.beta.2

**Comment by Reapor-Yurnero** [comment]
Actually my ss-local never crashed and because it has never been started. I have also tried 1.4 but problem still occurred.

**Comment by listenfree** [comment]
in my osx 10.11.6   completely not working too

**Comment by registe** [comment]
MacOS 10.12.4

Starting with mode m, g, p, `netstat -anp tcp` didn't show the default port 1080.

Can anybody tell me how to reset the configuration for Shadowsocksx-NG?

**Comment by registe** [comment]
```
./ss-local-3.0.5/ss-local -c ./ss-local-config.json dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libev/lib/libev.4.dylib
  Referenced from: /Users/cnhavee/Library/Application Support/ShadowsocksX-NG/./ss-local-3.0.5/ss-local
  Reason: image not found
Abort trap: 6
```

**Comment by emdoe** [comment]
@listenfree @Reapor-Yurnero Maybe you should resolved the package dependencies. In other words, all these packages, including libev, libsodium, mbedtls, and udns, should be installed correctly, e.g. `brew install libev libsodium mbedtls udns`.

@qiuyuzhou I think #341 #344 #350 maybe the same problem. And I believe you have already installed all of above packages, thus your software work perfectly.

**Comment by sirkyuubi** [comment]
I had this exact problem. When I upgraded from OS X El Capitan to High Sierra v10.13.1 SSX-NG stopped working. 

I ran `brew install libev libsodium mbedtls udns` and the problem went away
