### ISSUE TITLE
需要安装 mbedtls 才能启动  brew install mbedtls

### ISSUE THREAD

**Issue by liuyongsheng** [shadowsocks/ShadowsocksX-NG#294]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 
- Shadowsocksx-NG 1.5-beta

暗色菜单栏图标显示灰色，不是白色，像是关闭了一样，和其他图标比起来太暗，希望能调整。

另外需要安装 mbedtls 才能启动
- brew install mbedtls

**Comment by J-Liu** [comment]
能稳定工作啊？Google和gmail好像不能同时都打开啊，总有一个打不开，甚至俩都打不开。

**Comment by caizhencang** [comment]
安装了1.5 beta2，暗色菜单栏图标显示还是有问题

**Comment by qiuyuzhou** [comment]
@caizhencang 暗色菜单已经修好，还没发布。#295

**Comment by softfn** [comment]
系统使用“Use dark menu bar and Dock”时，启用图标就多了一个G很不明显，能否显示成白色图标？
