### ISSUE TITLE
icon is so dark.

### ISSUE THREAD

**Issue by xuxiaokang** [shadowsocks/ShadowsocksX-NG#295]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 (16E195)
- Shadowsocksx-NG 1.5.0 (2)

**Expected behavior:**
希望能够考虑一下dark menu bar的情况下icon的颜色。
<img width="155" alt="screen shot 2017-03-28 at 22 56 56" src="https://cloud.githubusercontent.com/assets/9929307/24412372/df4baf0a-140a-11e7-92b7-390c620b5547.png">

**Comment by julienschmidt** [comment]
<img width="165" alt="screen shot 2017-03-29 at 16 39 32" src="https://cloud.githubusercontent.com/assets/944947/24445961/6040a42e-149e-11e7-950a-383d8c813d62.png">

It looks like other icons in deactivated state (compare with the Bluetooth icon on the right). I was initially confused if Shadowsocks was on or not.
But that's basically how it should look like if Shadowsocks is turned off 😁

**Comment by qiuyuzhou** [comment]
Ok. I give issue a google, then I have got this: http://indiestack.com/2014/10/yosemites-dark-mode/

**Comment by qiuyuzhou** [comment]
Fix in 44c2a2a47bc28935ae72d72da20f2f165887d311
