### ISSUE TITLE
kcptun的端口设置问题？

### ISSUE THREAD

**Issue by hugodotlau** [shadowsocks/ShadowsocksX-NG#296]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 (16E195)
- Shadowsocksx-NG 1.5.0 (3)

**Expected behavior:**
目前改了kcptun 的端口 ss 端口也会随着变化，不应该是由"enable over kcptun"来确定是否使用kcptun的开关么？如果是按上述这么设计应该有两个独立不关联的端口才是啊。

**Comment by qiuyuzhou** [comment]
其实一直是一个属性，只是有很多人不知道启用kcptun后，要在上面设置端口。所以在UI布局上有所调整。
