### ISSUE TITLE
macOS 10.12 Beta 系统PAC代理不支持file://形式的url，需要以http://形式提供

### ISSUE THREAD

**Issue by meritozh** [shadowsocks/ShadowsocksX-NG#30]
如题，这个bug我无法理解……

**Comment by qiuyuzhou** [comment]
这个暂时解决不了，我没有机器可以装beta版，工作机器不能随便动。
有没有其他有条件的人给看下？

**Comment by qiuyuzhou** [comment]
@meritozh 建议你给出更多信息
- ~/.ShadowsocksX-NG/gfwlist.js在不在？
- 网络代理设置里的自动代理设置是否能正确设置上？

目前不知道是否10.12Beta都有问题？其他人有问题或没问题，都可以留言下

**Comment by meritozh** [comment]
@qiuyuzhou 
* gfwlist.js 存在
* 网络的代理设置正确

**Comment by itzhaclea** [comment]
@meritozh 可能是 Safari 的問題。在「Auto by PAC」模式下，Chrome 是可以正常連結 Google、YouTube 等網站的。

**Comment by qinyuhang** [comment]
这个可能是因为：

> 注：Safari浏览器不支持SOCKS5关键字，因此请再额外添加以"SOCKS"关键字开头的代理，IP与端口号不变

https://github.com/breakwa11/gfw_whitelist/blob/master/README.md

**Comment by qiuyuzhou** [comment]
缺省是包括socks关键字的

`var proxy = "SOCKS5 127.0.0.1:1086; SOCKS 127.0.0.1:1086; DIRECT;";`

**Comment by qinyuhang** [comment]
这个原因就有点不明了，可以试试回头用一个外接硬盘装一个10.12来测试一下。

**Comment by qiuyuzhou** [comment]
@meritozh 查看系统日志没有？

**Comment by qinyuhang** [comment]
经测试，10.12确实存在此问题。ShadowsocksX-NG PAC 模式下 Safari 不能FQ，但是原版的 SSX 的 PAC 模式可以正常工作。且直接在 macOS 10.12 下用 Xcode 编译 debug 没有直接报错，应该不是
疑似错误 console 截图如下：(需要的话把logs文件po到这里)
<img width="970" alt="2016-08-15 12 52 15" src="https://cloud.githubusercontent.com/assets/6239057/17653487/f935516c-62c8-11e6-8a81-cf4b4ea65e2e.png">
<img width="1178" alt="2016-08-15 12 55 21" src="https://cloud.githubusercontent.com/assets/6239057/17653490/0ae04e1c-62c9-11e6-9e64-a3a98b3b0522.png">
<img width="956" alt="2016-08-15 12 55 31" src="https://cloud.githubusercontent.com/assets/6239057/17653516/487b1e1e-62c9-11e6-9717-561d9d42bece.png">
<img width="580" alt="2016-08-15 12 56 11" src="https://cloud.githubusercontent.com/assets/6239057/17653518/48fbc5aa-62c9-11e6-8309-9cebade37550.png">
<img width="935" alt="2016-08-15 12 56 34" src="https://cloud.githubusercontent.com/assets/6239057/17653517/48f69f1c-62c9-11e6-88d5-aa3eeedb42f0.png">

**Comment by qiuyuzhou** [comment]
那就是对file://前缀的URL支持有问题，只能使用http://前缀pac地址。

先等apple修复吧，可以去apple报bug。

ShadowsocksX-NG进行workaround的话，需要内嵌web server

**Comment by qinyuhang** [comment]
所以这个只是Safari beta的问题？使用老版本的Safari可以解决？

Qiu Yuzhou <notifications@github.com>于2016年8月15日 周一09:23写道：

**Comment by qinyuhang** [comment]
https://github.com/swisspol/GCDWebServer/
这个 web server 库是原版用的，支持苹果全平台，现在开发更新也挺频繁的，可否考虑一下？

**Comment by meritozh** [comment]
@qinyuhang 这就应该是系统网络代理的问题了吧。Safari用的是系统代理设置，log显示PAC文件源无法读取，应该就是对`file://`协议限制了

**Comment by qinyuhang** [comment]
@meritozh 可否帮忙测试一下 https://github.com/qinyuhang/ShadowsocksX-NG/releases/tag/1.2 我做了 “workaround的话，需要内嵌web server” #42 的朋友 ~/.ShadowsocksX-NG/gfwlist.js 不存在

**Comment by Mac0ne16** [comment]
哎呀，GM版本也是无法使用的，估计正式版一样的。正式版估计也会被禁用的。

**Comment by qinyuhang** [comment]
要是很不方便的话 可以使用我那个补丁来源的app……

Mac0ne16 <notifications@github.com>于2016年9月8日 周四16:29写道：

**Comment by qinyuhang** [comment]
斑斑驳

秦宇航 <qinyuhangxiaoxiang@gmail.com>于2016年9月9日 周五20:03写道：

**Comment by g1084164986** [comment]
正式版中也无法使用啊，应该是Safari的问题，chrome使用pac模式就可以正常使用。

**Comment by Retorz** [comment]
@g1084164986 
chrome中pac是通过`SwitchyOmega `之类的plugin实现的吧？`SwitchyOmega `实际是preload ‘https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt’中的信息，并不是读取local file

**Comment by fifizy** [comment]
类似的问题，解决了。在网络设置中增加sock5代理。sock5和pac同时使用，Safari正常FQ
