### ISSUE TITLE
ld: library not found for -lBRLOptionParser clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by lampchop** [shadowsocks/ShadowsocksX-NG#301]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4  
- Shadowsocksx-NG dev

xcode ：8.2.1

error：
ld: library not found for -lBRLOptionParser
clang: error: linker command failed with exit code 1 (use -v to see invocation)

大概是啥情况呢

**Comment by qinyuhang** [comment]
check GitHub issue https://github.com/shadowsocksr/ShadowsocksX-NG/issues/17 <https://github.com/shadowsocksr/ShadowsocksX-NG/issues/17>

**Comment by lampchop** [comment]
666， 我果然和他一样蠢。 大佬辛苦了

**Comment by dalekzhangdong** [comment]
issues/17  is 404 error page

**Comment by dalekzhangdong** [comment]
#304 repair with $301 ,loop back

**Comment by dalekzhangdong** [comment]
#17 is 404 error page now , who can help me

**Comment by dalekzhangdong** [comment]
podfile have BRLOptionParser info , pod install ok , but can't compile , find BRLOptionParser  lib in /usr/local/lib and /usr/lib , not find .

**Comment by dalekzhangdong** [comment]
Showing Recent Messages
ld: warning: directory not found for option '-L/Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Products/Debug/BRLOptionParser'

**Comment by dxxbox** [comment]
it is not 404, just wrong link address.

change https://github.com/shadowsocksr/ShadowsocksX-NG/issues/17
to https://github.com/shadowsocks/ShadowsocksX-NG/issues/17
