### ISSUE TITLE
使用暗色菜单栏和Dock时，菜单栏图标不能切换为白色。

### ISSUE THREAD

**Issue by FateLight** [shadowsocks/ShadowsocksX-NG#302]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 (16E195)
- Shadowsocksx-NG 1.5.0 (3)

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by nylqd** [comment]
already fix in https://github.com/shadowsocks/ShadowsocksX-NG/commit/44c2a2a47bc28935ae72d72da20f2f165887d311

search before issue plz
