### ISSUE TITLE
KCP never works

### ISSUE THREAD

**Issue by ztxgeol** [shadowsocks/ShadowsocksX-NG#303]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 (16E195)
- Shadowsocksx-NG 1.4

**Expected behavior:**

Running the Shadowsocks client over KCP.

**Actual behavior:**

Failed to establish connection to remote server with KCP enabled after reboot the laptop.

**Steps to reproduce:**

Turn on KCP option & reboot

**How often does this happen?**

The KCP option only worked once and never worked any more.

_Sorry for NOT providing ANY logs since I don't have that time._

**Comment by Kaijun** [comment]
same with me https://github.com/shadowsocks/ShadowsocksX-NG/issues/313

**Comment by Kaijun** [comment]
u could try my solution https://github.com/shadowsocks/ShadowsocksX-NG/issues/313#issuecomment-292405423  and see if it also works for u

**Comment by ztxgeol** [comment]
@Kaijun Tks for the tips, but in fact all my paraments are correct.
Anyway, I've moved on and started using something else.
Much appreciate again.
