### ISSUE TITLE
求助：编译报错

### ISSUE THREAD

**Issue by northleafup** [shadowsocks/ShadowsocksX-NG#304]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4
- Shadowsocksx-NG 
- xcode：8.3
请问我在编译时为何报以下的错误呢，是否有些组件没有安装？

<img width="537" alt="error" src="https://cloud.githubusercontent.com/assets/15024762/24584557/ec48d74a-17a3-11e7-87c7-5705348d6fc0.png">

**Comment by qiuyuzhou** [comment]
#301
