### ISSUE TITLE
请问配置文件存放在什么路径？

### ISSUE THREAD

**Issue by octopusthu** [shadowsocks/ShadowsocksX-NG#305]
/Library/Application Support/ShadowsocksX-NG/ 下有个 proxy_conf_helper
~/.ShadowsocksX-NG/ 下是pac规则
还有其它的路径么？服务器地址一类的配置存放在何处？

**Comment by qiuyuzhou** [comment]
/Users/{Your user name}/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist

**Comment by octopusthu** [comment]
OK, 3x!
