### ISSUE TITLE
建议服务器选项中加入高可用选择项

### ISSUE THREAD

**Issue by ITXiaoPang** [shadowsocks/ShadowsocksX-NG#306]
我身边很多朋友都有多台SS服务器，他们也和我一样同时使用Mac和Windows两种平台，在Windows平台上有一个选项是高可用，可以按多台SS服务器的延迟（或其他判断方法、轮询、随机或其他）来自动选择相对比较快的SS服务器，这GFW干扰越来越强烈的今天，我觉得这个功能还是挺有用，所以来此提个建议，非常感谢作者的无私付出，我也希望有朝一日能为SS项目献出自己的一份力。

**Comment by omaidb** [comment]
😄

**Comment by gezigen** [comment]
这。。他们看得懂汉字吗？

**Comment by ITXiaoPang** [comment]
这是国人开发的哈~

**Comment by omaidb** [comment]
嗯哪
挨踢小胖 <notifications@github.com>于2017年4月7日 周五18:00写道：

**Comment by vinurs** [comment]
这个需求很有用，😄

**Comment by omaidb** [comment]
要贡献代码才能实现啊
Jon.Lee <omaidb@gmail.com>于2017年4月11日 周二12:42写道：

**Comment by hikuwo** [comment]
有一种东西叫haproxy，还有一种东西叫socat

**Comment by omaidb** [comment]
socat是什么？刚看了，好像是socath
hikuwo <notifications@github.com>于2017年8月13日 周日01:15写道：
