### ISSUE TITLE
如何彻底删除？

### ISSUE THREAD

**Issue by ronankim** [shadowsocks/ShadowsocksX-NG#308]
新本本，昨天装了1.4版本用的好好的，今天早上重新开机什么都没动竟然发现莫名其妙失灵了？折腾了近一个晚上换了n个版本发现没有一个能用的。现在只想问下如何能彻底删除ShadowsocksX-NG和ShadowsocksX，包括所有遗留配置和数据，我想再重新装下。

**Comment by qiuyuzhou** [comment]
`/Users/{Your user name}/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist`

**Comment by keenlovelife** [comment]
补充一点，在删除文件之前，先点 关闭Shadowsocks
然后删除
/Users/{Your user name}/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist
之后，

还有一部分可能在：/Users/{Your user name}/.ShadowsocksX 等
带有 Shadowsocks的隐藏文件夹

最后重启电脑

我安装的1.4.4-R8 就是这样清除掉的，再次安装后gui已经还原成功。

**Comment by xu455255849** [comment]
装个clean Mac 或者 别的清理软件 一键清理 ，1.82 不能放进应用程序 ，还有谷歌浏览器插件和ss会冲突 ，有翻墙的插件需要禁用，亲测

**Comment by congwenma** [comment]
rm -rf ~/Library/Application Support/ShadowsocksX-NG

**Comment by destroy314** [comment]
可能存在残留服务
https://lscho.com/tech/unload-sslocal.html
