### ISSUE TITLE
1.5 beta2 状态栏图标激活状态能不能高亮？

### ISSUE THREAD

**Issue by jfdnet** [shadowsocks/ShadowsocksX-NG#309]
之前版本的状态栏图标在激活状态下都是高亮的，1.5beta2该图标不再高亮。能不能还是维持激活状态高亮状态栏图标？

**Comment by carlguoshanghai** [comment]
也希望保持高亮。

**Comment by StevenTsao88** [comment]
你们的Mac升级了新版系统之后能翻墙吗？我的Mac升级到10.12.4之后就不能翻墙了，用老版的shadowsocks也不行

**Comment by carlguoshanghai** [comment]
@StevenTsao88 下的beta2，可以翻墙的。

**Comment by cypalen** [comment]
@StevenTsao88 可以翻的

**Comment by qiuyuzhou** [comment]
"保持高亮“是什么意思？可以给个截图吗

**Comment by jfdnet** [comment]
![](https://ww2.sinaimg.cn/large/006tKfTcgy1febna08c5ej303i01ct8m.jpg)

现在 激活状态 和 非激活状态 都是这个灰色

**Comment by nylqd** [comment]
这个问题已经解决过了，只是还没有发布而已，大家看看之前的issue嘛

**Comment by qiuyuzhou** [comment]
#302 
开新issue前，请先搜索
