### ISSUE TITLE
希望能支持SSR

### ISSUE THREAD

**Issue by Sharnodra** [shadowsocks/ShadowsocksX-NG#31]
windows下已有相应的客户端， 传送门：[ShadowsocksR](https://github.com/breakwa11/shadowsocks-rss)
Mac对应的客户端正空缺。
希望能考虑，谢谢！

**Comment by qiuyuzhou** [comment]
Sorry我目前不会考虑。

有人在QQ上对我说，要自己改NG支持SSR，也许不久有分支版本支持SSR。

**Comment by yichengchen** [comment]
我稍微改了一下（逃 https://github.com/yichengchen/ShadowsocksX-R

**Comment by qinyuhang** [comment]
我也稍微改了一下，同时支持SS和SSR
https://github.com/qinyuhang/ShadowsocksX-NG
求轻拍。。

**Comment by numbcoder** [comment]
为什么不发 PR，搞这么多分支也不大好吧？

**Comment by breakwa11** [comment]
@numbcoder 因为这个 #17

**Comment by numbcoder** [comment]
sigh
