### ISSUE TITLE
Mac OS 导入gui-config.json导致ss-ng崩溃退出

### ISSUE THREAD

**Issue by max-wen** [shadowsocks/ShadowsocksX-NG#316]
**System and Shadowsocksx-NG version:1.5

- macOS 10.11.6 (16E????)
- Shadowsocksx-NG 1.5

**Expected behavior:**

导入gui-config.json导致ss-ng崩溃退出

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by huhuang03** [comment]
遇到同样的问题，莫非是json解析错误？
