### ISSUE TITLE
Add load balancing for multi-servers?

### ISSUE THREAD

**Issue by leovan** [shadowsocks/ShadowsocksX-NG#319]
Can we add load balancing for multi-servers? Client for windows seems have this feature.

**Comment by qiuyuzhou** [comment]
Never would implement load balancing in ShadowsocksX-NG. 
ShadowsocksX-NG is just a GUI frontend of `ss-local` executable file from project `shadowsocks-libev`. ShadowsocksX-NG not implement shadowsocks protocol by itself.
