### ISSUE TITLE
Is it possible to bind to multiple interfaces?

### ISSUE THREAD

**Issue by QuantumGhost** [shadowsocks/ShadowsocksX-NG#320]
**System and Shadowsocksx-NG version:**

- macOS 10.12.3 (16D32)
- Shadowsocksx-NG 1.3

**Expected behavior:**

My computer has multiple network interfaces. One of them is `lo` (127.0.0.1) and another is `vboxnet0` (192.168.50.1). I would like to bind ShadowsocksX-NG to both of these two interfaces. Does the current version of ShadowsocksX-NG support this?

**Actual behavior:**

N/A

**Steps to reproduce:**

N/A

**How often does this happen?**

N/A

**ss-local.log**

N/A

**Application log**

N/A

**Crash Log**

N/A

**Comment by qiuyuzhou** [comment]
0.0.0.0

**Comment by QuantumGhost** [comment]
This is exactly the problem. I do not want to listen on `0.0.0.0` because this would expose my shadowsocks to all hosts in the same LAN.

**Comment by QuantumGhost** [comment]
Problem solved by using packet filter to block connections from LAN. Thank you for your help.

**Comment by QuantumGhost** [comment]
Also, you can use [Murus](http://www.murusfirewall.com/) if you don't want to write PF rules manually.
