### ISSUE TITLE
快捷键开关shadowsocks后失去当前窗口焦点

### ISSUE THREAD

**Issue by serapis** [shadowsocks/ShadowsocksX-NG#326]
- Shadowsocksx-NG 1.5.0(3)

在设置了开关shadowsocks的快捷键后，按下快捷键后会失去当前窗口的焦点，还需要点下触摸板激活窗口，不论是窗口模式还是全屏模式都是如此，有些不太方便。希望能改进下。

**Comment by qiuyuzhou** [comment]
Fix in #315
