### ISSUE TITLE
建议增加“用户PAC自动模式”

### ISSUE THREAD

**Issue by anyewuji** [shadowsocks/ShadowsocksX-NG#327]
最近遇到了和#317同样的问题，看见你已经在修复了，所以借个机会建议下增加“用户PAC自动模式”。
GFW List中的网站越来越多，而出现在列表中的网站实际用到的并不是太多，这就造成了不必要的判断，也增加了程序的反应时间（虽然判断已经很快了……）。
如果增加“用户PAC自动模式”的话，可以有效解决这一问题，只判断用户列出的PAC规则，这样的话也增加了用户的自由度。
在此感谢你一直以来的努力，辛苦了，加油，还有谢谢。

**Comment by lx75249** [comment]
+1, 还有一个使用场景就是墙外用户翻回墙内, 这时候就只需要自定义的规则而不需要管GFW
