### ISSUE TITLE
google earth pro crash after open shadowsocks-ng

### ISSUE THREAD

**Issue by starleafs** [shadowsocks/ShadowsocksX-NG#332]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 (16E195)
- Shadowsocksx-NG 1.50 (3)
- google earth pro 7.1.8

**Expected behavior:**
google earth pro lunches

**Actual behavior:**
google earth pro will crash (unable to lunch) when shadowsocks-ng is running and set to PAC mode, however, google earth pro is able to lunch when shadowsocks-ng is set to global/manual mode.

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by echosori** [comment]
I have the same problem, when I open google earth with shadowsocks service ON on my MacBook , it will crash instantly. If I make Shadowsocks service OFF, I get google earth opened normally.
