### ISSUE TITLE
编辑PAC用户自定规则需要用什么格式呢？

### ISSUE THREAD

**Issue by elvis1121** [shadowsocks/ShadowsocksX-NG#333]

**Comment by sinoon** [comment]
# 自定义pac列表规则

规则大概描述如下

- 通配符支持，如 \*.example.com/\* 实际书写时可省略 \* 如 .example.com/ 意即 \*.example.com/\*
- 正则表达式支持，以\开始和结束， 如 \[\w]+:\/\/example.com\
- 例外规则 @@，如 @@*.example.com/* 满足@@后规则的地址不使用代理
- 匹配地址开始和结尾 |，如 |http://example.com、example.com| 分别表示以 http://example.com 开始和以 example.com 结束的地址
- \|\| 标记，如 ||example.com 则 http://example.com 、https://example.com 、ftp://example.com 等地址均满足条件，只用于匹配地址开头
- 注释 ! 如 ! Comment
- 分隔符^，表示除了字母、数字或者 _ - . % 之外的任何字符。如 http://example.com^ ，http://example.com/ 和 http://example.com:8000/ 均满足条件，而 http://example.com.ar/ 不满足条件

如何使用自定义规则

```
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||amazonaws.com
||atom.io
||github.com^
```
推荐你用ip138或者百度试一下，看看ip地址是否改变

**Comment by saulzy** [comment]
为什么我添加了规则后不起作用。

```
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||ip138.com
```

**Comment by AiksRiver** [comment]
> @saulzy 要重启客户端，亲测有效
是的 有效

**Comment by zhujun8286** [comment]
> # 自定义PAC列表规则
> 规则大概描述如下
> 
> * 通配符支持，如* .example.com / *实际书写时可省略*如.example.com /意即* .example.com / *
> * 正则表达式支持，以\开始和结束，如[\ w] +：//example.com \
> * 例外规则@@，如@@ _.example.com /_满足@@后规则的地址不使用代理
> * 匹配地址开始和结尾|，如| [http：//example.com,example.com |](http://example.com%E3%80%81example.com%7C)分别表示以http://example.com开始和以example.com结束的地址
> * || 标记，||如example.com的则[http://example.com的](http://example.com)，https://example.com，FTP：//示例.com等地址均满足条件，只用于匹配地址开头
> * 注释！如！评论
> * 分隔符^，表示除了字母，数字或者_  - 。％之外的任何字符如。[HTTP：//example.com^](http://example.com%5E)，[http://example.com/的](http://example.com/)状语从句：http://example.com:8000/：均满足条件，而[http://example.com.ar /](http://example.com.ar/)不满足条件
> 
> 如何使用自定义规则
> 
> ```
> ! Put user rules line by line in this file.
> ! See https://adblockplus.org/en/filter-cheatsheet
> ||amazonaws.com
> ||atom.io
> ||github.com^
> ```
> 
> 推荐你用IP138或者百度试一下，看看IP地址是否改变

! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||xn--90wwvt03e.com
||baidu.com^
其他网址都可以,就是百度不行啊,不起作用!

**Comment by thinkycx** [comment]
switchyomega + ShadowsocksX-NG 最新版

规则：
```
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||*.ip138.com
||*.baidu.com
||*.evernote.com
||*.gmail.com
||imap.gmail.com
||smtp.gmail.com
```

重启 ShadowsocksX-NG也无效，应该怎么解决呢？

**Comment by syh0304** [comment]
> switchyomega + ShadowsocksX-NG 最新版
> 
> 规则：
> 
> ```
> ! Put user rules line by line in this file.
> ! See https://adblockplus.org/en/filter-cheatsheet
> ||*.ip138.com
> ||*.baidu.com
> ||*.evernote.com
> ||*.gmail.com
> ||imap.gmail.com
> ||smtp.gmail.com
> ```
> 
> 重启 ShadowsocksX-NG也无效，应该怎么解决呢？
||@@*.baidu.com

**Comment by thinkycx** [comment]
> > switchyomega + ShadowsocksX-NG 最新版
> > 规则：
> > ```
> > ! Put user rules line by line in this file.
> > ! See https://adblockplus.org/en/filter-cheatsheet
> > ||*.ip138.com
> > ||*.baidu.com
> > ||*.evernote.com
> > ||*.gmail.com
> > ||imap.gmail.com
> > ||smtp.gmail.com
> > ```
> > 
> > 
> > 重启 ShadowsocksX-NG也无效，应该怎么解决呢？
> > ||@@*.baidu.com

请问@@什么意思?

**Comment by rockdean** [comment]
> > > switchyomega + ShadowsocksX-NG 最新版
> > > 规则：
> > > ```
> > > ! Put user rules line by line in this file.
> > > ! See https://adblockplus.org/en/filter-cheatsheet
> > > ||*.ip138.com
> > > ||*.baidu.com
> > > ||*.evernote.com
> > > ||*.gmail.com
> > > ||imap.gmail.com
> > > ||smtp.gmail.com
> > > ```
> > > 
> > > 
> > > 重启 ShadowsocksX-NG也无效，应该怎么解决呢？
> > > ||@@*.baidu.com
> 
> 请问@@什么意思?


例外规则 @@，如 @@.example.com/ 满足@@后规则的地址不使用代理

上面有说

**Comment by monsuns** [comment]
> switchyomega + ShadowsocksX-NG 最新版
> 
> 规则：
> 
> ```
> ! Put user rules line by line in this file.
> ! See https://adblockplus.org/en/filter-cheatsheet
> ||*.ip138.com
> ||*.baidu.com
> ||*.evernote.com
> ||*.gmail.com
> ||imap.gmail.com
> ||smtp.gmail.com
> ```
> 
> 重启 ShadowsocksX-NG也无效，应该怎么解决呢？

|| 后面跟一个空格, 再写地址. 如
```
|| github.com^
```

**Comment by Horse888** [comment]
> > switchyomega + ShadowsocksX-NG 最新版
> > 规则：
> > ```
> > ! Put user rules line by line in this file.
> > ! See https://adblockplus.org/en/filter-cheatsheet
> > ||*.ip138.com
> > ||*.baidu.com
> > ||*.evernote.com
> > ||*.gmail.com
> > ||imap.gmail.com
> > ||smtp.gmail.com
> > ```
> > 
> > 
> > 重启 ShadowsocksX-NG也无效，应该怎么解决呢？
> 
> || 后面跟一个空格, 再写地址. 如
> 
> ```
> || github.com^
> ```

不需要. 更改之后必须要重启ShadowsocksX-NG.

**Comment by CheneyBear** [comment]
请问能否把这个规则用来打开pc上的一个软件？这个软件强制使用梯子？
