### ISSUE TITLE
如何查看哪些请求被PAC响应了？

### ISSUE THREAD

**Issue by CrisLi** [shadowsocks/ShadowsocksX-NG#334]
**System and Shadowsocksx-NG version:**

- macOS 10.11.6
- Shadowsocksx-NG 1.4.0

**Expected behavior:**

想根据log查看哪些请求被PAC响应了，真正走代理了。

**Actual behavior:**

log信息中只有开启关闭Shadowsocksx的信息。

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

Always

**ss-local.log**

2017-04-17 17:21:51 INFO: tcp port reuse enabled
 2017-04-17 17:21:51 INFO: listening at 127.0.0.1:1086
 2017-04-17 17:28:57 INFO: initializing ciphers... rc4-md5
 2017-04-17 17:28:57 INFO: tcp port reuse enabled
 2017-04-17 17:28:57 INFO: listening at 127.0.0.1:1086
 2017-04-17 17:29:38 INFO: initializing ciphers... rc4-md5
 2017-04-17 17:29:38 INFO: tcp port reuse enabled
 2017-04-17 17:29:38 INFO: listening at 127.0.0.1:1086
 2017-04-17 17:35:03 INFO: initializing ciphers... rc4-md5
 2017-04-17 17:35:03 INFO: tcp port reuse enabled
 2017-04-17 17:35:03 INFO: listening at 127.0.0.1:1086
 2017-04-17 17:44:26 ERROR: connect: Input/output error
 2017-04-17 17:46:58 INFO: initializing ciphers... rc4-md5
 2017-04-17 17:46:58 INFO: tcp port reuse enabled
 2017-04-17 17:46:58 INFO: listening at 127.0.0.1:1086

**Application log**

4/18/17 11:29:30.088 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43146]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:29:30.089 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:29:40.127 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43159]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:29:40.128 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:29:50.168 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43160]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:29:50.170 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:30:00.210 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43162]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:30:00.212 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:30:10.254 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43164]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:30:10.256 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:30:20.292 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43165]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:30:20.294 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:30:30.329 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43240]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:30:30.331 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:30:40.366 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43250]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:30:40.367 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:30:50.405 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43252]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:30:50.407 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
4/18/17 11:31:00.446 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[43274]) Could not find and/or execute program specified by service: 45: Operation not supported: com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper
4/18/17 11:31:00.447 AM com.apple.xpc.launchd[1]: (com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by qinyuhang** [comment]
check `verbose mode`, all connection log is in ss-local.log

**Comment by CrisLi** [comment]
@qinyuhang Thanks, it works
