### ISSUE TITLE
googleapis.l.google.com 无法访问到。

### ISSUE THREAD

**Issue by CrisLi** [shadowsocks/ShadowsocksX-NG#335]
**System and Shadowsocksx-NG version:**

- macOS 10.11.6
- Shadowsocksx-NG 1.4.0

**Expected behavior:**

在使用Proxifier做代理的情况下，能够访问googleapis.l.google.com

**Actual behavior:**

Timeout

**Steps to reproduce:**

使用Proxifier将发向googleapis.l.google.com的请求都经由shadowsocks代理。其他google相关的API都正常，只有googleapis.l.google.com没有响应。

已经修改Use PAC Rules

```
||googleapis.l.google.com
```

尝试了修改host文件，使用Proxifier将发向googleapis.l.google.com的请求直连，就正常了。

**How often does this happen?**

Always

**ss-local.log**

没有googleapis.l.google.com相关的log显示出来。

**Comment by xpader** [comment]
希望用户规则在生成的PAC中能优先排在前面。
在后面的问题是，有些gfwlist加入白名单的，我既使在用户规则里强制要求走代理也不会走。
非常无语。

**Comment by qinyuhang** [comment]
fixed not released yet

**Comment by cicku** [comment]
@xpader 请具体指出。

**Comment by xpader** [comment]
@cicku 就是说在原 gfwlist 中使用了 @@||fonts.googleapis.com 排除了 fonts.googleapis.com 的代理，然后就算我在 userRule 中添加了 ||fonts.googleapis.com，这个域名的请求也始终不会走代理。

虽然说这个域名有时候在国内能访问，但也经常无法访问，导致有些网站打开卡在这个域名上非常慢。我希望在用户规则中加了这个域名让它始终走代理却不行。

生成 pac 时，应该把用户的规则优先排在前面，而不是在后面，这样就应该解决这个问题b

**Comment by icearith** [comment]
I am still suffering from this problem.

My user rules are listed as follows:

```
||fonts.gstatic.com
||ip.cn
||googleapis.com
```

I could see the request log on my server of the first two domains, while the last one `googleapis.com` just did not pass the proxy. 

I am 100% sure that this domain could be reached when using Global Mode. 
Any suggestion please?

**Comment by timothyqiu** [comment]
According to the ABP Filter implementation, whitelists always have higher priority than blacklists. It has nothing to do with the order of rules.

GFW List rules and User Rules are combined into a single ABP Filter, so as long as GFW List whitelists `fonts.googleapis.com`, it will ignore other blacklist about that url and always bypasses the proxy.

https://github.com/shadowsocks/ShadowsocksX-NG/blob/784292ca57c09a18c3dc9a5863e5a24a421522f4/ShadowsocksX-NG/abp.js#L728-L744

**Comment by mscorp** [comment]
为啥维护gfwlist的人要把fonts.googleapi.com放到白名单里。
另外shadowsocksx-ng为啥不支持优先本地的gfwlist，windows版本的可以实现

**Comment by cicku** [comment]
@mscorp 很简单，该域名在国内被解析到谷翔的国内机房，不存在访问问题。

@seagle0128 同上。您还是先说一下自己的 ISP 吧。

**Comment by seagle0128** [comment]
@cicku 为什么全局模式能访问呢？WIndows上代理也可以

**Comment by mscorp** [comment]
似乎你没看清题目？

**Comment by mscorp** [comment]
@cicku 似乎你没看清题目？

**Comment by cicku** [comment]
@mscorp 似乎你也是跑题选手。

**Comment by zepinglee** [comment]
我也是遇到 `ping: cannot resolve fonts.googleapis.com: Unknown host`，但是 gfwlist 加进白名单不太合适吧？

**Comment by mscorp** [comment]
> @mscorp 很简单，该域名在国内被解析到谷翔的国内机房，不存在访问问题。
> 
> @seagle0128 同上。您还是先说一下自己的 ISP 吧。

事实并不是这样，国内fonts.googleapis.com还是无法直接打开
