### ISSUE TITLE
命令行下privoxy能否支持pac自动代理

### ISSUE THREAD

**Issue by tenfyzhong** [shadowsocks/ShadowsocksX-NG#339]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4
- Shadowsocksx-NG 1.4

**Expected behavior:**
开启pac自动代理模式，在iterm上走的http代理是全局模式，也就是所有的请求都会走代理。
希望跟pac模式一样，对于不需要fq的不走代理。

**Actual behavior:**
>
>~ $ curl ip.gs
>当前 IP：139.162.74.72 来自：日本东京都品川区 linode.com
>

**Comment by intspt** [comment]
试试proxychains4

**Comment by tenfyzhong** [comment]
@intspt 可以往privoxy.config里去加规则，当用户使用pac模式的时候。

**Comment by qiuyuzhou** [comment]
不可能实现。
