### ISSUE TITLE
更新macOS 10.12.5 Beta (16F60a)后，无法启动应用

### ISSUE THREAD

**Issue by LT21** [shadowsocks/ShadowsocksX-NG#340]
- macOS 10.12.5 Beta (16F60a)
- Shadowsocksx-NG 1.5-beta 2

无法启动应用

**Comment by ztechie** [comment]
Apr 27 09:51:03 MacBook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[1523]): Service exited with abnormal code: 255
Apr 27 09:51:03 MacBook-Pro com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
