### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by sevelee** [shadowsocks/ShadowsocksX-NG#343]
**System and Shadowsocksx-NG version:**

- macOS 10.11.6 (15G1421)
- Shadowsocksx-NG 1.5.0 (3)

希望能够增加对应mac暗色菜单栏的icon。谢谢：）

**Comment by FateLight** [comment]
手动PS，233

**Comment by sevelee** [comment]
@FateLight 有的程序图标是会配合菜单栏颜色变的www

**Comment by FateLight** [comment]
@sevelee 1.5正式版已经解决了
