### ISSUE TITLE
10.12.4出现无法连接wifi的情况

### ISSUE THREAD

**Issue by lchad** [shadowsocks/ShadowsocksX-NG#347]
**System and Shadowsocksx-NG version:1.4.0(3)

- macOS 10.12.4 (16E????)
- Shadowsocksx-NG 1.4.0(3)

电脑合上一段时间之后,重新打开,会出现wifi连接不上的状况,需要关闭wifi,再重新连接才可以上网,去苹果直营店检测过了,硬件没问题,他们说可能是代理导致的问题,我这边也在尝试重现.

**Comment by maddie** [comment]
It's totally unrelated to ShadowsocksX-NG.. It's most likely a bug in macOS, I have the same issue on machines that does not have ShadowsocksX-NG installed.

**Comment by lchad** [comment]
@maddie
thanks for your reply.
Could you please tell me how do you fix it?
Have you ever report it to the Apple Store?

**Comment by maddie** [comment]
Unfortunately there seems to be no effective fix :( It looks to me that the WiFi hardware might need to be reinitialized properly after wake, but it either was taking a long time or doesn't work at all. Turning it off and on again forces the system to reinitialize it.

**Comment by lchad** [comment]
@maddie Thank you!
