### ISSUE TITLE
HUD should not move every time using shortcut to switch (video attached)

### ISSUE THREAD

**Issue by wyudong** [shadowsocks/ShadowsocksX-NG#348]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4
- Shadowsocksx-NG 1.5.0

**Expected behavior:**

HUD should always stay still in the middle of screen.

**Actual behavior:**

HUD will move every time using shortcut to switch.

Video: https://www.youtube.com/watch?v=7zHPclvpMoE

**Steps to reproduce:**

1. Setup shortcut for switching Shadowsocksx-NG on/off
2. Press the shortcut continuously and HUD will move

**How often does this happen?**

Always.

**Comment by qiuyuzhou** [comment]
It's known issue. But I don't know the deep reason now. 
I don't have enough time and it's trivial. So I won't dig it recently.

**Comment by rizwankce** [comment]
i suspect [here](https://github.com/shadowsocks/ShadowsocksX-NG/blob/494a96b9e194d519b5b6fc8c5dbb5860509aa612/ShadowsocksX-NG/ToastWindowController.swift#L65) we might be having an issue which causes the window move every time using shortcut to switch. I will debug when i have time.

**Comment by wyudong** [comment]
@rizwankce I tried some time to debug this issue. If I remember right, even setting `hudWindowFrame.origin.x` to a static value, the HUD will still move using shortcut to switch. It will be nice you can have a look at it.

**Comment by rizwankce** [comment]
@wyudong it weird. I am running v1.5.1 ss-ng on macOS 10.12.4 (and 10.12.5) and i cannot reproduce the issue you have. 

is it possible for you to try installing v1.5.1 from first and check?

**Comment by wyudong** [comment]
![still](https://cloud.githubusercontent.com/assets/5687273/26098632/efbc3334-3a5a-11e7-9683-0bc74dd8709b.gif)
@rizwankce Same. v1.5.1 SS-ng on macOS 10.12.4.

**Comment by wyudong** [comment]
@rizwankce After reboot, the issue is gone now.
