### ISSUE TITLE
添加 Apple Script 支持

### ISSUE THREAD

**Issue by roife** [shadowsocks/ShadowsocksX-NG#351]
如果能加入 Apple Script 支持那就更好了，可以大大提高其拓展性
比如制作 Alfred 的 Workflow 等

**Comment by seudut** [comment]
这个可以自己模仿写个Apple script，然后在 Quicksilver 中调用，(Alfred 也应该可以)。
这有个类似的 apple script。https://github.com/seudut/dotfiles/blob/master/bin/emacs_toggle.applescript 将其中的 emacs 换成 shadowsocks 应该就可以了。

你这个需求应该不是 这个shadowsocks （某个具体的程序 ) 这个project 要做 和 能做的。

**Comment by Roife** [comment]
噢，我试试看。

打扰了 :)
________________________________
发件人: seudut <notifications@github.com>
发送时间: 2017年5月1日 15:53:39
收件人: shadowsocks/ShadowsocksX-NG
抄送: Roife; Author
主题: Re: [shadowsocks/ShadowsocksX-NG] 添加 Apple Script 支持 (#351)


这个可以自己模仿写个Apple script，然后在 Quicksilver 中调用，(Alfred 也应该可以)。
这有个类似的 apple script。https://github.com/seudut/dotfiles/blob/master/bin/emacs_toggle.applescript 将其中的 emacs 换成 shadowsocks 应该就可以了。

你这个需求应该不是 这个shadowsocks （某个具体的程序 ) 这个project 要做 和 能做的。

―

**Comment by Roife** [comment]
噢，我试试看。

打扰了 :)
________________________________
发件人: seudut <notifications@github.com>
发送时间: 2017年5月1日 15:53:39
收件人: shadowsocks/ShadowsocksX-NG
抄送: Roife; Author
主题: Re: [shadowsocks/ShadowsocksX-NG] 添加 Apple Script 支持 (#351)


这个可以自己模仿写个Apple script，然后在 Quicksilver 中调用，(Alfred 也应该可以)。
这有个类似的 apple script。https://github.com/seudut/dotfiles/blob/master/bin/emacs_toggle.applescript 将其中的 emacs 换成 shadowsocks 应该就可以了。

[https://avatars0.githubusercontent.com/u/10176521?v=3&s=400]<https://github.com/seudut/dotfiles/blob/master/bin/emacs_toggle.applescript>

seudut/dotfiles<https://github.com/seudut/dotfiles/blob/master/bin/emacs_toggle.applescript>
github.com
dotfiles - My dot files for emacs, vim, tmux, zsh, etc



你这个需求应该不是 这个shadowsocks （某个具体的程序 ) 这个project 要做 和 能做的。

―

**Comment by Ecohomicao** [comment]
网址里提供的参考，不知如何实现在SS上。。
另，提供GoAgent的applescript设置：

> tell application "GoAgentX"
    toggle current service status to running
end tell

[Control GoAgentX with Apple Script](https://github.com/BarelyWang/GoAgentX/wiki/Control-GoAgentX-with-Apple-Script)

**Comment by yangziy** [comment]
[Pull Request #883](https://github.com/shadowsocks/ShadowsocksX-NG/pull/883)
