### ISSUE TITLE
Google搜索之后部分网站无法打开或者打开缓慢，例如：Android开发者网站，http://fblitho.com/

### ISSUE THREAD

**Issue by wb1992321** [shadowsocks/ShadowsocksX-NG#354]
**System and Shadowsocksx-NG 1.5.1:**

- macOS 10.12.4 (16E????)
- Shadowsocksx-NG 1.5.1

**Google搜索可以正常，但是点击搜索结构部分网站打开很慢**
- http://fblitho.com/
- https://developer.android.com/index.html
- 等等

**Comment by DeronLee** [comment]
有换全局模式试试么？

**Comment by wb1992321** [comment]
全剧模式可以，我自定义rules也就可以了！加入以下内容到自定义rules
> 
> ||fblitho.com
> ||android.com
> ||google.com
