### ISSUE TITLE
不能扫描二维码

### ISSUE THREAD

**Issue by gnaixx** [shadowsocks/ShadowsocksX-NG#355]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 (16E????)
- Shadowsocksx-NG 1.5.0

**Expected behavior:**
 - 不能扫描屏幕上的二维码

**Comment by zhang13music** [comment]
System and Shadowsocksx-NG version:

- macOS 10.12.5
- Shadowsocksx-NG 1.5.1

同样问题！无法扫描二维码，提示“Not found valid qrcode of shadowsocks profile.”

**Comment by gnaixx** [comment]
貌似现在只能扫描 可配置的服务器的 二维码了 不能像以前都可以扫描了。但是以前好用啊

**Comment by MadisonRong** [comment]
我也遇到了这个问题，求解决方法

**Comment by timothyqiu** [comment]
Maybe this is a long existing bug in parsing the URI from the QR code. If your QR code is in legacy format and ends with a tag, try removing the tag.

---

For example, if your URI looks like this:
> ss://YmYtY2ZiOnRlc3RAMTkyLjE2OC4xMDAuMTo4ODg4#example-server

Try removing everything from the hashtag:
> ss://YmYtY2ZiOnRlc3RAMTkyLjE2OC4xMDAuMTo4ODg4
