### ISSUE TITLE
shadowsocks-ng 启动后，1086端口，不在监听，怎么办？

### ISSUE THREAD

**Issue by JohnChinaWu** [shadowsocks/ShadowsocksX-NG#356]

**Comment by gino2010** [comment]
如果你用了clean my mac 这样的工具，禁止（disable）了相应的plist服务，那么监听可能出现问题。（这是我遇到的场景，如果不是这个场景请忽略下面的内容）
这个问题在我提交的 pull requests进行了修改，避免未开启shadowsocks-ng时的端口监听，只有在使用是进行端口监听。这样就不需要disable plist服务了。

**Comment by JohnChinaWu** [comment]
对，就是这样，太感谢了！！！

**Comment by theodero** [comment]
楼主 如何解决的 我也遇到了同样的问题  
我直接卸载了clean my mac 都没用

**Comment by johnwenjunwu** [comment]
确保enable这两个
<img width="891" alt="image" src="https://user-images.githubusercontent.com/20377340/72138218-58d3b780-33c7-11ea-9701-294169eda40d.png">
