### ISSUE TITLE
顶部图标显示不正常

### ISSUE THREAD

**Issue by aboutlr** [shadowsocks/ShadowsocksX-NG#362]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 
- Shadowsocksx-NG 1.5.1

**Expected behavior:**

**Actual behavior:**

点击全局模式后, 顶部图标消失, 只有PAC模式是正常显示

**Comment by josephzjw** [comment]
我也有这个现象…我是最新版的ss
