### ISSUE TITLE
kcptun 开了连不上，贴了日志，求分析

### ISSUE THREAD

**Issue by smart-z** [shadowsocks/ShadowsocksX-NG#364]
小白一个，不懂代码，
1.5.1 的 ss 版本，
osx 是 10.12.4，
ss 服务器的 kcptun 版本是 2017.3.29的

## 改动了 偏好设置 中的 kcptun
本地监听端口 改为了 12948；其它的没改

## ss程序生成的kcptun-config.json 如下
```
{
  "nocomp" : false,
  "key" : "it's a secrect",
  "crypt" : "aes",
  "conn" : 1,
  "datashard" : 10,
  "mtu" : 1350,
  "mode" : "fast",
  "remoteaddr" : "***.***.***.***:12948",
  "localaddr" : "127.0.0.1:12948",
  "parityshard" : 3
}
```

## 客户端原来是
```
{
    "localaddr": ":12948",
    "remoteaddr": "***.***.***.***:29900",
    "key": "it's a secrect",
    "crypt": "aes",
    "mode": "fast",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 512,
    "rcvwnd": 512,
    "datashard": 10,
    "parityshard": 3,
    "dscp": 0,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 20,
    "resend": 2,
    "nc": 1,
    "sockbuf": 4194304,
    "keepalive": 10
}
```

## 服务器设置
```
地址：***.***.***.***:12948
加密方法：rc4-md5
密码：******
enable over kcptun: yes （这里我打勾了，打上勾那些网就无限加载中，打不开）
```

## 日志如下：
> 2017/05/12 15:29:44 version: 20170329
> 2017/05/12 15:29:44 listening on: 127.0.0.1:12948
> 2017/05/12 15:29:44 encryption: aes
> 2017/05/12 15:29:44 nodelay parameters: 0 30 2 1
> 2017/05/12 15:29:44 remote address: 45.62.117.17:12948
> 2017/05/12 15:29:44 sndwnd: 128 rcvwnd: 512
> 2017/05/12 15:29:44 compression: true
> 2017/05/12 15:29:44 mtu: 1350
> 2017/05/12 15:29:44 datashard: 10 parityshard: 3
> 2017/05/12 15:29:44 acknodelay: false
> 2017/05/12 15:29:44 dscp: 0
> 2017/05/12 15:29:44 sockbuf: 4194304
> 2017/05/12 15:29:44 keepalive: 10
> 2017/05/12 15:29:44 conn: 1
> 2017/05/12 15:29:44 autoexpire: 0
> 2017/05/12 15:29:44 scavengettl: 600
> 2017/05/12 15:29:44 snmplog: 
> 2017/05/12 15:29:44 snmpperiod: 60
> 2017/05/12 15:29:44 connection: 192.168.38.173:54552 -> 45.62.117.17:12948
> 2017/05/12 15:30:12 stream opened
> 2017/05/12 15:30:13 stream opened
> 2017/05/12 15:30:14 stream opened
> 2017/05/12 15:30:14 stream closed
> 2017/05/12 15:30:14 stream closed
> 2017/05/12 15:30:14 stream closed
> 2017/05/12 15:30:14 session marked as expired
> 2017/05/12 15:30:14 connection: 192.168.38.173:63038 -> 45.62.117.17:12948
> 2017/05/12 15:30:14 stream opened
> 2017/05/12 15:30:14 stream opened
> 2017/05/12 15:30:14 stream opened
> 2017/05/12 15:30:15 session normally closed
> 2017/05/12 15:30:15 stream opened
> 2017/05/12 15:30:15 stream opened
> 2017/05/12 15:30:16 stream opened
> 2017/05/12 15:30:18 stream opened
> 2017/05/12 15:30:22 stream opened
> 2017/05/12 15:30:24 stream opened
> 2017/05/12 15:30:32 stream opened
> 2017/05/12 15:30:33 stream opened
> 2017/05/12 15:30:43 stream opened
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 stream closed
> 2017/05/12 15:30:44 session marked as expired
> 2017/05/12 15:30:44 connection: 192.168.38.173:61149 -> 45.62.117.17:12948
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:44 stream opened
> 2017/05/12 15:30:45 session normally closed
> 2017/05/12 15:30:47 stream opened
> 2017/05/12 15:30:49 stream opened
> 2017/05/12 15:30:50 stream opened
> 2017/05/12 15:30:52 stream opened
> 2017/05/12 15:30:53 stream closed
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 stream closed
> 2017/05/12 15:31:14 session marked as expired
> 2017/05/12 15:31:14 connection: 192.168.38.173:60452 -> 45.62.117.17:12948
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:14 stream opened
> 2017/05/12 15:31:15 session normally closed
> 2017/05/12 15:31:16 stream closed
> 2017/05/12 15:31:16 stream opened
> 2017/05/12 15:31:18 stream closed
> 2017/05/12 15:31:18 stream opened

**Comment by kfh101** [comment]
尝试将"localaddr" : "127.0.0.1:12948", 里的本地地址改为SS服务器地址试试

**Comment by louCharon** [comment]
我觉得你的参数没问题
我windows kcp客户端也是这个问题，偶尔运气好才能连上，经常就是刚open就一直closed。
Android用kcptun插件是好的，一点问题没有
