### ISSUE TITLE
kcptun和ss设置疑惑

### ISSUE THREAD

**Issue by jy1989** [shadowsocks/ShadowsocksX-NG#373]
**System and Shadowsocksx-NG version:**

- macOS 10.12 (16A323)
- Shadowsocksx-NG 1.5.1

kcptun服务器设置，这个地方应该设置正确，密码为ss的密码，password为tcptun的key
![image](https://cloud.githubusercontent.com/assets/1291756/26136313/d0b30f56-3aed-11e7-8c5f-17e060c5aff8.png)

kcptun本地端口设置，**这个端口究竟有神马用？**
![image](https://cloud.githubusercontent.com/assets/1291756/26136294/af58d3f4-3aed-11e7-8192-9284b5847598.png)

ss本地socks5设置
![image](https://cloud.githubusercontent.com/assets/1291756/26136336/f6358664-3aed-11e7-96f2-87e2c5a4cfd1.png)

chrome插件的配置，
![image](https://cloud.githubusercontent.com/assets/1291756/26136384/3272e6e4-3aee-11e7-90fb-353482413f88.png)

网上搜索了下原理：
> 运行前我们先结合下图熟悉一下它的原理，说白了就是将之前shadowsocks的数据流又做了一次代理，让流量跑在更快的UDP协议上！
> 
> kcptun
> 
> 也就是说我们需要在kcptun的服务器端指定当前shadowsocks服务器的端口，然后在将其代理为一个新的端口。
> 
> 在客户端，我们也需要运行kcptun，但是我们直接连接的还是原本的shadowsocks客户端，但是我们需要将原客户端的服务器IP改为本地服务器的IP，一般为127.0.0.1，端口改为本地kcptun的服务端口。而kcptun的客户端只需要知道kcptun服务器的IP和地址即可！
> 
> 需要注意的是对于shadowsocks的服务器来说，可以想象kcptun是不存在的，所以其加密方式是对应的，如果原来用的aes和phpgao作为加密方式和密码，现在的也不需要变化，需要变化的只是服务器的IP和端口。
> 
> 聪明的你肯定已经想到了，kcptun的服务端与客户端之间也有自己的认证与加密方式，其二者也是对应的。
> 

**那么我该在shadowsocksX-ng里再新建一个服务器指向到本地的kcptun 443端口？？**

**这里kcptun究竟是怎么设置呢？chrome的插件代理又该指向到哪里呢？ 谢谢**

**Comment by yangeren** [comment]
据我所知，mac版本的自动就做了http的代理请求，不用chrome插件了。
我的大ubuntu还是得用chrome插件的。

**Comment by sharekey** [comment]
**kcptun本地端口设置，这个端口究竟有神马用？**
![kcptun_ports](https://cloud.githubusercontent.com/assets/8130889/26479530/9a9a1566-4206-11e7-830d-8fb0414caf4e.png)
这个设置是修改kcptun客户端的端口，对应图中的12948端口

**Comment by 471448446** [comment]
没人回答么

**Comment by qiuyuzhou** [comment]
@sharekey 已经说清楚了。

**Comment by xiebruce** [comment]
@jy1989 @sharekey  我还是不太明白，看我这个图， @jy1989  你说区域2的password为kcptun的key，可是我client_darwin_amd64启动参数里不也可以指定这个key么（如图红框部分）？不仅如此，其实区域2里的所有参数，都可以在client_darwin_amd64启动的时候，配置文件的方式指定，为什么要在ss客户端里又配置一次？到底以哪个为准？ss-NG这样让人感觉它是集成了kcptun的样子啊。另外，区域1的ip地址是什么？按@sharekey的说法，如果kcptun与ss-NG都在mac上，那这个地址应该就是127.0.0.1吧？这些我都搞不懂，麻烦大神解释一下，谢谢了！
<img width="384" alt="ss-NG配置" src="https://user-images.githubusercontent.com/13575500/34399225-526973c2-ebc0-11e7-9a50-cd3ec7f9f35e.png">

![client_darwin_amd64参数](https://user-images.githubusercontent.com/13575500/34399227-59133370-ebc0-11e7-88dc-37ec7ba7fd4c.png)

**Comment by 471448446** [comment]
对于kcptun配置
区域一
IP：填远程IP，
加密：对应的加密方式
其他：密码和端口可以不填
区域二
填写kcptun的对应配置就是，密码就是kcptun的密码

至于本地想代理那个端口可以在设置里面修改
![image](https://user-images.githubusercontent.com/7636279/34399358-b16af4a8-ebc1-11e7-93ad-cd873430d404.png)

**Comment by xiebruce** [comment]
@471448446 谢谢你！我想问一下，是不是mac这个ss-NG，已经集成了kcptun的？不需要我再去这里下载并运行kcptun客户端了？https://github.com/xtaci/kcptun/releases

**Comment by 471448446** [comment]
对，ss-NG已经集成了kcptun客户端了

**Comment by xiebruce** [comment]
@471448446 嗯，已经成功了，kcptun服务器端有log，请求ip正是来自我的客户端，所以肯定是用上了没错，但没感觉到加速哈哈，我要怎么用工具去评测加速了呢？

**Comment by yangfeicheung** [comment]
可以尝试去youtube看下视频的速度，视频右键 stats for nerds会显示当前网速，或者直接下载某个blocked site上的文件试试

**Comment by gMan1990** [comment]
尴尬，还是没弄明白怎么设置~

**Comment by zacharyshen** [comment]
@xiebruce 
按照你给的图片，你的情况应该是
Network Requests -> Shadowsocks Client Port (1080/tcp) -> KCP Client Port (443/tcp) -> KCP Server Port (4001/udp) -> Shadowsocks Server Port (8388/tcp)

如果你右键点ShadowsocksX客户端Show Package Content，会发现里面已经集成了kcptun_client，
所以在设置时，区域1应该填写shadowsocks服务器设置，区域2应该填写kcptun服务器设置

当然你也可以自己下载一个kcptun_client，配置好并run起来（假设还是443端口），然后在shadowsocksX里面建一个新配置文件，**不需要**Enable over kcptun，在区域1填address为127.0.0.1，port为443，然后连接，效果是一样的
