### ISSUE TITLE
升级 macOS 10.12.4 及更高版本后不能使用的临时解决方法

### ISSUE THREAD

**Issue by 0u0u0** [shadowsocks/ShadowsocksX-NG#376]
表现：
升级系统后无法使用，macOS 上 Chrome 判定为 代理服务器连接失败；
同一账号在同一网络的其他设备上均一切正常。

解决方法：
使用旧版：https://github.com/shadowsocks/shadowsocks-iOS/releases

**Comment by nanacheung** [comment]
表示使用这个好像也不行，哭哭

**Comment by cuteguy** [comment]
我也试试了 好像也不行

**Comment by TzLiu** [comment]
真的只有我可以用😂

**Comment by evanf** [comment]
旧版自动模式有问题，全局模式可用。

貌似是系统升级后“LaunchAgents”文件夹的Owner变成root导致的。系统升级后如果更改服务器配置无法写到LaunchAgents文件夹里，我把~/Library/LaunchAgents/ 文件夹的权限改成777后重启ShadowsocksX-NG程序就可以用了。

**Comment by cd4224** [comment]
怎么改
