### ISSUE TITLE
我想实现一个流量统计的功能，但是不知道如何下手

### ISSUE THREAD

**Issue by qinyuhang** [shadowsocks/ShadowsocksX-NG#38]
毕竟有些SS服务商流量有限，所以想要在里面实现流量统计功能。但是没有找到合适的API或者库，请问有什么建议嘛？
issue link: https://github.com/qinyuhang/ShadowsocksX-NG/issues/2

**Comment by qingkooo** [comment]
流量统计还没有实现么？

**Comment by aaaaskl** [comment]
您好 请问有个使用教程吗 ，初学者感觉门都还没入…谢谢大佬们指教。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: qingkooo <notifications@github.com>
发送时间: 2019年4月25日 08:54
收件人: shadowsocks/ShadowsocksX-NG <ShadowsocksX-NG@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[shadowsocks/ShadowsocksX-NG] 我想实现一个流量统计的功能，但是不知道如何下手 (#38)




流量统计还没有实现么？
