### ISSUE TITLE
切换SS模式后，系统中手动添加的代理白名单被清除

### ISSUE THREAD

**Issue by mijuu** [shadowsocks/ShadowsocksX-NG#382]
**System and Shadowsocksx-NG version:**

- macOS 10.12.4 (16E195)
- Shadowsocksx-NG 1.5.1

**Expected behavior:**
切换“手动模式”，“PAC模式”，“全局模式”时，MAC系统代理设置的白名单不被清除，能够保留

**Actual behavior:**

切换模式后，MAC系统代理中手动设置好的的白名单列表被清空

**Steps to reproduce:**

切换任意模式

**How often does this happen?**

每次

**Comment by qiuyuzhou** [comment]
duplicated of #1103
