### ISSUE TITLE
如何设定OS X host 上 SS 客户端允许局域网访问

### ISSUE THREAD

**Issue by iSteveyang** [shadowsocks/ShadowsocksX-NG#383]
**System and Shadowsocksx-NG version:1.5.1**

- macOS 10.12.5 (Macbook Air)
- Shadowsocksx-NG 1.5.1

**Expected behavior:**
我希望PD中的windows也可以上网
不知道如何设置才能共享主机网络。
利用桥接还是Host-only？

**Comment by rederry** [comment]
将http代理监听地址设置为0.0.0.0即可

**Comment by Bluelich** [comment]
@rederry  
我希望让手机上设置一下代理,然后可以走mac的ss
设置了http代理的地址未0.0.0.0,没效果
mac上的ss设置是默认的
socket5: 127.0.0.1   1080
http       :  127.0.0.1  1087
需要怎么设置,才可以呢?

**Comment by rederry** [comment]
@Bluelich 手机上http代理设置局域网内mac的ip地址，端口1087

**Comment by yimiaodaren** [comment]
@rederry  这样设置无效，手机上显示 与安全web代理服务器http通信时出现问题

**Comment by optics2046** [comment]
@rederry  

状态：
- MacOS10.13 
- Shadowsocksx-NG （14.3）
- 网络模式 共享

目标:
希望PD中的Linux也可以通过host上的SS代理上网

现在动作：将http代理监听地址设置为0.0.0.0-------------不行
                  更换Shadowsocksx-NG （1.5.1）-------------不行
                  更换Shadowsocksx-NG （1.6.1）-------------不行

**Comment by rederry** [comment]
@optics2046 
我用的1.5.1 http代理监听地址设置的0.0.0.0
其他设备只要设置了http代理都可以连上
你可以检查一下活动监视器里面是否有privoxy进程

**Comment by optics2046** [comment]
谢谢，还是不能连上，活动监视器里没有privoxy进程。最近墙太伟大了，SS不停抽风。

**Comment by darlk** [comment]
@optics2046 
http代理地址设置监听0.0.0.0，端口默认，
# **设置后重启一下ss(关闭代理，再开启)，**
设备设置电脑的局域网ip，端口填ss里面设置的一样，就ok

**Comment by 800sea** [comment]
我的是1.10.3 上面方法做了不行  新增了下面步骤就可以了,找到ShadowsocksX-NG 的安装目录 手动双击privoxy进程,如果User/你的电脑名/config 找不到 ,就把privoxy.config改名config 然后拷贝到User/你的电脑名/  就可以.... 但是还是要走上面大佬的逻辑 http代理地址设置监听0.0.0.0，端口默认，重启SS 这些步骤
