### ISSUE TITLE
dropbox连不上

### ISSUE THREAD

**Issue by bv5204978** [shadowsocks/ShadowsocksX-NG#384]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5
- Shadowsocksx-NG 1.5.1

dropbox服务器连接不上不能同步文件，用Shadowsocksx就可以

**Comment by bv5204978** [comment]
好吧，我自己解决了，果然自己动手丰衣足食，换了个监听端口

**Comment by yangfeicheung** [comment]
how to use dropbox on mac:

https://www.sednax.com/faq-3-cn.php
