### ISSUE TITLE
无法配合proxychains在终端中使用代理

### ISSUE THREAD

**Issue by zxf8665905** [shadowsocks/ShadowsocksX-NG#386]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5 (16F73)
- Shadowsocksx-NG 1.5.1

**Expected behavior:**
- 无法 配合proxychains在终端中使用代理。

**How often does this happen?**
- 之前版本使用没有问题，更新后一直无法使用。

**Comment by gizie** [comment]
搭车同问为什么`proxychains4`连接`ssh`的时候会一会就断开了

**Comment by supgeek-rod** [comment]
+1

**Comment by supgeek-rod** [comment]
使用 1086 端口依然不行
<img width="910" alt="2017-07-31 11 52 22" src="https://user-images.githubusercontent.com/5748006/28762171-c85fae3e-75e6-11e7-802e-c172db59304b.png">

**Comment by supgeek-rod** [comment]
`export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;` 倒是管用了

<img width="303" alt="2017-07-31 11 54 22" src="https://user-images.githubusercontent.com/5748006/28762201-04e765fe-75e7-11e7-9fa3-7d03b2131512.png">

**Comment by morganwu277** [comment]
Belongs to mac osx problem maybe, please review the issue here: 
https://github.com/rofl0r/proxychains-ng/issues/181
