### ISSUE TITLE
bug 扫描开启了OTA的二维码，结果是OTA没选择

### ISSUE THREAD

**Issue by ztechie** [shadowsocks/ShadowsocksX-NG#39]
bug 扫描开启了OTA的二维码，结果是OTA没选择

**Comment by qiuyuzhou** [comment]
原作者被喝茶后，没人协调标准。我只是按照[shadowsocks.org](shadowsocks.org)上的说明实现的。

- 谁知道怎么在url中设置OTA？
- 目前有哪些客户端版本支持？
- 在哪有相关资料？

**Comment by ztechie** [comment]
二维码来自shadowsocks-windows3.2版本的二维码

**Comment by wongsyrone** [comment]
https://github.com/shadowsocks/shadowsocks-org/issues/16

**Comment by haodong** [comment]
method和:中间加上-auth

**Comment by qiuyuzhou** [comment]
Should be fixed by PR #198.
