### ISSUE TITLE
新功能：自动选择最优服务器

### ISSUE THREAD

**Issue by wuzhe** [shadowsocks/ShadowsocksX-NG#391]
这是一个新功能的建议。

如果用户配置了多个服务器，希望软件能自动进行 ping （或其他）连接测试，选择最优的服务器进行连接，一切都是全自动的。可以在设置中增加一个『自动选择最优服务器』的勾选项。

预计这个小功能会大大提高用户感知到的网速。

**Comment by wangzexi** [comment]
设想：对于新的目的域名或ip，连接前首先测试，判断最优服务器后缓存，下次连接直接使用。缓存也应有失效时间。这样基本就可以抛弃 GFW List 了。

**Comment by jackielg** [comment]
对于加了多个ip来说，这个功能非常有用，请考虑~

**Comment by seagle0128** [comment]
强烈支持，Windows版本上有类似的功能。Mac版本上如果连接失败了每次都得手工重新找，麻烦死了。

**Comment by zhiqiang21** [comment]
那就默默的点个赞支持下。这个功能也就是对于土豪用户，配置了多个vpn服务器了吧

**Comment by seagle0128** [comment]
@zhiqiang21 很多用户都是租或者买的VPN，可能有多个账号。这个很便宜也很普遍的。

**Comment by zhiqiang21** [comment]
@seagle0128  ss不都是配置ip和端口的么，比如说我在国外买了一台vpn，那也是只有一个ip地址啊，虽然服务商支持更换ip服务。就算我配置了多个账号，但是实际上连的还是同一台服务器，没有什么区别吧

**Comment by KevinZhangt** [comment]
强烈支持这个功能！！

**Comment by seagle0128** [comment]
@zhiqiang21 我为什么就不能买多个VPN做负载均衡呢？如有一台被封或者太慢，我可以自动切换到其他服务器上。这个需求相当普遍。

**Comment by qiuyuzhou** [comment]
不会支持，ng只是个gui，内嵌来自shadowsocks-libev的ss-local

**Comment by hetaoos** [comment]
我是自己弄了个速度测试的，然后输出时间和排名供参考，自己**手动切换**。
*某些网站会检查来源IP，经常切换，特别是区域跨度大的，可能会触发安全策略，还是手动比较保险点*
![tim 20181110215947](https://user-images.githubusercontent.com/1094462/48302180-0b925680-e534-11e8-94c8-7eaa9e0853cc.jpg)

**Comment by leslieam** [comment]
支持开发负载均衡和自动切换用最好的路线

**Comment by uwings** [comment]
好像是很多人想要，作者觉得可能消耗流量会带来负面效果，或者本身与代理相关性不大，坚决不做。  只能找别的办法或者换软件了

**Comment by seagle0128** [comment]
做个开关呀，觉得费流量就不开不就行了吗？
