### ISSUE TITLE
可不可以增加个检查是否走ss还是直链的功能

### ISSUE THREAD

**Issue by zgfh** [shadowsocks/ShadowsocksX-NG#392]
可不可以增加一个检查功能，输入地址，检查访问是否会走ss代理，还是会通过直连访问？
目前的没找到好办法判断

**Comment by coderfox** [comment]
你可以使用分别访问 <http://cn.bing.com/search?q=ip> 和 <https://www.google.com/search?q=ip> 来检查。

**Comment by xavierzz** [comment]
这个很简单啊，你看你访问网页时指向的IP就可以了！推荐一个chrome插件：Website IP；这个插件可以在网页的左下角显示当前的IP。
