### ISSUE TITLE
Can't connect when using Shadowsocks-NG

### ISSUE THREAD

**Issue by hellobbn** [shadowsocks/ShadowsocksX-NG#396]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 Beta (16G16b)
- Shadowsocksx-NG 1.5.1

**Expected behavior:**

When connect, the browser shows: ERR_PROXY_CONNECTION_FAILED

**How often does this happen?**

Always.

**ss-local.log**

Can't Find the file....

**Application log**

Jun 18 20:05:51 chenluofandeMBP com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[927]): Service could not initialize: 16G16b: xpcproxy + 11765 [1505][3372BFBA-F568-3903-88C6-ACA67E372975]: 0xd
Jun 18 20:05:51 chenluofandeMBP com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.

**Comment by 1c7** [comment]
try SwitchyOmega on Chrome and config port to 1086?
try it.

**Comment by hellobbn** [comment]
1.  There are three port settings: SOCKS5, PAC and HTTP. Could you please tell me what your config is? 
2. Besides, I think that's not the problem of Chrome because when I started to use Shadowsocks, all my network failed.
3. When I use ShadowsocksX, all problems disappeared

**Comment by 1c7** [comment]
SOCKS5  127.0.0.1  port: 1086

**Comment by hellobbn** [comment]
@1c7 So what about other ports? I mistakenly changed them all wrong... Sorry to trouble you...

_Sent from my OnePlus ONEPLUS A3000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 1c7** [comment]
@hellobbn  
what you mean by other port? take a screenshot?

I just open up ShadowsocksX-NG with it's default setting.
and scan couple QR code for Proxy Server Config
![image](https://user-images.githubusercontent.com/1804755/27272320-3a0dd4ae-54fc-11e7-9560-ff15ca50afcf.png)

and then set browser proxy port to 1086 and SOCKS5 and everything work.

it shouldn't be that complicate

**Comment by 1c7** [comment]
you can't just open this software and hope it just working right the way.

just like you need SIM card in your phone to work.
(which you need pay for it)

you need server to let this work
(you can pay for it or build it yourself, which I highly recommend just pay for it, your time is valuable, spend time on that is not wise. )

**Comment by hellobbn** [comment]
好吧原来可以用中文。 
请问有问题么？（其实我觉得可能是HTTP 的问题）
另外，我确实已经在使用SS的账号了，在Android上是可以使用的。
![2017-06-19 4 14 19](https://user-images.githubusercontent.com/10683168/27286493-f0dd0c96-5532-11e7-867f-1c10282c4f7b.png)
![2017-06-19 4 01 44](https://user-images.githubusercontent.com/10683168/27286569-42f47758-5533-11e7-9eae-9023088ab21b.png)

**Comment by hellobbn** [comment]
问题突然小时了，在我改变了~/Library/Logs 的权限以后。 
还是非常感谢。

**Comment by 1c7** [comment]
@hellobbn  :D

**Comment by Hellowor1d** [comment]
u guys crack me up~:smile:
你俩太搞笑了（好吧原来可以用中文）

**Comment by leavez** [comment]
也是改了 ~/Library/Logs 的权限之后好了，不知道怎么变成 root 的了，改成用户所有之后就好了
