### ISSUE TITLE
macOS 10.12.5 NG1.5.1 doesn't work

### ISSUE THREAD

**Issue by gnostr** [shadowsocks/ShadowsocksX-NG#398]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5
- Shadowsocksx-NG 1.5.1

**ss-local.log**
default	21:24:10.284455 +0800	DuetHeuristic-BM	Stop network path monitoring for '<private>'
default	21:24:10.284554 +0800	DuetHeuristic-BM	NO LONGER RUNNING <private> ...Tasks running in group [<private>] are 0!
default	21:24:13.758598 +0800	Safari	Stream client bypassing proxies on TCP Conn [703:0x600000198530]
default	21:24:13.758672 +0800	Safari	TCP Conn 0x600000198530 started
default	21:24:13.760085 +0800	Safari	TCP Conn 0x600000198530 event 3. err: 61
error	21:24:13.760179 +0800	Safari	__nw_connection_get_connected_socket_block_invoke 717 Connection has no connected handler
default	21:24:13.760234 +0800	Safari	TCP Conn 0x600000198530 complete. fd: -1, err: 61
error	21:24:13.760298 +0800	Safari	TCP Conn 0x600000198530 Failed : error 0:61 [61]
default	21:24:13.760617 +0800	Safari	TCP Conn 0x600000198530 canceled
default	21:24:16.655132 +0800	com.apple.WebKit.WebContent	Current memory footprint: 42 MB
default	21:24:17.914905 +0800	com.apple.WebKit.Networking	TIC TCP Conn Cancel [948:0x7fafbd308a00]
default	21:24:17.915039 +0800	com.apple.WebKit.Networking	TIC TCP Conn Cancel [950:0x7fafbd2281b0]
default	21:24:17.915335 +0800	com.apple.WebKit.Networking	TIC TCP Conn Destroyed [948:0x7fafbd308a00]
default	21:24:17.915699 +0800	com.apple.WebKit.Networking	TIC TCP Conn Destroyed [950:0x7fafbd2281b0]
default	21:24:18.763317 +0800	Safari	Stream client bypassing proxies on TCP Conn [704:0x608000583740]

**Comment by dnf5320** [comment]
Turn off and open again

**Comment by gnostr** [comment]
@dnf5320  thx, but doesn't work

**Comment by wanggod** [comment]
@gnostr me too, it can't work most of the time

**Comment by qetee** [comment]
me too, it can't work;

**Comment by qetee** [comment]
![image](https://user-images.githubusercontent.com/2811986/27982249-077340a0-63d0-11e7-90d2-36ea81601865.png)

**Comment by seagle0128** [comment]
It does work well on my MacBook Pro (macOS 10.12.5).

**Comment by wanggod** [comment]
work well now
