### ISSUE TITLE
关于切换代码模式快捷键的bug

### ISSUE THREAD

**Issue by wanghan0501** [shadowsocks/ShadowsocksX-NG#403]
# 现版本切换模式快捷键时候出现的提示框会发生位移现象

具体情况如视频所示

![ezgif-3-89bb3e704a](https://user-images.githubusercontent.com/13730405/27572408-6c05b7d6-5b3e-11e7-8c6d-d7e622919ed7.gif)

**Comment by timothyqiu** [comment]
Duplicate of #348
