### ISSUE TITLE
导出的二维码无法被 shadowsocks-android 识别

### ISSUE THREAD

**Issue by FrancisKong** [shadowsocks/ShadowsocksX-NG#404]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5
- Shadowsocksx-NG 1.5.1
- shadowsocks-android 4.1.8

**Expected behavior:**
导出当前服务器的二维码能被 shadowsocks-android 识别

**Actual behavior:**
二维码无法被 shadowsocks-android 识别

相关问题： [4.0.2版本互相通过二维码分享服务器配置失败](https://github.com/shadowsocks/shadowsocks-android/issues/1118)

**Comment by idaima** [comment]
[ShadowsocksX-NG 1.5.2.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/1167284/ShadowsocksX-NG.1.5.2.zip)

我也遇到了这种尴尬的问题，修改下了代码。顺手打了个包，自测通过～
