### ISSUE TITLE
user-rule.txt有问题

### ISSUE THREAD

**Issue by ares333** [shadowsocks/ShadowsocksX-NG#405]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5
- Shadowsocksx-NG 1.5.1

**Expected behavior:**
目标是做一个用户pac的硬链接到iCloud.
/Applications/ShadowsocksX-NG.app/Contents/Resources/user-rule.txt这个文件不是app使用的文件，因为在app中点击“编辑PAC用户自定规则...“修改之后这个文件内容无变化，重启app和重启系统一样。
pac文件内容：
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||example.com

递归grep了整个用户目录没有找到用户PAC文件，问题来了，这个文件到底在哪？

**Comment by qinyuhang** [comment]
`${HOME}/.ShadowsocksX-NG/`

**Comment by ares333** [comment]
3Q

**Comment by ares333** [comment]
又有问题了，硬连接user-rule.txt到iCloud想实现所有机器的配置一致性，但是编辑pac之后文件的inode变了，导致硬连接断开，用软连接也不行，因为编辑完之后会产生实体文件覆盖软连接。是否可以修改user-rule.txt的文件位置？

**Comment by ares333** [comment]
使用freefilesync和rsync完美解决，调试了一下午，各种死循环。。。
https://www.freefilesync.org/download.php
[解决办法](http://blog.phpdr.net/freefilersync和rsync解决不同mac机器本地文件同步问题.html)

**Comment by senpng** [comment]
@ares333 Can link -s `.ShadowsocksX-NG` folder to `iCloud Drive`.

**Comment by ares333** [comment]
@senpng That doesn't work.The files under the folder can't be synchronized.

**Comment by timothyqiu** [comment]
@ares333 Try putting the actual directory in `iCloud Drive`, and make `~/.ShadowsocksX-NG` a symlink to that.

**Comment by ares333** [comment]
@timothyqiu That's a good idea and should work.I will test it when get home.Thank you.
