### ISSUE TITLE
本地pac无效

### ISSUE THREAD

**Issue by Lesen1991** [shadowsocks/ShadowsocksX-NG#408]
我本地编辑pac之后发现无效，然后在高级设置里面发现本地PAC监听端口是8,090，我试着把逗号去掉然后重启ssr，发现本地pac生效了。是不是程序端口多了个逗号？

**Comment by LuYu001** [comment]
默认本来就没有，的啊 是你的自己不小心改了吧

**Comment by Lesen1991** [comment]
@LuYu001 我重装了还是有。。

**Comment by LuYu001** [comment]
删除应用重新下载不会删除配置信息，配置信息存储位置在其他地方
