### ISSUE TITLE
关闭自动配置后, 我的系统Proxy配置仍然会被修改, 导致Google Drive客户端老是登出

### ISSUE THREAD

**Issue by RavenZZ** [shadowsocks/ShadowsocksX-NG#409]
**System and Shadowsocksx-NG version:**
1.5.1
- macOS 10.12.5
- Shadowsocksx-NG 1.?

**Expected behavior:**
![image](https://user-images.githubusercontent.com/3965218/27817041-aca85d2e-60c1-11e7-92c9-1f63ed8d2893.png)
When I Close the Auto Configure function, Proxies should not change without configure manually.

**Actual behavior:**
![image](https://user-images.githubusercontent.com/3965218/27817103-f4536056-60c1-11e7-979f-76b65b5084a7.png)
I configure WebProxy and SOCKS Proxy manually, but few hours later(may be when Wi-Fi swiched) it rollback~~

**Steps to reproduce:**
Close the Auto Configure , then configure Proxies , may be one day after or connect to another network it will be reproduce 

**How often does this happen?**
everyday

**ss-local.log**

[ss-local.log.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/1121112/ss-local.log.zip)

**Comment by batesme** [comment]
选择手动模式试试？

<img width="287" alt="screenshot 2017-08-11 14 17 22" src="https://user-images.githubusercontent.com/10877963/29202995-ce38f5f6-7e9f-11e7-8de6-ac10476d399d.png">
