### ISSUE TITLE
请问能否增加SSR功能？（或者在哪里？）

### ISSUE THREAD

**Issue by andyliu24** [shadowsocks/ShadowsocksX-NG#410]
能否增加SSR功能以增强混淆，防止封杀呢？
服务器端已开启SSR，但是客户端上没找到设置的地方。

**Comment by qinyuhang** [comment]
https://github.com/shadowsocksr/shadowsocksX-NG <https://github.com/shadowsocksr/shadowsocksX-NG>

**Comment by andyliu24** [comment]
Thanks.
