### ISSUE TITLE
shadowsocks cannot work

### ISSUE THREAD

**Issue by zelinlee0303** [shadowsocks/ShadowsocksX-NG#411]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5 (16E????)
- Shadowsocksx-NG 1.5.0

**Crash Log**

Failed to start process notifications for pid 860 (16)

**Comment by J-Liu** [comment]
1.5.1

**Comment by qetee** [comment]
1.5.1 cannot work too

**Comment by qetee** [comment]
![image](https://user-images.githubusercontent.com/2811986/27982249-077340a0-63d0-11e7-90d2-36ea81601865.png)

**Comment by bingo-taiwan** [comment]
Version 1.2 (1) cannot work

**Comment by qinyuhang** [comment]
U guys may not using a homebrew provided ss-local. The homebrew provided ss-local is not compiled with lib built in.
@qetee if you want fix UR problem try "brew install libev"

**Comment by qiongxuan** [comment]
high sierra
- V 1.5.1，can't work.
- V 1.4, no problem.
