### ISSUE TITLE
kcptun连接问题

### ISSUE THREAD

**Issue by 7449** [shadowsocks/ShadowsocksX-NG#412]
2017/07/06 11:01:52 version: 20170322
2017/07/06 11:01:52 listening on: 127.0.0.1:8388
2017/07/06 11:01:52 encryption: aes
2017/07/06 11:01:52 nodelay parameters: 0 30 2 1
2017/07/06 11:01:52 remote address: xx.xx.xx.xxx:445
2017/07/06 11:01:52 sndwnd: 128 rcvwnd: 512
2017/07/06 11:01:52 compression: false
2017/07/06 11:01:52 mtu: 1350
2017/07/06 11:01:52 datashard: 10 parityshard: 3
2017/07/06 11:01:52 acknodelay: false
2017/07/06 11:01:52 dscp: 0
2017/07/06 11:01:52 sockbuf: 4194304
2017/07/06 11:01:52 keepalive: 10
2017/07/06 11:01:52 conn: 1
2017/07/06 11:01:52 autoexpire: 0
2017/07/06 11:01:52 scavengettl: 600
2017/07/06 11:01:52 snmplog: 
2017/07/06 11:01:52 snmpperiod: 60

ss-local.log

 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 10:57:15 ERROR: getpeername: Invalid argument
 2017-07-06 11:01:52 INFO: initializing ciphers... aes-256-cfb
 2017-07-06 11:01:52 INFO: listening at 127.0.0.1:1086

kcptun_client,log

2017/07/06 11:13:53 stream opened
2017/07/06 11:13:53 stream opened
2017/07/06 11:13:54 session normally closed
2017/07/06 11:13:55 stream opened
2017/07/06 11:13:57 stream opened
2017/07/06 11:14:23 stream closed
2017/07/06 11:14:23 stream closed
2017/07/06 11:14:23 stream closed
2017/07/06 11:14:23 stream closed
2017/07/06 11:14:23 session marked as expired
2017/07/06 11:14:23 connection: 192.168.1.116:63780 -> xx.xx.xx.xxx:445
2017/07/06 11:14:23 stream opened
2017/07/06 11:14:23 stream opened
2017/07/06 11:14:24 session normally closed
2017/07/06 11:14:32 stream opened

地址： xx.xx.xx.xxx 445
加密 aes-256-cfb
密码 ss账号密码
kcptunport:445
mode:fast
encryption:aes
password:kcptun key
disable compression:true
datashard:10 
mtg:1350
parity shard:3
arguments:没填...

当前安装的 Kcptun 版本为: 20170525

可使用的客户端配置文件为:
{
  "localaddr": ":443",
  "remoteaddr": "xx.xx.xx.xxx:445",
  "key": "password",
  "crypt": "aes",
  "mode": "fast",
  "mtu": 1350,
  "sndwnd": 512,
  "rcvwnd": 512,
  "datashard": 10,
  "parityshard": 3,
  "dscp": 0,
  "nocomp": false,
  "nodelay": 0,
  "interval": 20,
  "resend": 2,
  "nc": 1,
  "acknodelay": false,
  "sockbuf": 4194304,
  "keepalive": 10
}

**Comment by 7449** [comment]
我使用kcptun_xclient和老版客户端使用是没有问题的 但是用ng一直用不了kcptun.,直接使用ss是可以连接的

**Comment by 7449** [comment]
问题找到了 ：
disable compression:false
偏好设置里面：
ss的 socks5 的监听端口应该改成 1080 其余不变就可以了

**Comment by dequn** [comment]
[issue-313](https://github.com/shadowsocks/ShadowsocksX-NG/issues/313)解释的比较清楚，kcptun配置的时候要填的是kcptun的密码，叫做key.
