### ISSUE TITLE
估计是被喝茶了

### ISSUE THREAD

**Issue by DemonCloud** [shadowsocks/ShadowsocksX-NG#413]
默哀一下作者

**Comment by nxtreaming** [comment]
any evidence?

**Comment by DemonCloud** [comment]
@nxtreaming 
从1.5.1 版本之后再也没有任何提交，估计是被喝茶了，最近TG严打，个大VPN死的死伤的伤。 估计Github也快了

**Comment by qiuyuzhou** [comment]
创业公司太忙了。。。

**Comment by DemonCloud** [comment]
@qiuyuzhou 好险自己出来冒泡了，不然以为真的喝茶去了
