### ISSUE TITLE
ss-local won't start with GUI

### ISSUE THREAD

**Issue by scenix007** [shadowsocks/ShadowsocksX-NG#418]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5
- Shadowsocksx-NG 1.5.1

**Expected behavior:**
ss-local start with GUI

**Actual behavior:**

No ss-local process can be found after GUI started.

**Steps to reproduce:**

No ss-local process can be found after GUI started.
Firstly run `./ss-local` give me errors that indicates cannot find some package.
so I run `brew install libev libsodium mbedtls udns`.
Then I can start ss-local by run `ss-local-3.0.5/ss-local -c ss-local-config.json` ,webpage can be opened normally.
But still ss-local can't start with GUI, or reload configuration after GUI updates its settings, to get things working I must manually start ss-local by command line every time. 

**How often does this happen?**

Every time.

**ss-local.log**

no ss-local.log file inside ~/Library/Logs/

**Application log**

```
default	15:03:48.088424 +0800	ShadowsocksX-NG	Start ss-local succeeded.
default	15:03:48.156941 +0800	ShadowsocksX-NG	Start privoxy succeeded.
default	15:03:48.224439 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
default	15:03:48.228504 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	15:03:48.277677 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [46971] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [46985] (3,0)
default	15:03:48.279465 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [46971] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [46985] (3,0)
default	15:03:48.282737 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [46971] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [46985] (3,0)
default	15:03:48.283892 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [46971] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [46985] (3,0)
default	15:03:48.287839 +0800	ShadowsocksX-NG	pac proxy set to auto

```
Even log shows ss-local started, but `ps aux | grep ss-local` shows nothing.

**Comment by digpara** [comment]
Met similar issue.
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libev/lib/libev.4.dylib
  Referenced from: /Users/nebulabox/Library/Application Support/ShadowsocksX-NG/ss-local-3.0.5/./ss-local
  Reason: image not found
Abort trap: 6

**Comment by timothyqiu** [comment]
The "Library not loaded" error is expected if you just execute `./ss-local`.

If you want to run it from the command line manually, `DYLD_LIBRARY_PATH` environment variable should be pointing to `~/Library/Application Support/ShadowsocksX-NG/ss-local-latest/`.

Check your `~/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist` file if `ss-local` is not starting with your GUI.
