### ISSUE TITLE
shadowscoks 上草榴怎么图片什么都挂了

### ISSUE THREAD

**Issue by kant11** [shadowsocks/ShadowsocksX-NG#422]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by gongxun0928** [comment]
why?

**Comment by timothyqiu** [comment]
Please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.

(I wonder if we should get a bot to do this kind of reply...)

**Comment by nanxiaodi** [comment]
兄弟~我就请问一下草榴怎么走？

**Comment by wjk930726** [comment]
我觉得你该搞一个机器人……
