### ISSUE TITLE
mac not work

### ISSUE THREAD

**Issue by artOfWarBut** [shadowsocks/ShadowsocksX-NG#423]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5
- Shadowsocksx-NG 1.5
 
**How often does this happen?**

this month

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

there is no  ss-local.log in   `~/Library/Logs`
 
**Application log**

默认	13:37:48.592321 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [21726] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [21748] (3,0)
默认	13:37:48.596316 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [21726] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [21748] (3,0)
默认	13:37:48.597720 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [21726] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [21748] (3,0)
默认	13:37:48.603815 +0800	ShadowsocksX-NG	pac proxy set to auto
默认	13:39:30.436871 +0800	useractivityd	SIMULATOR: Clearing current item, because it has been removed ( was CD663487-88E1-440A-A906-28BFF4E0404C/UAUserActivityInfo:{ type = UserActivity; uuid = CD663487-88E1-440A-A906-28BFF4E0404C; title = "(null)"; activityType = "com.google.chrome.handoff"; dynamicActivityType = "(null)"; teamID=; userInfo = $4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163 webPageURL=https://github.com/shadowsocks/ShadowsocksX-NG/issues/381 -  -  opts={} - }).
默认	13:39:42.595009 +0800	useractivityd	SIMULATOR: Clearing current item, because it has been removed ( was CD663487-88E1-440A-A906-28BFF4E0404C/UAUserActivityInfo:{ type = UserActivity; uuid = CD663487-88E1-440A-A906-28BFF4E0404C; title = "(null)"; activityType = "com.google.chrome.handoff"; dynamicActivityType = "(null)"; teamID=; userInfo = $4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163 webPageURL=https://github.com/shadowsocks/ShadowsocksX-NG/issues/381 -  -  opts={} - }).
默认	13:40:08.319135 +0800	useractivityd	SIMULATOR: Clearing current item, because it has been removed ( was A4399E88-A3FB-4816-88F3-B493C6B0BEF4/UAUserActivityInfo:{ type = UserActivity; uuid = A4399E88-A3FB-4816-88F3-B493C6B0BEF4; title = "(null)"; activityType = "com.google.chrome.handoff"; dynamicActivityType = "(null)"; teamID=; userInfo = $4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163 webPageURL=https://github.com/shadowsocks/ShadowsocksX-NG/issues/new -  -  opts={} - }).
默认	13:40:59.891713 +0800	useractivityd	SIMULATOR: Clearing current item, because it has been removed ( was 3D1F01A2-CC2A-4D8F-BABA-64CEBC050CC9/UAUserActivityInfo:{ type = UserActivity; uuid = 3D1F01A2-CC2A-4D8F-BABA-64CEBC050CC9; title = "(null)"; activityType = "com.google.chrome.handoff"; dynamicActivityType = "(null)"; teamID=; userInfo = $4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163 webPageURL=https://github.com/shadowsocks/ShadowsocksX-NG/issues/new -  -  opts={} - }).
默认	13:41:51.809775 +0800	useractivityd	SIMULATOR: Clearing current item, because it has been removed ( was 0E440763-A403-41B2-A06D-9DCEA159433E/UAUserActivityInfo:{ type = UserActivity; uuid = 0E440763-A403-41B2-A06D-9DCEA159433E; title = "(null)"; activityType = "com.google.chrome.handoff"; dynamicActivityType = "(null)"; teamID=; userInfo = $4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163 webPageURL=https://github.com/shadowsocks/ShadowsocksX-NG/issues/381 -  -  opts={} - }).
默认	13:42:20.668006 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [0] success
默认	13:42:20.705612 +0800	useractivityd	SIMULATOR: Clearing current item, because it has been removed ( was BAD4DB79-16D7-4F21-AD39-0F789D48495C/UAUserActivityInfo:{ type = UserActivity; uuid = BAD4DB79-16D7-4F21-AD39-0F789D48495C; title = "(null)"; activityType = "com.google.chrome.handoff"; dynamicActivityType = "(null)"; teamID=; userInfo = $4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163 webPageURL=https://github.com/shadowsocks/ShadowsocksX-NG/issues/new -  -  opts={} - }).
默认	13:42:36.236782 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	13:42:36.309166 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	13:42:36.378089 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	13:42:36.447875 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	13:42:36.517115 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	13:42:36.584595 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	13:42:36.586788 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	13:42:36.642106 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [21781] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [21780] (3,0)
默认	13:42:36.645085 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [21781] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [21780] (3,0)
默认	13:42:36.650921 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [21781] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [21780] (3,0)
默认	13:42:36.651926 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [21781] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [21780] (3,0)
默认	13:42:36.656584 +0800	ShadowsocksX-NG	pac proxy set to auto
默认	13:42:39.018367 +0800	useractivityd	SIMULATOR: Clearing current item, because it has been removed ( was BAD4DB79-16D7-4F21-AD39-0F789D48495C/UAUserActivityInfo:{ type = UserActivity; uuid = BAD4DB79-16D7-4F21-AD39-0F789D48495C; title = "(null)"; activityType = "com.google.chrome.handoff"; dynamicActivityType = "(null)"; teamID=; userInfo = $4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163 webPageURL=https://github.com/shadowsocks/ShadowsocksX-NG/issues/new -  -  opts={} - }).
默认	13:42:46.443431 +0800	useractivityd	SIMULATOR: Clearing current item, because it has been removed ( was BAD4DB79-16D7-4F21-AD39-0F789D48495C/UAUserActivityInfo:{ type = UserActivity; uuid = BAD4DB79-16D7-4F21-AD39-0F789D48495C; title = "(null)"; activityType = "com.google.chrome.handoff"; dynamicActivityType = "(null)"; teamID=; userInfo = $4d50030581aa6b4f726967696e4b6579aa6b4f726967696e4d6163 webPageURL=https://github.com/shadowsocks/ShadowsocksX-NG/issues/new -  -  opts={} - }).

**Comment by xavierzz** [comment]
我也遇到同样的问题，not work。
首先，我不懂为什么一开始socks5的端口是1086的，设置了这样的端口一直不行；然后，把他改成了1080就行了，但是却一直都成了全局模式。其他模式都不行。
所以，现在要么不行，要么一直是全局模式 😂

**Comment by artOfWarBut** [comment]
@xavierzz  看了你的，我跟你一样改成1080就好了， 但全局和pac模式都可以翻墙

**Comment by Time02** [comment]
@xavierzz 用你这个方法，昨天不行 ，今天却可以了 ！但是还没找到具体原因，之前一直好好的，突然就不可用了。。

**Comment by happychels** [comment]
@xavierzz 你好，你简直我的救命天使，特此注册账号以表感谢。在电脑前折腾了20+小时，可算解决了嗷嗷嗷。我改成1080后，遇到的问题跟你一样，只可在全局模式下进行。啊。谢谢天使。

**Comment by happychels** [comment]
@xavierzz  对了，天使，
1.我好像只有自己的热点可以用，公共Wi-Fi不可以
2.你现在用还可以在pac模式下用吗

**Comment by xavierzz** [comment]
@happychels 😂 😂  折腾了20+小时。有那么严重么😂  我现在没用shadowsocks客户端了，改用surge了。

**Comment by happychels** [comment]
断断续续吧，一会儿网络 一会儿chrome问题，累的哟




发自网易邮箱大师
在2017年09月02日 19:36，xavi 写道：

@happychels😂😂 折腾了20+小时。有那么严重么😂 我现在没用shadowsocks客户端了，改用surge了。
