### ISSUE TITLE
Configuration windows can't be closed.

### ISSUE THREAD

**Issue by ibtwbbab** [shadowsocks/ShadowsocksX-NG#429]
**System and Shadowsocksx-NG version:**

- macOS 10.12.3 (16E????)
- Shadowsocksx-NG 1.5.1

**Expected behavior:**

Close the configuration window when I click close button.

**Actual behavior:**

The configuration window never disappear.

**Steps to reproduce:**

1. Click preference to show the configuration window.
2. Click close button to close it.

**How often does this happen?**

Always

**ss-local.log**

[ss-local.txt](https://github.com/shadowsocks/ShadowsocksX-NG/files/1182989/ss-local.txt)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by timothyqiu** [comment]
The call to `NotificationCenter` post methods are synchronous, thus causing a lag between hitting the close button and the window disappearance. I think if the lag is long enough, users may misunderstand it as the window will never disappear.

Maybe we should use `NotificationQueue` instead? (That may need extra UI care-taking.)

p.s. There are [two continuous calls to `SyncSSLocal()`](https://github.com/shadowsocks/ShadowsocksX-NG/blob/e8e4f9ad11a4b72b831eb245d352a3db4afc2549/ShadowsocksX-NG/AppDelegate.swift#L96-L97), one in-place and one at the top of `applyConfig`. Is that redundant?

Ping @qiuyuzhou
