### ISSUE TITLE
Will this tool support start multi shadowsocks proxy on a PC as GoAgentX?

### ISSUE THREAD

**Issue by normanx** [shadowsocks/ShadowsocksX-NG#432]
**System and Shadowsocksx-NG version:**

- macOS 10.11.6
- Shadowsocksx-NG 1.5

Expected behavior: I have multi shadowsocks server and I start multi server at the same time for use for different app, such as : one for web browser, one for dropbox async... I have use  GoAgentX now but it won't update and won't support new features of shadowsocks, I want to switch to this tool, but I find it won't support start multi shadowsocks proxy on a PC, will this feature been add to future version?

**Comment by qiuyuzhou** [comment]
Won't.
