### ISSUE TITLE
How Can I edit the PAC url?

### ISSUE THREAD

**Issue by QWERT1984** [shadowsocks/ShadowsocksX-NG#437]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.5.1(1)

**Expected behavior:**

I want a specific URL  pass through the VPN server. Such as music.163.com. 

**Actual behavior:**

I don't know how to edit the PAC file or something else. Please Help me and thank you so much.

**Comment by timothyqiu** [comment]
You want to add a specific URL to the PAC, not to modify the PAC URL.

Go to Menu > Edit User Rules For PAC, and append your url to the text field. For example:

    ||music.163.com

This will make all requests to `music.163.com` to go through the proxy.

Refer to the content in the dialog for the full syntax reference.

**Comment by QWERT1984** [comment]
But I have another problem, I add the url to User Rules, but I cannot surf Facebook now. I choose Proxy Auto configure Mode. I want to bypass the location block with the SS server in China. Thank you so much.

**Comment by chermy** [comment]
"||amazon.com",
Do not forget quotation marks and commas.

**Comment by li0near** [comment]
The PAC, gfwlist along with user specified list are all located in ~/.ShadowsocksX-NG. You could modify the configuration files manually.

You can also use this "reversed" list: https://github.com/gfwlist/tsilwfg/blob/master/tsilwfg.txt

**Comment by whr2206** [comment]
When I accessed the config file manually, it just showed a bunch of jumbled numbers.

I'm also trying to add a few sites to the list (Like udacity and sensortower) 

“||http://udacity.com”,
“||http://sensortower.com”,

Is this the correct format?

**Comment by yangfeicheung** [comment]
if you guys want to try ShadowsocksX, follow this instructions to add custom rules, easy and simple

https://www.sednax.com/faq-7.php

**Comment by Sky-QingJia** [comment]
I have fixed. 
![image](https://user-images.githubusercontent.com/50317297/61852655-919cd480-aeec-11e9-80e3-548e955a727d.png)

**Comment by 08822407d** [comment]
while you edit pac through GUI, DO NOT add quotes and comma, write rules line by line
for example in GUI you write:

||gtihub.com
||google.com

software will auto convert it, in the file ~/.ShadowsocksX-NG/gfwlist.js you will see

"||gtihub.com",
"||google.com",

at the top of rule

**Comment by AChaoZJU** [comment]
> You want to add a specific URL to the PAC, not to modify the PAC URL.
> 
> Go to Menu > Edit User Rules For PAC, and append your url to the text field. For example:
> 
> ```
> ||music.163.com
> ```
> 
> This will make all requests to `music.163.com` to go through the proxy.
> 
> Refer to the content in the dialog for the full syntax reference.

What if I do not want the requests to a URL in PAC to go through the proxy?
Do I need to delete a URL from PAC?

**Comment by Symbolk** [comment]
> > You want to add a specific URL to the PAC, not to modify the PAC URL.
> > Go to Menu > Edit User Rules For PAC, and append your url to the text field. For example:
> > ```
> > ||music.163.com
> > ```
> > 
> > 
> > This will make all requests to `music.163.com` to go through the proxy.
> > Refer to the content in the dialog for the full syntax reference.
> 
> What if I do not want the requests to a URL in PAC to go through the proxy?
> Do I need to delete a URL from PAC?

Prepend @@ before the address.

**Comment by csxuejin** [comment]
> The file located in `~/.ShadowsocksX-NG/gfwlist.js` shows:
> 
> <img alt="screenshot" width="318" src="https://user-images.githubusercontent.com/12585858/44423794-9577f680-a5b9-11e8-8e9e-d45245e7086e.png">
> 
> and we can tell that if you want to use the full URL you need `|` instead of `||`.

this works, thx

**Comment by wangpin34** [comment]
> while you edit pac through GUI, DO NOT add quotes and comma, write rules line by line for example in GUI you write:
> 
> ||gtihub.com ||google.com
> 
> software will auto convert it, in the file ~/.ShadowsocksX-NG/gfwlist.js you will see
> 
> "||gtihub.com", "||google.com",
> 
> at the top of rule

thanks bro, save my day
