### ISSUE TITLE
如何连接shadowsocksR server呢?

### ISSUE THREAD

**Issue by hktalent** [shadowsocks/ShadowsocksX-NG#439]
如何连接shadowsocksR server呢?

**Comment by qinyuhang** [comment]
This app not support ssr

**Comment by tisfeng** [comment]
可以啊，我就是用的SSR啊

**Comment by qinyuhang** [comment]
The ssr fork is delete. This repo is not support ssr. Search the issues before ask a question. 
> 在 2017年8月4日，10:43，Tisfeng <notifications@github.com> 写道：
> 
> 可以啊，我就是用的SSR啊
>

**Comment by J-Liu** [comment]
据说ss被北邮破解了，是不是考虑下支持ssr啊？

**Comment by fatezeronight** [comment]
@qinyuhang 你的那个版本加一下kcptun就很完美了，我在用你的那个😂😂😂
