### ISSUE TITLE
mac上开机启动无效

### ISSUE THREAD

**Issue by korialuo** [shadowsocks/ShadowsocksX-NG#441]
RT，MacOS 10.12.5上设置开机启动，但每次开机未自动启动。

**Comment by timothyqiu** [comment]
Visit  / System Preferences / Users & Groups, select your user name on the left, then click Login Items at the top of the window. Is ShadowsocksX in the list?

**Comment by timothyqiu** [comment]
Sorry, my last post won't help, please ignore it. It was an old setting on my machine and I thought it matters. 😂

**Comment by korialuo** [comment]
I update it to the latest version, then it works. :)
