### ISSUE TITLE
1.5.1版本服务器测速功能实在是太难找了，是取消了么？

### ISSUE THREAD

**Issue by wjk930726** [shadowsocks/ShadowsocksX-NG#449]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6
- Shadowsocksx-NG 1.5.1

**Expected behavior:**

- 希望能在下拉菜单中添加一个服务器测速功能
- ps：配合proxifier不好使了，和老版本的设置方式相同，但是无法全局代理，不知道为什么

**Comment by dadupi** [comment]
楼主，请教一下，哪个版本有服务器测试功能？我试了1.5.1和1.5.0都没有找到啊

**Comment by wjk930726** [comment]
今年三月份的版本应该有，你试下1.4版？

**Comment by qiuyuzhou** [comment]
是SSR的衍生版有，这里没有过
