### ISSUE TITLE
socks5 port not listening

### ISSUE THREAD

**Issue by shiningwang** [shadowsocks/ShadowsocksX-NG#450]
**System and Shadowsocksx-NG version:**

- OS X 10.11.6 (15G1611)
- Shadowsocksx-NG 1.5.1(1)
- Server is shadowsocks(python) 3.0.0

**Expected behavior:**

the socks5 port is listen

**Actual behavior:**

the socks5 port is not listening

```shell
$ netstat -ant|grep LISTEN
tcp6       0      0  ::1.1089               *.*                    LISTEN
tcp4       0      0  127.0.0.1.1089         *.*                    LISTEN
tcp4       0      0  127.0.0.1.1087         *.*                    LISTEN
$ curl --socks5 localhost:1086 httpbin.org/ip
curl: (7) Failed to connect to localhost port 1086: Connection refused
```

**Steps to reproduce:**

1. install ShadowsocksX 2.6.3
2. open ShadowsocksX.app (PAC mode. Socks5 port listen 1080 works fine.)
3. install ShadowsocksX-NG 1.5.1
4. open ShadowsocksX-NG.app (PAC mode. Now the 1080 is listening, but 1086 is not.)
5. close all shadowsocks app
6. open ShadowsocksX-NG.app (PAC mode. Socks5 port listen 1086 is not listening.)

**How often does this happen?**

always

**ss-local.log**

[ss-local.log.txt](https://github.com/shadowsocks/ShadowsocksX-NG/files/1219520/ss-local.log.txt)

**Application log**

17/8/12 13:28:49.455 ShadowsocksX-NG[3889]: Call SMLoginItemSetEnabled with [0] success
17/8/12 13:28:49.528 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) This service is defined to be constantly running and is inherently inefficient.
17/8/12 13:28:49.538 ShadowsocksX-NG[3889]: Start ss-local succeeded.
17/8/12 13:28:49.548 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.http) This service is defined to be constantly running and is inherently inefficient.
17/8/12 13:28:49.559 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:28:49.589 ShadowsocksX-NG[3889]: Start privoxy succeeded.
17/8/12 13:28:49.655 ShadowsocksX-NG[3889]: Stop kcptun succeeded.
17/8/12 13:28:49.656 ShadowsocksX-NG[3889]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
17/8/12 13:28:49.716 ShadowsocksX-NG[3889]: pac proxy set to auto
17/8/12 13:28:59.585 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:29:09.610 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:29:19.637 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:29:29.664 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:29:39.693 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:29:49.719 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:29:59.743 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:30:09.768 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:30:19.792 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:30:29.817 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:30:39.846 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:30:49.872 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:30:59.894 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:31:09.923 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:31:19.950 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:31:29.975 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:31:40.002 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:31:50.026 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:32:00.053 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:32:10.075 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:32:20.101 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:32:30.130 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:32:40.159 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:32:50.183 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:32:58.903 ShadowsocksX-NG[3889]: Call SMLoginItemSetEnabled with [0] success
17/8/12 13:33:00.206 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:33:10.234 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:33:12.067 ShadowsocksX-NG[3889]: Start ss-local succeeded.
17/8/12 13:33:12.137 ShadowsocksX-NG[3889]: Start privoxy succeeded.
17/8/12 13:33:12.204 ShadowsocksX-NG[3889]: Stop kcptun succeeded.
17/8/12 13:33:12.272 ShadowsocksX-NG[3889]: Start ss-local succeeded.
17/8/12 13:33:12.340 ShadowsocksX-NG[3889]: Start privoxy succeeded.
17/8/12 13:33:12.406 ShadowsocksX-NG[3889]: Stop kcptun succeeded.
17/8/12 13:33:12.407 ShadowsocksX-NG[3889]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
17/8/12 13:33:12.467 ShadowsocksX-NG[3889]: pac proxy set to auto
17/8/12 13:33:20.257 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:33:30.282 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:33:40.308 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:33:50.339 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:34:00.366 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:34:10.391 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:34:20.415 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:34:30.439 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:34:40.469 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:34:50.493 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:35:00.521 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:35:10.550 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:35:20.575 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:35:30.598 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:35:40.627 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:35:50.653 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:36:00.679 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:36:10.707 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:36:20.732 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
17/8/12 13:36:21.143 ShadowsocksX-NG[3889]: Stop ss-local succeeded.
17/8/12 13:36:21.208 ShadowsocksX-NG[3889]: Stop kcptun succeeded.
17/8/12 13:36:21.215 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.http[3896]) Service exited with abnormal code: 15
17/8/12 13:36:21.274 ShadowsocksX-NG[3889]: Stop privoxy succeeded.
17/8/12 13:36:21.274 ShadowsocksX-NG[3889]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
17/8/12 13:36:21.357 ShadowsocksX-NG[3889]: pac proxy set to off

**Crash Log**

no crash

** quick-and-dirty fix  **

open the two shadowsocks app at the same time.
set ShadowsocksX-NG and ShadowsocksX socks5 port to the same number. eg. 1080.
then use ShadowsocksX-NG pac proxy and ShadowsocksX socks5 port listen.

**Comment by timothyqiu** [comment]
Hi, thank you for your detailed issue report. 🎉 

It seems that the reason is you're trying to use the deprecated "One Time Auth" feature. OTA is no longer supported by the upstream `shadowsocks-libev` project since February, so does SSX-NG.

There are lots of articles around explaining why OTA feature should not be used. Please take some time to read one and make your server config more secure :)

---

@qiuyuzhou As enabling OTA will cause SSX-NG to stop working "mysteriously", should the OTA check box be removed? Or at least make the profile invalid and disable the menu item?

**Comment by shiningwang** [comment]
i'll try, thanks.

**Comment by shiningwang** [comment]
it's works!
