### ISSUE TITLE
X-NG无法使用，NG-R8,X都是可以的

### ISSUE THREAD

**Issue by jonchsy** [shadowsocks/ShadowsocksX-NG#452]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by jonchsy** [comment]
ShadowsocksX，ShadowsocksX-NG-R8我都可以使用，但是最新的ShadowsocksX-NG却不行。SS确定没有问题

**Comment by smarxpan** [comment]
说明你的服务端是ssr，不是ss

**Comment by yangcin** [comment]
以前的版本都没用成功，唯独1.5.1完全无压力使用上了

**Comment by fatezeronight** [comment]
现在那个SSR版本的也有问题，没有kcptun的功能
