### ISSUE TITLE
在MAC 10.12.6中 ss-local有问题

### ISSUE THREAD

**Issue by adidi199** [shadowsocks/ShadowsocksX-NG#454]
`ss-local(43909,0x7fffcab1e3c0) malloc: *** error for object 0x10000001e: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug`

在log中会时不时出现这个错误。

其次现在的版本在mac中链接都基本连不上网，就短短续续的。比如链接了一下就链接就断了要刷新网页才行。

虽然我用的是R81.4.2。但R8也是从这边改的。如果是这边的问题的话，希望这个问题能解决

**Comment by qinyuhang** [comment]
去 github.com/qinyuhang/shadowsocksX-NG-R <http://github.com/qinyuhang/shadowsocksX-NG-R> 提问吧。

**Comment by adidi199** [comment]
@qinyuhang =。。=那边好像没有issues

**Comment by qiuyuzhou** [comment]
SSR的版本的ss-local被替换成ssr的版本了，跟我这里不一样。
