### ISSUE TITLE
ld: warning: directory not found for option * ld: library not found for -lBRLOptionParser

### ISSUE THREAD

**Issue by dalekzhangdong** [shadowsocks/ShadowsocksX-NG#457]
**System and Shadowsocksx-NG version:**
last version, git clone from website;
- macOS 10.??.?? (16E????)
moc os 10.12.4 (16E195)
- Shadowsocksx-NG 1.?
last version 
**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**
just compiled 
(N/A for feature requests)
no 
**How often does this happen?**
always 
(N/A for feature requests)

**Application log**
Ld /Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Products/Debug/proxy_conf_helper normal x86_64
cd /Users/dalek/Documents/work/shadowsock/ShadowsocksX-NG
export MACOSX_DEPLOYMENT_TARGET=10.11
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Products/Debug -L/Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Products/Debug/BRLOptionParser -F/Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Products/Debug -filelist /Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper.LinkFileList -mmacosx-version-min=10.11 -Xlinker -object_path_lto -Xlinker /Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -lBRLOptionParser -lPods-proxy_conf_helper -Xlinker -dependency_info -Xlinker /Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Intermediates/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_dependency_info.dat -o /Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Products/Debug/proxy_conf_helper

ld: warning: directory not found for option '-L/Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Products/Debug/BRLOptionParser'
ld: library not found for -lBRLOptionParser
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**### -ps 
**I compiled it with xcode8 , can't compile; I git clone BRLOptionParser project , and compile it with xcode , successful; in /Users/dalek/Library/Developer/Xcode/DerivedData folder, I find two BRLOptionParser folder, one is BRLOptionParser-ewnkqizkutygoabwuzwkzndhxfhc and the other is BRLOptionParser-ghvkglwoihixfjbfjfdekgogxqdf , I think one is which i git, the other is pod install ed , but ss project linked with /Users/dalek/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl/Build/Products/Debug/BRLOptionParser; but it is not ShadowsocksX-NG-hkltdvqxdwqmryfywfbmgmkbkxnl folder in DerivedData folder at all .****

**Comment by dalekzhangdong** [comment]
Pls help, ths a lot .

**Comment by timothyqiu** [comment]
@dalekzhangdong 

Please spare 5 minutes and checkout the *Get Started* section of <https://cocoapods.org/>. Make sure you know how to work with a CocoaPods enabled project.

Spoiler Alert: Use `.xcworkspace` instead of `.xcodeproj`.

p.s. You can always edit your previous comment with the "Edit comment" button at the top right corner of the comment entry.

**Comment by dalekzhangdong** [comment]
yes, I was successful. ths a lot . I use pod update and close the project and reopen the project with .xcworkspace, that  is ok now .

**Comment by dalekzhangdong** [comment]
My shadowsocks-ng is working now.
