### ISSUE TITLE
Is it possible to use IP address in PAC rules instead of domain names?

### ISSUE THREAD

**Issue by InfoHunter** [shadowsocks/ShadowsocksX-NG#459]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6
- Shadowsocksx-NG 1.4.1-R8

**Expected behavior:**

Could add an IP address range like 1.1.1.0/24 into PAC user defined rules

**Actual behavior:**

Don't know how to do it...

**Steps to reproduce:**

n/a

**How often does this happen?**

n/a

**Comment by timothyqiu** [comment]
Yes, and no.

For a plain PAC file, you just implement the `FindProxyForURL(url, host)` and return the desired proxy directives. So you can utilize the built-in `dnsResolve` function to get the corresponding IP from `host`, and do the compare / matching thing manually.

However, for SSX-NG, the "PAC" is auto-generated from the GFW List & User Rules, using the Adblock Plus filter syntax. There is no IP matching feature in ABP filter syntax, just URL matching I'm afraid.

**Comment by InfoHunter** [comment]
So there is no way to specify a customized PAC file in SSX-NG? If so, I think I could write that piece of code to match IP ranges myself...

**Comment by InfoHunter** [comment]
> So there is no way to specify a customized PAC file in SSX-NG?

I mean, force SSX-NG to use a 'plain PAC file' instead of generating one from `GFW List & User Rules` automatically...

**Comment by timothyqiu** [comment]
I think Pull Request #453 already did that.

If you want a plain PAC file, I think there is a work around:
* Select the Manual Mode in SSX-NG.
* Apple Menu / System Preferences / Network, choose the network interface and click "Advanced...".
* In the Proxy tab, enable "Automatic Proxy Configuration", and set your plain PAC file there.

**Comment by InfoHunter** [comment]
Awesome, thanks!
