### ISSUE TITLE
NG-R8怎么没有了，它这个有什么区别。

### ISSUE THREAD

**Issue by zh-chen** [shadowsocks/ShadowsocksX-NG#462]

**Comment by hly928** [comment]
ShadowsocksX-NG-R provides support for ShadowsocksR, while this is for original Shadowsocks. BTW, ShadowsocksX-NG-R was removed when SSR was removed, but it was back again a few days ago. The latest release is here: https://github.com/qinyuhang/ShadowsocksX-NG-R/releases

**Comment by fatezeronight** [comment]
我看了一下那边的NG-R8没有kcptun的支持。
