### ISSUE TITLE
请问PAC用户规则是用的blocking rules还是Exception rules

### ISSUE THREAD

**Issue by liuzhiyi0315** [shadowsocks/ShadowsocksX-NG#465]
For example
if i'd like to let some site going through proxy that not included by GFW list
i added this rule to user defined rules, but it seems not working..
||www.abc.org^

**Comment by Jesse-Fan** [comment]
i guess website in PAC list go through proxy? i mean  some pretty good sites

**Comment by nightire** [comment]
You need to refresh sometimes, I mean "Update GFW List" after you add entries in your user file.

**Comment by Kinka** [comment]
既然标题是中文,那我就说中文吧.
因为配置文件没更新, 自己操作了下,切换代理开关就可以了.
