### ISSUE TITLE
Mac系统电量消耗过度，使用期间一直启用独立显卡

### ISSUE THREAD

**Issue by srhpx06** [shadowsocks/ShadowsocksX-NG#466]
Mac OS 10.12.6 版本
2016款带touch bar macbook pro 15‘

脱离电源没多久电量暴跌，发现电量那里指示significant energy use，查找细节原因是一直使用独立显卡，不知这个是必要条件还是软件bug

**Comment by timothyqiu** [comment]
Duplicate of #370 

Restart after showing QR code may be an workaround.

**Comment by srhpx06** [comment]
Thanks！
