### ISSUE TITLE
The speed slows down after using kcptun (使用kcptun后速度变慢)

### ISSUE THREAD

**Issue by sdsy888** [shadowsocks/ShadowsocksX-NG#473]
**System and Shadowsocksx-NG version:**
- macOS 10.12.6 (16G29)
- Shadowsocksx-NG 1.5.1

**Expected behavior:** Faster connection after using kcptun

**Actual behavior:** The speed becomes slower

**Happens every time**

**ss-log:**
> 2017-09-02 21:21:56 INFO: initializing ciphers... aes-256-cfb
>  2017-09-02 21:21:56 INFO: udprelay enabled
>  2017-09-02 21:21:56 INFO: listening at 127.0.0.1:1086
>  2017-09-02 21:21:57 INFO: connect to s.youtube.com:443
>  2017-09-02 21:21:57 INFO: connect to www.youtube.com:443
>  2017-09-02 21:21:57 INFO: connect to s.youtube.com:443
>  2017-09-02 21:21:58 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:21:58 INFO: connect to s.youtube.com:443
>  2017-09-02 21:21:59 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:21:59 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:21:59 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:21:59 INFO: connect to www.youtube.com:443
>  2017-09-02 21:22:01 INFO: connect to www.google.com:443
>  2017-09-02 21:22:01 INFO: connect to i.ytimg.com:443
>  2017-09-02 21:22:39 INFO: connect to clients1.google.com:443
>  2017-09-02 21:22:55 INFO: connect to safebrowsing.googleapis.com:443
>  2017-09-02 21:23:00 INFO: TCP connection timeout
>  2017-09-02 21:23:01 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:23:03 INFO: TCP connection timeout
>  2017-09-02 21:23:03 INFO: TCP connection timeout
>  2017-09-02 21:23:50 INFO: TCP connection timeout
>  2017-09-02 21:24:01 INFO: TCP connection timeout
>  2017-09-02 21:24:39 INFO: connect to r5---sn-5ualdn7y.googlevideo.com:443
>  2017-09-02 21:24:43 INFO: connect to clients4.google.com:443
>  2017-09-02 21:25:10 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:25:52 INFO: TCP connection timeout
>  2017-09-02 21:25:55 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:27:49 INFO: TCP connection timeout
>  2017-09-02 21:29:25 INFO: TCP connection timeout
>  2017-09-02 21:29:36 INFO: connect to s.youtube.com:443
>  2017-09-02 21:29:36 INFO: connect to www.youtube.com:443
>  2017-09-02 21:29:36 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:29:54 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:30:37 INFO: TCP connection timeout
>  2017-09-02 21:30:43 INFO: TCP connection timeout
>  2017-09-02 21:31:45 INFO: connect to s.youtube.com:443
>  2017-09-02 21:31:45 INFO: connect to www.youtube.com:443
>  2017-09-02 21:31:45 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:31:47 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:32:30 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:32:48 INFO: TCP connection timeout
>  2017-09-02 21:33:18 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:33:34 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:33:37 INFO: TCP connection timeout
>  2017-09-02 21:33:49 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
>  2017-09-02 21:34:05 INFO: connect to r2---sn-a5mlrn7l.googlevideo.com:443
> 

============Chinese description of the issue===========

在VPS上配置了kcptun后, 在SSR设置中新建了一个专门连接kcptun端口的服务器配置, 使用新设置**可以通过kcptun连接VPS**, 但是速度**比不使用时要慢**:

> 在YouTube上测试发现不使用Kcptun的速度约为2000Kbps-3000Kbps,
> 使用后速度约为1000Kbps-1600Kbps
>
>使用fast.com测速也是使用kcptun的情况比不使用的情况要慢很多
>
>在设置中打开和关闭`使用UDP中继`对速度没有影响

相关设置如下:

<img width="702" alt="2017-09-02 21 11 23" src="https://user-images.githubusercontent.com/7611912/29995941-9f9000de-9027-11e7-9ef7-9c9b9be68d51.png">

![2017-09-02 21 22 49](https://user-images.githubusercontent.com/7611912/29995945-a0253bc2-9027-11e7-9cc0-6265598638f6.png)

<img width="640" alt="2017-09-02 21 13 06" src="https://user-images.githubusercontent.com/7611912/29995943-9fbfc80a-9027-11e7-881e-f54cb95c4aa3.png">

![2017-09-02 21 15 08](https://user-images.githubusercontent.com/7611912/29995944-9fd22b76-9027-11e7-8269-6abe536e336e.png)

![2017-09-02 21 15 16](https://user-images.githubusercontent.com/7611912/29995942-9fbf1702-9027-11e7-80cd-fa0308d7066f.png)

麻烦看一下,是设置的有问题吗? 我是参考了https://github.com/shadowsocks/ShadowsocksX-NG/issues/373 这个问题的设置

**Comment by sdsy888** [comment]
补充说明: 使用普通SSR+命令行kcptun加速的最终速度,与普通SSR相当, 均为2000+Kpbs (使用shadowsocksx-ng中自带的kcptun速度则会慢两到三倍.)

**Comment by xgz123** [comment]
me too。擦
