### ISSUE TITLE
app is mounting itself?

### ISSUE THREAD

**Issue by pc9527** [shadowsocks/ShadowsocksX-NG#478]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6
- Shadowsocksx-NG 1.5.1

**Expected behavior:**

N/A

**Actual behavior:**

When I `df -h` I got following line:
/Users/xxx/Downloads/ShadowsocksX-NG.app 112Gi 76Gi 35Gi 69% 2167782 4292799497 0% /private/var/folders/nd/rqn0fxdx0413f_whcnp3qxbm2000gn/T/AppTranslocation/82D21EB2-5EC2-40A8-8EB2-0E0783F8C581

Is this mounting supposed to be normal?

**Steps to reproduce:**

NA

**How often does this happen?**

NA
**ss-local.log**

NA

**Application log**

**Crash Log**

NA

**Comment by qiuyuzhou** [comment]
No.

**Comment by gMan1990** [comment]
@qiuyuzhou how         move to application folder?
