### ISSUE TITLE
No more rc4 encryption?

### ISSUE THREAD

**Issue by Nebelwerfer-G** [shadowsocks/ShadowsocksX-NG#479]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6
- Shadowsocksx-NG 1.5.1

**Expected behavior:**

Find out all rc4 encryption gone. Only have aes and camellia left, while can find them exists in older (1.3.2 or probably older) version.
A bunch of servers I'm using are still using rc4 or rc4-md5 encryption. This is not a vent of complant, I just need a explaination for removing rc4 encryption.

**Actual behavior:**

N/A

**Steps to reproduce:**

N/A

**How often does this happen?**

N/A

**Comment by qiuyuzhou** [comment]
Scroll down the list.
