### ISSUE TITLE
用快捷键控制开关和模式切换？

### ISSUE THREAD

**Issue by clavichord93** [shadowsocks/ShadowsocksX-NG#48]
在没有白名单支持的情况下，平时用的时候经常进行开关，可否加入脚本支持来支持Alfred的Workflow？

**Comment by qiuyuzhou** [comment]
你是想用快捷键切换pac和全局模式吗？

**Comment by clavichord93** [comment]
不是pac和全局，是“是否开启Shadowsocks”

**Comment by clavichord93** [comment]
用Apple Script或者快捷键都可以

**Comment by omaidb** [comment]
@qiuyuzhou  代理模式的pac自动模式和全局模式我都理解，手动模式是什么情况?

**Comment by rizwankce** [comment]
Added support in this [PR](https://github.com/shadowsocks/ShadowsocksX-NG/pull/206)
