### ISSUE TITLE
海外用户如何使用比较合理

### ISSUE THREAD

**Issue by 0x5e** [shadowsocks/ShadowsocksX-NG#483]
GFW List 没有关闭选项，清空GFW List URL也是无效的，求一个优雅的选择性翻墙回国的姿势：）

**Comment by J-Liu** [comment]
墙内买个阿里云，然后全局模式欢迎你

**Comment by 0x5e** [comment]
不想全局模式，我需要访问一些英国网站，还要回国绕一下- -ll

**Comment by J-Liu** [comment]
你在墙外，还访问不了英国网站？

**Comment by Chandler-Lu** [comment]
用ssr for mac的回国模式

**Comment by 0x5e** [comment]
@J-Liu 我是希望能同时访问到国内和国外，而不是访问国外的时候关代理，访问国内再开代理，这样子

@Chandler-Lu 谢谢，我试一下

**Comment by whlsxl** [comment]
有个`proxy back China` 模式 在`ALC Mode`里 你试试

**Comment by yangfeicheung** [comment]
您好，您可以参考下我改的这个，其中有一个海外模式，就是专门给海外用的：

https://github.com/yangfeicheung/Shadowsocks-X

选择留学生模式（oversea mode） 然后搭配一个国内的server就行了

**Comment by 0x5e** [comment]
谢谢！不过我已经回来了用不上了。。😅

**Comment by yangfeicheung** [comment]
@0x5e 哈哈，ok，回来不是还要翻回去嘛,shit happens all the time

**Comment by 0x5e** [comment]
:-)

**Comment by naoyeye** [comment]
@yangfeicheung 分享给海外的朋友了，国内 ssr 服务器要做什么配置吗？

**Comment by J-Liu** [comment]
@yangfeicheung 你可不可以把你做的那个功能merge进来啊？

**Comment by yangfeicheung** [comment]
@J-Liu  已经merge到这个版本了， 您可以直接在这里下载使用，并且已经添加了高可用性模式：

https://github.com/yangfeicheung/Shadowsocks-X/releases

**Comment by yangfeicheung** [comment]
@naoyeye 暂时还不支持ssr，ss暂时尚未发现被大面积cut off

**Comment by laomms** [comment]
回国模式只有MAC版吗？ windows版的有没有。

**Comment by yangfeicheung** [comment]
@laomms 
You can use global mode on windows, same effect, download windows version here:
[windows version](https://www.sednax.com/download.php)

**Comment by laomms** [comment]
我在国外，global mode可以翻墙回国，但是google等反而上不了，能不能实现只有国内IP才经过ss，本地的网络还是保存不变。

**Comment by yangfeicheung** [comment]
@laomms  I would fix this in the next release,please wait
