### ISSUE TITLE
Hard to detect & recognize the QR code correctly with the additional text on it

### ISSUE THREAD

**Issue by timothyqiu** [shadowsocks/ShadowsocksX-NG#484]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6
- Shadowsocksx-NG 1.6.0 (1)
- Shadowsocks 4.1.8 (Android Version)

**Steps to reproduce:**

1. Select a server profile in the servers menu
2. Click "Show QR Code For Current Server" menu item to show the QR Code window
  A. Click "Scan QR Code From Screen" menu item to scan the QR code
  B. Use the Android version to scan the QR code

**Expected behavior:**

A: SSX-NG detects the QR code and adds a duplicated server profile.

B: Android version detects the QR code and adds the server profile to the list.

**Actual behavior:**

A: SSX-NG can't detect any QR code on screen.

B: It's hard to get the QR code scanned and recognized as a server profile correctly.

**How often does this happen?**

I have three different server profiles, and for each profile I tried 10 times.

"Scan QR Code From Screen" can never detect the QR code in QR Code window.
(30/30 failures)

Scan the QR code with the Android version:
* For one of the three server profiles, the QR code can be detected easily and recognized correctly.
* For the other two server profiles
    * It is very hard to get the scanner to detect the QR code. I have to try different poses, zoom and tilt the camera randomly for a few seconds every time.
    * After the QR code gets detected, most of the time, the App consider the scanned result invalid. The QR code gets recognized correctly only twice.

(20/30 hard to detect, 18/30 recognize failures)

---

Then I modified 1.6.0, removing the "Shadowsocks-NG SIP002" text from the QR code. Everything works fine. If I move the text around, it sometime works and sometimes not.

So I believe it's the text that makes the QR code hard to detect and hard to be recognized correctly. The error correction mechanism of QR code is limited, we should prefer "reliable QR code" to "beautiful QR code".

**Comment by qiuyuzhou** [comment]
Maybe we could remove "Shadowsocks-NG" and keep the "SIP002" or "Legacy".
