### ISSUE TITLE
最近几个版本，都无法正常工作

### ISSUE THREAD

**Issue by ugist** [shadowsocks/ShadowsocksX-NG#485]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 (16G29)
- Shadowsocksx-NG 1.5.0 1.5.1 & 1.6.0

**默认	09:33:30.275816 +0800	ShadowsocksX-NG	Start ss-local failed.**
默认	09:33:30.342868 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
默认	09:33:30.409013 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
**默认	09:33:30.476178 +0800	ShadowsocksX-NG	Start ss-local failed.**
默认	09:33:30.543109 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
默认	09:33:30.609079 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	09:33:30.609819 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	09:33:30.642102 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [685] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [707] (3,0)
默认	09:33:30.643482 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [685] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [707] (3,0)
默认	09:33:30.645855 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [685] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [707] (3,0)
默认	09:33:30.646962 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [685] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [707] (3,0)
默认	09:33:30.649703 +0800	ShadowsocksX-NG	pac proxy set to auto

**Comment by gnostr** [comment]
建议把ss完全刪除，重新安裝1.6
1.6解決了我mac一直不能用ng的问题

**Comment by ugist** [comment]
@gnostr 早就试过完全删除，包括 `~/Library` 下的配置文件信息，还是失败。

**Comment by genius001** [comment]
你是中国移动用户吗？

**Comment by ugist** [comment]
@genius001 不是，`09:33:30.275816 +0800	ShadowsocksX-NG	Start ss-local failed.`

**Comment by Liyp625** [comment]
我的也是ss-local启动失败，https://lvii.gitbooks.io/outman/content/ss.mac.html，旧版 2.6.3 shadowscoks 可以使用

**Comment by colordove** [comment]
我的卸载1.5.1安装1.6.1版本后可以用了。

**Comment by Ltre** [comment]
@colordove 你的系统版本多少，我的OSX10.11, 卸载了1.5.1的，但1.6.1的还是不行

**Comment by colordove** [comment]
@Ltre 10.13

**Comment by Ltre** [comment]
@colordove 系统没提示我升级到OSX 10.13，咋升级来着，刚入手macbook不久，不太熟悉

**Comment by yangfeicheung** [comment]
试试这个版本哦，high sierra没问题的，us app store也可以下载：

https://github.com/yangfeicheung/Shadowsocks-X

![image](https://user-images.githubusercontent.com/33145750/34025335-3e176900-e18a-11e7-8d6e-2ad6b64942f6.png)
