### ISSUE TITLE
突然无法使用

### ISSUE THREAD

**Issue by ifreyr** [shadowsocks/ShadowsocksX-NG#486]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 
- Shadowsocksx-NG 1.6

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`

default	10:59:27.133656 +0800	Console	[0x7fe9fc8c2200] Created session
default	10:59:27.134018 +0800	Console	[0x7fe9fc8c2200] Decoding: C0 0x002A0027 0x0006354A 0x11111100 0x00000000 766
default	10:59:27.134044 +0800	Console	[0x7fe9fc8c2200] Options: 42x39 [FFFFFFFF,FFFFFFFF] 0001D060
default	10:59:27.134117 +0800	Console	[0x7fe9fc8c2200] Decoding completed without errors
default	10:59:27.134790 +0800	Console	[0x7fe9fc8c2200] Releasing session
default	10:59:27.892678 +0800	iTerm2	File descriptor server exited with status 0
default	10:59:29.615091 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	10:59:29.615367 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
default	10:59:29.615793 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	10:59:29.626177 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
error	10:59:33.907665 +0800	helpd	NSURLConnection finished with error - code -1001
default	10:59:33.923081 +0800	helpd	TIC TCP Conn Cancel [74:0x7fe9cd6ee8d0]
error	10:59:33.923297 +0800	helpd	HTTP load failed (error code: -999 [1:89])
default	10:59:36.769040 +0800	CalendarAgent	TIC TCP Conn Event [20:0x7fb1bcf35dc0]: 2 Err(0)
error	10:59:36.769174 +0800	CalendarAgent	TIC TCP Conn Missing Error [20:0x7fb1bcf35dc0]: Generating 3:-9806
default	10:59:36.769214 +0800	CalendarAgent	TIC TCP Conn Cancel [20:0x7fb1bcf35dc0]
default	10:59:36.769316 +0800	CalendarAgent	TIC TCP Conn Destroyed [20:0x7fb1bcf35dc0]
default	10:59:36.769673 +0800	CalendarAgent	NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9806)
error	10:59:36.769840 +0800	CalendarAgent	HTTP load failed (error code: -1200 [3:-9806])
error	10:59:36.769972 +0800	CalendarAgent	NSURLConnection finished with error - code -1200
default	10:59:36.771033 +0800	CalendarAgent	[com.apple.calendar.store.log.caldav.queue.producer] [ ***** context WILL SAVE notification -[CalDAVChangeRequestsProducer managedObjectContextWillSave:] *****]
default	10:59:36.772091 +0800	CalendarAgent	[com.apple.calendar.store.log.caldav.queue.producer] [Change request production initiated from: (
	0   CalendarPersistence                 0x00007fff9afdeabd -[CalDAVChangeRequestsProducer managedObjectContextWillSave:] + 335
	1   CoreFoundation                      0x00007fff90f7145c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	2   CoreFoundation                      0x00007fff90f7135b _CFXRegistrationPost + 427
	3   CoreFoundation                      0x00007fff90f710c2 ___CFXNotificationPost_block_invoke + 50
	4   CoreFoundation                      0x00007fff90f2e523 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1827
	5   CoreFoundation                      0x00007fff90f2d55c _CFXNotificationPost + 604
	6   Foundation                          0x00007fff92952677 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	7   CoreData                            0x00007fff90b71d81 -[NSManagedObjectContext save:] + 513
	8   CalendarPersistence                 0x00007fff9afdb219 -[CalManagedObjectContext save:] + 71
	9   CalendarPersistence                 0x00007fff9b11cbec -[CalManagedObjectContext saveIfContextHasChanges] + 63
	10  CalendarAgent                       0x00007fff9aeb6240 -[CalAgentAPSConnectionManager _sendAllSubscriptionRequestsForPrincipal:forDevelopment:] + 2058
	11  CalendarAgent                       0x00007fff9aeb5599 __50-[CalAgentAPSConnectionManager _registerAllTopics]_block_invoke + 674
	12  CalendarAgent                       0x00007fff9aeb4fa9 -[CalAgentAPSConnectionManager _registerAllTopics] + 1676
	13  libdispatch.dylib                   0x00007fffa66a58fc _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00007fffa66baa16 _dispatch_continuation_pop + 533
	15  libdispatch.dylib                   0x00007fffa66b0a6c _dispatch_source_latch_and_call + 194
	16  libdispatch.dylib                   0x00007fffa66a813b _dispatch_source_invoke + 1248
	17  libdispatch.dylib                   0x00007fffa66bb7db _dispatch_queue_serial_drain + 443
	18  libdispatch.dylib                   0x00007fffa66ae306 _dispatch_queue_invoke + 1046
	19  libdispatch.dylib                   0x00007fffa66a76b5 _dispatch_root_queue_drain + 476
	20  libdispatch.dylib                   0x00007fffa66a748c _dispatch_worker_thread3 + 99
	21  libsystem_pthread.dylib             0x00007fffa68f45a2 _pthread_wqthread + 1299
	22  libsystem_pthread.dylib             0x00007fffa68f407d start_wqthread + 13
)]
default	10:59:36.772216 +0800	CalendarAgent	[com.apple.calendar.store.log.caldav.queue.producer] [No change requests were inserted]
default	10:59:36.773006 +0800	UserEventAgent	Unregistered XPC Activity: com.apple.iCal.APSSubscriptionRefresh.x-coredata://43B3117A-F2B4-4932-A6E2-F1514F24786F/CalDAVPrincipal/p6
default	10:59:36.773543 +0800	UserEventAgent	SUBMITTING: <private>
default	10:59:36.773518 +0800	DuetHeuristic-BM	CANCELED: <private>!
default	10:59:36.773634 +0800	UserEventAgent	Registered XPC Activity: com.apple.iCal.APSSubscriptionRefresh.x-coredata://43B3117A-F2B4-4932-A6E2-F1514F24786F/CalDAVPrincipal/p6
default	10:59:36.773806 +0800	DuetHeuristic-BM	Submitted Activity: <private>
default	10:59:36.774057 +0800	DuetHeuristic-BM	Activity <private>: Optimal Score 0.6726 at <private> (Valid Until: <private>)
default	10:59:36.774957 +0800	CalendarAgent	ApplePushService: <APSConnection: 0x7fb1bcf2b4d0> setEnabledTopics (
    "com.me.cal"
) ignoredTopics (
) opportunisticTopics (
) sendToDaemon: YES

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by genius001** [comment]
你是中国移动用户吗？

**Comment by ifreyr** [comment]
@genius001 家里网络是联通的，之前一直1.5没有问题，现在1.5， 1.6都不能用，连不上

**Comment by lsj731965675** [comment]
我也是突然上不了网

**Comment by yangfeicheung** [comment]
sierra的最近好像问题比较多，试试这个版本吧，high sierra也没问题的：

https://github.com/yangfeicheung/Shadowsocks-X
