### ISSUE TITLE
Mac 平台下by pass proxy 老是被重置

### ISSUE THREAD

**Issue by zjffdu** [shadowsocks/ShadowsocksX-NG#494]
**System and Shadowsocksx-NG version:**

- macOS 10.11

Mac 平台下只要切换 server，by pass proxy就会被重置到 127.0.0.1, localhost. 我需要加一些host到 by pass proxy，但每次都会被重置

![image](https://user-images.githubusercontent.com/164491/30424786-a1352264-990c-11e7-898b-250ae9f29c83.png)

**Comment by Batyrj** [comment]
hi there, is there any solution found?
