### ISSUE TITLE
macOS 10.12.6的ShadowsocksX-NG无法使用

### ISSUE THREAD

**Issue by Liyp625** [shadowsocks/ShadowsocksX-NG#495]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 (16G29)
- Shadowsocksx-NG 1.6.0

**Expected behavior:**

(N/A for feature requests)

**Actual behavior:**

打开ShadowsocksX-NG后，ss-local和privoxy都启动失败，无法正常使用，代理服务器地址win下可用。

**Steps to reproduce:**

1、启动ShadowsocksX-NG软件
2、点击关闭Shadowsocks
3、点击打开Shadowsocks

**How often does this happen?**

最近一直都是。

**ss-local.log**

无法生成日志。

**Application log**

默认	19:51:30.392936 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
默认	19:51:30.460811 +0800	ShadowsocksX-NG	Start privoxy failed.
默认	19:51:30.528358 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	19:51:30.528746 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	19:51:30.570726 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2719] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2718] (3,0)
默认	19:51:30.572491 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2719] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2718] (3,0)
默认	19:51:30.575641 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2719] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2718] (3,0)
默认	19:51:30.576511 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2719] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2718] (3,0)
默认	19:51:30.579761 +0800	ShadowsocksX-NG	pac proxy set to off
默认	19:51:59.676542 +0800	ShadowsocksX-NG	Start ss-local failed.
默认	19:51:59.744408 +0800	ShadowsocksX-NG	Start privoxy failed.
默认	19:51:59.811154 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	19:51:59.811798 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	19:51:59.838863 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2719] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2731] (3,0)
默认	19:51:59.840309 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2719] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2731] (3,0)
默认	19:51:59.843689 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2719] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2731] (3,0)
默认	19:51:59.844562 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [2719] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [2731] (3,0)
默认	19:51:59.847899 +0800	ShadowsocksX-NG	pac proxy set to auto

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by loveanao** [comment]
OS重装过吧，我目前一切正常，10.12.6+1.6NG

**Comment by Zhouchuanwen** [comment]
NG1.5.1， MAC OS X 10.11.6 也用不了。。。

**Comment by Liyp625** [comment]
@loveanao 没有重装过系统😂

**Comment by Liyp625** [comment]
@Zhouchuanwen 这个旧版的的确可用，谢谢啊，为啥新版的就不行呢，之前还能用来着

**Comment by tennessine** [comment]
下载了v1.6.1 可以翻墙了

**Comment by Liyp625** [comment]
@tennessine 刚试了在我的本上不能用，还是老老实实用旧版 2.6.3吧，然后手动更新 PAC 文件列表 (GFWList)，要base64解密的。

**Comment by LittleStupid** [comment]
我使用2.6.3版本还是不行，我是直接覆盖安装的
