### ISSUE TITLE
能否禁用PAC只针对用户指定的rules工作？

### ISSUE THREAD

**Issue by 016** [shadowsocks/ShadowsocksX-NG#496]
现在程序运行正常，但是Mac系统或者某些程序会自动访问一些地址，有些不需要通过SS，因为没有被Q，现在想禁用PAC或者把PAC变成空白的，然后手动指定需要访问的url

不知道有没有办法编辑或者设置PAC内容？

PS尝试修改为一个错误的网址，但是没有用。

**Comment by 016** [comment]
我尝试在网站挂了一个 aa.com/pac.txt 然后使用空文本，但是无效
有人能提供pac为空的时候的内容格式吗？

谢谢

**Comment by myHXQ** [comment]
加一行输入下面这三个字符就行了
||*
@@表示跳过

这是我的，你可以直接复制粘贴。
! Put user rules line by line in this file.
! See https://adblockplus.org/en/filter-cheatsheet
||*
@@.ali
@@.cn
@@.le
@@126.net
@@163.com
@@1688.com
@@360.com
@@360buyimg.com
@@360doc.com
@@36kr.com
@@36krcdn.com
@@58.com
@@58cdn.c
@@aitaotu
@@amazon.c
@@baidu
@@baydn
@@bdimg
@@bdstatic
@@bilibili
@@bing.com
@@cctv
@@china
@@csdn
@@ctrip
@@dianping.com
@@douban
@@eastday.com
@@ele.me
@@gtimg.com
@@hdslb.c
@@hexun
@@huaxia
@@huanqiu
@@ifeng
@@jchere
@@jd.com
@@jd.hk
@@kugou
@@meiju
@@meituan.com
@@meitulu.com
@@netease
@@pstatp.com
@@qq.com
@@qunar
@@qiyi
@@shanbay
@@shimo.im
@@sina
@@suning.com
@@sohu
@@sougou
@@static.com
@@taobao
@@tenso
@@tianya
@@tmall
@@toutiao.com
@@ttsqgs.com
@@tudou
@@weibo
@@ximalaya
@@xinhuanet
@@xmcdn.c
@@yahoo
@@ykimg.com
@@youdao.com
@@zhaopin.com
@@zhihu

**Comment by 016** [comment]
@myHXQ 有办法让所有内容都不走代理吗？ 然后单条加白名单

**Comment by timothyqiu** [comment]
This can be done in two ways:

* Point your GFW List URL to an empty file, and click "Update PAC from GFW List".
* Or, make `~/.ShadowsocksX-NG/gfwlist.txt` an empty file, click "Edit User Rules For PAC", and then "OK".

This can be verified by checking `~/.ShadowsocksX-NG/gfwlist.js`. The `rules` array on the 6th line should contain your custom rules only (or nothing if you have no custom rules) after you have done.

**Comment by myHXQ** [comment]
@016 pac用户自定义规则加一行输入下面这三个字符就行了，这样就会代理所有内容。
||*

**Comment by myHXQ** [comment]
@016 pac默认跳过的网站可以去修改timothyqiu说的那个文件。

**Comment by myHXQ** [comment]
@@，，，，，两个@@开头是自定义的白名单。

**Comment by 016** [comment]
@timothyqiu I tried the first one, use an empty .txt file in pac url, then click "Update PAC from GFW List" the App shows "Update fail", you can try it yourself.

I will try the second one soon. many thx.

**Comment by 016** [comment]
最终解决了，具体解决方法见下面的link
http://yiilib.com/topic/750/ShadowSocks-NG+%E4%BD%BF%E7%94%A8%E7%99%BD%E5%90%8D%E5%8D%95%E6%A8%A1%E5%BC%8F
最后感谢 各位的帮助。

**Comment by vsp6688** [comment]
> @@，，，，，两个@@开头是自定义的白名单。
受教，非常有用，THANKS
