### ISSUE TITLE
 mac 10.12.6 上用不了

### ISSUE THREAD

**Issue by Criya** [shadowsocks/ShadowsocksX-NG#498]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 
- Shadowsocksx-NG 1.5.1?

**How often does this happen?**

After updating my mac to 12.6.*

**Application log**

 2017-09-21 10:48:40 INFO: initializing ciphers... aes-256-gcm
 2017-09-21 10:48:40 ERROR: bind: Address already in use
 2017-09-21 10:48:40 ERROR: bind() error
 2017-09-21 10:48:50 INFO: initializing ciphers... aes-256-gcm
 2017-09-21 10:48:50 ERROR: bind: Address already in use
 2017-09-21 10:48:50 ERROR: bind() error
 2017-09-21 10:49:00 INFO: initializing ciphers... aes-256-gcm
 2017-09-21 10:49:00 ERROR: bind: Address already in use
 2017-09-21 10:49:00 ERROR: bind() error

**Comment by zwxlovegithub** [comment]
me too。。。。

**Comment by LittleStupid** [comment]
the same with you...

**Comment by sunyongjian** [comment]
我这个连 log 都没有。

**Comment by timothyqiu** [comment]
#469 might be helpful.

**Comment by Criya** [comment]
@timothyqiu 
Ever time i begin the ss, the port 1086 must be used by privoxy and my ss can't work.
And i deleted the "Application Support/ShadowsocksX-NG/privoxy-3.0.26.static/privoxy", my ss worked again cause the port 1086 was used by ss-local. However, after i closed ss , i can't open it again.....

**Comment by Criya** [comment]
@timothyqiu
Now, after i click the shadowsock X-NG's application icon, it doesn't appear on my bar Orz, but port 1086 remains be used by ss-local and it doesn't work Orz

**Comment by Criya** [comment]
OWWW, after i reinstalled the ss,  the port 1086 is used by ss-local instead of privoxy, and ss service  work normally

**Comment by timothyqiu** [comment]
Try to configure them properly. Use two different ports for that two different services.

If the "privoxy" you mentioned is the one bundled with SSX-NG, you can change the port in the "HTTP" section of Preferences window.

p.s. If you have solved your problem, it'll be better to close the issue instead of changing the issue title.

**Comment by morfei1988** [comment]
@timothyqiu 您好，我遇到了同样的问题，在升级OS X之后SS无法正常使用，我尝试过更改端口至1080，也尝试过更改权限，均无法解决问题。我又是计算机小白，不知道如何提取log，如果可以的话还请您以中文分享操作方法
