### ISSUE TITLE
能解释下手动模式是做什么的么？？？

### ISSUE THREAD

**Issue by simonchenxy** [shadowsocks/ShadowsocksX-NG#501]
另外  编辑PAC 用户自定义规则  之后应该如何操作？重启软件，还是关闭shadowsocks然后重新打开？

重启之后规则是立即生效么？为什么我每次都要等好久呢～～～～

**Comment by timothyqiu** [comment]
<table>
<thead>
<tr><th>Shadowsocks</th><th>Mode</th><th><code>ss-local</code> (SOCKS5&nbsp;Proxy)</th><th>PAC Server</th><th>macOS System Proxy</th></tr>
</thead>
<tbody>
<tr><th rowspan="3">On</th><th>PAC Auto</th><td>✔</td><td>✔</td><td>Use the PAC file to config</td></tr>
<tr><th>Global</th><td>✔</td><td>✘</td><td>Use the SOCKS5 proxy</td></tr>
<tr><th>Manual</th><td>✔</td><td>✘</td><td>No proxy</td></tr>
<tr><th>Off</th><th>(Any)</th><td>✘</td><td>✘</td><td>No proxy</td></tr>
</tbody>
</table>

p.s. The on/off of HTTP proxy server is controlled separately in the Preference Window.

**Comment by simonxinyuan** [comment]
@timothyqiu 那关于编辑用户自定义规则呢？如何生效？

**Comment by timothyqiu** [comment]
The PAC content served by SSX-NG's PAC server updates almost immediately. But client Apps use their own policy of caching PAC content or even caching PAC solving results, which is out of the control of SSX-NG.

So, please check the document of your client App (e.g. Browser) to find out how it caches PAC. That'll solve your problem.

---

Maybe changing the URL every time the PAC content updates will help the client Apps to invalidate their caches, but I'm not sure. (The Windows version does append the update time to the PAC URL as query parameter though) cc @qiuyuzhou

**Comment by simonxinyuan** [comment]
@timothyqiu thank you for your answer. But why do not we talk about it in Chinese? 
And my client app is ShadowsocksX-NG1.6.1

**Comment by macron77** [comment]
@simonchenxy Not only Chinese are facing "the GFW Problem", so keeping conversations in English may helps other users to unterstand issues better.

**Comment by simonchenxy** [comment]
@macron77  所以 这个手动模式到底是怎么用呢～～～

**Comment by timothyqiu** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/blob/b31452e984f48d831fc8a913d8f8a6a2bf972911/README.md#L61-L62

**Comment by qzi** [comment]
> Shadowsocks	Mode	`ss-local` (SOCKS5 Proxy)	PAC Server	macOS System Proxy
> On	PAC Auto	✔	✔	Use the PAC file to config
> Global	✔	✘	Use the SOCKS5 proxy
> Manual	✔	✘	No proxy
> Off	(Any)	✘	✘	No proxy
> p.s. The on/off of HTTP proxy server is controlled separately in the Preference Window.

mannual mode 试了下可以用socks5代理
