### ISSUE TITLE
无法使用kcptun的ipv6

### ISSUE THREAD

**Issue by great15** [shadowsocks/ShadowsocksX-NG#502]
如题，普通ipv6正常。

**Comment by ScaldingBlood** [comment]
遇到同样的问题，相同配置下ipv4可以使用kcp。
ipv6下可以远端可以找到本机v6地址，但是出现broken pipe。
在另一台ubuntu机器上我使用ipv6+kcp可以正常使用。

**Comment by great15** [comment]
@ScaldingBlood 问题解决了，绑定个域名就行了，不能直接用原始ipv6地址。close issue.

**Comment by LukeLu0415** [comment]
@great15 你好，我也遇到了ipv6不能加速的问题，请问如何绑定域名

**Comment by great15** [comment]
@LukeLu0415 https://help.aliyun.com/knowledge_detail/39813.html
你可以参考一下这个。
好像很多人不知道ipv6问题可以通过绑定域名解决，为了便于有人能搜索到，所以暂时把这个issue打开了。
