### ISSUE TITLE
Not found valid qrcode of shadowsocks profile.

### ISSUE THREAD

**Issue by lyuxxx** [shadowsocks/ShadowsocksX-NG#503]
- macOS 10.12.6
- Shadowsocksx-NG 1.6.1(1)

扫描屏幕上的二维码一直提示这个

**Comment by kind03** [comment]
same here

**Comment by heliu0328** [comment]
1.6.1的版本只有浏览器里边弹出层的二维码不能扫描。直接选择二维码在新窗口打开的话可以扫描

**Comment by kun-zhou** [comment]
same issue here. running 1.6.1

**Comment by Basim-Alamuddin** [comment]
same issue here. running 1.7.0

**Comment by AndyChen2005121** [comment]
I feel the same too on 1.7.0, but it works fine on legacy 1.3.1

**Comment by yangfeicheung** [comment]
In case anyone interested, you can try this one:

https://github.com/yangfeicheung/Shadowsocks-X
