### ISSUE TITLE
ShadowsocksX-NG 如何设置上行代理

### ISSUE THREAD

**Issue by syhily** [shadowsocks/ShadowsocksX-NG#505]
最新的 shadowsocks-windows 版本已经支持对 Shadowsocks 客户端本身设置上行代理，使得 ss-local 可以走 HTTP 或者 Socks 代理，再去访问实际的远程 ss-server。

但是在当前的 macOS 客户端上并没有看到此类功能，请问是还不支持么？
或者有无方式可以实现此类需求。

**Comment by wonderffee** [comment]
也需要这个功能，有跳板需求

**Comment by syhily** [comment]
@wonderffee 我现在通过 `brew install proxychains-ng shadowsocks-libev`
然后 proxychains4 -f proxychains.conf ss-local -c ss-local-config.json 的方式启动代理，可以从公司内外走跳板访问外网。
后面基于 cow 修改定制了一下，现在主要用cow，虽然没有GUI，但是自己通过修改脚本实现了大部分功能。

**Comment by wonderffee** [comment]
我试过用Proxifier，不知道为啥不行。说是跳板其实就是朋友给了一个ssh访问可以在本地生成socks5端口。我就是想把ss的网络访问走这个端口，也就是本机 --> ssx-NG -- 本地socks5端口 --> 互联网，跟你需求的情况类似吧？
你这个我也想尝试一下，但是不知道ss-local路径在哪里，以及你的conf和json是怎么详细配置的，能否说明一下呢？

**Comment by wonderffee** [comment]
感觉上你是没有用上ShadowsocksX-NG，而是用shadowsocks命令行弄的？

**Comment by syhily** [comment]
我看了 ShadowsocksX-NG 的源码，它的核心就是调用 ss-local，所以你要实现上行，就意味着要去修改这块调用的逻辑，在 macOS 上，类似 proxychains-ng 的方式，感觉蛮麻烦。
后面发现 cow 和定制起来方便，就放弃 ShadowsocksX-NG 了。
