### ISSUE TITLE
希望增加负载均衡和服务器测速功能

### ISSUE THREAD

**Issue by seagle0128** [shadowsocks/ShadowsocksX-NG#507]
希望增加负载均衡和服务器测速功能，就像Windows版本一样。手动切换服务器非常浪费时间，自动切换并负载均衡很有效率。谢谢！

**Comment by ElfSundae** [comment]
能加个服务器测速就感激涕零了.. 其他的不奢望

**Comment by seagle0128** [comment]
Windows 版本功能相当齐全啊，不能歧视MAC用户吧

**Comment by seagle0128** [comment]
为什么close了呢？
