### ISSUE TITLE
Just does not work with L2TP, but Wi-Fi or PPPOE is OK.

### ISSUE THREAD

**Issue by Oborozukiyo** [shadowsocks/ShadowsocksX-NG#509]
- macOS 10.12.6
- Shadowsocksx-NG 1.6.1

Does not work with L2TP even if using the Global Mode,
but it works perfectly with Wi-Fi or PPPOE.

does it support L2TP?

**Comment by Telehub** [comment]
same problem

**Comment by timothyqiu** [comment]
SSX-NG only sets proxy for AirPort, Wi-Fi, and Ethernet profiles currently.

https://github.com/shadowsocks/ShadowsocksX-NG/blob/b31452e984f48d831fc8a913d8f8a6a2bf972911/proxy_conf_helper/main.m#L129-L138

(The `networkServiceKeys` option is not used in the main App.)

As a workaround, you can try to setup the proxy manually: 

* Choose Apple menu > System Preferences, then click Network.
* Select the network service you use in the list. (The L2TP VPN in this case)
* Click Advanced, then click Proxies.
* Select Auto Proxy Discovery or SOCKS Proxy, and fill in the corresponding URL.
