### ISSUE TITLE
Is there anyway to edit PAC file manually?

### ISSUE THREAD

**Issue by 7nights** [shadowsocks/ShadowsocksX-NG#510]
On windows there is a pac file on local disk in the same folder with shadowsocks, but I can't find any pac file with ShadowsocksX-NG. It seems you can only add some rules with the 'Edit User Rules For Pac...' function. Is there any possibility to edit PAC file manually?

**Comment by z3oc** [comment]
Was having the same problem. You can find it in the '.ShadowsocksX-NG' directory, same pattern as the original ShadowsocksX
