### ISSUE TITLE
全局模式不能打开google

### ISSUE THREAD

**Issue by tiny1990** [shadowsocks/ShadowsocksX-NG#512]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 (16E????)
- Shadowsocksx-NG 1.6.1

**Expected behavior:**

全局模式，不能翻墙

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

1. 启动全局模式
2. 关闭chrome 插件 不能上外网，能上国内
3. 启动chrome 插件可以上外网

有时需要mac 全局外网，发现启动并不能使用，和之前shadowsX又冲突？ng的配置保存在哪，我删除重新下载还是使用了 之前的配置，难道是配置冲突？

刚测试 safari可以 chrome不行，是协议格式不太一样？

**Comment by tiny1990** [comment]
@qinyuhang

**Comment by morfei1988** [comment]
我也是macOS 10.12.6 (16E????)
Shadowsocksx-NG 1.6.1

SS一打开什么都上不去。。。OS自动更新后不知道出现了什么问题

**Comment by tiny1990** [comment]
@morfei1988  你可以看看 mac 网络中代理的设置是不是有问题，我的是chrome要装插件，全局chrone无效，其他可以用 好奇怪

**Comment by tiny1990** [comment]
问题确认 装了swtichomg，设置了chrome原因，有问题童鞋看看chrome 系统设置就知道了
