### ISSUE TITLE
Kcptun 和普通模式切换问题

### ISSUE THREAD

**Issue by soxfmr** [shadowsocks/ShadowsocksX-NG#513]
版本：
- Shadowsocksx-NG 1.6.1

模式：
- 普通模式：不开启 Kcptun，与 Shadowsocks 服务器直连
- Kcptun 模式：开启 Kcptun

当开启 Kcptun 时，修改 Kcptun 端口，同时普通模式的端口也会被自动修改。或者在普通模式下修改端口，Kcptun 端口处的文本框也会被自动更新。

建议不同步两个文本框内容，在网络环境不同时，开启和关闭 Kcptun 都需要修改端口，有点繁琐。

Regard

**Comment by timothyqiu** [comment]
+1

The current version overloads the meaning of `ServerProfile.serverHost` and `ServerProfile.serverPort`. But IMHO, there should be separate host / port fields in `KcptunProfile`.

Also, considering the "Plugin Spec" (SIP003), different plugins now can be managed by `ss-local` itself using a defined & unified interface. (Kcptun added SIP003 support in `v20170718`.) Separating these two options can be a great step toward supporting SIP003.

**Comment by ilovebamboo** [comment]
能不能支持 none 算法
