### ISSUE TITLE
SS1.5.1在OS X10.12.6上无法工作

### ISSUE THREAD

**Issue by morfei1988** [shadowsocks/ShadowsocksX-NG#515]
我尝试过在偏好设置里更改端口至sock5端口至1080，尝试过在终端里输入命令更改权限，尝试过完整删除后重新安装（1.5.1和1.6.1版本）现在真的无计可施了，还希望各位大神帮忙。
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 (16E????)
- Shadowsocksx-NG 1.5.1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

Process:               ss-local [1696]
Path:                  /Applications/ShadowsocksX-NG.app/Contents/Resources/ss-local
Identifier:            ss-local
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        bash [1690]
Responsible:           ss-local [1696]
User ID:               501

Date/Time:             2017-10-06 09:22:33.037 +0800
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        03FA404F-7FD9-85AE-8613-D56F2669F3F8

Time Awake Since Boot: 7000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: */libev.4.dylib
  Referenced from: /Applications/ShadowsocksX-NG.app/Contents/Resources/ss-local
  Reason: image not found

Binary Images:
       0x10fc2e000 -        0x10fc4cff3 +ss-local (0) <FE894517-4A16-3D5B-9394-72859184FAEF> /Applications/ShadowsocksX-NG.app/Contents/Resources/ss-local
       0x114ff3000 -        0x115030dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fffa9e90000 -     0x7fffa9e91ffb  libSystem.B.dylib (1238.60.2) <F18AC1E7-C6F1-34B1-8069-BE571B3231D4> /usr/lib/libSystem.B.dylib

If the app crashes and pop up a crash log, please copy and paste here

**Comment by tennessine** [comment]
shadowsocks的服务不靠谱，我自己搭建了

**Comment by zcoding** [comment]
+1

**Comment by Criya** [comment]
偏好设置那里设置，自动获取就好了。
将HTTP和Socks5分别设置为1080和1086
`lsof -n -P -sTCP:LISTEN -iTCP:1080`
`lsof -n -P -sTCP:LISTEN -iTCP:1086`
再看看这个结果

**Comment by morfei1988** [comment]
@Criya 
  报告首长，1.5.1的偏好设置里没有自动获取啊，端口重设之后打开终端是这个样子
liuweihaodeMacBook:~ liuweihao$ lsof -n -P -sTCP:LISTEN -iTCP:1080
COMMAND  PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
privoxy 4176 liuweihao    3u  IPv4 0xc70c812372bb2c65      0t0  TCP 127.0.0.1:1080 (LISTEN)
liuweihaodeMacBook:~ liuweihao$ lsof -n -P -sTCP:LISTEN -iTCP:1086
liuweihaodeMacBook:~ liuweihao$ lsof -n -P -sTCP:LISTEN -iTCP:1086
liuweihaodeMacBook:~ liuweihao$ lsof -n -P -sTCP:LISTEN -iTCP:1086

**Comment by morfei1988** [comment]
@Criya 
  我反向设置后变成了这样，但是依然不能正常链接
bogon:~ liuweihao$ lsof -n -P -sTCP:LISTEN -iTCP:1086
COMMAND  PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
privoxy 4333 liuweihao    3u  IPv4 0xc70c812368839c65      0t0  TCP 127.0.0.1:1086 (LISTEN)
bogon:~ liuweihao$ lsof -n -P -sTCP:LISTEN -iTCP:1080
COMMAND   PID      USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
ss-local 4349 liuweihao    8u  IPv4 0xc70c812368837885      0t0  TCP 127.0.0.1:1080 (LISTEN)

**Comment by Criya** [comment]
@Criya
不是ss的偏好设置，是系统网络那里的，打开ss后你去看看那有没获取到
<img width="516" alt="2017-10-09 17 58 47" src="https://user-images.githubusercontent.com/23690459/31333161-9d58f96c-acae-11e7-8edd-aba744ff087f.png">
<img width="554" alt="2017-10-09 17 59 41" src="https://user-images.githubusercontent.com/23690459/31333191-af582412-acae-11e7-9472-2c1af3fc8a51.png">
这两个分别是我现在pac模式和全局模式下的情况
ps：我现在用的是ssr

**Comment by timothyqiu** [comment]
> Dyld Error Message:
Library not loaded: */libev.4.dylib
Referenced from: /Applications/ShadowsocksX-NG.app/Contents/Resources/ss-local
Reason: image not found

I wonder why the crash log shows it's using the `ss-local` from the App Bundle. SSX-NG should be using `~/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local`.

Are you trying to run `ss-local` manually in terminal? It'll fail definitely by design. If not, what's the content of `Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist`?

**Comment by morfei1988** [comment]
@Criya   显示获取到Sock5代理
  代理服务器：127.0.0.1：1080
  要求用户名和密码均为空白
  忽略名单获取到127.0.0.1、localhost

**Comment by morfei1988** [comment]
@timothyqiu 

  您好，我未能在您所说的路径（/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local）上找到ss-local，其路径中只含有“LaunchHelper”文件
  另，未能在Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist找到目标文件。

  最后十分感谢您的帮助，但我并不能阅读英文，通过懂英文的朋友以及谷歌翻译查看您的信息十分费力，如可以的话请使用中文进行交流？
  thanks for your help， but I can not use English talk to you. Help your friends in English and Google Translate to view your information is very laborious, if you can, please use the Chinese to communicate?

**Comment by amboo2** [comment]
@morfei1988 您好，请问这个问题解决了吗？我的情况跟您一模一样，崩溃了T.T

**Comment by morfei1988** [comment]
@amboo2 没有解决，谷歌现在上不去，youtube上不去，yahoo japan的搜索也被屏蔽了。没有VPN的日子真的好难熬。。。

**Comment by morfei1988** [comment]
@tennessine 可否单独联系我如何使用shadowsocks软件连接您搭建的服务器通信？我愿意与您一起承担服务器，云端，虚拟机的租赁费用及由此产生的连带费用。

**Comment by morfei1988** [comment]
@tennessine 我现在连shadowsocks的客户服务中心网页都打不开，钱白交了感觉。

**Comment by Lisupy** [comment]
@tennessine 我现在有一个问题很类似，就是使用PAC模式，每一个请求如果点了更换代理，可以正确翻墙，但是如果没有的话，就一直卡着不动，这个应该是一个bug？@timothyqiu
我现在的解决方法是使用手动模式，chrome+ SwitchyOmega插件来使用，shell的话使用proxychains4来实现代理。
我是从Linux过来的，能够忍受。
