### ISSUE TITLE
PAC模式， ACL模式

### ISSUE THREAD

**Issue by bigbigda** [shadowsocks/ShadowsocksX-NG#519]
- macOS 10.12.6 
- Shadowsocksx-NG 1.4.3

请问：
1 点开显示网速，没有发现任何变化，不知道网速在哪显示？
2 请问PAC自动模式，白名单模式，ACL模式分别有什么区别？  如果是PAC模式，能否补充自己定制的规则（如果是通过编辑PAC用户规则，如何生效，试了一下感觉没有生效），白名单模式的白名单怎么设置

**Comment by bigbigda** [comment]
再补充一点，macOS版本怎么设置为windows版本下对应的 全局模式（绕过局域网与大陆）

**Comment by toptian** [comment]
pac 模式确实没有全部生效，有一部分是生效的。比如这个服务器ip不是大陆的就会生效，如果填入百度的域名，就没有生效。搞得我要糊涂了。。。

**Comment by timothyqiu** [comment]
Blacklisting `baidu.com` does not work because it is whitelisted in GFW List.

In current PAC implementation, _once whitelisted, always whitelisted_, no matter in GFW List or Custom Rules.

**Comment by anticpc** [comment]
ACL类似于升级版的PAC

**Comment by sgricky** [comment]
我也有这个疑问，什么时候是PAC的场景？什么时候是ACL的场景？

**Comment by yangfeicheung** [comment]
1. PAC and ACL are basically doing the same thing, check the url and then decide if this network would be completed via Shadowsocks server.
2. PAC are only supported by browswer, e.g. chrome, firefox, safari, which means local apps on mac wouldn't be able to use PAC mode to deal with things.
3. ACL mode is used by shadowsocks internal function itself, it's integrated into it. But shadowsocks-ng does not support acl currently.

if you want to use ACL mode, you guy could try this app:
https://github.com/yangfeicheung/Shadowsocks-X

**Comment by JacFrak** [comment]
我使用proxifier代理googledrive时，要用acl模式才能生效，查了下貌似acl支持更底层的协议，pac只支持http协议的代理

**Comment by xieqing0428** [comment]
mac客户端使用ACL模式后Proxifier定向转发就失效了, 谷歌搜索好像没有相关回答, 想接个地方问问有没有相同情况的, 打扰了

**Comment by bowencool** [comment]
> mac客户端使用ACL模式后Proxifier定向转发就失效了, 谷歌搜索好像没有相关回答, 想接个地方问问有没有相同情况的, 打扰了

一样的情况，同事的机器就没问题，版本一样，acl地址一样。哭辽

**Comment by anticpc** [comment]
> mac客户端使用ACL模式后Proxifier定向转发就失效了, 谷歌搜索好像没有相关回答, 想接个地方问问有没有相同情况的, 打扰了

mac客户端白名单模式
