### ISSUE TITLE
希望能在ui界面由用户提交直接提交已和谐的地址，然后同步到gfwlist，审核后下发给所有用户

### ISSUE THREAD

**Issue by omaidb** [shadowsocks/ShadowsocksX-NG#52]
希望能在ui界面由用户提交直接提交已和谐的地址，然后同步到gfwlist，审核后下发给所有用户。
前面看到 shadowsocks 作者说无人提交网址，不是无人提交，是提交方式和提交入口太隐蔽，小白根本找不到啊

**Comment by bluefo** [comment]
这是list维护的事，干嘛强加给ss。
