### ISSUE TITLE
用不了咯

### ISSUE THREAD

**Issue by 9crk** [shadowsocks/ShadowsocksX-NG#521]
用不了咯。。。

**Comment by timothyqiu** [comment]
Please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.

**Comment by 9crk** [comment]
说的不是这个软件用不了了。。是shadowsocks官网。。提供的服务器 不行了

**Comment by timothyqiu** [comment]
This project is just a macOS SS client. It has nothing to do with any SS service provider.

If it's a server failure, you should contact the service provider instead.

**Comment by skksdd** [comment]
去问你的服务商, shadowsocks没有所谓官网
这边是shadowsocksX-NG讨论的地方.不出售任何所谓“服务”
如果你分不清楚,请先做一些功课.

**Comment by 9crk** [comment]
@skksdd  shadowsocks.com 不是官网？跟维护者没有半毛钱关系？

**Comment by timothyqiu** [comment]
No, it has nothing to do with the Shadowsocks project although it has the word _shadowsocks_ in the fancy ".com" domain name.

The official site of the Shadowsocks project is [shadowsocks.org](https://shadowsocks.org) (Corresponding repo of the site is https://github.com/shadowsocks/shadowsocks-org).

**Comment by skksdd** [comment]
@timothyqiu 

Thx for your great contribution to ShadowsocksX-NG.

Recently, massive Chinese shadowsocks service providers were in a bad situation where their IP or ports are banned by Chinese ISPs.

As a result, lots of  their customers began to spam their  complaints here and there.

Sorry for all the inconvenience  you're going through.

You have a good day:)
