### ISSUE TITLE
用充了钱，才没几天就没用了？？

### ISSUE THREAD

**Issue by better666** [shadowsocks/ShadowsocksX-NG#522]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by WangYifang** [comment]
2017-10-07 23:47:14 INFO: initializing ciphers... aes-256-cfb
 2017-10-07 23:47:19 ERROR: failed to resolve server name, wait 2 seconds
 2017-10-07 23:47:23 ERROR: failed to resolve server name, wait 4 seconds
 2017-10-07 23:47:31 ERROR: failed to resolve server name, wait 8 seconds
 2017-10-07 23:47:47 ERROR: failed to resolve server name, wait 16 seconds

**Comment by timothyqiu** [comment]
SSX-NG has nothing to do with your account. Please ask your service provider for help.

The log mean that your server hostname can't be resolved. Please check your local DNS settings, use IP instead of domain name, or check if your service provider has any announcements.

**Comment by 9crk** [comment]
目测并非运营商断掉了shadowsocks数据包，而是shadowsocks.com提供的服务器在十九大的压力下不敢顶风作案了。。大家可以自己购买阿里云服务器，并搭建shadowsocks服务器。

**Comment by jessiexcat** [comment]
确定吗？我工作需要用ss翻墙啊！！！！！不然根本工作不了！！！好郁闷，什么时候才重新开启服务器？？

**Comment by timothyqiu** [comment]
@jessiexcat Please ask your service provider for help.

**Comment by 9crk** [comment]
@jessiexcat 买个阿里云 香港服务器 一键搭建自己的ss服务器 先买一个月顶着。
