### ISSUE TITLE
macOS 10.13 正式版不可用

### ISSUE THREAD

**Issue by lmy98129** [shadowsocks/ShadowsocksX-NG#523]
**System and Shadowsocksx-NG version:**

尝试包括更改权限、更改端口等各种方法，
服务器在Windows 10/Android 5.0 上连接正常
在macOS 10.12.6 上连接正常
在macOS 10.13 正式版上，PAC/ Global 在Safari、Chrome下均不可，手动模式未尝试

- macOS 10.13
- Shadowsocksx-NG 1.6.2

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by timothyqiu** [comment]
Please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.

**Comment by timothyqiu** [comment]
I updated my system to 10.13 just now, and SSX-NG works fine after the update. So this might not be an OS update issue, your log will be helpful.

**Comment by onefboy** [comment]
ss-local.log
2017-09-14 22:55:59 INFO: initializing ciphers... rc4-md5

**Comment by CharlesHugh** [comment]
I also have this problem, mac10.13 can not work, iphone normal. shadowsocksX-NG replaced shadowsocksX 2.6.3 can continue to work ...

**Comment by fr0der1c** [comment]
Same here. Not working on macOS 10.13

**Comment by okayz** [comment]
Me too Not Working 10.13

**Comment by PhthonKGB** [comment]
Me too, not working on MacOS High Sierra 10.13.1(17b48)

1.4.1-R8 (4)   can be used

**Comment by hechuangju** [comment]
我的也是～现在用回1.4版本可以正常使用

**Comment by k432ts** [comment]
same here. Using Surge now.

**Comment by Prinsphield** [comment]
+1，no problem in Android phone and ipad. But what is wrong with Mac OS high sierra

**Comment by tony-haibo-zhu** [comment]
+1 , doesn't working fine.

**Comment by geeksu** [comment]
+1，not working

**Comment by paulcarpenter** [comment]
Not working here either.

**Comment by yangfeicheung** [comment]
guys, you can try this one by me, it works fine on high sierra 10.13.2

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by tony-haibo-zhu** [comment]
@yangfeicheung Yeah! That's very nice. And one more question, will it have android version? l feel  shadowsocks native android client is also tough to use .

**Comment by yangfeicheung** [comment]
@tony-haibo-zhu We currently have both mac & win version,ios version would be released soon, for android, you may have to stick to that one, it's not that easy to use, but that's the only option, lol.
If you use iphone, then u have more options

**Comment by byronwind** [comment]
mac10.13.4 ng1.7.1（1） same problem

**Comment by tony-haibo-zhu** [comment]
@byronwind see the comment by @yangfeicheung. That client for ss is very well.

**Comment by yangfeicheung** [comment]
@byronwind   if you failed to connect, you can reach me via my email, I would fix this for you step by step, or you can follow those steps:
[reinstall SSX on mac](https://www.sednax.com/faq-0-cn.php)
