### ISSUE TITLE
被禁了？

### ISSUE THREAD

**Issue by walden1981** [shadowsocks/ShadowsocksX-NG#526]
前一阵用的好好的，突然就又不能用了？我还买了3个账号

**Comment by timothyqiu** [comment]
This App has nothing to do with your account. Please ask your service provider for help.

If your sever is OK, please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.

**Comment by zxf8665905** [comment]
开18da了，很多服务器被墙了。

**Comment by WangYifang** [comment]
楼上“开18da了”啥意思？服务器被墙了过段时间会好吗？

**Comment by zxf8665905** [comment]
@WangYifang 百度“18大”   什么时候好，我也不知道。
