### ISSUE TITLE
ShadowsocksX-NG 无法科学上网

### ISSUE THREAD

**Issue by juaner630** [shadowsocks/ShadowsocksX-NG#532]
**System and Shadowsocksx-NG version:**

- macOS 10.11.6- Shadowsocksx-NG 1.6.1

**Expected behavior:**

**Actual behavior:**

无法使用

**Steps to reproduce:**

N/A 

**How often does this happen?**

前几天我从n8升级到1.6.1然后就再也不行了，降级也不行
不知道为啥，上传不了log
用的是ssr，是这个原因么？之前是好的，手机上现在也能用，应该不是ssr的问题。

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

![Uploading 屏幕快照 2017-10-09 上午8.58.44.png…]()
![Uploading 屏幕快照 2017-10-09 上午8.59.05.png…]()
![Uploading 屏幕快照 2017-10-09 上午8.59.20.png…]()

**Comment by timothyqiu** [comment]
There is no SSR support in this project.

**Comment by juaner630** [comment]
可是，我用之前的版本是支持的啊，如果这一版本不支持ssr，请问降级到哪个版本可以？我貌似降级过，但是还是不能用。。

**Comment by timothyqiu** [comment]
SSX-NG never supported SSR. I'm afraid this is not the project you are looking for. Most projects with SSR support have an extra letter "R" in their names.

**Comment by juaner630** [comment]
多谢啦。。

**Comment by 9crk** [comment]
不是客户端问题，这几天都用不了了。人家服务器关闭了。

**Comment by juaner630** [comment]
感谢。。已解决

**Comment by purezhi** [comment]
@juaner630 请问怎么解决的，我也是遇到了突然不能使用的情况。服务器应该是正常的，因为我手机可以连。

**Comment by juaner630** [comment]
我是自己升级的时候下错了软件，我本来用的是ssr，平时都是在软件上升级，结果那天现实无法刷新还是啥，我就自己来github下了这个软件，正如软件所有者所言，应该是后面带R的那个才是我该下载的。。如果你用的是ssr下另一个，是ss就下这个..如果还不能上我就不懂了，多半是不可描述的力量吧
