### ISSUE TITLE
不能用google,Facebook等網站

### ISSUE THREAD

**Issue by RC63111** [shadowsocks/ShadowsocksX-NG#534]
**System and Shadowsocksx-NG version:**

- macOS 10.11.6 
- Shadowsocksx-NG 1.6.1

**Expected behavior:**
能正常試用google,FACEBOOK等網站

**Actual behavior:**
ss開啟期間能用baidu或國內的網站，但不能用google，facebook等

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

9/10/2017 12:20:03.440 ShadowsocksX-NG[501]: Start ss-local succeeded.
9/10/2017 12:20:03.507 ShadowsocksX-NG[501]: Start privoxy succeeded.
9/10/2017 12:20:03.574 ShadowsocksX-NG[501]: Stop kcptun succeeded.
9/10/2017 12:20:03.575 ShadowsocksX-NG[501]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
9/10/2017 12:20:03.614 ShadowsocksX-NG[501]: pac proxy set to auto
9/10/2017 12:20:03.618 configd[55]: network changed: v4(en0:192.168.1.101) DNS Proxy! SMB
9/10/2017 12:20:03.627 networkd[195]: -[NETProxyLookup url] invalid URL scheme '5223'
9/10/2017 12:20:03.634 networkd[195]: -[NETProxyLookup url] invalid URL scheme '5223'
9/10/2017 12:20:04.000 kernel[0]: Google Chrome He[965] triggered unnest of range 0x7fffa0000000->0x7fffa0200000 of DYLD shared region in VM map 0x5ca96035288b4887. While not abnormal for debuggers, this increases system memory footprint until the target exits.

**Comment by timothyqiu** [comment]
Please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.

**Comment by zsmhub** [comment]
error log message : 
2017-10-09 17:17:57 INFO: initializing ciphers... aes-256-cfb
 2017-10-09 17:17:59 ERROR: failed to resolve server name, wait 2 seconds
 2017-10-09 17:18:03 ERROR: failed to resolve server name, wait 4 seconds
 2017-10-09 17:18:11 ERROR: failed to resolve server name, wait 8 seconds
 2017-10-09 17:18:27 ERROR: failed to resolve server name, wait 16 seconds
 2017-10-09 17:18:59 ERROR: failed to resolve server name, wait 32 seconds

**Comment by timothyqiu** [comment]
See #525 #531

**Comment by RC63111** [comment]
Last login: Mon Oct  9 17:21:13 on ttys000
Reginede-MacBook-Pro:~ RC_631$ /Users/RC_631/Downloads/ShadowsocksX-NG.app/Contents/Resources/ss-local ; exit;
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/libev/lib/libev.4.dylib
  Referenced from: /Users/RC_631/Downloads/ShadowsocksX-NG.app/Contents/Resources/ss-local
  Reason: image not found
Trace/BPT trap: 5
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[程序完成]

**Comment by timothyqiu** [comment]
@RC63111 Don't run the bundled `ss-local` manually, it will always fail.

Please follow the instructions in the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) to get your log. (steps are listed in the _ss-local.log_ section)

**Comment by RC63111** [comment]
9/10/2017 17:39:15.522 ShadowsocksX-NG[726]: Start ss-local succeeded.
9/10/2017 17:39:15.588 ShadowsocksX-NG[726]: Start privoxy succeeded.
9/10/2017 17:39:15.655 ShadowsocksX-NG[726]: Stop kcptun succeeded.
9/10/2017 17:39:15.656 ShadowsocksX-NG[726]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
9/10/2017 17:39:15.693 ShadowsocksX-NG[726]: pac proxy set to auto
9/10/2017 17:39:15.696 configd[55]: network changed: v4(en0:192.168.1.103) DNS Proxy! SMB
9/10/2017 17:39:15.706 networkd[192]: -[NETProxyLookup url] invalid URL scheme '5223'
9/10/2017 17:39:15.713 networkd[192]: -[NETProxyLookup url] invalid URL scheme '5223'
9/10/2017 17:39:24.112 acise[404]: Function: increaseBackoffTimer Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 458 Level: info :: Probe interval changed from 432 sec to 649 sec.
9/10/2017 17:39:24.112 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 781 Level: debug :: Couldn't get best default route
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter lo0, operStatus=1, wifi=no
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter gif0, operStatus=1, wifi=no
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter stf0, operStatus=1, wifi=no
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter en0, operStatus=1, wifi=no
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter en1, operStatus=1, wifi=no
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter en2, operStatus=1, wifi=no
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter p2p0, operStatus=1, wifi=no
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter awdl0, operStatus=1, wifi=no
9/10/2017 17:39:24.142 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 804 Level: debug :: adapter bridge0, operStatus=1, wifi=no
9/10/2017 17:39:24.143 acise[404]: Function: CFGUTIL Thread Id: 0xA3766000 File: ConfigData.cpp Line: 197 Level: warn :: ISEPostureCFG.xml not found, using defaults
9/10/2017 17:39:24.143 acise[404]: Function: CFGUTIL Thread Id: 0xA3766000 File: ConfigData.cpp Line: 197 Level: warn :: ISEPostureCFG.xml not found, using defaults
9/10/2017 17:39:24.143 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 891 Level: debug :: MSG_NS_SWISS_SEARCHING, 
9/10/2017 17:39:24.143 acise[404]: Function: collectTargets Thread Id: 0xA3766000 File: SwiftHttpRunner.cpp Line: 958 Level: debug :: No target - Default route , #wifi=0, #nonWifi=1,bestDefaultRouteIsWifi=0
9/10/2017 17:39:24.143 acise[404]: Function: logTransition Thread Id: 0xA3766000 File: SMNav.cpp Line: 169 Level: info :: Cur State = SW_UNKNOWN, Event = EV_NW_STATUS_CHANGE  
9/10/2017 17:39:24.143 acise[404]: Function: sendUIStatus Thread Id: 0xA3766000 File: SwiftManager.cpp Line: 284 Level: debug :: MSG_SU_STEP_STATUS, {{Status=6}, {Compliant=3}, {Phase=0}, {StepNumber=-1}, {Progress=-1}, {Attention=0}, {Cancellable=0}, {Restartable=0}, {Description1="System scan not required on current Wi-Fi."}, {Description2=""}}
9/10/2017 17:39:24.143 acise[404]: Function: timerPrc Thread Id: 0xA3766000 File: SwiftManager.cpp Line: 378 Level: debug :: MSG_SH_S_DEL_TIMER, {{sm=0}, {return_code=509}, {ev_str="delete searching timer"}, {interval=0}}
9/10/2017 17:39:24.143 acise[404]: Function: logTransition Thread Id: 0xA3766000 File: SMNav.cpp Line: 169 Level: info :: New State = SW_UNKNOWN, New Event = EV_NO_EVENT  
9/10/2017 17:39:49.768 login[1113]: USER_PROCESS: 1113 ttys000
