### ISSUE TITLE
使用不了了

### ISSUE THREAD

**Issue by jiajun1991** [shadowsocks/ShadowsocksX-NG#535]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6
- Shadowsocksx-NG 1.61?

**Expected behavior:**
能够正常访问youtube，Instagram等网站。

**Actual behavior:**
youtube，Instagram都访问不了。
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

2017-10-09 12:21:26 ERROR: One time auth has been deprecated. Try AEAD ciphers instead.

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by timothyqiu** [comment]
> 2017-10-09 12:21:26 ERROR: One time auth has been deprecated. Try AEAD ciphers instead.

See #450

**Comment by 9crk** [comment]
shadowsocks.com 不敢在十九大召开之际提供服务 不是客户端问题 都用不了啦 等下个月吧 或者自己搭一个ss服务器

**Comment by jiajun1991** [comment]
Thanks
