### ISSUE TITLE
Can not use Google Backup & Sync on Mac in mainland China with other functions working well 

### ISSUE THREAD

**Issue by orisson003** [shadowsocks/ShadowsocksX-NG#539]
**System and Shadowsocksx-NG version:**

- macOS 10.13(17A405))
- Shadowsocksx-NG 1.6.1(1)

**Expected behavior:**
In either Global or PAC mode, Google Backup & Sync app shall work well on Mac.

**Actual behavior:**
Users can view the webpages via Chrome or Safari, but can not sign into the Google app.

**Steps to reproduce:**
1. Download Google Backup & Sync for Mac: https://www.google.com/drive/download/
2. Open ShadowsocksX-NG and turn into either PAC Auto mode or Global mode.
3. Google Backup & Sync will remind the users that "unable to connect" and stop working. 

**How often does this happen?**
Always. 

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**
N/A

**Crash Log**
N/A
[ss-local.log.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/1368771/ss-local.log.zip)

**Comment by timothyqiu** [comment]
If the proxy works in Chrome or Safari (can access various google sites without interference), there might be something wrong with the proxy settings of Google Backup & Sync for Mac.

**Comment by orisson003** [comment]
Hi timothyqiu, I checked the proxy settings of Google Backup & Sync for Mac and it turned out that everything is fine. In fact I can us this app when connecting to internet via Cisco Anyconnect. I was wondering whether this is a problem of the special connection used by Google, which was not supported by Shadowsocks yet. (Guess it would not be a simple FTP or Https link)

**Comment by orisson003** [comment]
The problem is solved by changing the settings of Proxy Server Port from 1080 into 1086 in Proxifer. This is a change made by Shadowsocks NG that it changed the port into 1086 from 1080, which is used by Shadowsocks.

**Comment by liu-jc** [comment]
Hi orisson003, I wonder if I don't want to use Proxifer, is there any possibility to use google backup & sync for mac only with shadowsocks NG? How can I make it?

**Comment by zhoujunpei** [comment]
Yes, it would be really helpful if the google backup & sync for mac can work with shadowsocks NG directly.

**Comment by fattypiggy** [comment]
> Yes, it would be really helpful if the google backup & sync for mac can work with shadowsocks NG directly.

+1

**Comment by fattypiggy** [comment]
Proxifier is a easy to set up solution for me.

**Comment by txdywy** [comment]
Their are more options to setup VPN locally other than using Proxifier and
they are free.

One is Jigsaw(Google)'s ss client Outline:
https://github.com/Jigsaw-Code/outline-client

There is an even cooler one https://github.com/qwj/python-vpn
pvpn can setup an IKEv2 VPN and transfer the traffic to ss

**Comment by KornbergFresnel** [comment]
**A feasible solution works with ShadowsocksNG-X (for macOS)**

1. open "System Preferences" -> "Network" -> "Proxies"
2. configure "Web Proxy (HTTP)" (optional) and "Secure Web Proxy (HTTPS)" manually. for example, the web proxy server address may be `127.0.0.1:1087`. 

**NOTES**: If you don't know what the address is, you can also find it in the "Preferences->HTTP" panel of ShadowsocksNG-X.

**System & Software information**

- macOS 10.15.1
- ShadowsocksNG-X 1.9.4

**For Windows 10**: I found that there is the same problem for windows, you can update the user rule for PAC with `||drive.google.com`, then relaunch the Shadowsocks.

**Comment by HAK-Krypton** [comment]
> **A feasible solution works with ShadowsocksNG-X (for macOS)**
> 
> 1. open "System Preferences" -> "Network" -> "Proxies"
> 2. configure "Web Proxy (HTTP)" (optional) and "Secure Web Proxy (HTTPS)" manually. for example, the web proxy server address may be `127.0.0.1:1087`.
> 
> **NOTES**: If you don't know what the address is, you can also find it in the "Preferences->HTTP" panel of ShadowsocksNG-X.
> 
> **System & Software information**
> 
> * macOS 10.15.1
> * ShadowsocksNG-X 1.9.4
> 
> **For Windows 10**: I found that there is the same problem for windows, you can update the user rule for PAC with `||drive.google.com`, then relaunch the Shadowsocks.

I have tried your soluton but not working, perhaps I need to enter server address, which I don't know which one I can use in China. I use PANDA VPN to connect Internet. My PC works fine, my Macbook everythings works fine but "Backup & Sync"

Please advice!!!

**Comment by KornbergFresnel** [comment]
> > **A feasible solution works with ShadowsocksNG-X (for macOS)**
> > 
> > 1. open "System Preferences" -> "Network" -> "Proxies"
> > 2. configure "Web Proxy (HTTP)" (optional) and "Secure Web Proxy (HTTPS)" manually. for example, the web proxy server address may be `127.0.0.1:1087`.
> > 
> > **NOTES**: If you don't know what the address is, you can also find it in the "Preferences->HTTP" panel of ShadowsocksNG-X.
> > **System & Software information**
> > 
> > * macOS 10.15.1
> > * ShadowsocksNG-X 1.9.4
> > 
> > **For Windows 10**: I found that there is the same problem for windows, you can update the user rule for PAC with `||drive.google.com`, then relaunch the Shadowsocks.
> 
> I have tried your soluton but not working, perhaps I need to enter server address, which I don't know which one I can use in China. I use PANDA VPN to connect Internet. My PC works fine, my Macbook everythings works fine but "Backup & Sync"
> 
> Please advice!!!

You got the point. Though I have no experience on PANDA VPN, I can tell your the key to address this issue is that your VPN supports http/https proxy (it might be locally or you can get it from your service provider). @HAK-Krypton
