### ISSUE TITLE
SS-NG not working

### ISSUE THREAD

**Issue by busyfree** [shadowsocks/ShadowsocksX-NG#540]
**System and Shadowsocksx-NG version:**

- macOS 10.13 (17A405)
- Shadowsocksx-NG 1.6.1

Shadowsocks server enable tcp-fast-open feature

**Actual behavior:**
kcptun not working

**ss-local.log**
$cat ~/Library/Logs/ss-local.log 
 2017-10-10 00:50:06 INFO: connect to clients4.google.com:443
 2017-10-10 00:50:14 INFO: connect to www.facebook.com:443
 2017-10-10 00:53:39 INFO: connect to clients4.google.com:443
 2017-10-10 00:53:45 INFO: closed gracefully
 2017-10-10 00:53:46 INFO: initializing ciphers... aes-256-cfb
 2017-10-10 00:53:46 INFO: listening at 127.0.0.1:1086
 2017-10-10 00:54:49 INFO: initializing ciphers... aes-256-cfb
 2017-10-10 00:54:49 INFO: listening at 127.0.0.1:1086
 2017-10-10 00:54:51 INFO: connect to www.google.com:443
 2017-10-10 00:54:52 INFO: connect to mtalk.google.com:443
 2017-10-10 00:55:14 INFO: connect to www.facebook.com:443

** kcpserver-log**
2017/10/09 16:44:35 version: 20170930
2017/10/09 16:44:35 listening on: [::]:4000
2017/10/09 16:44:35 target: (*****hide*****):9528
2017/10/09 16:44:35 encryption: aes
2017/10/09 16:44:35 nodelay parameters: 1 20 2 1
2017/10/09 16:44:35 sndwnd: 1024 rcvwnd: 1024
2017/10/09 16:44:35 compression: true
2017/10/09 16:44:35 mtu: 1350
2017/10/09 16:44:35 datashard: 10 parityshard: 3
2017/10/09 16:44:35 acknodelay: false
2017/10/09 16:44:35 dscp: 0
2017/10/09 16:44:35 sockbuf: 4194304
2017/10/09 16:44:35 keepalive: 10
2017/10/09 16:44:35 snmplog:
2017/10/09 16:44:35 snmpperiod: 60
2017/10/09 16:44:35 pprof: false

2017/10/09 16:45:17 remote address: (***hide***):36084

** kcpclient-log**

$./client_darwin_amd64 -c client.json 
2017/10/10 00:45:07 version: 20170930
2017/10/10 00:45:07 listening on: [::]:8388
2017/10/10 00:45:07 encryption: aes
2017/10/10 00:45:07 nodelay parameters: 1 20 2 1
2017/10/10 00:45:07 remote address: (****hide*****):4000
2017/10/10 00:45:07 sndwnd: 128 rcvwnd: 512
2017/10/10 00:45:07 compression: true
2017/10/10 00:45:07 mtu: 1350
2017/10/10 00:45:07 datashard: 10 parityshard: 3
2017/10/10 00:45:07 acknodelay: false
2017/10/10 00:45:07 dscp: 0
2017/10/10 00:45:07 sockbuf: 4194304
2017/10/10 00:45:07 keepalive: 10
2017/10/10 00:45:07 conn: 1
2017/10/10 00:45:07 autoexpire: 0
2017/10/10 00:45:07 scavengettl: 600
2017/10/10 00:45:07 snmplog: 
2017/10/10 00:45:07 snmpperiod: 60
2017/10/10 00:45:07 connection: (*****hide***):52270 -> (****hide*****):4000

** SSNG-server-config***
![image](https://user-images.githubusercontent.com/504251/31349356-83cd70b0-ace8-11e7-8e0a-82e1b535f39f.png)

** SSNG-config**
![image](https://user-images.githubusercontent.com/504251/31349450-f17b9e20-ace8-11e7-9cea-d8cbddfd71f2.png)
![image](https://user-images.githubusercontent.com/504251/31349456-f99ee576-ace8-11e7-99ba-4a3a7a33de5f.png)
![image](https://user-images.githubusercontent.com/504251/31349461-000fcdda-ace9-11e7-9638-b67cd1ca29b1.png)

**Comment by ranjin** [comment]
the same issue. please let the author check it .we need a answer.

**Comment by itbdw** [comment]
ShadowsocksX-NG gives me connection refused error, while Shadowsocks works great.

```
➜  ~ curl --socks5 127.0.0.1:1086 google.com

curl: (7) Failed to connect to 127.0.0.1 port 1086: Connection refused

➜  ~ curl --socks5 127.0.0.1:1080 google.com

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.ca/?gfe_rd=cr&amp;dcr=0&amp;ei=nOD7Wf78Aeam8weP7YfgCw">here</A>.
</BODY></HTML>
```

**Comment by crown3** [comment]
i met this issue,too.
when i tru to run some command operation, such as 'brew update',it doesn't work ,and give me this
"fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': Failed to connect to 127.0.0.1 port 1086: Connection refused"

**Comment by yanghaikun** [comment]
finally i find out how to make it works, you need to set up http & https proxy, in net work config
![image](https://user-images.githubusercontent.com/3261489/32695426-7b526490-c796-11e7-93ff-11db75f852b8.png)
