### ISSUE TITLE
断开连接后，不会自动重连

### ISSUE THREAD

**Issue by happyeddie** [shadowsocks/ShadowsocksX-NG#541]
**System and Shadowsocksx-NG version:**

- macOS 10.13 (17A405)
- Shadowsocksx-NG 1.6.1 (1)

**Expected behavior:**
当服务端重启，或者失去连接后，客户端应该自动尝试重连

**Actual behavior:**
经常需要手动关闭服务，再开启服务才能连上服务器

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by yangfeicheung** [comment]
NG本身是不维持连接的，请求完了就会断开，所以服务端重启不会影响到客户端，你说的这种，有可能是客户端比方说ss-local crash了导致的，NG本身是依赖ss-local进行连接的

**Comment by happyeddie** [comment]
@yangfeicheung 嗯，可能是这种情况，重启服务端确实不会影响，但是之前用GoAgentX没有遇到过类似的问题
刚才搜了下log，关键词（shadow）可能不太对，只搜到一条：
“LSExceptions shared instance invalidated for timeout.”
这个时候不能翻墙
手动停止NG，再开启，就好了

**Comment by yangfeicheung** [comment]
这个应该是NG本身的bug导致的，默认连接就是不维持的，你可以试试我改的版本，也是不维持连接的，应该不需要重启
