### ISSUE TITLE
MacOS sierra 无法使用

### ISSUE THREAD

**Issue by GavinYIN1991** [shadowsocks/ShadowsocksX-NG#55]
今天手贱更新了 MacOS 到 10.12，发现『PAC自动模式』无法翻墙了……
现在必须挂『全局模式』才有效

**Comment by qinyuhang** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/pull/44 这个pull
request会解决这个问题，请等待merge，或使用补丁方的release

Gavin <notifications@github.com>于2016年9月9日 周五19:34写道：

**Comment by GavinYIN1991** [comment]
ShadowsocksX-NG-R5.app
我用了这个版本包，现在已经正常了，灰常感谢。

**Comment by qinyuhang** [comment]
:p 等待merge

Gavin <notifications@github.com>于2016年9月9日 周五19:46写道：

**Comment by pow2n10** [comment]
@GavinYIN1991  ShadowsocksX-NG-R5.app 有地址吗？

**Comment by GavinYIN1991** [comment]
@pow2n10 https://github.com/qinyuhang/ShadowsocksX-NG/releases 目前还是测试版，请等待 merge 哈

**Comment by Nathaniel-Wu** [comment]
最简单的临时解决办法是用python开一个静态的HTTP server，或者apachectl也可以。
`cd ~/.ShadowsocksX-NG;python -m SimpleHTTPServer 8090`
然后就可以用http://127.0.0.1:8090/gfwlist.js手动设置代理了。

**Comment by jasonj99** [comment]
更新到10.12 GM2，发现各种模式都无法使用。试过全局模式也不能FQ。ShadowsocksX-NG-R6.app，是需要手动再设置些什么么？

**Comment by jasonj99** [comment]
问题解决了，chmod +x ss-local，不知道为什么没给ss-local可执行权限。

**Comment by qiuyuzhou** [comment]
ShadowsocksX-NG-R6.app 不是我打包吧

**Comment by ronanhardiman** [comment]
@jasonj99  我的也是这个情况，请问下具体的解决方案 谢谢。

**Comment by addozhang** [comment]
@ronanhardiman 去到shadowsocksx安装目录，找到ss-local。比如我的目录是/Applications/ShadowsocksX-NG-R8.app/Contents/Resources，然后运行chmod +x ss-local

**Comment by parkche** [comment]
chmod了还是不行啊

**Comment by addozhang** [comment]
@parkche 重启shadowsocksx了没

**Comment by parkche** [comment]
全局都不能用，尝试了半天有一次在wifi代理设置设置了一下，出来点了应用就能上了，但是就那一次，之后就都不行了，话说shadowsocks怎么全部卸载，每次重新装版本，之前的信息都有
