### ISSUE TITLE
Can't work after updating to MacOS 10.13

### ISSUE THREAD

**Issue by wsyzxxxx** [shadowsocks/ShadowsocksX-NG#551]
- macOS 10.13 
- Shadowsocksx-NG 1.6.1

It works well in 10.12.6. But when I update to 10.13, there is something wrong.
I can't find the problem with the ss log, so I have to report the issue.
It seems that something blocks the TCP connection.

(My ss server works well. I have test it with my mobile phone and anther PC.)

**ss-local.log**

 2017-10-14 08:19:57 INFO: initializing ciphers... aes-256-cfb
 2017-10-14 08:19:57 INFO: listening at 127.0.0.1:1086
 2017-10-14 08:20:01 INFO: connect to p46-caldav.icloud.com:443
 2017-10-14 08:20:11 INFO: TCP connection timeout
 2017-10-14 08:20:11 INFO: connect to p46-caldav.icloud.com:443
 2017-10-14 08:20:21 INFO: TCP connection timeout
 2017-10-14 08:20:21 INFO: connect to p46-caldav.icloud.com:443
 2017-10-14 08:20:31 INFO: TCP connection timeout
 2017-10-14 08:20:31 INFO: connect to p46-caldav.icloud.com:443
 2017-10-14 08:20:40 INFO: connect to www.google.com:443
 2017-10-14 08:20:41 INFO: TCP connection timeout
 2017-10-14 08:20:42 INFO: connect to www.google.com:80
 2017-10-14 08:20:51 INFO: TCP connection timeout
 2017-10-14 08:20:52 INFO: TCP connection timeout
 2017-10-14 08:20:52 INFO: connect to www.google.com:80
 2017-10-14 08:21:02 INFO: TCP connection timeout
 2017-10-14 08:21:02 INFO: connect to www.google.com:80
 2017-10-14 08:21:12 INFO: TCP connection timeout

a piece of system log (I think it is related)
Oct 14 08:20:32 MacBook-Pro-6 languageassetd[413]: dnssd_clientstub ConnectToServer: connect()-> No of tries: 1
Oct 14 08:20:33 MacBook-Pro-6 languageassetd[413]: dnssd_clientstub ConnectToServer: connect()-> No of tries: 2
Oct 14 08:20:34 MacBook-Pro-6 languageassetd[413]: dnssd_clientstub ConnectToServer: connect()-> No of tries: 3
Oct 14 08:20:35 MacBook-Pro-6 languageassetd[413]: dnssd_clientstub ConnectToServer: connect() failed path:/var/run/mDNSResponder Socket:4 Err:-1 Errno:1 Operation not permitted
Oct 14 08:20:38 MacBook-Pro-6 com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit

**Comment by timothyqiu** [comment]
Try

    nc -v YOUR_SERVER_HOST YOUR_SERVER_PORT

Does it fail?

**Comment by wsyzxxxx** [comment]
It's so strange.
Today when I want to try the command, shadowsocks accidentally works well.

I check the network settings. In proxy setting, it sets the socks proxy automatically, but it can't be set automatically before.
Yesterday I tried 'lantern' as well, it can't work either. But it works well today, too.
I guess 'lantern' may change some of my network configuration.

Thanks so much. If the situation happens again, I'll try the test and report it to you.

**Comment by Jorye** [comment]
developer pls update version

**Comment by wsyzxxxx** [comment]
I've tried it for some days. I found that shadow socks can't work with the VPN. Since I need to use the L2TP VPN to use the school networks. If I use the VPN setting of MacOS, Shadowsocks can't work. I can only use another authentication way of school networks (Web authentication) for using ss.

**Comment by wsyzxxxx** [comment]
I don't know whether it is a bug or not, I just report it.

**Comment by Jorye** [comment]
Resolvent ： Find SS password encryption, change it

**Comment by wsyzxxxx** [comment]
After some test, I found the reason.
SS can only set the socks proxy for the default network connection (Wifi network).

**Comment by wsyzxxxx** [comment]
But when I use the VPN, the data are passing through the VPN network.

**Comment by qiuyuzhou** [comment]
@wsyzxxxx 
![image](https://user-images.githubusercontent.com/2310221/31823280-3b2591bc-b571-11e7-874f-64e365074e0b.png)

**Comment by lining1991** [comment]
我用的shadowsocks 因为shadowsocks-ng不支持自动扫描屏幕二维码
nc -v YOUR_SERVER_HOST YOUR_SERVER_PORT
我运行了这一行 提示服务器连接成功了 但是依旧是无法访问呢 什么问题
