### ISSUE TITLE
MacOS 10.13 本地端口不能启动

### ISSUE THREAD

**Issue by bigggge** [shadowsocks/ShadowsocksX-NG#552]
**System and Shadowsocksx-NG version:**

- macOS 10.13
- Shadowsocksx-NG 1.6.1

**Actual behavior:**

本地1086端口没有启动，无法连接，但是iOS客户端可以连接服务器

```
$ lsof -Pn -i4|grep LISTEN                                                              
QQ          321  ice   37u  IPv4 0xe09c82402496dd4f      0t0  TCP 127.0.0.1:4300 (LISTEN)
QQ          321  ice   38u  IPv4 0xe09c824024970bdf      0t0  TCP 127.0.0.1:4301 (LISTEN)
node       8322  ice   16u  IPv4 0xe09c82404509f93f      0t0  TCP 127.0.0.1:4200 (LISTEN)
steam_osx 14074  ice   14u  IPv4 0xe09c824047b577cf      0t0  TCP 127.0.0.1:57343 (LISTEN)
steam_osx 14074  ice  106u  IPv4 0xe09c824047b5493f      0t0  TCP *:27036 (LISTEN)
privoxy   20087  ice    3u  IPv4 0xe09c82402497028f      0t0  TCP 127.0.0.1:1087 (LISTEN)
idea      33445  ice  133u  IPv4 0xe09c824033437fef      0t0  TCP 127.0.0.1:54143 (LISTEN)
idea      33445  ice  206u  IPv4 0xe09c824033bbb28f      0t0  TCP 127.0.0.1:6943 (LISTEN)
idea      33445  ice  236u  IPv4 0xe09c824033bb9fef      0t0  TCP 127.0.0.1:58087 (LISTEN)
idea      33445  ice  719u  IPv4 0xe09c82402fc5728f      0t0  TCP 127.0.0.1:63343 (LISTEN)
idea      33445  ice  784u  IPv4 0xe09c824033bb7aaf      0t0  TCP *:53553 (LISTEN)
node      84559  ice   11u  IPv4 0xe09c8240450a0bdf      0t0  TCP *:9876 (LISTEN)
```

**ss-local.log**
 2017-09-21 21:53:20 INFO: listening at 127.0.0.1:1086
 2017-09-22 09:03:06 INFO: initializing ciphers... rc4-md5
 2017-09-22 09:03:08 INFO: tcp port reuse enabled
 2017-09-22 09:03:08 INFO: listening at 127.0.0.1:1086
 2017-09-27 09:48:02 INFO: initializing ciphers... rc4-md5
 2017-09-27 09:48:03 INFO: tcp port reuse enabled
 2017-09-27 09:48:03 INFO: listening at 127.0.0.1:1086
 2017-09-27 20:27:18 INFO: initializing ciphers... rc4-md5
 2017-09-27 20:27:19 INFO: tcp port reuse enabled
 2017-09-27 20:27:19 INFO: listening at 127.0.0.1:1086
 2017-09-27 21:37:46 INFO: initializing ciphers... rc4-md5
 2017-09-27 21:37:47 INFO: tcp port reuse enabled
 2017-09-27 21:37:47 INFO: listening at 127.0.0.1:1086
 2017-09-28 07:29:48 INFO: initializing ciphers... rc4-md5
 2017-09-28 07:29:49 INFO: tcp port reuse enabled
 2017-09-28 07:29:49 INFO: listening at 127.0.0.1:1086
 2017-10-09 14:13:42 INFO: initializing ciphers... rc4-md5
 2017-10-09 14:13:42 INFO: tcp port reuse enabled
 2017-10-09 14:13:42 INFO: listening at 127.0.0.1:1086
 2017-10-09 14:28:45 INFO: initializing ciphers... rc4-md5
 2017-10-09 14:28:45 INFO: tcp port reuse enabled
 2017-10-09 14:28:45 INFO: listening at 127.0.0.1:1086
 2017-10-11 07:35:25 INFO: initializing ciphers... rc4-md5
 2017-10-11 07:35:25 INFO: tcp port reuse enabled
 2017-10-11 07:35:25 INFO: listening at 127.0.0.1:1086

**Application log**

ShadowsocksX-NG LSExceptions shared instance invalidated for timeout.

**Comment by wsyzxxxx** [comment]
我和你的情况有些类似， Application log中是同样的提示，可以参考一下我的问题 #551 我尝试了其他软件似乎都和tcp端口问题有关，有空我们可以讨论一下

**Comment by tsunamilx** [comment]
我也是端口起不来

macOS 10.13
Shadowsocksx-NG 1.6.1

**Comment by vanton** [comment]
cd /Library/Application Support/ShadowsocksX-NG
ln -fs ss-local-latest/ss-local

1.6.1升级后的小bug，ss-local 默认指向旧版本。

**Comment by nictse2013** [comment]
Is 
第二个命令行运行不了

状况同lz

**Comment by wolf206521** [comment]
macOS 10.13
Shadowsocksx-NG 1.6.1

状况同LZ

**Comment by bigggge** [comment]
我删了 /Library/Application Support/ShadowsocksX-NG 然后重新安装就可以用了

**Comment by nictse2013** [comment]
Ls的方法不行
命令行也不行
1.5到1.61我都试了也不行

**Comment by guozhongrui000** [comment]
Shadowsocksx-NG 1.6.1本地socks5端口改为1086了，我改成1086就可以了。
$ cat "/Users/yourname/Library/Application Support/ShadowsocksX-NG/ss-local-config.json"

{
  "method" : "rc4-md5",
  "server" : "IP",
  "password" : "...",
  "local_address" : "127.0.0.1",
  "server_port" : ...,
  "auth" : false,
  "timeout" : 60,
  "local_port" : 1086
}

**Comment by nictse2013** [comment]
Ls 你这个位置 我这里没有那个文件…只有一个proxy_conf_helper的文件

**Comment by xxxxzr** [comment]
Ls 换个端口就行了，我换成了1085就可以了，之前由于某种原因，1086起不来

**Comment by 3xeye** [comment]
请问ls怎么换端口?

**Comment by 3xeye** [comment]
换了,也还是不行...

**Comment by nictse2013** [comment]
换了也不行…

**Comment by flashermaster** [comment]
@vanton 用了你的方法，可行

**Comment by kjian** [comment]
重启系统以后报同样的错, 打开配置文件查看, 发现密码被还原了, 再把密码改回来就行了, 估计是客户端的Bug.
配置文件: /Users/<username>/Library/Application Support/ShadowsocksX-NG/ss-local-config.json
感谢 @guozhongrui000

**Comment by bobotoken** [comment]
同样的问题，改为1.7.0还是解决不了，求解决方法，万分感激

**Comment by yangfeicheung** [comment]
如果不能用，试试这个版本吧，high sierra可以用的

https://github.com/yangfeicheung/Shadowsocks-X/releases

**Comment by lining1991** [comment]
shadowsocks 同样的报错怎么解决呢 上边楼主说的文件是对应ng的么，shadowsocks找不到

**Comment by liquanjin** [comment]
我的是查看ShadowsocksX-NG / ss-local-config.json 文件发现莫名其妙地密码多了一个空格。。。
2333 ，无语了。最后改了密码就行了
还好看了log，不然不知道什么时候才能定位到了

**Comment by FelixZYY** [comment]
> Ls 换个端口就行了，我换成了1085就可以了，之前由于某种原因，1086起不来

完美解决

**Comment by dixieboy** [comment]
报错了

> Unable to load Info.plist exceptions (eGPUOverrides)

网上搜了下说是，Mojave系统的bug，可是为啥过了这么 久，苹果还没有修复呢！！
https://forums.developer.apple.com/thread/110340

**Comment by mushanzi1216** [comment]
我是之前安装过shadowsocks-R，并且设置了开机自动启动，虽然在应用程序里删除了，但是每次重启mac后还是自动重启，与shadowsocks-NG冲突了端口。删除shadowsocks-R后问题解决，困扰了我好几个月的问题 233333

**Comment by YohaneWW** [comment]
Resolve:
`rm ~/Library/Application Support/ShadowsocksX-NG/`

**Comment by boboidream** [comment]
我也是同样的问题，最后找到问题所在，是手欠自己在 App Cleaner 把 ShadowsocksX-NG 服务关了。打开就好了，附上检查命令
```
cat ~/Library/Logs/ss-local.log # 检查日志
lsof -Pn -i4|grep LISTEN # 检查端口占用
ls ~/Library/Application\ Support/ShadowsocksX-NG # 检查配置
```

<img width="1112" alt="Screen Shot 2019-08-28 at 9 51 43 PM" src="https://user-images.githubusercontent.com/13171903/63862135-ab937080-c9de-11e9-8ff0-9034fbfdfb49.png">

**Comment by sillykelvin** [comment]
我也出现过这个错误，服务器明明是好的，最后发现DNS有问题，在设置->网络->DNS里面改成四个8就可以了。
