### ISSUE TITLE
shadowsock can not link chrom 

### ISSUE THREAD

**Issue by BlueBlueBlueSky** [shadowsocks/ShadowsocksX-NG#553]
错误	14:32:07.017487 +0800	parsecd	Server endpoint not set, data can't be sent to server
错误	14:32:42.306419 +0800	Finder	warning: dynamic accessors failed to find @property implementation for 'uniqueId' for entity ABCDInfo while resolving selector 'uniqueId' on class 'ABCDInfo'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?
错误	14:32:42.310173 +0800	accountsd	"Cannot check access to a private account type: com.apple.account.IMAP"
错误	14:32:42.310479 +0800	accountsd	"Client <private> is not allowed to access accounts of type com.apple.account.IMAP."
错误	14:32:42.310751 +0800	Finder	"Error returned from daemon: <private>"
错误	14:32:44.233838 +0800	quicklookd	SQLite[14]: <private>
错误	14:32:44.233879 +0800	quicklookd	SQLite[14]: <private>
错误	14:32:44.426453 +0800	QuickLookSatellite	0 is not a valid connection ID.
错误	14:32:44.447498 +0800	QuickLookSatellite	0 is not a valid connection ID.
错误	14:32:44.447521 +0800	QuickLookSatellite	0 is not a valid connection ID.
错误	14:32:44.447536 +0800	QuickLookSatellite	0 is not a valid connection ID.
错误	14:32:45.394206 +0800	Finder	warning: dynamic accessors failed to find @property implementation for 'serialNumber' for entity ABCDAddressBookSource while resolving selector 'serialNumber' on class 'ABCDAddressBookSource'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?
错误	14:32:45.470984 +0800	Finder	warning: dynamic accessors failed to find @property implementation for 'uniqueId' for entity ABCDAddressBookSource while resolving selector 'uniqueId' on class 'ABCDAddressBookSource'.  Did you remember to declare it @dynamic or @synthesized in the @implementation ?
错误	14:35:47.001967 +0800	NeteaseMusic	[0x7f95d2385c00] Decoding failed with error code -1
错误	14:35:47.136317 +0800	NeteaseMusic	NSURLSessionTask finished with error - code: -999

**Comment by timothyqiu** [comment]
Please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.
