### ISSUE TITLE
能支持kcpraw吗？

### ISSUE THREAD

**Issue by vvhh2002** [shadowsocks/ShadowsocksX-NG#559]
https://github.com/ccsexyz/kcpraw
这个新的fork，支持流量伪装，内置ss-go 
十分方便，建议采用。

**Comment by ccsexyz** [comment]
我试了下，可以直接替换 SSX-NG 所使用的 kcptun 二进制文件
文件路径为  ~/Library/Application Support/ShadowsocksX-NG/kcptun_20170322/kcptun_client   
替换后如果还需要兼容 kcptun 的服务端，可以在额外参数那里加上 --udp  
<img width="309" alt="2017-10-21 8 19 16" src="https://user-images.githubusercontent.com/13003124/31851677-4e74889a-b69d-11e7-97ef-1005a771eca7.png">

**Comment by vvhh2003** [comment]
我试了，可以用，楼上是kcpraw 的作者，👏

**Comment by gMan1990** [comment]
@vvhh2002 kcptun这个东西要怎么用？在ssx-ng里

**Comment by vvhh2002** [comment]
@gMan1990  看楼上
