### ISSUE TITLE
能否像windows版代理的配置从gui-config.json加载

### ISSUE THREAD

**Issue by likebeta** [shadowsocks/ShadowsocksX-NG#56]
现在很多条代理需要一条一条添加，能否像windows版本那样，直接从gui-config.json中读取？ 这样就通用了

**Comment by qinyuhang** [comment]
https://github.com/qinyuhang/ShadowsocksX-NG/releases
这个可以直接读取windows版的gui-config.json

易思龙 <notifications@github.com>于2016年9月11日 周日01:23写道：

**Comment by likebeta** [comment]
@qinyuhang 多谢， 不知道官方考虑并入这个功能不， 一个一个加实在是太麻烦了

**Comment by qinyuhang** [comment]
@likebeta 发了一个pr过来，看啥时候merge吧

**Comment by qinshou** [comment]
macOS 10.12.1 下，使用导入配置功能会导致程序 crash 退出

**Comment by likebeta** [comment]
@qinyuhang 这个功能好像不会被merge吗 -_-

**Comment by qinyuhang** [comment]
PR已发，可以稍微等待一下？

**Comment by qiuyuzhou** [comment]
已经merge qinyuhang 的PR
