### ISSUE TITLE
加密方法切换到 chacha20 后不能再点击切换，全局都如此

### ISSUE THREAD

**Issue by JWBlueLiu** [shadowsocks/ShadowsocksX-NG#560]
**System and Shadowsocksx-NG version:**

- macOS 10.13
- Shadowsocksx-NG 1.6.1

**Expected behavior:**
可以切换加密方式

**Actual behavior:**
不能切换加密方式

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by yunyu950908** [comment]
同样的问题，求修这个bug =.=

**Comment by lanten** [comment]
+1

**Comment by lanten** [comment]
加密方法下拉框点不出来，有没有什么临时的解决方案？

**Comment by lanten** [comment]
加密方法下拉框点不出来，有没有什么临时的解决方案？

**Comment by qiuyuzhou** [comment]
duplicate of #894 ?

**Comment by JWBlueLiu** [comment]
嗯
Duplicate of 894#
