### ISSUE TITLE
无法科学上网啊大佬！

### ISSUE THREAD

**Issue by 479487666** [shadowsocks/ShadowsocksX-NG#561]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5 (16E????)
- Shadowsocksx-NG 1.6.1

**Expected behavior:**

**Actual behavior:**

全局、PAC全部无法上网更无法翻wall，同样的配置在安卓机和win10都可以正常翻wall

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

大概发生了一到两周，一直无法使用

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found

**Application log**

默认	09:39:16.444711 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
默认	09:39:16.509880 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	09:39:16.574772 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	09:39:16.575045 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	09:39:16.608230 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [803] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [802] (3,0)
默认	09:39:16.610755 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [803] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [802] (3,0)
默认	09:39:16.615279 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [803] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [802] (3,0)
默认	09:39:16.616033 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [803] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [802] (3,0)
默认	09:39:16.618892 +0800	ShadowsocksX-NG	pac proxy set to off

**Crash Log**
Process:               ss-local [788]
Path:                  /Users/USER/Library/Application Support/ShadowsocksX-NG/*/ss-local
Identifier:            ss-local
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           ss-local [788]
User ID:               501

Date/Time:             2017-10-20 09:38:22.627 +0800
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        FA521A8A-8ACF-2A19-8AF7-448AAE20F39B

Time Awake Since Boot: 960 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/Users/yjq/Library/Application Support/ShadowsocksX-NG/ss-local-latest/

Dyld Error Message:
  Library not loaded: */libmbedcrypto.0.dylib
  Referenced from: /Users/USER/Library/Application Support/ShadowsocksX-NG/*/ss-local
  Reason: image not found

Binary Images:
       0x10b152000 -        0x10b170ff3 +ss-local (0) <FE894517-4A16-3D5B-9394-72859184FAEF> /Users/USER/Library/Application Support/ShadowsocksX-NG/*/ss-local
       0x10b182000 -        0x10b188ffb +libev.4.dylib (0) <AD3C63E6-B62D-3C0E-82FF-D5D561BD1015> /Users/USER/Library/Application Support/ShadowsocksX-NG/*/libev.4.dylib
       0x10b195000 -        0x10b19bff3 +libudns.0.dylib (0) <E9E49743-E4FD-320C-BE61-EE47D8FC636A> /Users/USER/Library/Application Support/ShadowsocksX-NG/*/libudns.0.dylib
       0x10b1a8000 -        0x10b202ff7 +libsodium.18.dylib (0) <3FD9E2D1-08B9-3634-A378-823168712E49> /Users/USER/Library/Application Support/ShadowsocksX-NG/*/libsodium.18.dylib
       0x10fba5000 -        0x10fbe2dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff9ef9e000 -     0x7fff9ef9fffb  libSystem.B.dylib (1238.60.2) <FC9E9F13-3B18-305C-BE0A-97C7843652B0> /usr/lib/libSystem.B.dylib

**Comment by timothyqiu** [comment]
A quick-and-dirty solution you may want to try is deleting `~/Library/Application Support/ShadowsocksX-NG` and restart SSX-NG.

**Comment by 479487666** [comment]
@timothyqiu thx but i tried what u said and still not working....and the log showed the same thing"Library not loaded"

**Comment by 479487666** [comment]
![2017-10-20 10 25 55](https://user-images.githubusercontent.com/18607612/31802534-66369512-b581-11e7-8905-1d56520fc4bf.png)

i found the missing file... but what's going on now?

**Comment by timothyqiu** [comment]
I think you've deleted the wrong directory, or the Date Created / Date Modified won't be `2017/9/17`.

**Comment by 479487666** [comment]
so...what can i do with that?

**Comment by 479487666** [comment]
i deleted whole ssNG stuff and reinstall it, it works now!

**Comment by NicolJiang** [comment]
How to delete the whole ssNG please?

I have the same problem.
