### ISSUE TITLE
十九大期间用不了了？

### ISSUE THREAD

**Issue by jamesiter** [shadowsocks/ShadowsocksX-NG#567]
部署的最新ss，十九大期间不能用了？我telnet可以到远程服务器ss端口，但是本地开启ssx没作用。是不是被gfw识别出特征了？

**Comment by jamesiter** [comment]
我IDC机房的机器可以连接ss服务器，但是版办公室的个人电脑无法连到ss服务器。不过办公室的电脑，用telnet测试ss服务器所开启的端口是正常的。

**Comment by haobird** [comment]
今天办公室电脑无法访问了。。

**Comment by muzea** [comment]
@haobird 我今天也是突然都挂掉了，中国奠信

**Comment by wanglin02** [comment]
mac下无法正常使用了，但是同样的服务器，iOS的还是正常的，看来是有什么特殊的问题吗？

**Comment by CFM880** [comment]
我的还可以用

**Comment by rainy0824** [comment]
@wanglin02  哥们，iOS  怎么用？

**Comment by wanglin02** [comment]
@rainy0824 iOS改区域到美国/香港/日本，去app store搜索shadowrocket /wingy

**Comment by mengdodo** [comment]
上海联通发来噩耗，跪了

**Comment by wanglin02** [comment]
我这里又神奇的好了，不过不知道能坚持多久，不会是GFW在测试吧

**Comment by jamesiter** [comment]
我也很想知道是什么原因导致无法连接ss服务器的。

**Comment by xxxxzr** [comment]
+1  我的mac，iphone用不了了，ipad和windows正常，日了狗了

**Comment by 7449** [comment]
等阵子嘛，这段时间敏感都知道...

**Comment by shiningstarpxx** [comment]
深圳跪了

**Comment by icemanstudy** [comment]
长沙电信。mac死活用不了，手机用的同一个wifi没问题。。。真是见鬼了。

**Comment by jamesiter** [comment]
看来真的是被gfw侦测到了。或者这套源码有问题？

**Comment by suenyb** [comment]
有什么后备方案或者软件推荐吗？在线等

**Comment by suenyb** [comment]
现在大会都已经结束了，还是这样

**Comment by shiningstarpxx** [comment]
民脂民膏都用这里了，加了混淆也不行了

**Comment by wanglin02** [comment]
我换了一个host1plus的服务器，现在好了，北京联通

**Comment by shiningstarpxx** [comment]
现在的问题是可以检测了，换ip看样子是不行了，迟早被发现

**Comment by xusss** [comment]
把十九大去掉，以后都有可能不能用

**Comment by shiningstarpxx** [comment]
想到这个心里哇凉哇凉

**Comment by nocodo189753** [comment]
wireshark抓包，tcp可以建立连接，psh发包时一直retransmission，连vpn后一切正常

**Comment by immorlee** [comment]
同无法使用，mac os 10.13, 版本1.6.1

**Comment by ahlixinjie** [comment]
我的手机  台式 笔记本全都跪了

**Comment by shiningstarpxx** [comment]
不确定是长期还是短期，不过看样子简单混淆应该不行了

**Comment by ahlixinjie** [comment]
额  刚刚重新装了最新版的ss 可以用了，，，，，还是同一个ip  速度依然很好  应该是我的服务端出问题了。。。
