### ISSUE TITLE
shadowsocks server service in the US?

### ISSUE THREAD

**Issue by HMKMG** [shadowsocks/ShadowsocksX-NG#570]
Hello
urgent question from China.
The service that I have been using: ssrrcloud.com seems to be taken offline.
Can anybody recommend a server service in the US or another country that cannot be censored by the PRC Gov?
thks for your support.
Herri

**Comment by xxxxzr** [comment]
you can try vultr or digital ocean,but obviously prc gov can censor them by using whitelist

**Comment by HMKMG** [comment]
thks.
How does the prc gov technically whitelist a service?

**Comment by xxxxzr** [comment]
Actually I don't know how GFW works,but I'm quite sure that GFW now has the ability to recognize some of SS's net flow.Especially yesterday afternoon,all my vps is blocked..

**Comment by HMKMG** [comment]
yes so was mine. Hope u can get back on track soon.
