### ISSUE TITLE
mac OS10.12.6启动失败

### ISSUE THREAD

**Issue by cdkd321** [shadowsocks/ShadowsocksX-NG#571]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 (16E????)
- Shadowsocksx-NG 1.6.1

**Expected behavior:**
程序可以启动

**Actual behavior:**
我下载
https://github.com/shadowsocks/ShadowsocksX-NG/releases/download/v1.6.1/ShadowsocksX-NG.1.6.1.zip
后，并不能打开程序，提示“shadow..."不能打开
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by cdkd321** [comment]
好吧，我自己搞定的。命令行执行：

xattr -rd com.apple.quarantine ShadowsocksX-NG.app

**Comment by precious-ming** [comment]
请问能用吗？我的能打开，连接上服务器之后，不能用，pac 超时

**Comment by cdkd321** [comment]
不能用，我靠啊，最近网络封锁越来越严重了！
