### ISSUE TITLE
KCP设置界面问题

### ISSUE THREAD

**Issue by duzhen1996** [shadowsocks/ShadowsocksX-NG#572]
首先感谢开发者的贡献！

之前我一直使用KCP（https://github.com/xtaci/kcptun）官方提供的客户端，最近发现SSX-NG整合了一个KCP client。所以我使用了这个新的feature。虽然已经设置完了，但是界面的设计让我产生了困惑。
kcp的设置需要到两个不同的地方。这让我一时不知道kcpclient的本地端口去哪里填了，我一度以为kcptun port后面应该填的是本地端口，上面的地址后面填的是远程端口，但是二者又强制保持一致让我一时怀疑人生。
![](https://ws2.sinaimg.cn/large/006tNc79gy1fkur010gxsj30d80k7wf0.jpg)
![](https://ws4.sinaimg.cn/large/006tNc79gy1fkur06jz89j30io0dj3yo.jpg)

不知道开发者能不能对此有所改进，比如在Kcptun Port那里改成Kcptun server remote Port，并且在同一个界面中再加入一个Kcptun client local Port的填写位置。当选择enable kcp之后，上面之前填ss server端口的输入框可以隐藏（同一个输入框里端口的意义在enable kcp之前和之后发生了变化，容易造成歧义和困惑）。另外两个密码和加密方式可不可以分别注明是ss server的还是kcp server的，这里也让我引起了困惑。

虽然KCP的设置让我一时摸不着头脑，但是对于这样优秀易用的软件来说这种小问题是无伤大雅的。不过如果开发者可以优化一下这里的设计我将不胜感激。

**Comment by duzhen1996** [comment]
希望可以将两个界面整合起来。

**Comment by duzhen1996** [comment]
@idewindy ?

**Comment by monstertmh** [comment]
@duzhen1996 请问上下两个密码分别填写什么的密码呢？

**Comment by duzhen1996** [comment]
@monstertmh 你好，上面是ss-server的密码，下面是kcp-server的密码。也希望开发者大哥可以今早做出改进。

**Comment by monstertmh** [comment]
@duzhen1996 感谢，确实容易混淆，标注一下就更完美了！

**Comment by duzhen1996** [comment]
@monstertmh 没关系，现在kcp的设置确实容易让人困惑

**Comment by jokeroy** [comment]
到底怎么填啊，一直不对，kcp端口在哪个填

**Comment by jokeroy** [comment]
@duzhen1996

**Comment by flipphos** [comment]
软件设置里面填写，包括ss端口也是一样。不在服务器管理界面的。

**Comment by duzhen1996** [comment]
@jokeroy 你好，在偏好设置的kcptun填写本地端口，在ss端口设置上填远程的kcp server端口

**Comment by yangfeicheung** [comment]
上半部分填写的和没有使用kcptun的时候一样的，就是shadowsocks的server相关的信息，和kcptun本身无关，下半部分填写的是kcptun相关的部分，跟shadowsocks的server无关，是kcptun server的相关信息

**Comment by jokeroy** [comment]
@duzhen1996 本地端口随便填还是填服务器ip和端口？

**Comment by duzhen1996** [comment]
@jokeroy 本地端口是kcp client的端口
