### ISSUE TITLE
所以，shadowsocks是被禁了？这段时间一直都不能上Google等网站

### ISSUE THREAD

**Issue by budazhe** [shadowsocks/ShadowsocksX-NG#575]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by cdkd321** [comment]
neng yong ma, xianzai?

**Comment by unpin** [comment]
正常使用无问题，先检查你的代理服务器是否能正常访问

**Comment by kelvinkuo** [comment]
但是上不去网站，没法看自己的代理服务器地址啊

**Comment by budazhe** [comment]
查看代理服务器？现在怎么都上不去，连shadowsocks.com.hk都连不上。所以shadowsocks是彻底被墙了？

**Comment by AomoDa** [comment]
@budazhe  应该是这个版本的问题，我的是1.0版本的没有问题，然后用1.6.1也是无法使用，后来没办法还是用1。0.。。。。。。

**Comment by Asleepludan** [comment]
同前两天不能用。用的1.6.1版本，我的已经恢复了，但是速度很慢。
