### ISSUE TITLE
PAC自动模式去哪里编辑啊

### ISSUE THREAD

**Issue by since2004** [shadowsocks/ShadowsocksX-NG#577]
现在使用 PAC模式无法使用dropbox，使用白名单模式则国内的网慢

**Comment by timothyqiu** [comment]
AFAIK, you have to set the proxy in Dropbox manually.

Click the Dropbox icon in the menu bar, and click the gear icon. Select __Preferences...__ in the menu, and click the __Network__ tab. Fill in your proxy settings under the section appropriately labeled Proxy Settings. (SOCKS5, 127.0.0.1, and the `ss-local` port)

**Comment by isoyang** [comment]
在dropbox的首选项里打开网络，更改网络配置，如下图

![snip20171027_324](https://user-images.githubusercontent.com/1218257/32091528-30cb9d0e-bb27-11e7-9fce-9f6f3921f75a.png)

端口是ss里面的本地Socks5监听端口
