### ISSUE TITLE
 Mac Version 10.12.6   I can not connect shadowsocks , this is my  error log ,  who can help me?

### ISSUE THREAD

**Issue by zilinyo** [shadowsocks/ShadowsocksX-NG#578]
default	00:02:56.829578 +0800	Console	[0x7faf4d04d000] Created session
default	00:02:56.829945 +0800	Console	[0x7faf4d04d000] Decoding: C0 0x002A0027 0x0006354A 0x11111100 0x00000000 766
default	00:02:56.829980 +0800	Console	[0x7faf4d04d000] Options: 42x39 [FFFFFFFF,FFFFFFFF] 0001D060
default	00:02:56.830045 +0800	Console	[0x7faf4d04d000] Decoding completed without errors
default	00:02:56.830314 +0800	Console	[0x7faf4d04d000] Releasing session
default	00:02:56.997512 +0800	opendirectoryd	initiating reconnect of module connection
default	00:02:57.001467 +0800	opendirectoryd	queuing request to connection - '<private>'
default	00:02:57.001752 +0800	opendirectoryd	queuing request to connection - '<private>'
default	00:02:57.004168 +0800	opendirectoryd	cache miss with id type: 1
default	00:02:57.005213 +0800	opendirectoryd	queuing request to connection - '<private>'
default	00:02:57.005363 +0800	opendirectoryd	queuing request to connection - '<private>'
default	00:02:57.006447 +0800	opendirectoryd	cache miss with id type: 1
default	00:02:57.015661 +0800	opendirectoryd	queuing request to connection - '<private>'
default	00:02:57.015986 +0800	opendirectoryd	queuing request to connection - '<private>'
default	00:02:57.902624 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	00:02:57.902953 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
default	00:02:57.903311 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	00:02:57.905560 +0800	taskgated	MacOS error: -67062
default	00:02:57.935897 +0800	com.apple.WebKit.Networking	TIC TCP Conn Cancel [90:0x7f9dedd18230]
default	00:02:57.936100 +0800	com.apple.WebKit.Networking	TIC TCP Conn Destroyed [90:0x7f9dedd18230]
default	00:03:02.260443 +0800	identityservicesd	Saving database.
default	00:03:02.260513 +0800	identityservicesd	Beginning cleanup of outgoing message database
default	00:03:02.260602 +0800	identityservicesd	Destroying database.
default	00:03:02.284802 +0800	identityservicesd	Closed database.
default	00:03:02.288184 +0800	identityservicesd	Cleaned up 0 expired messages
default	00:03:02.288342 +0800	identityservicesd	Beginning cleanup of outgoing message database for quickswitched messages
default	00:03:02.288541 +0800	identityservicesd	Ending cleanup of outgoing message database for quickswitched messages
default	00:03:02.288577 +0800	identityservicesd	Beginning cleanup of outgoing message database for messages older than 2 days past enqueue date
default	00:03:02.288614 +0800	identityservicesd	Using Time Interval 530726582.288597
default	00:03:02.288847 +0800	identityservicesd	Ending cleanup of 0 outgoing message database for older than 2 days past enqueue date
default	00:03:02.289040 +0800	identityservicesd	Ending cleanup of outgoing message database
default	00:03:05.473612 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	00:03:05.473942 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
default	00:03:05.474303 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	00:03:05.481028 +0800	trustd	asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (taskgated[441])
default	00:03:05.481629 +0800	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (taskgated[441])
default	00:03:05.481957 +0800	ocspd	0x7ff715702a50 opened /private/var/db/crls/crlcache2.db: 29496 bytes
default	00:03:05.484376 +0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	00:03:07.507047 +0800	DuetHeuristic-BM	Rescoring all 64 activities [<private>]
default	00:03:07.522277 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:28.020000, denominator:28.020000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.523073 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:28.020000, denominator:28.020000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.523913 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:28.020000, denominator:28.020000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.524763 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:28.020000, denominator:28.020000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.525323 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:26.610000, denominator:29.010000, FinalDecision: Can Proceed FinalScore: 0.917270}
default	00:03:07.525374 +0800	DuetHeuristic-BM	'<private>' CurrentScore: 0.917270, ThresholdScore: 0.547560 DecisionToRun:1
default	00:03:07.526072 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:26.010000, denominator:28.010000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.526818 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:26.010000, denominator:28.010000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.527587 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:28.020000, denominator:28.020000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.528205 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:28.020000, denominator:28.020000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.528733 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:39.420000, denominator:39.420000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.529263 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:28.020000, denominator:28.020000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.529952 +0800	DuetHeuristic-BM	<private>:[
<private> ] sumScores:31.010000, denominator:33.010000, FinalDecision: Must Not Proceed FinalScore: 0.000000}
default	00:03:07.530010 +0800	DuetHeuristic-BM	Running activities : <private>
default	00:03:07.530567 +0800	DuetHeuristic-BM	Arming timer for activity <private>
default	00:03:07.530566 +0800	UserEventAgent	STARTING: <private>
default	00:03:07.531230 +0800	DuetHeuristic-BM	Setting timer (waking=1) between <private> and <private>
default	00:03:07.628574 +0800	UserEventAgent	Initiating XPC Activity: com.apple.helpd.sdmmap_building
default	00:03:07.645009 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	00:03:07.685380 +0800	helpd	Could not find access page in directory /System/Library/PrivateFrameworks/CoreChineseEngine.framework
default	00:03:07.929057 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	00:03:07.929723 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
default	00:03:07.930441 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	00:03:07.931436 +0800	taskgated	MacOS error: -67062
default	00:03:08.181672 +0800	UserEventAgent	Completed XPC Activity: com.apple.helpd.sdmmap_building
default	00:03:08.182696 +0800	DuetHeuristic-BM	COMPLETED <private>!
default	00:03:08.185318 +0800	UserEventAgent	Unregistered XPC Activity: com.apple.helpd.sdmmap_building
default	00:03:08.248426 +0800	helpd	Could not find access page in directory /System/Library/PrivateFrameworks/CoreChineseEngine.framework
default	00:03:09.482380 +0800	apsd	<APSCourier: 0x7f946e762d10>: Sending keep alive message via tcpStream: <APSTCPStreamMaster: 0x7f946e61f3d0>
default	00:03:09.784101 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	00:03:09.788009 +0800	helpd	0x7ff5ea52e720 opened /var/folders/6n/xm3z1f1x5sd37p3dtd3hgggm0000gn/C//mds/mdsObject.db: 4636 bytes
default	00:03:09.788515 +0800	helpd	0x7ff5ea42d2d0 opened /var/folders/6n/xm3z1f1x5sd37p3dtd3hgggm0000gn/C//mds/mdsDirectory.db: 50744 bytes
default	00:03:09.791302 +0800	helpd	0x7ff5ec85cce0 opened /var/folders/6n/xm3z1f1x5sd37p3dtd3hgggm0000gn/C//mds/mdsDirectory.db: 50744 bytes
default	00:03:09.794531 +0800	helpd	0x7ff5ec859a80 opened /Users/linzi/Library/Keychains/login.keychain-db: 208816 bytes
default	00:03:09.800817 +0800	helpd	0x7ff5ea7d4f70 opened /Library/Keychains/System.keychain: 33256 bytes
default	00:03:09.821169 +0800	helpd	TIC TCP Conn Start [1:0x7ff5ea43e310]
default	00:03:09.823004 +0800	helpd	PAC fetch start for <private>
default	00:03:09.834791 +0800	apsd	<APSCourier: 0x7f946e762d10>: Outstanding data received: <0d000000 00> (length 5)
default	00:03:09.834930 +0800	apsd	<APSCourier: 0x7f946e762d10>: Stream processing: complete yes, invalid no, length parsed 5, parameters {
    APSProtocolCommand = 13;
}
default	00:03:09.835001 +0800	apsd	<APSCourier: 0x7f946e762d10>: Received successful keep-alive response {
    APSProtocolCommand = 13;
}
default	00:03:09.835165 +0800	apsd	<APSCourier: 0x7f946e762d10>: Stream processing: complete no, invalid no, length parsed 0, parameters (null)
default	00:03:09.848134 +0800	helpd	Faulting in NSHTTPCookieStorage singleton
default	00:03:09.848191 +0800	helpd	Faulting in CFHTTPCookieStorage singleton
default	00:03:09.848226 +0800	helpd	Creating default cookie storage with process/bundle identifier
default	00:03:09.850479 +0800	helpd	TIC TCP Conn Start [2:0x7ff5ec844e60]
default	00:03:09.852632 +0800	helpd	TIC TCP Conn Event [2:0x7ff5ec844e60]: 1 Err(0)
default	00:03:09.852723 +0800	helpd	TIC TCP Conn Connected [2:0x7ff5ec844e60]: Err(0)
default	00:03:09.850895 +0800	kernel	necp_application_find_policy_match_internal: helpd(1645) does not hold the necessary entitlement to delegate network traffic for other processes by euuid
default	00:03:09.852169 +0800	kernel	necp_application_find_policy_match_internal: helpd(1645) does not hold the necessary entitlement to delegate network traffic for other processes by euuid
default	00:03:09.855846 +0800	helpd	TIC TCP Conn Event [2:0x7ff5ec844e60]: 2 Err(0)
default	00:03:09.856067 +0800	helpd	TIC TCP Conn Cancel [2:0x7ff5ec844e60]
default	00:03:09.856377 +0800	helpd	TIC TCP Conn Destroyed [2:0x7ff5ec844e60]
default	00:03:09.871064 +0800	helpd	PAC fetch end for <private>. data 0x7ff5ea542140 response 0x7ff5ec85f0b0 statusCode 200 error 0x0
default	00:03:11.272185 +0800	helpd	TIC TCP Conn Event [1:0x7ff5ea43e310]: 1 Err(0)
default	00:03:11.272294 +0800	helpd	TIC TCP Conn Connected [1:0x7ff5ea43e310]: Err(0)
default	00:03:11.272674 +0800	helpd	TIC Enabling TLS [1:0x7ff5ea43e310]
default	00:03:11.451292 +0800	helpd	TIC TLS Event [1:0x7ff5ea43e310]: 2, Pending(0)
default	00:03:11.453185 +0800	helpd	TIC TLS Event [1:0x7ff5ea43e310]: 11, Pending(0)
default	00:03:11.454591 +0800	helpd	TIC TLS Event [1:0x7ff5ea43e310]: 12, Pending(0)
default	00:03:11.454705 +0800	helpd	TIC TLS Event [1:0x7ff5ea43e310]: 14, Pending(0)
default	00:03:11.471064 +0800	helpd	TIC TLS Trust Result [1:0x7ff5ea43e310]: 0
default	00:03:11.678457 +0800	helpd	TIC TLS Event [1:0x7ff5ea43e310]: 20, Pending(0)
default	00:03:11.679393 +0800	helpd	TIC TCP Conn Event [1:0x7ff5ea43e310]: 8 Err(0)
default	00:03:11.679524 +0800	helpd	TIC TLS Handshake Complete [1:0x7ff5ea43e310]
default	00:03:11.876804 +0800	helpd	TIC TCP Conn Start [3:0x7ff5ec871040]
default	00:03:12.088752 +0800	helpd	TIC TCP Conn Event [3:0x7ff5ec871040]: 1 Err(0)
default	00:03:12.088825 +0800	helpd	TIC TCP Conn Connected [3:0x7ff5ec871040]: Err(0)
default	00:03:12.089018 +0800	helpd	TIC Enabling TLS [3:0x7ff5ec871040]
default	00:03:12.292863 +0800	helpd	TIC TLS Event [3:0x7ff5ec871040]: 2, Pending(0)
default	00:03:12.293100 +0800	helpd	TIC TLS Event [3:0x7ff5ec871040]: 20, Pending(0)
default	00:03:12.294600 +0800	helpd	TIC TCP Conn Event [3:0x7ff5ec871040]: 8 Err(0)
default	00:03:12.294659 +0800	helpd	TIC TLS Handshake Complete [3:0x7ff5ec871040]
default	00:03:14.153332 +0800	pboard	Installing local data provider: (uuid:C1C77E74-0105-440C-A542-5011AF0C88B2 gen: 9 item: 789514 flavor: 'public.utf8-plain-text') for gen: 9 index: 0 item: 789514
default	00:03:14.154097 +0800	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	00:03:14.154464 +0800	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 9, <private>
default	00:03:14.209046 +0800	pboard	Sending pasteboard update to server: <private>
default	00:03:14.209174 +0800	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	00:03:14.209964 +0800	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 9, <private>
default	00:03:14.387950 +0800	pboard	Installing local data provider: (uuid:195E1C82-C3E6-44B0-8E94-550774F53091 gen: 10 item: 789514 flavor: 'public.utf8-plain-text') for gen: 10 index: 0 item: 789514
default	00:03:14.388032 +0800	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	00:03:14.388310 +0800	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 10, <private>
default	00:03:14.441166 +0800	pboard	Sending pasteboard update to server: <private>
default	00:03:14.441300 +0800	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	00:03:14.441943 +0800	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 10, <private>
default	00:03:14.558597 +0800	pboard	Installing local data provider: (uuid:C7A1CF1B-4AB1-444A-898B-9429688ED158 gen: 11 item: 789514 flavor: 'public.utf8-plain-text') for gen: 11 index: 0 item: 789514
default	00:03:14.558697 +0800	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	00:03:14.558958 +0800	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 11, <private>
default	00:03:14.612848 +0800	pboard	Sending pasteboard update to server: <private>
default	00:03:14.613003 +0800	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	00:03:14.613636 +0800	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 11, <private>
default	00:03:14.649753 +0800	useractivityd	PICKING: 6147191A-1B16-4B3C-865C-B5EF46D27CF8/<private> as the current item-to-advertise.
default	00:03:15.501111 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	00:03:15.501357 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
default	00:03:15.501668 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	00:03:15.505133 +0800	trustd	asynchronously fetching CRL (http://crl.apple.com/timestamp.crl) for client (taskgated[441])
default	00:03:15.505329 +0800	trustd	asynchronously fetching CRL (http://crl.apple.com/root.crl) for client (taskgated[441])
default	00:03:15.506945 +0800	trustd	cert[2]: AnchorTrusted =(leaf)[force]> 0
default	00:03:17.943139 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	00:03:17.943405 +0800	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 20, EGID: 20
default	00:03:17.943784 +0800	opendirectoryd	Client: <private>, UID: 501, EUID: 501, GID: 20, EGID: 20
default	00:03:17.944814 +0800	taskgated	MacOS error: -67062
default	00:03:18.785969 +0800	pboard	Installing local data provider: (uuid:5BF5CBAE-2742-4599-9FF9-16BC49FF70E9 gen: 12 item: 789514 flavor: 'public.utf8-plain-text') for gen: 12 index: 0 item: 789514
default	00:03:18.786052 +0800	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	00:03:18.786355 +0800	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 12, <private>
default	00:03:18.836671 +0800	pboard	Sending pasteboard update to server: <private>
default	00:03:18.836790 +0800	pboard	[Local Pasteboard] Adding alias: public.text for type: public.utf8-plain-text
default	00:03:18.837387 +0800	useractivityd	[PBOARD CONTROLLER] Got type update from client, gen: 12, <private>
default	00:03:19.282474 +0800	useractivityd	PICKING: 6147191A-1B16-4B3C-865C-B5EF46D27CF8/<private> as the current item-to-advertise.
default	00:03:20.081287 +0800	symptomsd	rssi (-45) or transmitRate (52.000000) changed on interface en0 for BSSID:<private>
default	00:03:21.390785 +0800	com.apple.WebKit.WebContent	Current memory footprint: 90 MB

**Comment by jackpt** [comment]
try remove these
~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist
~/Library/Application Support/ShadowsocksX-NG/
then restart your x-ng , it works for me

**Comment by hankcocco** [comment]
i met the same problem

**Comment by ip192** [comment]
God! That works for me too @jackpt . BTY I use [https://shadowsocks.com](url)
