### ISSUE TITLE
切换服务器就连接不了，需要退出重启

### ISSUE THREAD

**Issue by littlee** [shadowsocks/ShadowsocksX-NG#584]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6
- Shadowsocksx-NG 1.6.1

**Expected behavior:**
切换服务器可以正常连接

**Actual behavior:**
切换服务器之后，不能正常连接，需要退出，重新启动
(N/A for feature requests)

**Steps to reproduce:**
点击图标，选择不是当前正在使用的其他服务器
(N/A for feature requests)

**How often does this happen?**
每一次切换服务器的时候
(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)
[ss-local.log](https://github.com/shadowsocks/ShadowsocksX-NG/files/1427496/ss-local.log)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by Lisupy** [comment]
I encountered the same problem with yours.

**Comment by yangfeicheung** [comment]
可能是因为切换的时候ss-local的启动和关闭失败了导致的，试试这个版本：
[shadowsocks x](https://github.com/yangfeicheung/Shadowsocks-X)
