### ISSUE TITLE
配置代理服务器后上不了外网 

### ISSUE THREAD

**Issue by bryant81pts** [shadowsocks/ShadowsocksX-NG#585]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6
- Shadowsocksx-NG 1.6.1

**Expected behavior:**
配置代理服务器后上不了外网 
代理服务器在其他设备可用
[ss-local.log](https://github.com/shadowsocks/ShadowsocksX-NG/files/1429960/ss-local.log)

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by timothyqiu** [comment]
It seems that Verbose Mode is not enabled, so there're not much useful information in `ss-local.log`.

Please follow the instructions in the issue template to enable Verbose Mode and get the resulting `ss-local.log`.

BTW, you can try `curl --socks5 127.0.0.1:1086 ip.cn` to verify if SSX-NG is working correctly. (Change the `1086` port if you ever changed the SOCKS5 listening port.)

**Comment by bryant81pts** [comment]
[ss-local.log](https://github.com/shadowsocks/ShadowsocksX-NG/files/1436604/ss-local.log)
Now I enable the Verbose Mode and this is my latest ss-local.log

When I try curl --socks5 127.0.0.1:1086 ip.cn, the feedback is curl: (52) Empty reply from server.

**Comment by itbdw** [comment]
➜  ~ curl --socks5 127.0.0.1:1086 ip.cn
curl: (7) Failed to connect to 127.0.0.1 port 1086: Connection refused

**Comment by budazhe** [comment]
我能说我的完全不能用了吗？所以ss到底是怎么了？指定的网址（https://portal.shadowsocks.com.hk）也上不了。

**Comment by yangfeicheung** [comment]
ng版本的http代理是独立的一个服务，可能会有依赖，这个版本的Shadowsocks X是可以用的，集成了http代理：
[https://github.com/yangfeicheung/Shadowsocks-X](https://github.com/yangfeicheung/Shadowsocks-X)

**Comment by xiaopanddxiong** [comment]
@yangfeicheung 感谢你提供的这个版本，现在可用正常作为代理使用了

**Comment by xiaopanddxiong** [comment]
@yangfeicheung 感谢你提供的这个版本，现在可用正常作为代理使用了

**Comment by YL0523** [comment]
> ➜ ~ curl --socks5 127.0.0.1:1086 ip.cn
> curl: (7) Failed to connect to 127.0.0.1 port 1086: Connection refused
同样的问题  请问你解决了没

**Comment by 850977164** [comment]
![image](https://user-images.githubusercontent.com/39330916/72771361-a2c86300-3c3b-11ea-98f9-7622ca218498.png)
我配置代理链接ho后，出现了这个问题
