### ISSUE TITLE
配置之后无法使用

### ISSUE THREAD

**Issue by 316956942** [shadowsocks/ShadowsocksX-NG#586]
手机配置之后可以使用，但是mac上使用不了。最新版本......

**Comment by dingquantracy** [comment]
是不是真的用不了了

**Comment by timothyqiu** [comment]
Please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.

**Comment by soladong** [comment]
在shadowsocksvpn网站买的，已经关闭了不知道能不能还不会不会恢复，总之完全用不了
