### ISSUE TITLE
9月初以后再也不能联网了，官网我的邮箱不知道为什么显示未注册，所以完全不能更新

### ISSUE THREAD

**Issue by breakstoner** [shadowsocks/ShadowsocksX-NG#588]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by breakstoner** [comment]
对了  我有支付凭据的 99元 8月份才买的

**Comment by timothyqiu** [comment]
The Shadowsocks open source project is not related to any SS service provider. The official website of this project is [shadowsocks.org](https://shadowsocks.org).

If you're having problem using `shadowsocks.com`, unfortunately, this is the wrong place to ask for help.

**Comment by duzhen1996** [comment]
你好，ss只是一个客户端，有问题请和VPN服务的提供商联系

**Comment by BingJin-Zheng** [comment]
更新最新的版本,就可以了,我用的是Mac,现在可以连外网!
