### ISSUE TITLE
新版本限量使用了?

### ISSUE THREAD

**Issue by Fov6363** [shadowsocks/ShadowsocksX-NG#589]
新版官网一个月限量50G,是刚推出还是之前就有的?
对于国内的补偿方案是什么?
官网地址: https://portal.shadowsocks.la/

**Comment by timothyqiu** [comment]
Please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.
