### ISSUE TITLE
希望rules可以支持多个list, server list可以和rule关联

### ISSUE THREAD

**Issue by kairyou** [shadowsocks/ShadowsocksX-NG#59]
- Rules像Servers那样, 有个列表可以切换.
- 或, server可以选择关联一个rule规则.

场景如下:

- 公司路由自带VPN, 常用域名都可以翻, 但是封了部分资源下载的站点(我需要用ss看这些.) 
- 而家里就是正常的流程了, 只需要翻真正被封的那些域名.

2个环境, 需要2个不同的规则.  
如果在公司或者家里, 每次都需要重新改下规则, 感觉略麻烦.

**Comment by qiuyuzhou** [comment]
Sorry，这种小众需求，没时间做。欢迎发PR来
