### ISSUE TITLE
不能上网了,ShadowsocksX-NG不行

### ISSUE THREAD

**Issue by BingJin-Zheng** [shadowsocks/ShadowsocksX-NG#590]
咋回事?有教程没?

**Comment by timothyqiu** [comment]
Please refer to the [Issue Template](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/ISSUE_TEMPLATE.md) and provide at least the `ss-local.log`.

**Comment by tempzc** [comment]
[ss-local.log](https://github.com/shadowsocks/ShadowsocksX-NG/files/1436704/ss-local.log)

**Comment by gpanda** [comment]
same issue，same log, please help

**Comment by huangzonghao** [comment]
用的那个服务提供商挂了，不是软件的问题，可以试一下别的提供ssr的服务商

**Comment by gpanda** [comment]
Sorry, it works now. My ShadowsocksX-NG.app(v1.3.1) was out of date, after changed to v1.6.1 and configured it with the *exact* cipher algorithm used by my service provider, everything is fine again.

**Comment by BingJin-Zheng** [comment]
我这边用的是ShadowsocksX-NG 配合谷歌浏览器中的插件Proxy SwitchyOmega 使用,然后现在还翻不了墙

**Comment by BingJin-Zheng** [comment]
[ss-local.log](https://github.com/shadowsocks/ShadowsocksX-NG/files/1437349/ss-local.log)
已经在使用的地址?重了?

**Comment by duzhen1996** [comment]
你好，ss只是一个客户端，有问题请和VPN服务的提供商联系

**Comment by BingJin-Zheng** [comment]
好的,我知道是个客户端,我把最新的下载下来了,官网提供的客户端不是最新的,不好意思,一直没注意这个版本!可以把这个问题关闭了!
