### ISSUE TITLE
昨天公告恢复，但是window10的机子可以，mac不行，求解。

### ISSUE THREAD

**Issue by yangyiRunning** [shadowsocks/ShadowsocksX-NG#591]
目前windows可以，mac不行，都是用的同样的账号和配置信息。

**Comment by WaterChan** [comment]
windows不知道，但是我在Mac运行是正常的，你是不是要再检查一下？

**Comment by ip192** [comment]
我的Mac也不行, 客户端是刚从 [https://portal.shadowsocks.la/index.php?rp=/download](url) 下载的。

**Comment by yangyiRunning** [comment]
@ip192   用brew把shadow更新到最新版本，然后按照公告上说的关了停10分钟retry，然后还是不行，你那边能连上了么？
