### ISSUE TITLE
开放访问之后，更新服务器配置信息，一直连不上

### ISSUE THREAD

**Issue by bazhuang** [shadowsocks/ShadowsocksX-NG#592]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5 
- Shadowsocksx-NG 1.6.1

**Expected behavior:
能够访问外网

**Actual behavior:
无法连接，日志显示
remote_recv_cb_recv: Connection reset by peer
已经将服务器通过扫码屏幕二维码方式同步到软件中来了

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**
[ss-local.log](https://github.com/shadowsocks/ShadowsocksX-NG/files/1439969/ss-local.log)

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by timothyqiu** [comment]
Please check your server configuration manually in case the QR code is not recognized correctly.

p.s. If you use the wrong configuration, you may be banned by the server automatically after several failed attempts.

**Comment by qiuyuzhou** [comment]
找你的服务提供商
