### ISSUE TITLE
shadowsocks使用指南

### ISSUE THREAD

**Issue by tangxuelong** [shadowsocks/ShadowsocksX-NG#593]
使用指南
https://portal.shadowsocks.la/aff.php?aff=12091

加密方式需要設置為 chacha20-ietf-poly1305 ，必須完全一致
舊版本客戶端可能不支持該加密方式，請更新

• Windows  客戶端下載 https://portal.shadowsocks.la/files/Shadowsocks-4.0.6.zip 注：需要安裝 .NET FrameWork 4.6.2 以上版本

• iOS  相關客戶端與使用方法請參考下述鏈接： https://github.com/Shadowsocks-Wiki/shadowsocks/blob/master/4-ios-settings.md

• MAC OS  請更新到 ShadowsocksX-NG 使用 下載地址： https://portal.shadowsocks.la/files/ShadowsocksX-NG.1.6.1.zip

• Android下載地址  下載地址： https://portal.shadowsocks.la/files/shadowsocks-nightly-4.2.5.zip

• Linux用戶  請使用最新的 Shadowsocks-libev 命令行版本 安裝與使用請參考：https://github.com/shadowsocks/shadowsocks-libev

Best Regards,
Shadowsocks.com Team

**Comment by AnyoeDove** [comment]
**请不要在这里臭不要脸的推销伪官网并加上自己的 aff，issue 不是这样滥用的。**
