### ISSUE TITLE
ubuntu16无法使用

### ISSUE THREAD

**Issue by Zuckjet** [shadowsocks/ShadowsocksX-NG#596]
本人的ubuntu16系统今天突然无法科学上网．　能连接上去，但是连上去几乎没有速度，浏览器打开网站无反应．
同一账号，在mac上可以正常使用，在ubuntu上就无法使用．不过mac上我是用的shadowsocksX NG．
请问有人遇到和我一样的情况吗？

**Comment by Lisupy** [comment]
Check your configuration in the shadowsocks。By the way，on Linux， you can use shadowsrocks-qt5 as the GUI client
