### ISSUE TITLE
SSR for Mac最近只能用全局模式了？

### ISSUE THREAD

**Issue by susozhang** [shadowsocks/ShadowsocksX-NG#597]
全局模式才能访问，自由模式不行，Mac版和Windows   ##版本都有问题，iOS则OK，是啥原因？

**Comment by mengdodo** [comment]
我的是ShadowsocksX-NG 1.6.1 mac下全局模式有效，
pac模式能运行gfw list更新下的规则，
自己添加pac规则测试百度还是走的本机IP
使用的规则：||baidu.com^

**Comment by mengdodo** [comment]
抱歉，我好像找到原因了
It's because jd.com is whitelisted in GFW List. #335 

白名单的优先级高于黑名单

**Comment by susozhang** [comment]
好像没有讨论如何解决自由模式如何生效？

**Comment by mengdodo** [comment]
@susozhang 
我觉得这应该是你想要的 。 #27

**Comment by susozhang** [comment]
后来删除gfw list文件然后在更新一下即可实现Pac模式有效
