### ISSUE TITLE
打开ss，无法登陆外网，路线正确 设置正确，打开之后等于是断网，麻烦解答下问题，谢谢。

### ISSUE THREAD

**Issue by joygavin** [shadowsocks/ShadowsocksX-NG#599]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by huodon** [comment]
我从老板本切换到1.6后也变成了这样.

**Comment by skyerforce** [comment]
同样的问题 待解决

**Comment by yangfeicheung** [comment]
发截图给我，我帮看下，直接mail给我就好，yangfei.cheung@gmail.com
