### ISSUE TITLE
小白问题，老版本ss2.6.3换到xng1.6.1，该如何配置可让chrome插件switchyomega

### ISSUE THREAD

**Issue by aspieteer** [shadowsocks/ShadowsocksX-NG#602]
ss2.6.3版本使用时，小飞机在PAC模式关闭状态下，可使用Chrome下的switchy omega愉快玩耍，更换到NG1.6.1时不更改设置Chrome便提示无网络连接，求教该如何设置，（和High Sierra系统有关系吗？），另外从这里下载的app安装就是直接拖到application文件夹，那该如何彻底卸载？

- macOS 10.13.1
- Shadowsocksx-NG 1.6.1
- Chrome 62.0.3202.89 (x64)
- SwitchyOmega 2.5.6

**Comment by osirisjaret** [comment]
貌似我这里也出问题了
