### ISSUE TITLE
macOS 10.12.6 无法连接服务器

### ISSUE THREAD

**Issue by quan-xie** [shadowsocks/ShadowsocksX-NG#605]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 
- Shadowsocksx-NG 1.6.1

**Expected behavior:**

无法连接服务器

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by haopengfly** [comment]
请问日志这里具体怎么操作

**Comment by zcjim2003** [comment]
服务器设置里不要打开: Enable OTA (deprecated)，我的不知道为何默认开了……
