### ISSUE TITLE
终端export后并没有代理

### ISSUE THREAD

**Issue by note286** [shadowsocks/ShadowsocksX-NG#607]
**System and Shadowsocksx-NG version:**

- macOS 10.13.1
- Shadowsocksx-NG 1.6.1(1)

情况是这样的，以前我使用的是 [ShadowsocksX-2.6.3.dmg](https://github.com/shadowsocks/shadowsocks-iOS/releases)

出问题在终端代理上，使用ShadowsocksX-2.6.3.dmg的时候，我只需要在终端里输入`export ALL_PROXY=socks5://127.0.0.1:1080`，然后再执行`curl ip.cn`是可以显示出代理服务器IP信息的，说明终端代理是可以的

但是使用ShadowsocksX-NG的时候，使用自带的复制export功能，即`export http_proxy=http://127.0.0.1:1087;export https_proxy=http://127.0.0.1:1087;` ，然后再执行`curl ip.cn`就会报错，错误如下：

```
<html>
<head>
 <title>500 Internal Privoxy Error</title>
 <link rel="shortcut icon" href="http://config.privoxy.org/error-favicon.ico" type="image/x-icon"></head>
<body>
<h1>500 Internal Privoxy Error</h1>
<p>Privoxy encountered an error while processing your request:</p>
<p><b>Could not load template file <code>forwarding-failed</code> or one of its included components.</b></p>
<p>Please contact your proxy administrator.</p>
<p>If you are the proxy administrator, please put the required file(s)in the <code><i>(confdir)</i>/templates</code> directory.  The location of the <code><i>(confdir)</i></code> directory is specified in the main Privoxy <code>config</code> file.  (It's typically the Privoxy install directory, or <code>/etc/privoxy/</code>).</p>
</body>
</html>
```

两个软件我都是选择的全局代理，求问是哪里我没有配置对吗？？

ShadowsocksX-NG开启代理后，Safari是可以走代理的，只是终端export不能代理。

**Comment by BrandoZhang** [comment]
我也出现了同样的问题

**Comment by note286** [comment]
@BrandoZhang 终端代理的时候我使用ShadowsocksX，其他的时候使用Shadowsocksx-NG，反正同时开启也不冲突，他俩的端口是不一样的，所以也算是勉强解决了问题，不是很影响使用。

**Comment by BrandoZhang** [comment]
@note286 实测 ShadowsocksX-NG 1.7.0(1) 可以使用。
配置方法参考了 [雷鸣的博客-Mac命令行代理配置](http://willwei.me/2017/09/11/Mac%E5%91%BD%E4%BB%A4%E8%A1%8C%E4%BB%A3%E7%90%86%E9%85%8D%E7%BD%AE/)

**Comment by note286** [comment]
@BrandoZhang 我不我看后面的那个还是那样子，我没测试，是软件修复了吗？

**Comment by BrandoZhang** [comment]
@note286 应该是的，我这里问题已经解决了， `pon curl ip.cn` 显示的是代理服务器的地址。

**Comment by note286** [comment]
@BrandoZhang 好的，非常感谢，我一会试一下！
