### ISSUE TITLE
ShadowsocksX-NG 间歇性不可用的恢复办法

### ISSUE THREAD

**Issue by xicilion** [shadowsocks/ShadowsocksX-NG#613]
已经数次用这个方法恢复使用了。

一、停止 ShadowsocksX-NG 并卸载
二、进入 ./Library/Application Support
三、rm -rf ShadowsocksX-NG
四、重新安装 ShadowsocksX-NG (要不要重启我不记得了)

希望对大家有用。

**Comment by cuyl** [comment]
我pac模式就有时断，每次都要切到Global 模式一会再切回来

**Comment by Liqiankun** [comment]
@xicilion @cuyl 是不是High Sierra?

**Comment by xicilion** [comment]
@Liqiankun 是 High Sierra.

**Comment by cuyl** [comment]
@Liqiankun 是的
