### ISSUE TITLE
全局模式不可用

### ISSUE THREAD

**Issue by Ihindng** [shadowsocks/ShadowsocksX-NG#614]
**系统信息**
- macOS 10.12.6 (16E????)
- Shadowsocksx-NG 1.6.1

自动代理和手动模式无问题，全局模式不可用

**ss-local.log**
无输出

**Comment by yangfeicheung** [comment]
try this one,it has more modes & supports ad-blocking
[https://github.com/yangfeicheung/Shadowsocks-X](url)
