### ISSUE TITLE
ShadowsocksX-NG无法使用，老版本可以

### ISSUE THREAD

**Issue by vagrant1991** [shadowsocks/ShadowsocksX-NG#615]
自己搭建的服务器也不可以，https://portal.shadowsocks.la/clientarea.php 这里购买的服务器也不可以。

**Comment by ProfFL028** [comment]
请问下，老版是哪个，我下了1。6和1。6。1都不可以

**Comment by yangfeicheung** [comment]
试试这个
[https://github.com/yangfeicheung/Shadowsocks-X](https://github.com/yangfeicheung/Shadowsocks-X)

**Comment by zhaojiankai** [comment]
要注意手动把之前版本的关闭，不是直接退出，或者可以直接重启电脑。
