### ISSUE TITLE
Not stable under High Sierra

### ISSUE THREAD

**Issue by Liqiankun** [shadowsocks/ShadowsocksX-NG#616]
**System and Shadowsocksx-NG version:**

- macOS 10.13.1 
- Shadowsocksx-NG 1.6.1?

**Comment by yangfeicheung** [comment]
Try this one,I've used this and it works fine on Sierra
[https://github.com/yangfeicheung/Shadowsocks-X](https://github.com/yangfeicheung/Shadowsocks-X)

**Comment by Liqiankun** [comment]
@yangfeicheung  I tried this one, but It seems like it has the same issue! I will try it again!

**Comment by yangfeicheung** [comment]
Hi,I’m the developer,tell me what the issue is,I’m gonna solve it,the original version has one issue,and I’ve already fixed it,u cud download and try again. Feel free to tell me if there’s more issue

**Comment by Liqiankun** [comment]
@yangfeicheung Sure

**Comment by Liqiankun** [comment]
It goes well this time! Last time It gave me many alertViews, requires me to input my password.

**Comment by yangfeicheung** [comment]
Yup,that’s the issue I’m talking about,I’ve fixed it and hope u enjoy it,thanks, if possible,give it a 5-star rate on app-store,thanks^_^
and feel free to contact me, if there’s other issues or some missing function

**Comment by Liqiankun** [comment]
Sure! Why not!

**Comment by Liqiankun** [comment]
@yangfeicheung I did see it on App store! Give me the link!

**Comment by yangfeicheung** [comment]
It’s in the us store,  https://itunes.apple.com/app/shadowsocks-x/id1295053131?ls=1&mt=8 <https://itunes.apple.com/app/shadowsocks-x/id1295053131?ls=1&mt=8>

**Comment by Liqiankun** [comment]
Ok I got it !
