### ISSUE TITLE
开启ss后，本地hosts配置的域名均无法访问

### ISSUE THREAD

**Issue by Fennay** [shadowsocks/ShadowsocksX-NG#617]
**System and Shadowsocksx-NG version:**

- macOS 10.12.5 (16F73)
- Shadowsocksx-NG 1.6.1

请问下，Mac系统下，开启ss后，本地hosts配置的域名均无法访问（访问Nginx web服务）
直接访问localhost或者是127.0.0.1是可以直接访问Nginx服务器，
关闭ss后，localhost,127.0.0.1，自行配置的域名都可以访问

说明：
全局模式和PAC模式下都有此问题
公司Windows10系统，没有此问题

错误提示如下：
![image](https://user-images.githubusercontent.com/4941514/32991303-a2b53890-cd73-11e7-941d-f363b064dfa3.png)

**Comment by mengdodo** [comment]
确实是这样的，本地host不走了，全跑到ss上去了

**Comment by Fennay** [comment]
@mengdodo 没有别的的解决办法么，
公司用的windows10 系统，PAC模式没有这个问题，
很奇怪，不知道如何解决

**Comment by zhaojiankai** [comment]
自定义 pac应该可以的吧，@@||blog.dev

**Comment by Fennay** [comment]
@zhaojiankai 尝试了下，还是不行

**Comment by yangfeicheung** [comment]
这个应该是默认的dns解析导致的，因为比方说全局模式，解析会直接走server端，忽略掉本地的dns解析，这也是为了防止dns污染的初衷，我修改了一个版本，应该可以解决您说得的这个问题，具体的操作就是先现在这个版本的app，
[https://github.com/yangfeicheung/Shadowsocks-X/releases](https://github.com/yangfeicheung/Shadowsocks-X/releases)
然后在在偏好设置界面，把hosts里面对应的域名，添加到如下的红框里，用逗号分割
![image](https://user-images.githubusercontent.com/33145750/33975775-c16d51f8-e0cb-11e7-8ba0-dbe15d95a7ab.png)

如果有问题，可以发mail给我

**Comment by Fennay** [comment]
@yangfeicheung 非常感谢您，更新了这个版本后，似乎没有这个问题了，
我先使用下，如果还有问题，那还得请教下您
