### ISSUE TITLE
自已搭的服务器端一直无法使用ShadowsocksX-NG，ShadowsocksX则正常

### ISSUE THREAD

**Issue by xiebruce** [shadowsocks/ShadowsocksX-NG#618]
请问用这种方式：http://morning.work/page/2015-12/install-shadowsocks-on-centos-7.html 自己安装的服务器端为什么无法使用ShadowsocksX-NG.1.6.1 ？只能用ShadowsocksX？NG版本需要安装哪个服务器端？另外，到底哪个版本好？

**Comment by yangfeicheung** [comment]
兼容的，应该没什么问题，看你的具体问题是出在哪里

**Comment by HaoChuan9421** [comment]
我也是这个问题,同求

**Comment by r2for** [comment]
NG版本对于的服务器版本应该是shadowsocksR的版本！
但是OSX的的NG版本客户端类似没有加入混淆参数选择与定义，协议默认也只能是origin~混淆默认类似也默认的plain

**Comment by r2for** [comment]
如果要使用R版本搭建的服务器，那么需要在服务器上默认协议必须是origin,混淆设置为plain~
测试过，可以使用~

**Comment by yangfeicheung** [comment]
对的，ng版本还没添加混淆这个功能

**Comment by r2for** [comment]
而且屏幕录入二维码类似也不好用~ 嘿嘿~

**Comment by yangfeicheung** [comment]
怎么个不好用法？

**Comment by r2for** [comment]
not found valid qrcode of shadowsocks profile
客户端系统报告：
unknown key for boolean: _HighBitsASLR

**Comment by yangfeicheung** [comment]
@r2for  你可以mail一个测试的二维码给我，我看看
