### ISSUE TITLE
PAC自定义规则好像经常抽风

### ISSUE THREAD

**Issue by HasjOH** [shadowsocks/ShadowsocksX-NG#624]
比如进入Github并没有加速，反而要开全局

**Comment by yangfeicheung** [comment]
要添加自定义规则的，而且域名不会仅仅限于github.com，比如download的内容就不是github.com

**Comment by gMan1990** [comment]
@HasjOH @yangfeicheung 这个用户自定义pac要怎么添加？比如要添加telegram.org走代理，，（我怎么看不懂rule。。。

**Comment by gMan1990** [comment]
@HasjOH @yangfeicheung 这个用户pac要怎么加？
比如我要让  t.me  走代理
![image](https://user-images.githubusercontent.com/5050994/33613595-ff24c64c-da0f-11e7-987e-dccf1b557202.png)

**Comment by yangfeicheung** [comment]
@gMan1990  这个规则说实话，我看了，没记住，有点别扭，你可以尝试看下里面的规则连接，或者尝试下我改写的版本，我简化了规则

**Comment by anticpc** [comment]
@HasjOH 因为Github并没有被墙(哪怕是访问速度慢)，所以在规则里是不走代理。
