### ISSUE TITLE
Move to Applications folder?

### ISSUE THREAD

**Issue by gMan1990** [shadowsocks/ShadowsocksX-NG#625]
**System and Shadowsocksx-NG version:**

- macOS 10.13.1 (17B48)
- Shadowsocksx-NG 1.6.1

--------------------
![image](https://user-images.githubusercontent.com/5050994/33237774-f26c753a-d2b7-11e7-97a1-1ecf241b9e05.png)
----------------
how to ,,,,,,,, Move shadowsocks to Applications folder?

**Comment by yangfeicheung** [comment]
isn't it already in the applications folder?wot r u trying to to do?

**Comment by gMan1990** [comment]
@yangfeicheung 
、这个app有个mount，为什么其它APP不会有，，，，，我记得初次运行iterm2的时候会提示“Move to Applications folder”，类似这样：https://camo.githubusercontent.com/38d2e0b5ede085cd11148620fdc630cba24f29fc/687474703a2f2f692e696d6775722e636f6d2f657554525a69492e706e67,    然后就没有mount了。。。。
、可以试着搜搜这个AppTranslocation，这个是什么？

**Comment by yangfeicheung** [comment]
@gMan1990  I guess that has nothing to do with shadowsocks,and it's kinda like a tradition that we always move app to Applications folder,as the msg suggested: keep your downloads folder uncluttered^_^, you can contact me for more details.

**Comment by timothyqiu** [comment]
It's a macOS security feature. The App is already in `/Applications`, but the system creates a temporary disk image every time before launch.

It seems that you moved `ShadowsocksX-NG.app` from `~/Downloads` to `/Applications` without using Finder (e.g. by the `mv` command).

From Apple Tech Note: https://developer.apple.com/library/content/technotes/tn2206/_index.html
> This practice avoids an attack where a validly signed app launched from a disk image, ZIP archive, or ISO (CD/DVD) image can load malicious code or content from untrusted locations on the same image or archive. Starting with macOS Sierra, running a newly-downloaded app from a disk image, archive, or the Downloads directory will cause Gatekeeper to isolate that app at a unspecified read-only location in the filesystem. This will prevent the app from accessing code or content using relative paths.

Detailed explanation and a simple solution: https://lapcatsoftware.com/articles/app-translocation.html
> If you move the app, using Finder, from the app's original unarchived location to another folder, even a subfolder, e.g., ~/Downloads/Test/, then App Translocation does not occur. However, if you move the app using mv from Terminal, then App Translocation will still occur. Normally you would move the app from ~/Downloads to /Applications, and that would cause the app to be launched from /Applications like normal, but the locations of the particular folders don't seem to matter.
> **The mere act of moving the app using Finder stops App Translocation from happening.** Indeed, once you've moved the app once, it will no longer experience App Translocation again, even if you then move it back to ~/Downloads.

**Comment by gMan1990** [comment]
@timothyqiu 3q,,,  got it !!!
