### ISSUE TITLE
Mac os使用proxifier+SS全局代理失败，无法接收数据

### ISSUE THREAD

**Issue by beichen98** [shadowsocks/ShadowsocksX-NG#626]
自己在阿里云租了个内地IP的ECS部署了SS代理，然后本地SS配合proxifier来代理音乐客户端，windows平台下昨天测试成功，安卓也是好用的

但是mac os里SS好用，proxifier不好用，只能发送，不能接受
我在VPS的防火墙规则和阿里云的防火墙规则都已经对我mac 的IP放行了，而且SS好用应该就说明SS本身没有问题，proxifier转换的时候无法接受数据如何解决？

目前了解到SS-NG的本地监听端口是1086，在proxifier也是这么设置的还是不行，请问如何解决？

还有一点就是我用proxycap 设置同样的代理好用，端口都是1086，proxy就能成功代理，两个都是下载的最新版，感觉好奇怪，难道是和我windows端的冲突了吗？

![image](https://user-images.githubusercontent.com/33040796/33244682-97815188-d2b0-11e7-9e41-74827ac61d97.png)

**Comment by yangfeicheung** [comment]
你要实现什么功能？听qq音乐之类的ip不受限制？

**Comment by beichen98** [comment]
是的，用途就是使用本地需要使用国内IP的客户端，主要是视频和音乐
顺道问一下，我怎么回复你的回复啊？

**Comment by yangfeicheung** [comment]
我也不太熟悉，就是会 @beichen98, 你加下我，我帮你看下问题

**Comment by huzs1622** [comment]
我的也是一样的问题

**Comment by yangfeicheung** [comment]
可以尝试看下我修改的版本,已经实现了这个功能：

https://github.com/yangfeicheung/Shadowsocks-X/releases
