### ISSUE TITLE
High-perf GPU & QRCode

### ISSUE THREAD

**Issue by HippoBaro** [shadowsocks/ShadowsocksX-NG#627]
**System and Shadowsocksx-NG version:**

- macOS 10.13.1 (17B48)
- Shadowsocksx-NG 1.6.1 (1)

**Expected behavior:**

ShadowsocksX-NG should not require High-perf GPU to save battery-life.

**Actual behavior:**

ShadowsocksX-NG requires High-perf GPU (cf. Activity Monitor, Tab Energy). Requiring this prevents macOS from putting the discrete GPU to sleep, which hurts battery-life significantly.

**Steps to reproduce:**

Start ShadowsocksX-NG, and display the QR code for the current server.

**How often does this happen?**

N/A

**Comment by HippoBaro** [comment]
A simple way to circumvent this issue would be to add `NSSupportsAutomaticGraphicsSwitching` to `false` inside Info.plist. I don't have a working Xcode to test, though.

**Comment by qiuyuzhou** [comment]
Hi，this have been fixed in develop branch.
Hippolyte Barraud <notifications@github.com>于2017年11月28日 周二下午3:37写道：

**Comment by HippoBaro** [comment]
Ah, didn't see that. Sorry!
