### ISSUE TITLE
只有谷歌系的网站无法连接

### ISSUE THREAD

**Issue by yangboy0811** [shadowsocks/ShadowsocksX-NG#630]
**System and Shadowsocksx-NG version:**

- macOS 10.13.1 
- Shadowsocksx-NG 1.6.1

**Expected behavior:**
在打开shadowsocks设置好服务器之后，可以更新PAC，其他的外网（yahoo、Wikipedia、facebook等）都可以上，但是google、youtube等谷歌系的就不可以，不知道原因为何？

**Comment by liruqi** [comment]
我自己测试是可以的。
你的服务器在其它客户端上测试过么？感觉有可能是你服务器问题。

**Comment by yangboy0811** [comment]
我在win平台下和ios平台下都没有任何问题，但就是使用mac时会有问题。

**Comment by yangboy0811** [comment]
刚发现我关了代理之后，在mac条件下上Pinterest、github也是没问题，这是说明电脑之前装过别的代理是吗？

**Comment by Lax** [comment]
看看是不是hosts文件里绑定ip了

**Comment by CUGbaoyi** [comment]
同样的问题...

**Comment by yangboy0811** [comment]
有个不知原因的解决办法：使用二维码来配置shadowsocks，而不是自己手动敲！

**Comment by yangfeicheung** [comment]
Try this one, I can use it to access all google service:

https://github.com/yangfeicheung/Shadowsocks-X
