### ISSUE TITLE
我把http代理监听和socket5代理监听都改成了0.0.0.0，但局域网内其他机器连不上

### ISSUE THREAD

**Issue by jaredhu** [shadowsocks/ShadowsocksX-NG#632]
macOS  10.13.1
Shadowsocksx-NG 1.6.1

安装好后，我在偏好设置里面，把socket5本地监听地址和http监听代理地址都改成了0.0.0.0，局域网其他机器连不上，看配置你这个也是用的privoxy，可以理解成是内置了privoxy？
为什么必须另外安装一个privoxy代理，局域网其他机器才能使用？本身是否有提供这种功能？

**Comment by qiuyuzhou** [comment]
先检查你的mac防火墙
