### ISSUE TITLE
不能下载Youtube视频

### ISSUE THREAD

**Issue by laudaniel** [shadowsocks/ShadowsocksX-NG#636]
为什么我用Shadowsocks上网，能在线看Youtube，但不能下载的，我换其他VPN是可以正常下载的，请问是什么原因？如何可以解决？

**Comment by Lax** [comment]
你用什么方式下载的？

先确认下载有没有经过shadowsocks。浏览器下载是经过代理的，如果是下载工具可能需要在软件里设置代理。
