### ISSUE TITLE
macOS 10.13.1 can not work.

### ISSUE THREAD

**Issue by samforit** [shadowsocks/ShadowsocksX-NG#640]
- macOS 10.13.1
- Shadowsocksx-NG 1.6.1

Can not work.

I tried to reinstall , but there is no use.

**Comment by gMan1990** [comment]
i can

**Comment by zhangmingjing0** [comment]
我的mac是10.13.2，shadowsocks-ng和shadowsocks-ng-r8不能用，shadowsocksx可以用。今天把试试把launchctl load 改成launchctl load -w，可以了！

**Comment by yangfeicheung** [comment]
[ssx-mac-v14.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/1559962/ssx-mac-v14.zip)
试试这个版本

**Comment by wjzhao** [comment]
@zhangmingjing0 你好，我系统升级成10.13.2后，发现shadowsocks-ng 一直用不了，我下载 shadowsocksx发现还是用不了，不知道你是怎么解决的，请求帮助啊！！！

**Comment by lawpro** [comment]
Mac OS 10.13.2    Shadowsocks-NG 1.6.1 没有问题的。
建议你重启后试试。

**Comment by yangfeicheung** [comment]
@wjzhao 您可以发截图，我帮您看下

**Comment by zhangmingjing0** [comment]
@wjzhao 
您可以发一下配置截图，日志信息。

**Comment by samforit** [comment]
[https://github.com/yichengchen/ShadowsocksX-R/releases](https://github.com/yichengchen/ShadowsocksX-R/releases)
这个版本可用，解决了。
