### ISSUE TITLE
请教一下如何跟踪某个网站涉及哪些域名？以便添加自定义pac

### ISSUE THREAD

**Issue by hcpub** [shadowsocks/ShadowsocksX-NG#641]
拿QQ的群通知地址来说  http://web.qun.qq.com/announce/index.html#gc=145389303
我用全局代理能打开，但是用pac模式，在safari下用开发模式看了网页源文件后，加了 qq.com，idqqimg.com，url.cn三个域名，也还是不能打开。

估计可能跟url.cn是腾讯的短域名解析服务有关，真正域名被隐藏了。
也可能是用了一些cgi、js等，看不到直接调用了哪些资源

请教有什么好办法能跟踪某个地址在打开过程中共涉及到了哪些域名，以便手工添加pac

**Comment by gMan1990** [comment]
> 以便手工添加pac

你知道怎么添加么？https://github.com/shadowsocks/ShadowsocksX-NG/issues/646

**Comment by Chandler-Lu** [comment]
抓包

**Comment by yangfeicheung** [comment]
可以使用wireshark抓包看看，然后直接添加ip，如果一定要域名，可以参考一下我修改的版本的规则，网站通配符使用*
*.somesite.com 或者直接ip就可以，如果有不清楚的地方，可以mail我，我帮您看下。
NG版本PAC的添加规则比较繁琐，如果要高度定制，先看一下以下的规则：
https://adblockplus.org/en/filter-cheatsheet

**Comment by ismejun** [comment]
F12开发人员工具打开，红色错误里面就是没有加载成功的

**Comment by qiuyuzhou** [comment]
Try chrome plugin proxy-switchyomega
