### ISSUE TITLE
服务端kcp-server，怎么配置ShadowsocksX-NG

### ISSUE THREAD

**Issue by xyz3282836** [shadowsocks/ShadowsocksX-NG#644]
服务端kcp-server（https://github.com/clangcn/kcp-server），怎么配置ShadowsocksX-NG
服务端运行socks5和kcp-server，替换了ss
那么ShadowsocksX-NG支持配置吗？

**Comment by yangfeicheung** [comment]
支持的，直接在server编辑界面填入kcp相关的信息即可
