### ISSUE TITLE
1.7.0在macOS 10.13.2下闪退

### ISSUE THREAD

**Issue by HasjOH** [shadowsocks/ShadowsocksX-NG#645]
**System and Shadowsocksx-NG version:**

- macOS 10.13.2
- Shadowsocksx-NG 1.7.0

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by msongz** [comment]
10.12.6 也是閃退

**Comment by xyz3282836** [comment]
10.13.2 没有闪退啊 （1.7.2）

**Comment by ahlixinjie** [comment]
确实会闪退 用前一个版本正常

**Comment by yangfeicheung** [comment]
闪退的crash log呢？ 有可能是某些冲突导致的，或者是权限问题，具体要看crash log。
可以尝试一下我修改的版本：[Shadowsocks X](https://github.com/yangfeicheung/Shadowsocks-X)

**Comment by duxiaofeng-github** [comment]
+1
