### ISSUE TITLE
PAC自定义规则要怎么配置？？？

### ISSUE THREAD

**Issue by gMan1990** [shadowsocks/ShadowsocksX-NG#646]
System and Shadowsocksx-NG version:
macOS 10.13.1 (17B48)
Shadowsocksx-NG 1.6.1

这个用户pac要怎么加？比如我要让 t.me走代理，里面的说明我看的懂一些就是配置不成功
![image](https://user-images.githubusercontent.com/5050994/33613595-ff24c64c-da0f-11e7-987e-dccf1b557202.png)

old: 之前的ShadowsocksX是按域名配置的。

**Comment by yangfeicheung** [comment]
这个参考里面给出的网址，按照规则添加即可，如果觉得比较繁琐，可以试试我的版本，直接添加类似
*.somesite.com 即可：
[Shadowsocks X](https://github.com/yangfeicheung/Shadowsocks-X)

**Comment by ssrpanel** [comment]
@yangfeicheung 已star您的版本，谢谢

**Comment by gMan1990** [comment]
https://adblockplus.org/en/filter-cheatsheet#blocking2
比如：https://www.ipip.net/
我配置：||www.ipip.net^
怎么不生效

**Comment by yangfeicheung** [comment]
@ssrpanel  多谢

@gMan1990  可能需要重启下app，如果觉得麻烦，可以考虑下我修改的版本，可以立即生效
