### ISSUE TITLE
连不上被墙的网站

### ISSUE THREAD

**Issue by Arrow-Li** [shadowsocks/ShadowsocksX-NG#65]
无论是手动然后用代理插件还是全局模式都连不上，浏览器Firefox和Safari都试过了。
SS服务器是好的，在Win上可以正常上Google。
<img width="566" alt="2016-09-18 14 53 57" src="https://cloud.githubusercontent.com/assets/17962902/18613546/d360d69e-7daf-11e6-8129-e67fa8622ccd.png">
16/9/18 14:39:27.213 ShadowsocksX-NG[1060]: Stop ss-local succeeded.
16/9/18 14:39:27.214 ShadowsocksX-NG[1060]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
16/9/18 14:39:27.274 ShadowsocksX-NG[1060]: pac proxy set to off
16/9/18 14:45:33.701 ShadowsocksX-NG[1060]: bind profile 0
16/9/18 14:45:35.320 ShadowsocksX-NG[1060]: bind profile 1
16/9/18 14:45:36.005 ShadowsocksX-NG[1060]: bind profile 2
16/9/18 14:45:36.603 ShadowsocksX-NG[1060]: bind profile 3
16/9/18 14:45:37.191 ShadowsocksX-NG[1060]: bind profile 4
16/9/18 14:45:38.089 ShadowsocksX-NG[1060]: bind profile 0
16/9/18 14:45:59.863 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) This service is defined to be constantly running and is inherently inefficient.
16/9/18 14:45:59.923 ShadowsocksX-NG[1060]: Start ss-local succeeded.
16/9/18 14:45:59.923 ShadowsocksX-NG[1060]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
16/9/18 14:45:59.979 ShadowsocksX-NG[1060]: pac proxy set to off
16/9/18 14:50:28.834 ShadowsocksX-NG[1060]: Start ss-local succeeded.
16/9/18 14:50:28.835 ShadowsocksX-NG[1060]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
16/9/18 14:50:28.890 ShadowsocksX-NG[1060]: pac proxy set to global

**Comment by Arrow-Li** [comment]
用XX-Net可以正常上

**Comment by qinyuhang** [comment]
可否参考一下 https://github.com/shadowsocks/ShadowsocksX-NG/issues/55 ？

**Comment by Arrow-Li** [comment]
用了测试版还是不行

**Comment by qinyuhang** [comment]
有按照方法改过ss-local的执行权限吗？

Arrow-Li <notifications@github.com>于2016年9月18日 周日19:04写道：

**Comment by Arrow-Li** [comment]
SS运行了，如果没运行提示应该是
<img width="466" alt="2016-09-18 19 16 54" src="https://cloud.githubusercontent.com/assets/17962902/18615257/931b292a-7dd4-11e6-8a13-94d62f940946.png">

**Comment by qinyuhang** [comment]
我是指修改权限……

Arrow-Li <notifications@github.com>于2016年9月18日 周日19:18写道：

**Comment by Arrow-Li** [comment]
ss-local在运行,权限肯定是对的

**Comment by Arrow-Li** [comment]
2016-09-19 00:50:49 INFO: protocol origin
 2016-09-19 00:50:49 INFO: method http_simple
 2016-09-19 00:50:49 INFO: obfs plain
 2016-09-19 00:50:49 INFO: obfs_param 
 2016-09-19 00:50:49 INFO: initializing ciphers... http_simple
 2016-09-19 00:50:49 ERROR: Invalid cipher name: http_simple, use table instead
 2016-09-19 00:50:49 INFO: tcp port reuse enabled
 2016-09-19 00:50:49 INFO: listening at 127.0.0.1:1088
 2016-09-19 00:50:52 ERROR: remote_recv_cb_recv: Connection reset by peer
 2016-09-19 00:50:53 ERROR: remote_recv_cb_recv: Connection reset by peer
 2016-09-19 00:50:59 ERROR: remote_recv_cb_recv: Connection reset by peer
 2016-09-19 00:51:02 ERROR: remote_recv_cb_recv: Connection reset by peer
 
一访问被墙的就是Connection reset by peer

**Comment by qinyuhang** [comment]
simple http 已被移除支持，请使用其他加密方法

Arrow-Li <notifications@github.com>于2016年9月19日 周一00:51写道：

**Comment by Arrow-Li** [comment]
搞定了，是扫描二维码的问题
rc4-md5的加密，扫描二维码进来变成http-simple了。
这是bug吧

**Comment by qinyuhang** [comment]
有可能。但是不知道你的二维码是哪样的。如果可以的话，自己扫码解密一下，把格式贴上来看看

Arrow-Li <notifications@github.com>于2016年9月19日 周一12:35写道：

**Comment by Arrow-Li** [comment]
在Win上shadowsocksR和iOS shadowrocket上扫都是对的

**Comment by qinyuhang** [comment]
我知道了，你用的可能是旧版的ssr二维码，请参考 https://github.com/qinyuhang/ShadowsocksX-NG/issues/7 目前还不支持旧版ssr二维码，尽量用新的。

**Comment by Arrow-Li** [comment]
的确是ss://开头

发自我的 iPhone
