### ISSUE TITLE
can't compatible with  Firefox57.0.2

### ISSUE THREAD

**Issue by jksdzh** [shadowsocks/ShadowsocksX-NG#650]
**System and Shadowsocksx-NG version:**

- osX10.11.6
- Shadowsocksx-NG 1.7.0

**Expected behavior:**
shadowsocksX can compatible with Firefox57.0.2

**Actual behavior:**
Firefox  can not  browser any websites when shadowsocksX is working.
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by agenttb** [comment]
ss-local.log
2017-12-11 07:54:07 INFO: initializing ciphers... aes-256-cfb
 2017-12-11 07:54:07 INFO: tcp port reuse enabled
 2017-12-11 07:54:07 INFO: listening at 127.0.0.1:1080
 2017-12-11 07:54:24 INFO: initializing ciphers... aes-256-cfb
 2017-12-11 07:54:24 INFO: tcp port reuse enabled
 2017-12-11 07:54:24 ERROR: bind: Address already in use
 2017-12-11 07:54:24 ERROR: bind() error

console.app log
默认	07:49:31.522026 +0800	ShadowsocksX-NG	pac proxy set to auto
默认	07:53:45.971008 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
默认	07:53:46.008458 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	07:53:46.074710 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
默认	07:53:46.074994 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	07:53:46.113824 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [918] (3,0)
默认	07:53:46.115557 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [918] (3,0)
默认	07:53:46.118517 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [918] (3,0)
默认	07:53:46.119539 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [918] (3,0)
默认	07:53:46.121401 +0800	ShadowsocksX-NG	pac proxy set to off
默认	07:54:07.176459 +0800	lsd	SecTranslocateCreateSecureDirectoryForURL: created /private/var/folders/6p/2j5p3jdj1fzfbp640w5q1lsh0000gn/T/AppTranslocation/62B6977E-61D3-460F-8EE6-E673EB4DECB3/d/ShadowsocksX-NG-2.app
默认	07:54:07.616173 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [0] success
默认	07:54:07.684287 +0800	ShadowsocksX-NG	pinging 69.171.68.54
默认	07:54:07.684536 +0800	ShadowsocksX-NG	#0 sent
默认	07:54:07.859932 +0800	ShadowsocksX-NG	#0 received, size=64
默认	07:54:07.953822 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	07:54:08.021639 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	07:54:08.087419 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	07:54:08.090516 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	07:54:08.115538 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [948] (3,0)
默认	07:54:08.117180 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [948] (3,0)
默认	07:54:08.119501 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [948] (3,0)
默认	07:54:08.120519 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [948] (3,0)
默认	07:54:08.122159 +0800	ShadowsocksX-NG	pac proxy set to auto
默认	07:54:12.502753 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [0] success
默认	07:54:21.845901 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
默认	07:54:21.912851 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	07:54:21.979120 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	07:54:21.979684 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	07:54:22.004686 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [960] (3,0)
默认	07:54:22.006023 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [960] (3,0)
默认	07:54:22.008296 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [960] (3,0)
默认	07:54:22.009190 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [960] (3,0)
默认	07:54:22.010676 +0800	ShadowsocksX-NG	pac proxy set to off
默认	07:54:24.446929 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	07:54:24.513203 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	07:54:24.579841 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	07:54:24.580498 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	07:54:24.605208 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [973] (3,0)
默认	07:54:24.606473 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [973] (3,0)
默认	07:54:24.608756 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [973] (3,0)
默认	07:54:24.609712 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [919] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [973] (3,0)
默认	07:54:24.611014 +0800	ShadowsocksX-NG	pac proxy set to auto
默认	07:57:43.698807 +0800	mdworker	zip importer encountered an error (3) scanning "/Users/tianbin/Downloads/ShadowsocksX-NG.1.6.1.zip".

**Comment by yangfeicheung** [comment]
you might need to change your port,as the error msg suggests: bind: Address already in use, which means it's already occupied by some other app. Change the port and check again.

**Comment by qiuyuzhou** [comment]
需要在Firefox的设置里自己设置代理
