### ISSUE TITLE
完全无法连接被屏蔽的网站，求解。

### ISSUE THREAD

**Issue by babelove** [shadowsocks/ShadowsocksX-NG#653]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**（不确定是不是这个）

默认	13:00:04.768256 +0800	Console	[0x7fe075203600] Created session
默认	13:00:04.768702 +0800	Console	[0x7fe075203600] Decoding: C0 0x002A0027 0x0006354A 0x11111100 0x00000000 766
默认	13:00:04.768742 +0800	Console	[0x7fe075203600] Options: 42x39 [FFFFFFFF,FFFFFFFF] 0001D060
默认	13:00:04.768832 +0800	Console	[0x7fe075203600] Decoding completed without errors
默认	13:00:04.769146 +0800	Console	[0x7fe075203600] Releasing session

**Comment by yangfeicheung** [comment]
可以发mail给我，我帮您看下问题 yangfei.cheung@gmail.com
