### ISSUE TITLE
已经好久无法使用了，不知道是什么问题

### ISSUE THREAD

**Issue by lightGo** [shadowsocks/ShadowsocksX-NG#656]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by shop2008** [comment]
一样的好久都要用不了，有没有人给解决下

**Comment by rickycm** [comment]
shadowsocks-ng 1.7很好用啊，一直在用

**Comment by yangfeicheung** [comment]
我改的这个版本可以用哦，感兴趣的可以试试，多了些方便的小功能，比如屏蔽广告，高可用性模式，macOS 13.2也运行正常

https://github.com/yangfeicheung/Shadowsocks-X
