### ISSUE TITLE
如何获取APP对应的域名或服务器IP地址？

### ISSUE THREAD

**Issue by yhgszi** [shadowsocks/ShadowsocksX-NG#657]
我们公司网管封锁了微信、Apple store、youku等软件和网站。通过使用「yangfeicheung」大神提供的版本，在自定义规则里添加了youku.com后，优酷网站可以正常打开了。
但是，微信、applestore 仍然无法打开，微信通过接口获取到了最新IP也不行，APPLE STORE 的IP地址不知道怎么获取。

请问，有什么方法吗？或者新增功能：选择本地电脑内已安装的软件，就自动把它加入了自定义规则内。
![image](https://user-images.githubusercontent.com/34730193/34239168-836f1786-e640-11e7-9607-d8d7585f9790.png)
![image](https://user-images.githubusercontent.com/34730193/34239176-8cdd8870-e640-11e7-984a-130156181816.png)

**Comment by ahlixinjie** [comment]
surge完美适合你的所有需求, 但是这个软件很贵. 说实话,我真的觉得ss的一些功能不太先进,比如自定义规则就很麻烦,而且不能根据应用走规则, 像mac上的词典, 终端和邮件都无法走代理.   surge其实是很现代化的,但是就是太贵了...

**Comment by yhgszi** [comment]
好贵啊好贵啊，都跟1password一个价了

**Comment by ahlixinjie** [comment]
是贵，但是这个真的好用，微信无法通过ss代理，但是可以通过surge代理，虽然我没买，但是我试用了一个月，这个真的是太先进了
