### ISSUE TITLE
macos sierra的safari使用pac模式无法翻墙

### ISSUE THREAD

**Issue by ynhzzu** [shadowsocks/ShadowsocksX-NG#66]
只能全局模式

**Comment by RalphTsui** [comment]
遇到相同问题，求解~

**Comment by ynhzzu** [comment]
看了看之前的issues反馈，我发现是file:///.../gfwlist.js在新版safari上无法使用，所以我安装了一个nginx，把pac文件放到nginx目录中，用http://.../gfwlist.js可以正常使用了。

**Comment by Jesse-Fan** [comment]
楼上兄弟，有具体的操作方法嘛？或者又自动的sell 求教

**Comment by ynhzzu** [comment]
brew install nginx  #安装nginx
brew services start nginx   #启动nginx服务
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.nginx.plist   #加入开机启动
cp -r ~/.ShadowsocksX-NG/* /usr/local/var/www/     #复制gfwlist.js到nginx
设置->网络->代理->自动代理配置->file:///.../gfwlist.js修改为http://127.0.0.1:8080/gfwlist.js

**Comment by RalphTsui** [comment]
我在这里下的1.3 R6 
PAC的地址已经是http了
不过毕竟不是正式版可能有点问题，比如点了下显示网速之后挂掉了
https://github.com/qinyuhang/ShadowsocksX-NG/releases

**Comment by ynhzzu** [comment]
@RalphTsui 抱歉，我用的是1.2release版本，无法还原那个问题。

**Comment by RalphTsui** [comment]
@ynhzzu 显示网速崩溃的问题吗？作者已经知道这个问题了，期待merge的正式版能解决吧。我现在用了几个小时1.3R6了，除了这个问题感觉还好

**Comment by qinyuhang** [comment]
显示网速的问题是 macOS 的问题，我已经给 Apple 发了 bug report 了，还没有得到反馈。

**Comment by arjunmayilvaganan** [comment]
I'm not complaining. But I'd be happy if someone helps translate these content in English.
My issue: I'm running MacOS Sierra. This is the first time I'm running `ShadowsocksX-NG`. It seems to be running fine and all. But, IP address hasn't changed, the censored sites still remain censored.

**Comment by qinyuhang** [comment]
@arjunmayilvaganan did you try visit youtube? what's your browser's hit? did you add shadowsocks servers to ShadowsocksX-NG.

**Comment by arjunmayilvaganan** [comment]
@qinyuhang Yes, I tried to visit YouTube. The page is not loading (like it usually would not).
The server list is empty. I have no idea where from to get Server address, password etc.

**Comment by RalphTsui** [comment]
@arjunmayilvaganan you can use your own server or 3rd-party service. Google before ask.

**Comment by arjunmayilvaganan** [comment]
@RalphTsui Of course I google before I asked. I have that courtesy and I'm not an internet Newbie. I don't have my own server. I googled only to not find any 3rd-party service.

**Comment by ynhzzu** [comment]
@arjunmayilvaganan 
http://www.quanminxingkong.com
this is my website,you can use my shadowsocs service to test it.

**Comment by qinyuhang** [comment]
@arjunmayilvaganan this tool requires knowledge on shadowsocks, due to regulation we can't post things here directly, so please google it if you can. Maybe you should using (server address and password) from @ynhzzu . Any problem in configure the tool, just comment here.

**Comment by arjunmayilvaganan** [comment]
Thank you @ynhzzu. I have e-mailed you, to take this discussion off this thread.

**Comment by arjunmayilvaganan** [comment]
@qinyuhang, Thank you for responding. I understand. I used credentials from @ynhzzu to add the server to my list and selected the server from the Menu bar and still does not seem to be connecting. Help if you will or I understand. I'll google and try to understand. No issues.

**Comment by jiangxiluning** [comment]
HI, the solution is fairly easy. 
`
Mac-mini:~ luning$ cd .ShadowsocksX-NG/
Mac-mini:.ShadowsocksX-NG luning$ nohup python -m SimpleHTTPServer 8765 &
`
And  change your pac setting to http://localhost:8765/gfwlist.js
It's Done.

**Comment by heartinfei** [comment]
我也遇到了同样的问题！

**Comment by jiangxiluning** [comment]
@heartinfei 试试我的方法

**Comment by heartinfei** [comment]
@jiangxiluning 没有成功～

**Comment by jiangxiluning** [comment]
@heartinfei 确保你装了 python 且是2.7

**Comment by heartinfei** [comment]
@jiangxiluning change your pac setting to http://localhost:8765/gfwlist.js
的意思是
设置》网络》高级》代理》自动代理配置   吗？

**Comment by jiangxiluning** [comment]
是的

**Comment by tanpengsccd** [comment]
@jiangxiluning 
this work!!!!Thank you !
`
cd .ShadowsocksX-NG/
nohup python -m SimpleHTTPServer 8765 &
`

**Comment by danielfree** [comment]
updated solution with nginx
brew install nginx
sudo brew services start nginx
ln -s ~/.ShadowsocksX-NG/gfwlist.js /usr/local/var/www/gfwlist.js #link gfwlist.js to nginx directory
network -> advanced -> proxy -> auto proxy config -> file:///.../gfwlist.js change to http://127.0.0.1:8080/gfwlist.js

**Comment by fayland** [comment]
every time I restarted my computer, it was reset into the file:// again. how to fix that?

**Comment by qinyuhang** [comment]
please wait until merge
https://github.com/shadowsocks/ShadowsocksX-NG/pull/44 or get R7……

Fayland Lam <notifications@github.com>于2016年9月26日 周一18:12写道：

**Comment by vernohy** [comment]
同样的问题，希望尽快出新版来解决！

**Comment by wanghz** [comment]
http://127.0.0.1:1089/proxy.pac即可。Mark 一下备忘

**Comment by luckycloves** [comment]
@jiangxiluning 
Theank for your help .
