### ISSUE TITLE
与Firefox Quantum有关的问题

### ISSUE THREAD

**Issue by simplylife99** [shadowsocks/ShadowsocksX-NG#663]
环境：
macOS 10.13.2
shadowsocksX-NG 1.6.0(1)
Firefox Quantum 57.0.2

问题：
当firefox设置成“使用系统代理设置”，无法访问任何网站；设置成“自动检测此网络的代理设置”，无法访问google等。应该不是shadowsocks的设置问题，因为通过上网safari是成功的。但因习惯使用firefox，新人求解，是否哪里设置得不对？……

**Comment by kun-zhou** [comment]
tested with Firefox Quantum, same issue. You need to set it manually. If you use Gloabl Mode, simply input your local SOCKS proxy info to the fields. Tested and works on macOS 10.13.2. See below for an illustration. Your port might be different depending on setup. Go to the `Preferences` panel of ShadowsocksX-NG and click on `Advanced`, you will see the Socks Listening Port and Address.

<img width="656" alt="screen shot 2017-12-24 at 10 22 32 am" src="https://user-images.githubusercontent.com/19158151/34323823-8122e894-e894-11e7-8ed3-97d1118b7e6d.png">

**Comment by yangfeicheung** [comment]
check out this one

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by simplylife99** [comment]
To kun-zhou，有效，谢谢！

To yangfeicheung，好的，我试一下，谢谢！

**Comment by kun-zhou** [comment]
@simplylife99 客气。you can close the issue now

**Comment by xiebruce** [comment]
@simplylife99 @kun-zhou 这样是有效，但是结果就是不管我ss开pac还是开全局，firefox访问任何网站都会走代理，这不是我们想要的呀，这样pac就没意义了。

Firefox：`65.0.1 (64-bit)`
ssX-NG: `1.8.2`
macOS: `10.14.1 (18B75)`

**Comment by yulinfeng000** [comment]
考虑和` Proxy SwitchyOmega `协同使用吧，chrome都是好好的，就Firefox不兼容，转一个别人的配置贴https://shadowsockshelp.github.io/Shadowsocks/Firefox.html
