### ISSUE TITLE
请问 服务器订阅 在哪里？

### ISSUE THREAD

**Issue by fjk2707** [shadowsocks/ShadowsocksX-NG#664]
之前用的1.4.3，为什么最新版的没有了……

**Comment by xiaobuxun** [comment]
我也是想使用这个功能的时候发现没有了，建议作者再加上！

**Comment by qiuyuzhou** [comment]
重来就没有过这个功能。你们原来用的应该是服务商定制的版本

**Comment by xiaobuxun** [comment]
那可否在我们的版本中再加上这个功能呢？

**Comment by HakureiMarisa** [comment]
附议一下，如果可能的话，建议大佬加上这个功能吧，这个功能还是很有用的

**Comment by Justsoos** [comment]
不是服务商定制版，作者删库了。
https://github.com/search?q=ShadowsocksX-NG-R8
确实有很多功能，比如测速，订阅服务器分组 ……
![image](https://user-images.githubusercontent.com/3480043/62003877-2ce1b400-b150-11e9-8223-4b64ade4731b.png)
