### ISSUE TITLE
XCODE编译失败

### ISSUE THREAD

**Issue by ilovebamboo** [shadowsocks/ShadowsocksX-NG#665]
Ld /Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Products/Debug/proxy_conf_helper normal x86_64
    cd /Users/blackrose/Downloads/ShadowsocksX-NG-develop
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Products/Debug -L/Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Products/Debug/BRLOptionParser -F/Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Products/Debug -filelist /Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Intermediates.noindex/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper.LinkFileList -mmacosx-version-min=10.11 -Xlinker -object_path_lto -Xlinker /Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Intermediates.noindex/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -ObjC -lBRLOptionParser -lPods-proxy_conf_helper -Xlinker -dependency_info -Xlinker /Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Intermediates.noindex/ShadowsocksX-NG.build/Debug/proxy_conf_helper.build/Objects-normal/x86_64/proxy_conf_helper_dependency_info.dat -o /Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Products/Debug/proxy_conf_helper

ld: warning: directory not found for option '-L/Users/blackrose/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gawsmcujbtpnftdiqxdjihpjrxuv/Build/Products/Debug/BRLOptionParser'
ld: library not found for -lBRLOptionParser
clang: error: linker command failed with exit code 1 (use -v to see invocation)
![qq20171224-204326](https://user-images.githubusercontent.com/6214084/34326566-2b81cd36-e8eb-11e7-96af-56c2531c6136.png)
请问这个是什么原因啊  该如何编译

**Comment by yangfeicheung** [comment]
just as the message suggests: the lib of BRLOptionParser was missing....

**Comment by ilovebamboo** [comment]
我知道看反馈，我是第一次编译这个项目，之前没有太多XCODE编程经验，而且说明并没有讲编译过程啊。

**Comment by developforapple** [comment]
pod install 成功了么？

**Comment by qiuyuzhou** [comment]
打开错项目文件了。
是ShadowsocksX-NG.xcworkspace
不是ShadowsocksX-NG.xcodeproj

**Comment by qinyuhang** [comment]
just search keyword lBRLOptionParser in this repo's issues.

发自我的 iPhone

> 在 2017年12月24日，20:44，Lotus <notifications@github.com> 写道：
> 
> lBRLOptionParser
