### ISSUE TITLE
`chmod +s on proxy_conf_helper' is too dangerous

### ISSUE THREAD

**Issue by march1993** [shadowsocks/ShadowsocksX-NG#667]
see https://github.com/shadowsocks/ShadowsocksX-NG/commit/4ab5ebe9b7701056e81e5feac5964806cfec8d30 .

It turns out any program can use this executable to change the system behaviour, which means bringing risk to the system.

**Comment by yangfeicheung** [comment]
proxy_conf_helper is basically a tool used to change the proxy settings of the pc's network,if u removed this,then you have to manually configure the network settings every time you want to use shadowsocks and turn it off when u disable shadowsocks, if you worry about the safety or privacy issue,you can either download the source and compile by yourself,or you can use app store version,which is under strict sandbox environment(but as I said,you have to configure the network manually,because proxy_conf_helper doesn't work any more).

https://itunes.apple.com/us/app/shadowsocks-x/id1295053131?mt=12

**Comment by march1993** [comment]
I worry about the safety. And the problem is, even if I downloaded the source code and compiled it myself, the problem would still exist.
I know the necessity of granting `proxy_conf_helper' with root privileges. But in your source code, there is no mechanic to make sure that this program is called by `ShadowsocksX-NG' only, not other ones.

**Comment by yangfeicheung** [comment]
that's correct,my suggestion is you can remove that and use the app store version,and you have to configure the socks5 setting by yourself,that's the price you have to pay,either you grant that permission to app,or you revoke it and do it by yourself.
Another question is,even if other apps called proxy_conf_helper, so what?  I don't seem harmful things in that,maybe hijacking your network or what?

**Comment by yangfeicheung** [comment]
btw,I'm not the author of Shadowsocks-NG^_^,but he's great to create an app like this

**Comment by march1993** [comment]
Hijacking is definitely a kind of threat. I hope you guys could reminder users these potential risks.

**Comment by yangfeicheung** [comment]
if an app could make use of proxy_conf_helper,then it could make use of other command as well, so I guess it's probably your own duty to keep your os clean & safe,as I said,if you worry about that,you can download & use app store version,but if you want to use non app store version,I don't think most apps would even notice this,unless you install some malicious apps on ur pc. on the other hand,you can view the source code of proxy_conf_helper,and it's only a tool used to change network settings,you can always check ur network settings manually if you are suspicious,if some other apps change this,you would definitely notice a change in the proxy settings

**Comment by march1993** [comment]
`if an app could make use of proxy_conf_helper, then it could make use of other command as well`
I can't agree. `proxy_conf_helper` is capable of privileged actions, which affects the system security while other commands are strictly limited (`ping` command is also granted with `s` bit, but it is harmless).

`you would definitely notice a change in the proxy settings`
How do I suppose to notice? Without opening the system setting dialog, general users can't sense such proxy changes.

I have a suggestion, whenever `proxy_conf_helper` is called, send a message to the OS X GUI in the right top corner.
