### ISSUE TITLE
NG client doesn't work under auto pac mode - macOS 10.13.2

### ISSUE THREAD

**Issue by tony-haibo-zhu** [shadowsocks/ShadowsocksX-NG#670]
Hey there,

Today l purchased a new server to build my ss server. 
l built connection successfully with my iPhone using shadowrocket but not working on my mac.
And l found something strange that when l select pac mode, the proxy of system will set Automatic proxy configuration's url to `http://127.0.0.1:1086/proxy.pac` , but when l acces google, the 'Downloading proxy script' text will show on bottom bar in chrome and l also couldn't get the 'proxy.pac' through accessing 127.0.0.1:1086 in browser(chrome), and did l miss something please ? my client on mac is shadowsocksX-NG. Thank you.  

- macOS 10.13.2
- Shadowsocksx-NG 1.7 release

**Comment by tony-haibo-zhu** [comment]
l only see three files in my ~/.ShadowsocksX-NG directory that is gfwlist.js, gfwlist.txt and user-rule.txt. But where is 'proxy.pac' ?

There should be a web file server like nginx etc. to put 'proxy.pac' on it in my opinion. 

Is there somebody to answer my question?   

Thanks in advance.

**Comment by tony-haibo-zhu** [comment]
I checked ss-local.log just now when l set to pac mode. It shows 'INFO: TCP connection timeout'. I think it means 'Downloading proxy script' which shows on bottom bar in chrome timeout.

So some file server which put proxy.auto on it like l said before doesn't start successfully on my machine ?

**Comment by tony-haibo-zhu** [comment]
By the way, the global mode works fine.

**Comment by yangfeicheung** [comment]
you can try to add custom rules and see if it works

**Comment by tony-haibo-zhu** [comment]
@yangfeicheung 'Downloading proxy script' still in there.

**Comment by tony-haibo-zhu** [comment]
Anyone can offer  help please?

**Comment by tony-haibo-zhu** [comment]
When I change URL to `file:///Users/myusername/.ShadowsocksX-NG/gfwlist.js` from `http:127.0.0.1:myport/proxy.pac`, it works fine, so wried, doesn't it ? 
I still find a way of changing nothing myself to use this proxy software.

**Comment by yangfeicheung** [comment]
mate,try this one and see if it works:

https://github.com/yangfeicheung/Shadowsocks-X/releases

**Comment by tony-haibo-zhu** [comment]
Yep, l use shadowsocksX a fews days ago, l switch to NG cause its powerful and maintainance which hear from other people. So l still trend to use this client as my service. 
But thank you for your advice. @yangfeicheung

**Comment by zuimeiaj** [comment]
@tony-haibo-zhu Thank you!
