### ISSUE TITLE
ssr 服务器配置了协议和混淆，请问ShadowsocksX-NG 如果配置？

### ISSUE THREAD

**Issue by hardcattle** [shadowsocks/ShadowsocksX-NG#677]
**System and Shadowsocksx-NG version:**

- macOS 10.13.2
- Shadowsocksx-NG 1.7

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by sssshadowsocks** [comment]
https://portal.shadowsocks.la/aff.php?aff=12091
