### ISSUE TITLE
ServerProfile.makeLegacyURL erroneously URL-encodes passwords 

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/ShadowsocksX-NG#678]
**Expected behavior:** Password for legacy URLs should NOT be URL-encoded (unless I'm mistaken).
**Actual behavior:** The opposite.

https://github.com/shadowsocks/ShadowsocksX-NG/blob/89de12ba24b98cdf64f714787b9ffaa8fad296eb/ShadowsocksX-NG/ServerProfile.swift#L263-L281

This caused inconsistent behavior across platforms. It's okay to not encode strings because there wouldn't be any ambiguity (consider the string `bf-cfb:aes-256-cfb:password@stillpassword.com:33/#lol@example.com:1234`, clearly there's still only one way to interpret it).

I could see that this confusion comes from [shadowsocks.org](https://shadowsocks.org/en/config/quick-guide.html):

> Where the plain URI should be:
>```
>    ss://method:password@hostname:port
>```

@madeye Maybe we should fix that. 😄

**Comment by qiuyuzhou** [comment]
This behavior is implemented by the URLComponents，not me.
Please have a look at the [RFC for URI](https://tools.ietf.org/html/rfc3986#section-3.2.1).
```
userinfo    = *( unreserved / pct-encoded / sub-delims / ":" )
```

**Comment by madeye** [comment]
Fix the description via https://github.com/shadowsocks/shadowsocks-org/commit/78ca46cd6859a4e9475953ed34a2d301454f579e

**Comment by Mygod** [comment]
@qiuyuzhou Yes that's not supposed to be the correct behavior (or how other clients implements it). Here's how it's implemented in shadowsocks-android:

https://github.com/shadowsocks/shadowsocks-android/blob/d7a11eaa3b8feda48dadec091907275e04061c97/mobile/src/main/java/com/github/shadowsocks/database/Profile.kt#L41

**Comment by Mygod** [comment]
Also shadowsocks-windows: https://github.com/shadowsocks/shadowsocks-windows/blob/63980b3a12150a7ff3066889db778c49b02dcba4/shadowsocks-csharp/Model/Server.cs#L17
