### ISSUE TITLE
如何续订VPN服务 原网站已经挂了

### ISSUE THREAD

**Issue by winnie976464** [shadowsocks/ShadowsocksX-NG#684]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by sssshadowsocks** [comment]
https://portal.shadowsocks.la/aff.php?aff=12091

**Comment by gfw-breaker** [comment]
免费账号来这里，长期更新 [https://github.com/gfw-breaker/ssr-accounts](https://github.com/gfw-breaker/ssr-accounts)

**Comment by Shadowsocksla** [comment]
付费账号来这里，长期有效 https://portal.shadowsocks.la/aff.php?aff=12091

**Comment by yangfeicheung** [comment]
@winnie976464, try this

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by qiuyuzhou** [comment]
各位，不要打广告。想让国家把我这也封了是吧？
