### ISSUE TITLE
SOCKS port 和 HTTP port 不能使用同样的端口号了.

### ISSUE THREAD

**Issue by foobarjohnny** [shadowsocks/ShadowsocksX-NG#685]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 (16G1114)
- Shadowsocksx-NG 1.7

**Expected behavior:**
NG的旧版和 Windows 版都支持 SOCKS port 和 HTTP port 使用同样的端口号

**Actual behavior:**
近来发布的几个版本都不支持.

**Steps to reproduce:**

**How often does this happen?**

**ss-local.log**

**Application log**

**Crash Log**

**Comment by yangfeicheung** [comment]
为什么会有这种需求？

**Comment by foobarjohnny** [comment]
由于 Windows 中两者是一样的, 所以每次把某个 Windows App 中的 proxy 配置拷贝粘贴到 macOS 下时, 都要人为的记住还需要修改端口号, 而事实上经常会忘记这些小细节, 造成原本不必要的麻烦.

**Comment by qiyuey** [comment]
我也遇到了同样的问题

**Comment by yangfeicheung** [comment]
修改一下吧，mac下不支持同样的端口号

**Comment by qiuyuzhou** [comment]
Won't support this feature.

**Comment by hyacinthus** [comment]
好苦恼，我一直是自己架http的。 后来发现mac的自带了，这很好。
后来发现windows的也自带了，这也很好。
结果发现windows的不能设置成不一样的。
我各种app同步的proxy配置就歇菜了。。。比如vscode
