### ISSUE TITLE
服务器设置，不能使用超过 90000 的端口

### ISSUE THREAD

**Issue by sanlengjingvv** [shadowsocks/ShadowsocksX-NG#686]
**System and Shadowsocksx-NG version:**

- macOS 10.13.2
- Shadowsocksx-NG 1.7.0

**Steps to reproduce:**
1. 服务器设置，填写端口 90001，确定  
2. 查看服务器设置  

**Expected behavior:**
端口号是 90001  

**Actual behavior:**
端口号是 9000

**Comment by yangfeicheung** [comment]
@sanlengjingvv  端口号最大值是 65535.。。。。。。。。
一般是1025-65535之间选取一个
