### ISSUE TITLE
ubuntu shadowsocks && mac shadowsocks-NG cannot work

### ISSUE THREAD

**Issue by leiz-me** [shadowsocks/ShadowsocksX-NG#687]
**System and Shadowsocksx-NG version:**

- macOS 10.13.2 (16E????)
- Shadowsocksx-NG 1.7.0 (1)

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

 2018-01-09 20:45:16 INFO: tcp port reuse enabled
 2018-01-09 20:45:16 INFO: listening at 127.0.0.1:1086
 2018-01-09 20:45:57 INFO: initializing ciphers... salsa20
 2018-01-09 20:45:57 INFO: tcp port reuse enabled
 2018-01-09 20:45:57 INFO: listening at 127.0.0.1:1086
 2018-01-09 20:46:12 INFO: connect to apidata.googleusercontent.com:443
 2018-01-09 20:46:22 INFO: connect to www.youtube.com:443
 2018-01-09 20:46:29 INFO: connect to www.youtube.com:443
 2018-01-09 20:46:47 INFO: connect to www.youtube.com:443
 2018-01-09 20:47:06 INFO: connect to clients4.google.com:443
 2018-01-09 20:47:52 INFO: connect to www.youtube.com:443

**Application log**
default	20:48:43.995830 +0800	ShadowsocksX-NG	Start ss-local succeeded.
default	20:48:44.069311 +0800	ShadowsocksX-NG	Start privoxy succeeded.
default	20:48:44.139370 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
default	20:48:44.139773 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	20:48:44.283267 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [90088] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [90087] (3,0)
default	20:48:44.303956 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [90088] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [90087] (3,0)
default	20:48:44.329063 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [90088] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [90087] (3,0)
default	20:48:44.350122 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [90088] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [90087] (3,0)
default	20:48:44.354000 +0800	ShadowsocksX-NG	pac proxy set to global

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

=============================

Shadowsocks 2.8.2 - Ubutun
ShadowsocksX-NG Version 1.7.0 (1) - MacOS

shadowsocks.json as followed,
{
"server": "xxxxx",
"server_port": 8388,
"local_address": "127.0.0.1",
"local_port": 1080,
"password": "xxxxx",
"timeout": 300,
"method": "salsa20",
"fast_open": false
}

cannot work, and server's log says:

2018-01-09 07:35:31 WARNING unsupported addrtype 235, maybe wrong password or encryption method

But ShadowsocksX with Shadowsocks 2.8.2 works well.

Please give me some hint.

**Comment by sssshadowsocks** [comment]
https://portal.shadowsocks.la/aff.php?aff=12091

**Comment by leiz-me** [comment]
@sssshadowsocks 
I am not using the paid services from your website. I am hosting the shadowsocks with my own server. Do you mean NG macOS client is designed for the paid service you mentioned, I should not use this client for self-hosted SS?

**Comment by leiz-me** [comment]
@qiuyuzhou 

Should I take the message from @sssshadowsocks  as official replay of this NG client opensource project?

**Comment by yangfeicheung** [comment]
@leiz-me  You can ABSOLUTELY use your own servers, sssshadowsocks just want to promote their own servers, both NG and version developed by me can use your own servers without any limitation.Just ignore what sssshadowsocks said, he's trying to advertise.

**Comment by leiz-me** [comment]
@yangfeicheung 
Could you provide any clue to solve the problem I have mentioned above? 
Thank you.

**Comment by yangfeicheung** [comment]
@leiz-me  You can try this version here:

https://github.com/yangfeicheung/Shadowsocks-X/releases

this is developed by me and users say they can run this well on macOS 10.13.2,mine is high Sierra too. I guess there might be some conflict for NG version. Anyway, as to my version, you can give it a shot. Do feel free to contact me via email if you have any issue.

**Comment by leiz-me** [comment]
@yangfeicheung 
感谢回复。
你给的链接是我现在在使用的能正常工作的版本。
我想确认一下，现在是不是NG版不能用在和shadowsocks 2.8.2进行连接？
还是说我应该升级shadowsocks的版本去适配NG？

**Comment by yangfeicheung** [comment]
@leiz-me  NG版本不是我开发的，我估计是因为在high sierra系统上可能有什么冲突，貌似不少用户都说不能用，具体的问题您可以去询问下@qiuyuzhou
