### ISSUE TITLE
mac下无法翻墙

### ISSUE THREAD

**Issue by Rex1217** [shadowsocks/ShadowsocksX-NG#688]
同样的配置，windows下使用正常，mac就不翻不了，是神马情况，求大神解救

**Comment by sssshadowsocks** [comment]
https://portal.shadowsocks.la/aff.php?aff=12091

**Comment by menglingyu** [comment]
我的mac好几天都无法翻墙了 之前还是可以有时候翻墙成功的，

**Comment by yangfeicheung** [comment]
@menglingyu  这个可以的：

 https://github.com/yangfeicheung/Shadowsocks-X
