### ISSUE TITLE
1.3.3-R6 无法播放youtube视频

### ISSUE THREAD

**Issue by J-Liu** [shadowsocks/ShadowsocksX-NG#69]
网站可以打开，就是视频无法播放，不知道为啥。

**Comment by qinyuhang** [comment]
可有检查过浏览器console，是否是html播放器的问题呢？

Jia Liu <notifications@github.com>于2016年9月23日 周五20:58写道：

**Comment by J-Liu** [comment]
Safari没有console啊，不知道为啥，Firefox是可以播放的，不知道为啥Safari不行，Safari真心好用啊，求解决办法，别让我换浏览器，我的原则是能用Apple的软件，不用第三发，Apple出品，必属精品。

**Comment by ookangzheng** [comment]
safari可以哦

**Comment by J-Liu** [comment]
搞定了，是因为ClickToFlash的问题，现在Safari没有一个好用的flash blocker了

**Comment by qinyuhang** [comment]
油管已经全面支持html5视频了吧。不是取消了flash了么

Jia Liu <notifications@github.com>于2016年9月24日 周六18:02写道：

**Comment by J-Liu** [comment]
问题就在于，如果有ClickToFlash，就不会播放H5视频，我也不知道为啥。
恶心的是，国内一些网站，flash广告，背景音乐很多。

**Comment by adonischain** [comment]
我之前clicktoflash 还是可以的，然后重启了一下，就不行了。

**Comment by qinyuhang** [comment]
暂时禁用一下吧？毕竟油管全面html5视频了

adonischain <notifications@github.com>于2016年9月25日 周日11:56写道：

**Comment by J-Liu** [comment]
ClickToFlash已删，作者说鉴于水果政策，不再更新
