### ISSUE TITLE
自定义本地监听地址的BUG

### ISSUE THREAD

**Issue by devcxm** [shadowsocks/ShadowsocksX-NG#690]
**System and Shadowsocksx-NG version:**

- macOS 10.13.2 (17C88)
- Shadowsocksx-NG 1.7

进入"偏好设置"，自定义"高级"的"本地Socks5监听地址"为本机IP地址（192.168.1.xx，非127.0.0.1），然后设置全局或者自动代理模式，Safari不能正常访问谷歌，原因是"系统偏好设置"-"网络"里的Socks代理服务器和PAC文件里地址为"127.0.0.1"，修改192.168.1.xx后即可正常访问。

**Comment by qiuyuzhou** [comment]
Workaround: Set it to `0.0.0.0`
