### ISSUE TITLE
MAC10.13.2不能科学上网

### ISSUE THREAD

**Issue by jordansuo** [shadowsocks/ShadowsocksX-NG#691]
**System and Shadowsocksx-NG version:**

- macOS 10.13.2
- Shadowsocksx-NG 1.7.0(1)

**Expected behavior:**
之前一直可以正常使用，今天突然出问题。帮忙看下是SS-NG的问题，还是代理服务器端的问题。
在单位的WINDOWS电脑上可以翻墙，用的是同一个代理。

另外，我配完服务器后新的服务器名后面会加上个“（超时）”

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**
 2018-01-10 22:45:39 INFO: connect to www.facebook.com:443
 2018-01-10 22:45:39 ERROR: remote_recv_cb_recv: Connection reset by peer
 2018-01-10 22:45:40 INFO: connect to www.facebook.com:443
 2018-01-10 22:45:40 ERROR: remote_recv_cb_recv: Connection reset by peer
 2018-01-10 22:45:45 INFO: connect to www.facebook.com:443
 2018-01-10 22:45:46 ERROR: remote_recv_cb_recv: Connection reset by peer

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by kiongweidong** [comment]
我的是不能添加配置文件，一添加就制动闪退，扫描二维码也用不了，只能手动添加，下载找了个老版本的R8可以扫描二维码

**Comment by jordansuo** [comment]
remote_recv_cb_recv: Connection reset by peer 是什么错？服务器拒绝MAC SS的请求？

**Comment by ayaup** [comment]
me，too mac 10.13.2 不行。

**Comment by sssshadowsocks** [comment]
从来没有遇到mac的版本问题
https://portal.shadowsocks.la/aff.php?aff=12091

**Comment by yangfeicheung** [comment]
我改的这个版本可以用哦，感兴趣的可以试试，多了些方便的小功能，比如屏蔽广告，高可用性模式，macOS 10.13.2也运行正常

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by WhiteSoulss** [comment]
我也是這個問題換個版本就好了，我用的是1.5beta2的可以用，你可以試試

**Comment by giftedunicorn** [comment]
会不会是电脑上被什么软件干扰了？比如各种管家？
