### ISSUE TITLE
这软件到底能使不能使，输入那么密码，跟个流氓似的

### ISSUE THREAD

**Issue by fenggnay** [shadowsocks/ShadowsocksX-NG#694]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by sssshadowsocks** [comment]
扫描二维码就可以的吧？看来你没有get到正确的打开方式
https://portal.shadowsocks.la/aff.php?aff=12091

**Comment by yangfeicheung** [comment]
需要root权限安装配置网络的东西。。。。否则每次要手动设置的。。。
你可以试试app store版本，不需要您授权输入密码：

https://itunes.apple.com/us/app/shadowsocks-x/id1295053131?mt=12

**Comment by Shadowsocksla** [comment]
扫描二维码不行吗？

**Comment by yangfeicheung** [comment]
@Shadowsocksla 他说的是要配置网络授权那个，刚开始的时候会跳出来，否则网络配置不了

**Comment by panqiao** [comment]
我觉得也是，为啥要输入密码？
