### ISSUE TITLE
macOS 10.13.1无法使用

### ISSUE THREAD

**Issue by bimingda100** [shadowsocks/ShadowsocksX-NG#695]
- macOS 10.13.1  
- Shadowsocksx-NG 1.6.1

默认	16:10:18.924148 +0800	WD Drive Agent	Sending HTML failed
默认	16:10:19.138275 +0800	useractivityd	DETERMINE: 38A21D57-2A88-4B1D-962E-03A3ADE82FCA/<private> as the current item-to-advertise.
默认	16:10:19.886984 +0800	useractivityd	[PBOARD CONTROLLER] Remove Local Timer Fired
默认	16:10:19.917245 +0800	useractivityd	DETERMINE: 6057E664-BC4B-4449-83A1-9C3EFFC11002/<private> as the current item-to-advertise.
默认	16:10:19.991615 +0800	WD Drive Agent	Sending HTML failed
默认	16:10:20.591257 +0800	useractivityd	-- Demoting self.advertisingProcess to nil (was UserActivityClient(pid=622/com.google.Chrome uuids={6057E664-BC4B-4449-83A1-9C3EFFC11002 })) and trigger pickNewAdvertisement because the previous advertisingProcess had a current activity.
默认	16:10:20.645414 +0800	useractivityd	DETERMINE: No item is being advertised, so removing any previously set of advertised items.
默认	16:10:21.403316 +0800	Google Chrome Helper	Failed to look up the port for "com.apple.windowserver.active" (1100)
错误	16:10:21.488362 +0800	Google Chrome Helper	failed to read /System/Library/Preferences/Logging/Subsystems/com.apple.launchservices.plist: [1: Operation not permitted]
错误	16:10:21.489232 +0800	Google Chrome Helper	failed to read /System/Library/Preferences/Logging/Subsystems/com.apple.launchservices.plist: [1: Operation not permitted]
默认	16:10:21.770464 +0800	identityservicesd	Beginning cleanup of outgoing message database
默认	16:10:21.771759 +0800	identityservicesd	Cleaned up 0 expired messages
默认	16:10:21.772245 +0800	identityservicesd	Beginning cleanup of outgoing message database for quickswitched messages
默认	16:10:21.772678 +0800	identityservicesd	Ending cleanup of outgoing message database for quickswitched messages
默认	16:10:21.772752 +0800	identityservicesd	Beginning cleanup of outgoing message database for messages older than 2 days past enqueue date
默认	16:10:21.773068 +0800	identityservicesd	Using Time Interval 537351021.772920
默认	16:10:21.773823 +0800	identityservicesd	Ending cleanup of 0 outgoing message database for older than 2 days past enqueue date
默认	16:10:21.774003 +0800	identityservicesd	Beginning cleanup of outgoing message database
默认	16:10:21.774916 +0800	identityservicesd	Ending cleanup of outgoing message database

**Comment by sssshadowsocks** [comment]
https://portal.shadowsocks.la/aff.php?aff=12091

**Comment by yangfeicheung** [comment]
我改的这个版本可以用哦，感兴趣的可以试试，多了些方便的小功能，比如屏蔽广告，高可用性模式，macOS 13.2也运行正常

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by WhiteSoulss** [comment]
我也是這個問題換個版本就好了，我用的是1.5beta2的可以用，你可以試試

**Comment by tainsunyi** [comment]
1.7.0，shadowsocksX-NG,正常使用。

**Comment by tainsunyi** [comment]
@fattypiggy，我就是直接普通安装，然后把shadowsocks服务器相关的信息填入之后，就可以用了。或许跟路线有关吧

**Comment by zhandao** [comment]
https://github.com/iMeiji/shadowsocks_install/releases/tag/0.13
1.5.1 正常
