### ISSUE TITLE
提议每次 release 的信息中添加 MD5、SHA1、SHA256、SHA512 的值

### ISSUE THREAD

**Issue by BrandoZhang** [shadowsocks/ShadowsocksX-NG#698]
就像隔壁 [Windows-release](https://github.com/shadowsocks/shadowsocks-windows/releases) 一样，有个哈希值方便校验下载的是不是官方版本。

**Comment by BrandoZhang** [comment]
@qiuyuzhou

**Comment by fr11** [comment]
这个 每次要怎么验证呢？
