### ISSUE TITLE
aws acounts only doesn't work on macOS with both Shadowsocksx-NG & ShadowsocksX

### ISSUE THREAD

**Issue by astrobear2** [shadowsocks/ShadowsocksX-NG#699]
**System and Shadowsocksx-NG version:**

- macOS 10.13.2 (16E????)
- Shadowsocksx-NG 1.7

acounts from AWS that works on ubuntu and Android, doesn't work on macOS from 10.12 to 10.13.2
at the same time, some 'public' free acounts works on all platform..

quite strange and anoying

**Comment by WhiteSoulss** [comment]
我也是這個問題換個版本就好了，我用的是1.5beta2的可以用，你可以試試
