### ISSUE TITLE
状态栏图标有点偏下了，没有对齐

### ISSUE THREAD

**Issue by Bronts** [shadowsocks/ShadowsocksX-NG#70]
貌似太贴近底部了，能看出和其他的图标底部没在同一水平线，另一个图标是原来官方版本的。
右边起第一个纸飞机是这个项目的
![wechatimg3](https://cloud.githubusercontent.com/assets/3986255/18806369/2b099f64-825d-11e6-9e90-508ab47d7358.jpeg)

**Comment by leeben11** [comment]
。。。经提醒注意到了，强迫症表示很难受

**Comment by heiyo** [comment]
我也快崩溃了……

**Comment by FrancoWay** [comment]
吓的我继续用1.2版本。。。

**Comment by qiuyuzhou** [comment]
Won't fix it.

**Comment by heiyo** [comment]
楼上的~~~~~~   其实已经修复了  太坏~~
