### ISSUE TITLE
添加服务器，无法选择加密模式

### ISSUE THREAD

**Issue by Helica-core** [shadowsocks/ShadowsocksX-NG#702]
**System and Shadowsocksx-NG version:**

- macOS 10.13.2 (16E????)
- Shadowsocksx-NG 1.7

**Expected behavior:**

**Actual behavior:**

点击选择加密模式无法点开，之后加密模式下拉菜单一闪而过。
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by qiuyuzhou** [comment]
duplicated of #894 ?
