### ISSUE TITLE
编译失败请问是什么原因啊

### ISSUE THREAD

**Issue by ilovebamboo** [shadowsocks/ShadowsocksX-NG#708]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

![qq20180120-111124](https://user-images.githubusercontent.com/6214084/35179299-abd392c0-fdd2-11e7-89d8-c10e2ae92ccb.png)

**Comment by xiaomingplus** [comment]
same

**Comment by qiuyuzhou** [comment]
Try branch release/v1.8.0
