### ISSUE TITLE
如何在Mac系统中同时运行多个SS代理

### ISSUE THREAD

**Issue by bianwenbo** [shadowsocks/ShadowsocksX-NG#710]
- 需求场景：两个Shadowsocks服务器A和B，A代理稳定高速但流量小，B代理速度慢但流量大。Mac系统希望能够在1080端口使用A的SS服务、在1082端口使用B的SS服务。
- 目前状态：ShadowsocksX-NG的配置文件在 $HOME/.ShadowsocksX-NG 中，所以即使在应用程序文件夹复制两份ShadowSocksX-NG应用其配置也无法独立配置。
- 疑问：能够指定配置文件位置？或者通过其他方案来在不同监听端口运行两个SS代理客户端？

谢谢。

**Comment by bianwenbo** [comment]
目前一个临时的解决方案是使用 ShadowsocksX-NG 配置A代理，通过终端brew安装并运行 ss-local 命令使用B代理。
不知道是否有更好的方案？

**Comment by ttimasdf** [comment]
个人的需求到这里来提issue不太好吧。自己动手呗。建议close

**Comment by jeange1003** [comment]
同需求，对与不同的网站，希望能切换到速度相对比较快的代理

**Comment by bianwenbo** [comment]
如果后面有人有同样的需求，这里提供方案：使用 [Shadowsocks-X](https://github.com/yangfeicheung/Shadowsocks-X) 可以和 ShadowsocksX-NG 同时运行，且不存在相互影响。

备注：

- 考虑使用 GUI 界面而非终端的方案，理由是可以简单的调用负载均衡功能。
- ShadowsocksX-NG, ShadowsocksX-NG-R8 均是基于 [ShadowsocksX](https://github.com/shadowsocks/shadowsocks-iOS/wiki/Shadowsocks-for-OSX-%E5%B8%AE%E5%8A%A9) 的衍生版本，因此不能同时调用不同的端口。
- 上述 ShadowsocksX 系列在 macOS 中没有指定配置文件（或难以编辑）。
- 如果没有负载均衡或者图形化操作的需求，更建议通过命令行使用 Shadowsocks-libev 版本后台运行。

**Comment by qiangbro** [comment]
+1

**Comment by ttimasdf** [comment]
2020年的方法：用 [V2ray](https://www.v2fly.org/) 或 [Clash](https://github.com/yichengchen/clashX) 。针对需求对不同域名/ip段写好路由，导流到不同的ss server就行了。
