### ISSUE TITLE
mac 10.13.1 无法使用

### ISSUE THREAD

**Issue by keepkay** [shadowsocks/ShadowsocksX-NG#711]
**System and Shadowsocksx-NG version:**

- macOS 10.13.1 (16E????)
- Shadowsocksx-NG 1.52 - 1.7.0 都不行

ss设置好后用，chrome 127.0.0.1:1086，1080都不行，试了N个版本都一样，windows / Linux下毫无问题

默认	01:11:22.970555 +0800	dasd	501:PDCardFileManager.CacheMaintenance:AA91F0:[
	{name: DeviceActivityPolicy, policyWeight: 20.000, response: {Decision: Must Not Proceed, Score: 0.00, Rationale: [{deviceActivity == 1}]}}
 ], FinalDecision: Must Not Proceed}
默认	01:11:22.971054 +0800	dasd	0:com.apple.apsd.apprefresh:624030:[
	{name: PowerNapPolicy, policyWeight: 5.000, response: {Decision: Must Not Proceed, Score: 0.00, Rationale: [{inADarkWake == 0 AND appRefresh == 1}]}}
 ], FinalDecision: Must Not Proceed}
默认	01:11:22.971096 +0800	dasd	Running activities : <private>
默认	01:11:22.971357 +0800	UserEventAgent	STARTING: <private>
默认	01:11:22.971506 +0800	UserEventAgent	STARTING: <private>
默认	01:11:22.971614 +0800	UserEventAgent	STARTING: <private>
默认	01:11:22.971894 +0800	dasd	Setting timer (isWaking=1, activityRequiresWaking=0) between <private> and <private> for <private>
默认	01:11:23.042072 +0800	UserEventAgent	Initiating XPC Activity: com.apple.suggestd.persist-stats
默认	01:11:23.041950 +0800	UserEventAgent	Initiating XPC Activity: com.apple.timed.ntp.wanted
默认	01:11:23.042663 +0800	UserEventAgent	Initiating XPC Activity: com.apple.cloudkit.assetHandleExpiration
默认	01:11:23.043558 +0800	UserEventAgent	Completed XPC Activity: com.apple.timed.ntp.wanted
默认	01:11:23.043767 +0800	UserEventAgent	Completed XPC Activity: com.apple.suggestd.persist-stats
默认	01:11:23.044045 +0800	dasd	COMPLETED 0:com.apple.timed.ntp.wanted:C9B562 <private>!
默认	01:11:23.044175 +0800	dasd	COMPLETED 501:com.apple.suggestd.persist-stats:154B85 <private>!
默认	01:11:23.044687 +0800	UserEventAgent	Rescheduling XPC Activity: com.apple.suggestd.persist-stats
默认	01:11:23.045085 +0800	UserEventAgent	Unregistered XPC Activity: com.apple.timed.ntp.wanted
默认	01:11:23.045154 +0800	UserEventAgent	SUBMITTING: <private>
默认	01:11:23.045448 +0800	dasd	Submitted Activity: 501:com.apple.suggestd.persist-stats:A3A388 <private>
默认	01:11:23.045627 +0800	dasd	Activity <private>: Optimal Score 0.5229 at <private> (Valid Until: <private>)
默认	01:11:23.045653 +0800	UserEventAgent	Completed XPC Activity: com.apple.cloudkit.assetHandleExpiration
默认	01:11:23.045979 +0800	dasd	COMPLETED 501:com.apple.cloudkit.assetHandleExpiration:CCE75D <private>!
默认	01:11:23.046233 +0800	UserEventAgent	Rescheduling XPC Activity: com.apple.cloudkit.assetHandleExpiration
默认	01:11:23.046514 +0800	UserEventAgent	SUBMITTING: <private>
默认	01:11:23.046723 +0800	dasd	Submitted Activity: 501:com.apple.cloudkit.assetHandleExpiration:03AE79 <private>
默认	01:11:23.046874 +0800	dasd	Activity <private>: Optimal Score 0.3596 at <private> (Valid Until: <private>)
默认	01:11:23.055328 +0800	kernel	encrypt_live_fs_data:3051: er: need to try again starting at fext: 0xa8972:0x0.
默认	01:11:25.869031 +0800	kernel	encrypt_live_fs_data:3051: er: need to try again starting at fext: 0xa8b85:0x0.
默认	01:11:26.961321 +0800	kernel	AGC:: [Google Chrome He pid:2520] force EG up last PID 2520 WS-ready 1 switch-state 0 IG FBs 1 EG FBs 0:0 power-state 6 3D busy HDA idle
默认	01:11:27.162374 +0800	kernel	AGC:: :::::::> PEG start powerup [0m 45.285s downtime]
默认	01:11:27.575818 +0800	kernel	AGC:: *******> PEG powerup took: 0.414s
默认	01:11:27.691725 +0800	kernel	+ IOAudioDevice[<private>]::protectedSetPowerState(1, <private>)
默认	01:11:27.691742 +0800	kernel	+ IOAudioDevice[<private>]::initiatePowerStateChange(<private>) - current = 0 - pending = 1
默认	01:11:27.693198 +0800	kernel	+- IOAudioDevice[<private>]::flushAudioControls()
默认	01:11:27.693208 +0800	kernel	+ IOAudioDevice[<private>]::protectedCompletePowerStateChange() - current = 0 - pending = 2
默认	01:11:27.693215 +0800	kernel	- IOAudioDevice[<private>]::protectedCompletePowerStateChange() - current = 2 - pending = 2 returns 0x0
默认	01:11:27.693223 +0800	kernel	+ IOAudioDevice[<private>]::protectedCompletePowerStateChange() - current = 2 - pending = 2
默认	01:11:27.693226 +0800	kernel	- IOAudioDevice[<private>]::protectedCompletePowerStateChange() - current = 2 - pending = 2 returns 0x0
默认	01:11:27.693229 +0800	kernel	- IOAudioDevice[<private>]::initiatePowerStateChange(<private>) - current = 2 - pending = 2 returns 0x0
默认	01:11:27.693232 +0800	kernel	- IOAudioDevice[<private>]::protectedSetPowerState(1, <private>) returns 0x0
默认	01:11:28.197043 +0800	kernel	encrypt_live_fs_data:3051: er: need to try again starting at fext: 0xa8d25:0x0.

**Comment by 0xfeedface1993** [comment]
试试打开终端，执行下面的代码：

` cd /Applications/ShadowsocksX-NG.app/Contents/Resources
chmod +x ss-local`

**Comment by keepkay** [comment]
cd /Applications/ShadowsocksX-NG.app/Contents/Resources     
chmod +x ss-local

尝试过你发的命令了，chrome 里 socks5 127.0.0.1 1086还是无法科学上网


ssr客户端应该没问题看到监听端口了，chrome还是不行
bogon:Resources deadpool$ lsof -iTCP -sTCP:LISTEN -n -P
COMMAND   PID     USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
QQ        416 deadpool   33u  IPv4 0x866b303c49cbddff      0t0  TCP 127.0.0.1:4300 (LISTEN)
QQ        416 deadpool   34u  IPv4 0x866b303c4a25af2f      0t0  TCP 127.0.0.1:4301 (LISTEN)
ss-local 3651 deadpool    6u  IPv4 0x866b303c40c94dff      0t0  TCP 127.0.0.1:1086 (LISTEN)
privoxy  3656 deadpool    3u  IPv4 0x866b303c4c93eb5f      0t0  TCP 127.0.0.1:1087 (LISTEN)

**Comment by 0xfeedface1993** [comment]
SSR? 这里是SS的客户端

本地Socks5监听地址试试设置为0.0.0.0看看

另外开了SS就应该可以科学上网了

**Comment by idealtimes** [comment]
哥们，你问题解决了吗？ss客户端的偏好设置应该如何设置？

**Comment by orangle** [comment]
+1 很老的版本的没事，换这个版本跟楼主一样的问题

**Comment by jungle89** [comment]
這個問題，建議你先安裝1.50bate2版本，試下是否可以上，如果可以再安裝最新版本。

**Comment by zhengyichen** [comment]
https://www.minicreo.com/omni-remover/
可以先用这个软件把shadowsocksX卸载了，然后重新安装，我就是这样解决的。。。

**Comment by xming4321** [comment]
+1  还是没解决啊

楼上贴的这个地址，软件下载下来不能用
