### ISSUE TITLE
10.13.1

### ISSUE THREAD

**Issue by Abner0802** [shadowsocks/ShadowsocksX-NG#717]
10.13.1刚刚更新了1.7不能翻墙了，每次开机都要提示输入密码？

**Comment by leonardwu** [comment]
10.13.2 表示正常使用

**Comment by Mourris** [comment]
1012.6 代开闪退啊

**Comment by Mourris** [comment]
1.7.0 用macOS 10.12.6打开闪退啊
允许任何来源已经打开了的

**Comment by yangfeicheung** [comment]
try this one and see if it works:

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by Abner0802** [comment]
搞了一个r8版本可以了，还可以ssr

**Comment by longpf** [comment]
10.13.3 应用打不开,Shadowsocks-X也打不开.右上角状态栏没有显示.又遇到的吗??

**Comment by Mourris** [comment]
请问你用的那个版本呀? 我用的是这个版本, 你换成这个版本试试
这个网站: http://ssr.superssr.me/
你注册了以后, 点击mac可以下载如下版本






在 2018-01-31 15:08:43，"long·pf" <notifications@github.com> 写道：


10.13.3 应用打不开,Shadowsocks-X也打不开.右上角状态栏没有显示.又遇到的吗??
