### ISSUE TITLE
PAC自动模式和全局模式翻墙效果不同

### ISSUE THREAD

**Issue by f2sky** [shadowsocks/ShadowsocksX-NG#721]
**System and Shadowsocksx-NG version:**

- macOS 10.11.6
- Shadowsocksx-NG 1.7.0（1）

打开 Google 服务（例如 Google 搜索或者 Gmail），在「PAC自动模式」下不能翻墙，或者翻墙速度很慢，但是切换到「全局模式」则可以比较顺畅的翻墙，翻墙速度还不错。

这种情况是怎么回事？

**Comment by yangfeicheung** [comment]
可能是由于部分连接没有在pac的列表里，更新下pac试试

**Comment by f2sky** [comment]
Google 的服务和应用怎么可能不在 PAC 列表里呢？

现在设置了切换模式的快捷键，需要的时候切换成全局模式来使用。

貌似这个应用没有配置教程，是系统自动配置代理模式，还是需要进行设置？

**Comment by yangfeicheung** [comment]
从原理上来说，pac模式会相对更快的，因为本地只有blocked的流量走server，其他都是直接连接，如果速度比较慢，其中可能的一个原因就是程序中的pac server有bug，导致请求pac的时候，有延迟，不过这个属于技术层面的，您不一定能理解。 可以尝试重启下app试试。 如果还有问题，可以尝试下我修改的版本，这个里面没有pac的问题，当然我也只是猜测可能的原因，如果不对，还请谅解。

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by f2sky** [comment]
从实际使用情况来看，浏览墙外网站时，确实「全局模式」比「PAC自动模式」稍微快一些，有时候「PAC自动模式」打不开的时候（例如梯子可能不是很稳定的时候），「全局模式」却能够打开。极端情况是，「PAC自动模式」完全打不开，而「全局模式」能打开，这时可能存在配置问题，原因不明。

所以猜想「PAC自动模式」是否存在翻墙效率降低的可能？

**Comment by yangfeicheung** [comment]
@f2sky  原理我已经说过了，pac效率不会低的，如果pac比全局低，那么可能就是某些pac的bug导致的，虽然pac未必比全局效率高很多，但是可以确定也不会低很多，在连接blocked网站方面，两个效率是差不多的。
至于pac模式打不开，全局模式可以打开，这个就是因为pac列表里面不包含您说的这个，所以默认直接连接，所以打不开。您可以自定义规则

**Comment by jdk137** [comment]
PAC 翻墙比全局慢太多， 之前的老版本没有这个问题，现在的新版本的问题。

**Comment by tuchang** [comment]
不是更新pac的问题 pac是正确的也依然用不了 只能用全局模式上

**Comment by mengyilangan** [comment]
我现在也遇到了，有解决方案吗？pac模式完全不可用，全局模式很流畅

**Comment by qiuyuzhou** [comment]
检查你们浏览器的配置和插件：
Chrome：SwitchyOmega
Firefox：有自己的代理设置

**Comment by tuchang** [comment]
之前就试过的 firefox edge 还有其他软件 都是这样 不是设置的问题
