### ISSUE TITLE
1.71 getpeername: Invalid argument

### ISSUE THREAD

**Issue by lunarc3** [shadowsocks/ShadowsocksX-NG#724]
getpeername: Invalid argument

I do not know how did this happen, but it appears on ss-local.log,which cause my Shadowsocks not working properly. Please help.

**Comment by shinyT** [comment]
mee too， How to resolve this?

**Comment by shinyT** [comment]
@lunarc3 mine has been resolved, I found the ss server port  is midified by update OSX on my machine!

**Comment by dmitri-vlasov** [comment]
Hi @tpfei578 ! could you please give me an advise how to resolve it? I have the same issue in logs. Thank you.

**Comment by yikerman** [comment]
> Hi @tpfei578 ! could you please give me an advise how to resolve it? I have the same issue in logs. Thank you.

It’s a system bug. Try updating your macOS.
