### ISSUE TITLE
Release 1.7.1 doesn't enable simple-obfs

### ISSUE THREAD

**Issue by ortonomy** [shadowsocks/ShadowsocksX-NG#732]
https://github.com/shadowsocks/ShadowsocksX-NG/releases/tag/v1.7.1

closed https://github.com/shadowsocks/ShadowsocksX-NG/issues/406 but it doesn't work. There are no simple-obfs settings. 

Suggest reopen #406

**Comment by pan-long** [comment]
It seems that PR didn't make it for 1.7.1 release https://github.com/shadowsocks/ShadowsocksX-NG/compare/v1.7.1...develop

Probably wait for the next release?

**Comment by bzdk** [comment]
+1

**Comment by xlf2630** [comment]
waiting for obfs

**Comment by maxming2333** [comment]
请看 #587 最下面的谈论

**Comment by qiuyuzhou** [comment]
Wait release of version 1.8.0
Or build branch `release/1.8.0` by yourself.
