### ISSUE TITLE
close

### ISSUE THREAD

**Issue by MicroKibaco** [shadowsocks/ShadowsocksX-NG#734]

**Comment by guolang** [comment]
手贱更新了10.13了吧，哈哈

**Comment by MicroKibaco** [comment]
我没有更新10.13 ,只是换了一个网络环境,就不能愉快的使用了.不过今天下午就彻底更新10.13 啦! 看来等发新版本才能使用的吧. firewalld,Apache,Nginx,全部禁🚫用,依然没有解决这个问题.主要想知道log日志描述的什么内容,希望大牛帮我解决一下.谢谢.

**Comment by guolang** [comment]
我用的最新的shadowsocksX-NG-r8 版本是1.4.3-r8 ，可以用

在 2018年2月22日 下午9:38，Zhengyou Yang <notifications@github.com>写道：

**Comment by MicroKibaco** [comment]
你要是不介意我们可以留个联系方式:QQ 569015640

**Comment by guolang** [comment]
https://github.com/qinyuhang/ShadowsocksX-NG-R/releases

在这里下载，然后设置服务器， chrome 中用switchyOmega, 直接用系统代理上网

注意： 这个r8的本地代理地址默认设置的是 127.0.0.1 , 端口  1086
