### ISSUE TITLE
建议使用域名作为服务器地址时，不定期刷新DNS解析，或超时后主动刷新DNS

### ISSUE THREAD

**Issue by umbrellary** [shadowsocks/ShadowsocksX-NG#740]
**System and Shadowsocksx-NG version:**

- macOS 10.13.3
- Shadowsocksx-NG 1.7.1

**应用场景:**
 - 使用OpenWRT路由器配合联通宽带做ss中转的时候，由于路由器地址使用DDNS，所以每次在更换公网IP的时候ss客户端便会无法使用。只有在开关一次ss客户端口，重新更新了DNS便可正常使用。（或者在Mac或者iPhone切换了网络，比如切换了不同Wi-Fi后也同样具有开关ss客户端相同的效果，刷新了DNS）

**Comment by qiuyuzhou** [comment]
NG是使用shadowsocks-libev的ss实现，本身只是个GUI界面。无法实现你要求。
