### ISSUE TITLE
1.7.1 pac 自动模式无法 访问google.com

### ISSUE THREAD

**Issue by gufengyouqi** [shadowsocks/ShadowsocksX-NG#741]
1.7.1 版本

直接安装的客户端，更新 从GFW list 更新pac文件——提示成功

选择pac自动模式

打开safari浏览器访问google.com，无法打开，

**Comment by yangfeicheung** [comment]
first check the network proxy, if the proxy has been successfully set, if not, you can set it manually.
and if you like, you can try this version as well:

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by gufengyouqi** [comment]
好的，谢谢，问题已经解决
使用姿势错误
问题原因是新配的代理，配好后不能及时生效，重启软件后，才会生效

**Comment by karottc** [comment]
> 好的，谢谢，问题已经解决
> 使用姿势错误
> 问题原因是新配的代理，配好后不能及时生效，重启软件后，才会生效

我的重启也不行，google 搜索勉强可以，但是docs.google.com 这个所有的google doc 不能访问
