### ISSUE TITLE
Chrome无法使用，Safari一切正常

### ISSUE THREAD

**Issue by limitMe** [shadowsocks/ShadowsocksX-NG#743]
**System and Shadowsocksx-NG version:**

- macOS 10.13.3 (16E????)
- Shadowsocksx-NG 1.7.1
- Chrome 64

Chrome无法使用（PAC与全局模式），Safari一切正常。
是否需要对Chrome进行特殊设置？

**Comment by limitMe** [comment]
是因为Chrome有额外插件的原因，设置里搜Proxy，看到的插件禁用即可。
我这里是因为Host Switch Plus这个插件。

**Comment by lxx2013** [comment]
![image](https://user-images.githubusercontent.com/20529542/79131730-a6ebc300-7ddb-11ea-9450-c375ae8a21b8.png)
我遇到了同样的问题, 关闭 Astar VPN 后可以用了

**Comment by fly-china** [comment]
chrome://extensions/  禁用了几个插件后，chrome 也正常了
