### ISSUE TITLE
macOS 10.13.3连接SS后，无法科学上网

### ISSUE THREAD

**Issue by yanhuiandy** [shadowsocks/ShadowsocksX-NG#748]
**System and Shadowsocksx-NG version:**

- macOS 10.13.3 (17D102)
- Shadowsocksx-NG 1.7.1 (1)

**Expected behavior:**
重装系统后第一次可以连接，之后就一直无法连接了
Ps. 移动端任何设备都可以连接，只有macOS 10.13.3无法连接

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log
[ss-local.log](https://github.com/shadowsocks/ShadowsocksX-NG/files/1789224/ss-local.log)

**

**Comment by juesexingqiu** [comment]
shadowsocks-qt5 installed on my Ubuntu pc can work correctly,while Shadowsocksx-NG 1.7.1 (1) install on Mac can't

**Comment by oamzn** [comment]
macOS 10.13.3 一样Shadowsocksx-NG 1.7.1无法使用

**Comment by tsmairc** [comment]
macOS 10.13.3 一样Shadowsocksx-NG 1.7.1无法使用

**Comment by Shadowsocksla** [comment]
叫我雷锋
购买地址 [https://portal.shadowsocks](https://portal.shadowsocks.to/aff.php?aff=12091)

加密方式需要設置為 chacha20-ietf-poly1305 ，必須完全一致
舊版本客戶端可能不支持該加密方式，請更新
• Windows  客戶端下載 https://portal.shadowsocks.la/files/Shadowsocks-4.0.6.zip 注：需要安裝 .NET FrameWork 4.6.2 以上版本
• iOS  相關客戶端與使用方法請參考下述鏈接： https://github.com/Shadowsocks-Wiki/shadowsocks/blob/master/4-ios-settings.md
• MAC OS  請更新到 ShadowsocksX-NG 使用 下載地址： https://portal.shadowsocks.la/files/ShadowsocksX-NG.1.6.1.zip
• Android下載地址  下載地址： https://portal.shadowsocks.la/files/shadowsocks-nightly-4.2.5.zip
• Linux用戶  請使用最新的 Shadowsocks-libev 命令行版本 安裝與使用請參考：https://github.com/shadowsocks/shadowsocks-libev

**Comment by m4XEp1** [comment]
没法上网 +1

**Comment by yangfeicheung** [comment]
please try this one macOS 10.13:
https://github.com/yangfeicheung/Shadowsocks-X

**Comment by yanhuiandy** [comment]
我的目前解决了：
1.先安装2.12 (22)，更新PAC后，
2.在安装1.7.1 (1)，暂时可以用了

**Comment by MingCrash** [comment]
shadowsocks的MacOS客户端是不是不行了？

**Comment by yangfeicheung** [comment]
follow the instructions here:

https://www.sednax.com/faq-0-cn.php

**Comment by mujiansu** [comment]
我这边看下来是默认得偏好设置有误，Socks5监听端口和Http监听端口是同一个，修改Http监听端口即可

**Comment by lichengqi0805** [comment]
sock5监听端口在哪查看？

**Comment by yangfeicheung** [comment]
偏好设置

**Comment by lichengqi0805** [comment]
没看到偏好设置这个选项啊

**Comment by OrangeCatLei** [comment]
http端口改成啥啊

**Comment by mujiansu** [comment]
只要现在没被使用的就可以

**Comment by yangfeicheung** [comment]
@OrangeCatLei
http port:  1025-65535
socks port: 1025-65535

for example, you can set it as
http port:  10888
socks port: 10889

These two ports should be set to different values.

**Comment by OrangeCatLei** [comment]
how to input my server by QR code？？？

**Comment by gzf6** [comment]
macos 10.13.4: It shows "Not found valid qrcode of shadowsocks profile".

**Comment by tlee1987** [comment]
确实不能上网啊。我和环境跟楼主的是一样的，MacOS:10.13.3  ShadowsocksX-NG:1.7.1(1)，无法科学上网。请大神修复Bug

**Comment by jaya1992** [comment]
macOS 10.13.5  Shadowsocksx-NG 1.7.1 也无法使用

**Comment by yangfeicheung** [comment]
Try this version if you are interested:

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by jaya1992** [comment]
@yangfeicheung  试过了，还是不行。ping过主机IP没有被墙，有没有可能是vps里的ss被墙了呢？之前NG这个软件一直可以顺利翻墙的，就是前几天忽然不行了

**Comment by yangfeicheung** [comment]
@jaya1992
能ping通不表示就可以連上，有些是可以ping，但是根本連不上，您可以嘗試用掃描端口的app測試下，端口是否打開

**Comment by yangfeicheung** [comment]
如果是您自己的server的話，您直接ssh看是否可以連接上，如果連不上，但是ping得通，那就是ip被block了

**Comment by jaya1992** [comment]
@yangfeicheung  非常感谢，是我的ip被墙了，换IP后，1.7 在 macOS 10.13.5 上完美运行
