### ISSUE TITLE
自动模式上不去阿里云国际站，全局模式又导致PayPal被封

### ISSUE THREAD

**Issue by lhmcn** [shadowsocks/ShadowsocksX-NG#750]
**System and Shadowsocksx-NG version:**

- macOS 10.13.1 (17B1003)
- Shadowsocksx-NG 1.7.1 (1)

**Expected behavior:**
在User Rules for PAC中添加了
||alibaba.com
||aliyun.com
||alibabacloud.com
希望正常访问阿里云国际站（https://ecs-buy-intl.aliyun.com/），并通过PayPal支付

**Actual behavior:**
PAC模式无法打开页面，全局模式可以。
但挂着代理用PayPal会被封账户

不知是否跟我的网络有关，但希望全局模式能有个排除名单，这样就完美了

**Comment by lrz0** [comment]
为什么不使用 Proxy SwitchyOmega 等浏览器插件呢？

全局模式+排除名单不就是 pac 模式了吗？

或者你可以试试反向 [gfwlist](https://github.com/gfwlist/tsilwfg) ？

**Comment by yangfeicheung** [comment]
Hi @lhmcn, you can try this version:

https://github.com/yangfeicheung/Shadowsocks-X

1. choose Auto Mode
2. open Custom Rules and add:
alibaba.com
aliyun.com
alibabacloud.com

Then I guess it's good to go
