### ISSUE TITLE
开启全局模式后为什么网络偏好设置只开启了socket5代理？

### ISSUE THREAD

**Issue by CrazyMouse** [shadowsocks/ShadowsocksX-NG#751]
有个疑问想请教一下：
为什么开启全局模式后网络偏好设置只开启了socket5代理？在这个情况下，chrome能正常走SS，但我自己用python写的代码就不会走SS，为啥全局模式不自动开启http和https代理呢？
还有一个疑问是全局模式没有开启http和https代理的情况下，是怎么实现让chrome和safari自动走ss的socket通道的？望不吝赐教，谢谢

**Comment by lrz0** [comment]
全局模式只能影响大部分GUI程序的代理，CLI程序的代理需要手动设置，这是系统机制决定的。

**Comment by CrazyMouse** [comment]
@lrz0 总算搞明白这个原理了，非常感谢您的解答，我的python脚本就是用您上面说的HTTP_PROXY=127.0.0.1:xxx 来搞定的
