### ISSUE TITLE
目前Shadowscoks在北京都不能使用

### ISSUE THREAD

**Issue by green77120** [shadowsocks/ShadowsocksX-NG#756]
請問大家有這個問題嗎？

自從2017.09.買完一年會員之後短暫使用過幾個星期。。。

之後2017.10月中國19大會議之後到現在都不能使用ＶＰＮ。。。

連會員網站都進不去 請問該怎麼處理呢？

第一次是在2017.10寄過一次e-mail後回覆說會議結束後會恢復系統並且有相關補償。。。

之後再寄信連寄信都沒有回覆了....

請問大家如何處理？有沒有shadowscoks的官方聯絡方式？或者有其他退費方法？

**Comment by yangfeicheung** [comment]
hi, try this one, it should be working fine on your mac:

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by chiseller** [comment]
这是来错地方了吧
