### ISSUE TITLE
请问在pac模式下，如果手动添加一个ip段到翻墙列表中

### ISSUE THREAD

**Issue by henrikzheng** [shadowsocks/ShadowsocksX-NG#758]
pac模式下，但是telegram还是不能访问，虽然通过在telegram里面手动设置socks5代理能解决。但是这样设置起来很麻烦。

请问有什么办法能将telegram的ip段 91.108.56.0/22加入翻墙中，这样就不用设置代理了

**Comment by henrikzheng** [comment]
ipset add gfwlist 91.108.56.0/22【修改/etc/misstar/applications/ss/script/ss 在 start_ss_rules_gfwlist函数中加入这一行，路由器重启也能自动生效】

**Comment by yangfeicheung** [comment]
follow this instructions:

https://www.sednax.com/faq-7-cn.php

**Comment by henrikzheng** [comment]
this will solve the proble too. But it need to add so many ip address to the rules.
just modify the gfwlist.js and add this line will be fine:
  if (isInNet(host, "91.108.56.0", "255.255.252.0")) return proxy;

**Comment by yangfeicheung** [comment]
@henrikzheng
not verybody knows how to change a js file, for ppl who don't know js, it's pretty hard and may lead to corrupt js file, so the best way is to add via UI menus

**Comment by qiuyuzhou** [comment]
从原理无法实现，应该pac匹配是在域名解析前，是用域名进行匹配的，如果需要翻墙，是在服务器进行域名解析的。
