### ISSUE TITLE
macOS 10.13.13 启动没反应

### ISSUE THREAD

**Issue by BENULL** [shadowsocks/ShadowsocksX-NG#759]
- macOS 10.13.13 
- Shadowsocksx-NG 1.7

**Actual behavior:**
启动无响应
(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by yangfeicheung** [comment]
follow the instructions here and try again:

https://www.sednax.com/faq-0.php
