### ISSUE TITLE
官网上不去了，有人看下吗？

### ISSUE THREAD

**Issue by whyssjn** [shadowsocks/ShadowsocksX-NG#760]
**System and Shadowsocksx-NG version:**

- macOS 10.13.3
- Shadowsocksx-NG 1.7.1(1)

**Expected behavior:**
我访问的官网地址是  https://portal.shadowsocks.la/clientarea.php   但是现在访问不了了。
今天使用客户端时，我的一个服务器地址已经不能使用了，幸好另一个保存的可以使用。
我担心的是官网不能登陆的话，那么我剩下的这个服务器也不能使用了，那么我还怎么使用呀？

**Comment by yangfeicheung** [comment]
This is not the official site, it's simply a seller

**Comment by evenardo** [comment]
no official site any where ~

**Comment by moonclock** [comment]
这只是一个开源软件,不参与任何的买卖ss服务的网站.

**Comment by bluicezhen** [comment]
这个不是官网，只是一个卖SS服务的服务商
