### ISSUE TITLE
ACL自动模式和白名单模式都出问题啦

### ISSUE THREAD

**Issue by renjiale1214** [shadowsocks/ShadowsocksX-NG#761]
上周末开始slack在公司的WiFi下被墙，无奈只好开启了全局，但是全局对国内访问实在不友好。
琢磨了一下发现白名单模式是OK的，可以正常走国内节点，科学上网也很正常，重要的是slack又能用了！

蓝鹅蓝鹅，我就去开了个会，回来打开电脑后白名单模式出问题了，不能访问外网&slack。遂决定切回ACL，结果ACL也不能科学上网了。
开了一天全局，刚才尝试了一下PAC发现PAC倒是正常，虽说slack还是不能用。

我中途操作过更新gfw列表和白名单，是不是因为这个造成的？我也尝试了更换我的订阅以及删除重新下载dmg，不过以前的配置应该都保留着，只要一打开就像之前一样。

有没有懂的人帮忙解释一下，是因为我的订阅商的问题，还是SS出问题了

**Comment by yangfeicheung** [comment]
hi, contact me via my email, I'll look into this for you.

**Comment by renjiale1214** [comment]
Thks， I‘ve fixed this issue, I use PAC with a customed list now.

**Comment by qiuyuzhou** [comment]
官方版的实现，不支持ACL和白名单模式

**Comment by 1991wangyufei** [comment]
我跟你遇到的问题一模一样，也是中途不小心操作过更新了gfw列表和ACL白名单、PAC名单，然后首页里的“白名单模式”就用不了了，google都打不开，其他几个模式正常，怎么能恢复白名单模式呢？
