### ISSUE TITLE
启动代理后无法访问网络

### ISSUE THREAD

**Issue by huawei798** [shadowsocks/ShadowsocksX-NG#763]
**System and Shadowsocksx-NG version:**

- macOS 10.11.16  
- Shadowsocksx-NG 1.7.1

启动代理后无法访问网络
日志：
com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[4672]): Service could not initialize: 15G1611: xpcproxy + 12684 [1462][04735878-FE18-3961-8430-E328A07D7B91]: 0xd

**Comment by yangfeicheung** [comment]
Hi, if you like ,follow this instructions and give it a shot:

https://www.sednax.com/faq-0-cn.php

**Comment by swnb** [comment]
thanks,it works @yangfeicheung
