### ISSUE TITLE
Using Global Mode but some Apps not passing via ShadowSocks-X NG

### ISSUE THREAD

**Issue by fahadsgalaxy** [shadowsocks/ShadowsocksX-NG#767]
Hi,

I was using the older version of Shadow Socks-X. Just recently switched to NG version. Its pretty nice.

I'm having issues with passing Application traffic. Some Apps just connect to the network directly and not via the ShadowSocks. Making Global also doesnt work.

Is there some thing that I'm missing ?

**Comment by yangfeicheung** [comment]
If that app uses system proxy, then shadowsocks will work, it that app skips system proxy, then you need to manually set network proxy for that app, let's take dropbox for example, you need to set network proxy for dropbox, check it out here:

https://www.sednax.com/faq-3.php

**Comment by qiuyuzhou** [comment]
Not all applications support using system proxy settings.
