### ISSUE TITLE
Change Mod or close the ss will kill the ss-local and run the privoxy

### ISSUE THREAD

**Issue by yuanjingsong** [shadowsocks/ShadowsocksX-NG#769]
**System and Shadowsocksx-NG version:**

- macOS 10.13
- Shadowsocksx-NG 1.7.1

**Expected behavior:**
When i change the ss mod or close the ss, ss-local will be killed and privoxy will run.
And then it shows the `Address already in use; bind() error`
When the ss works well, it will only run the ss-local
So  I have to kill the privoxy and close the ss (if need) and run ` ln -fs ss-local-latest/ss-local` and `chmod +x  ss-local` to run the ss-local correctly.

Maybe the provixy doesn't work on macOS 10.13 ?

**Comment by yangfeicheung** [comment]
Hi bro, Shadowsocks NG makes use of ss-local and runs it as another standalone service, if you want one without standalone application, you can try this version:

https://github.com/yangfeicheung/Shadowsocks-X

It runs directly without ss-local

**Comment by yuanjingsong** [comment]
@yangfeicheung Thanks for replaying~ 
But i think i didn't make myself clear. 
To make the ss works well, ss-local has to work directly without privoxy.
I think it is the privoxy that made my ss doesn't work 👍 D

**Comment by yangfeicheung** [comment]
privoxy actually has nothing to do with ss-local, privoxy is just a http/https proxy, e.g. if you need http/https proxy, then NG will start privoxy, then privoxy will be working as a http proxy but it working on top of ss-local, without ss-local, privoxy won't work as well.

Hope you can understand this
