### ISSUE TITLE
直接开个telegram群大家交流方便点

### ISSUE THREAD

**Issue by omaidb** [shadowsocks/ShadowsocksX-NG#77]
直接开个telegram群大家交流方便点，https://telegram.me/joinchat/BlgWbT_2Roa-1qPYVCQUMA

**Comment by FromTG** [comment]
1、打开纸飞机后，点击右上角的放大镜

2、然后先输入一个@符号。在这个@符号后面输入 zwdhqun 这个中文导航群可以帮助你找到你想要的群

3、输入后点击这个群的图标

4、接着点击底部加入就可以进入到群里面了。加入了以后发送任意关键字到群内查找你喜欢的内容
