### ISSUE TITLE
Shimo PPTP with SS

### ISSUE THREAD

**Issue by TIL-MICE** [shadowsocks/ShadowsocksX-NG#770]
**System and Shadowsocksx-NG version:**

- macOS 10.13.3 (17D102)
- Shadowsocksx-NG 1.7

**Expected behavior:**

Can't use it with Shimo PPTP

For some reason, i have to  use Shimo PPTP to connect internet, and i want use ss to proxy, but it not work.

When i use windows，it's ok ,

**Actual behavior:**

i can use internet ,but can't proxy.

**ss-local.log**

 2018-03-24 11:26:22 INFO: initializing ciphers... aes-256-cfb
 2018-03-24 11:26:22 INFO: listening at 127.0.0.1:1086
 2018-03-24 15:21:28 INFO: initializing ciphers... aes-256-cfb
 2018-03-24 15:21:28 INFO: tcp port reuse enabled
 2018-03-24 15:21:28 INFO: listening at 127.0.0.1:1086
no more ...

**Application log**
None

**Comment by xindubawukong** [comment]
Did you solved this problem? I can't connect with shimo either.

**Comment by xindubawukong** [comment]
@TIL-MICE 
Did you solved this problem? I can't connect with shimo either. 您后来怎么解决的？

**Comment by TIL-MICE** [comment]
> @TIL-MICE
> Did you solved this problem? I can't connect with shimo either. 您后来怎么解决的？

简言之，我放弃了
