### ISSUE TITLE
Don't trust yangfeicheung.

### ISSUE THREAD

**Issue by developforapple** [shadowsocks/ShadowsocksX-NG#772]
Don't trust yangfeicheung. 
Don't trust yangfeicheung.
Don't trust yangfeicheung.

**Comment by yangfeicheung** [comment]
lol, why?

**Comment by Kroderia** [comment]
@yangfeicheung publish a open source Shadowsocks, that's great.  
However, you add your selling infomation in it and go ShadowsocksX-NG issues for advertising.  
I just download that "fake" ShadowsocksX-NG from the link you provided minutes ago.
As a major developer @qiuyuzhou, can you just ban him and answer issues sometimes?
