### ISSUE TITLE
support go throw upstream proxy or not ??

### ISSUE THREAD

**Issue by openLic** [shadowsocks/ShadowsocksX-NG#775]
Hello, is there any way use shadowsocksX-NG behind a http proxy, because my company network also  has a gfw.
I know tinyproxy and squid also support that with upstream or cache_peer some parameters.
Like this:
SS-Client -> Proxy Server -> Internet -> SS-Server

Thank you very much!

**Comment by qiuyuzhou** [comment]
Not possible.
