### ISSUE TITLE
launchpad没有ShadowsocksX-NG图标,但finder里面有

### ISSUE THREAD

**Issue by exxfzc** [shadowsocks/ShadowsocksX-NG#776]
不知道这个问题会不会很突兀,安装了ShadowsocksX-NG1.7.1,macos10.12.1,可以顺利翻墙,但是发现在launchpad发现并没有ShadowsocksX-NG的快捷方式图标(翻到第二页还是没有),但是在finder应用程序里面就有,很奇怪
<img width="1280" alt="2018-03-31 12 00 09" src="https://user-images.githubusercontent.com/23161815/38159364-89fc183c-34d9-11e8-888f-97d1ad8b01e3.png">
<img width="1280" alt="2018-03-31 11 59 50" src="https://user-images.githubusercontent.com/23161815/38159365-8a3dbd82-34d9-11e8-9f2a-dadccfee0af2.png">

**Comment by yknext** [comment]
Because the code is not signed, it will not be displayed there

**Comment by bi-kai** [comment]
一样的问题，而且我的启动不起来，点了没反应

**Comment by CoderSF** [comment]
图上launchpad第一列第三行是什么？

**Comment by Arthur244** [comment]
你需要把r8那个版本删掉才能看到你安装的.

**Comment by laughter8** [comment]
> 一样的问题，而且我的启动不起来，点了没反应

所以你的最后怎样解决的呢

**Comment by bi-kai** [comment]
@laughter8 不要装最新版本的，新版本在macos上基本没可用过。网上找找可用版本吧。
