### ISSUE TITLE
does not work in osx 10.13.3

### ISSUE THREAD

**Issue by cathowlet** [shadowsocks/ShadowsocksX-NG#777]
**System and Shadowsocksx-NG version:**

- macOS 10.13.3 
- windows7 (Shadowsocks 4.0.9)
- Shadowsocksx-NG 1.7.0(1)
- ShadowsocksX 2.14(24)

it works well on windows7 with Shadowsocks 4.0.9 while it does not work on my mac macOS 10.13.3 with Shadowsocksx 2.14(24) None-Store-App version downloaded on sednax.com.

**Comment by OrangeCatLei** [comment]
mine too，never worked_(:з」∠)_

**Comment by maplebeats** [comment]
me too, can't start it - -

**Comment by wubx** [comment]
mine too，never worked

**Comment by helibin** [comment]
10.13.3 can work, but not perfect.

the dropdown menu for crypto method has some mistake

**Comment by yangfeicheung** [comment]
for those who fails to start app on mac, you can reach me via my email, I would instruct you to install it step by step on your mac.

**Comment by bi-kai** [comment]
does not work too

**Comment by yangfeicheung** [comment]
For those who fails to start app on mac, you can reach me via my email, I would instruct you to install it step by step on your mac, or you can follow those steps:

https://www.sednax.com/faq-0.php
