### ISSUE TITLE
分享一个ss/ssr账号

### ISSUE THREAD

**Issue by udvrsedy** [shadowsocks/ShadowsocksX-NG#778]
IP：104.160.176.35
端口：666
密码：dongtaiwang.com
加密方式：aes-256-cfb
协议：auth_sha1_v4
混淆：plain

不限速，不限流量。协议和混淆兼容ss版，使用期限：直到被墙。

**Comment by gMan1990** [comment]
3q

**Comment by gMan1990** [comment]
that is great
