### ISSUE TITLE
网络代理设置，设置为`自动发现代理`后失效。

### ISSUE THREAD

**Issue by yzfdjzwl** [shadowsocks/ShadowsocksX-NG#779]
除了Title的一个问题，还有两个问题想要得到解决，在网上搜了都没有找到解决办法。

* 第一个问题，每次打开shadowsocksX-ng的时候，系统都会提示`ShadowsocksX-NG`想要进行更改，请输入密码。在系统设置里也没找到关闭的选项。(确实有强迫症)
![1](https://user-images.githubusercontent.com/21030370/38186955-2a8d8b78-3688-11e8-9673-07d7f6150aa1.jpeg)
* 第二个问题， 我想要听网易云的歌曲，但是提示地区版权不支持，说明在使用网易云音乐的时候也是在墙外，这个问题该如何解决呢？
* 第三个问题，就是Title中的问题，如果我设置了`自动发现代理`而不设置`SOCKS`代理，那么会失效，翻不出去。
![2](https://user-images.githubusercontent.com/21030370/38187081-ab31819e-3688-11e8-9184-833cf5ba74a1.png)

PS：之前用ShadowSocks都没有这几个问题，现在装了SS-ng后就出现了这几个问题。猜测是配置不对，若有小伙伴遇类似的问题，感谢告之。

MacOS: 10.12.6
SS-ng: 1.7.1

**Comment by yangfeicheung** [comment]
You can reach me via email, I can fix this for you by sending you instructions

**Comment by yzfdjzwl** [comment]
@yangfeicheung 太感谢～

**Comment by keepondream** [comment]
怎么解决的？

**Comment by yangfeicheung** [comment]
@keepondream,
some permission issue
