### ISSUE TITLE
SSX-NG 经常申请要求高性能GPU

### ISSUE THREAD

**Issue by Loyea** [shadowsocks/ShadowsocksX-NG#780]
SSX-NG其实对能耗要求很低，但是SSX-NG有个明显的问题就是偶尔会要求高性能GPU，导致被macOS认定为高耗能应用，这个问题从一开始的版本到现在都会有，一般都是SSX-NG打开一段时间后才会出现。

<img width="196" alt="qq20180402-184941 2x" src="https://user-images.githubusercontent.com/3928564/38193916-24122f96-36a7-11e8-85a0-fa85cc8b0c30.png">

<img width="762" alt="qq20180402-185018 2x" src="https://user-images.githubusercontent.com/3928564/38193918-28fadc9c-36a7-11e8-905c-173af2fcb6b9.png">

**Comment by timothyqiu** [comment]
Hi, did you open the QR code window?
It would also be appreciated if you could provide the version of SSX-NG.

**Comment by Loyea** [comment]
我也不记得之前出现这样的情况是不是因为扫描了屏幕上的二维码。

但是经过测试的确在使用‘扫描屏幕上的二维码’功能之后，ssx-ng会被系统列入高能耗应用。

另外我的ssx-ng版本是 1.7.1 （不过这问题很早就有了）

**Comment by Loyea** [comment]
@yangfeicheung 一样的，扫描二维码后进入高能耗应用列表

**Comment by qiuyuzhou** [comment]
这个曾经修复过。是独立显卡的电脑才有问题。
显示二维码会开启GPU，因为使用了CoreGraph库生成QRCode。
我这是测试不了的，没有带独立显卡的mac。

**Comment by totoroyyb** [comment]
@qiuyuzhou 1.7.1版本也存在问题。测试的确是因为扫描过屏幕二维码后，使用了独显。但是扫描完成后，SS依旧申请着高性能GPU。不知能否在扫描过后，Dispose一下，不再调用高性能GPU。因为不然系统一直挂着独显。谢谢。

**Comment by Loyea** [comment]
@totoroyyb 换shadowsocksX-NG-R8吧，修复了这个问题
