### ISSUE TITLE
Where Can I buy ShadowSocks Subscription in China ?

### ISSUE THREAD

**Issue by fahadsgalaxy** [shadowsocks/ShadowsocksX-NG#784]
I am looking for a good ShadowSocks Proxy Provider in China

Can someone help me please ?

Thanks

**Comment by SimonHolmeslm** [comment]
before, i can open the ShadowSocks  website and buy it, but now i cannot open it :(

**Comment by yangfeicheung** [comment]
try this one:

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by rtpro** [comment]
You can try using https://shadowtunnelz.com/
