### ISSUE TITLE
编译出来的包双击后没有任何反应

### ISSUE THREAD

**Issue by liugang1014** [shadowsocks/ShadowsocksX-NG#785]
下载你的源码后，加了一个自动获取免费服务器并且定时刷新免费服务器的功能，在xcode里面直接debug运行没有任何问题，正常翻墙。但是尝试直接双击运行编译出来的包是没有任何效果，不知道问题出在哪呢？请指教。

os:10.13.1
xcode:9.2

**Comment by qiuyuzhou** [comment]
macos的新安全机制，未签名的app不准运行。请自行google怎么调整设置
