### ISSUE TITLE
无论怎么设置,流量都不走ShadowsocksX-NG

### ISSUE THREAD

**Issue by aababy** [shadowsocks/ShadowsocksX-NG#789]
**System and Shadowsocksx-NG version:**

- macOS 10.11.6 (15G31)
- Shadowsocksx-NG 1.6.1 /1.7.1

**Expected behavior:**
运行正常

**Actual behavior:**
手机是完全正常的, 就是mac连不起(同一个服务器)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

 2018-04-13 20:21:27 INFO: initializing ciphers... aes-256-cfb
 2018-04-13 20:21:27 INFO: listening at 127.0.0.1:10889
 2018-04-13 20:27:16 INFO: initializing ciphers... aes-256-cfb
 2018-04-13 20:27:16 INFO: listening at 127.0.0.1:10889

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

18/4/13 下午7:28:51.598 ShadowsocksX-NG[1536]: Call SMLoginItemSetEnabled with [1] success
18/4/13 下午7:29:24.816 ShadowsocksX-NG[1536]: Stop ss-local succeeded.
18/4/13 下午7:29:24.893 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.http[1601]) Service exited with abnormal code: 15
18/4/13 下午7:29:24.952 ShadowsocksX-NG[1536]: Stop privoxy succeeded.
18/4/13 下午7:29:25.020 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:29:25.095 ShadowsocksX-NG[1536]: Stop ss-local succeeded.
18/4/13 下午7:29:25.166 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:29:25.233 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:29:25.234 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:29:25.290 ShadowsocksX-NG[1536]: pac proxy set to global
18/4/13 下午7:29:25.915 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:29:26.076 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:29:26.191 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
18/4/13 下午7:29:26.200 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:29:30.484 ShadowsocksX-NG[1536]: Call SMLoginItemSetEnabled with [1] success
18/4/13 下午7:29:39.150 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.local) Service only ran for 2 seconds. Pushing respawn out by 8 seconds.
18/4/13 下午7:29:39.197 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:29:39.269 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:29:39.338 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:29:39.373 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:29:39.430 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:29:39.465 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:29:39.465 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:29:39.517 ShadowsocksX-NG[1536]: pac proxy set to global
18/4/13 下午7:34:57.406 ShadowsocksX-NG[1536]: Call SMLoginItemSetEnabled with [1] success
18/4/13 下午7:35:34.342 ShadowsocksX-NG[1536]: Stop ss-local succeeded.
18/4/13 下午7:35:34.413 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.http[1719]) Service exited with abnormal code: 15
18/4/13 下午7:35:34.471 ShadowsocksX-NG[1536]: Stop privoxy succeeded.
18/4/13 下午7:35:34.539 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:35:34.611 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:35:34.683 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:35:34.742 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:35:34.743 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:35:34.825 ShadowsocksX-NG[1536]: pac proxy set to global
18/4/13 下午7:35:35.366 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:35:35.590 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:36:21.961 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:36:22.032 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:36:22.099 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:36:22.107 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:36:22.157 ShadowsocksX-NG[1536]: pac proxy set to auto
18/4/13 下午7:36:28.920 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:36:28.990 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:36:29.057 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:36:29.058 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:36:29.113 ShadowsocksX-NG[1536]: pac proxy set to global
18/4/13 下午7:36:43.418 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:36:43.488 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:36:43.556 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:36:43.557 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:36:43.608 ShadowsocksX-NG[1536]: pac proxy set to off
18/4/13 下午7:39:05.201 ShadowsocksX-NG[1536]: bind profile 0
18/4/13 下午7:39:27.426 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:39:27.499 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:39:27.571 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:39:28.624 ShadowsocksX-NG[1536]: Start kcptun succeeded.
18/4/13 下午7:39:30.703 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:39:30.725 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:39:30.748 ShadowsocksX-NG[1536]: Start kcptun succeeded.
18/4/13 下午7:39:30.748 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:39:30.804 ShadowsocksX-NG[1536]: pac proxy set to global
18/4/13 下午7:39:51.404 ShadowsocksX-NG[1536]: bind profile 0
18/4/13 下午7:40:00.252 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:40:00.323 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:40:00.357 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:42:59.021 ShadowsocksX-NG[1536]: Start ss-local succeeded.
18/4/13 下午7:42:59.105 ShadowsocksX-NG[1536]: Start privoxy succeeded.
18/4/13 下午7:42:59.181 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:42:59.182 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:42:59.266 ShadowsocksX-NG[1536]: pac proxy set to off
18/4/13 下午7:49:12.632 ShadowsocksX-NG[1536]: Stop ss-local succeeded.
18/4/13 下午7:49:12.699 ShadowsocksX-NG[1536]: Stop kcptun succeeded.
18/4/13 下午7:49:12.711 com.apple.xpc.launchd[1]: (com.qiuyuzhou.shadowsocksX-NG.http[1996]) Service exited with abnormal code: 15
18/4/13 下午7:49:12.760 ShadowsocksX-NG[1536]: Stop privoxy succeeded.
18/4/13 下午7:49:12.760 ShadowsocksX-NG[1536]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:50:03.270 com.qiuyuzhou.ShadowsocksX-NG.LaunchHelper[323]: ShadowsocksX-NG LaunchHelper
18/4/13 下午7:50:08.082 ShadowsocksX-NG[371]: Call SMLoginItemSetEnabled with [1] success
18/4/13 下午7:50:08.376 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午7:50:08.585 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午7:50:08.656 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午7:50:08.657 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:50:08.763 ShadowsocksX-NG[371]: pac proxy set to off
18/4/13 下午7:51:54.274 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午7:51:54.345 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午7:51:54.412 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午7:51:54.413 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:51:54.474 ShadowsocksX-NG[371]: pac proxy set to global
18/4/13 下午7:54:47.868 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午7:54:47.939 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午7:54:48.006 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午7:54:48.018 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午7:54:48.080 ShadowsocksX-NG[371]: pac proxy set to auto
18/4/13 下午8:17:46.735 ShadowsocksX-NG[371]: Stop ss-local succeeded.
18/4/13 下午8:17:46.806 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:17:46.873 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:17:46.873 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:17:46.925 ShadowsocksX-NG[371]: pac proxy set to off
18/4/13 下午8:17:50.924 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:17:50.998 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:17:51.066 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:17:51.067 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:17:51.117 ShadowsocksX-NG[371]: pac proxy set to auto
18/4/13 下午8:18:17.204 ShadowsocksX-NG[371]: bind profile 0
18/4/13 下午8:18:24.195 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:18:24.267 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:18:24.334 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:18:33.912 ShadowsocksX-NG[371]: Stop ss-local succeeded.
18/4/13 下午8:18:33.984 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:18:34.052 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:18:34.052 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:18:34.110 ShadowsocksX-NG[371]: pac proxy set to off
18/4/13 下午8:18:40.795 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:18:40.866 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:18:40.934 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:18:40.935 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:18:40.992 ShadowsocksX-NG[371]: pac proxy set to auto
18/4/13 下午8:20:02.983 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:20:03.054 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:20:03.124 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:20:03.125 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:20:03.197 ShadowsocksX-NG[371]: pac proxy set to global
18/4/13 下午8:20:22.708 ShadowsocksX-NG[371]: bind profile 0
18/4/13 下午8:20:37.712 ShadowsocksX-NG[371]: Call SMLoginItemSetEnabled with [1] success
18/4/13 下午8:20:47.683 ShadowsocksX-NG[371]: Stop ss-local succeeded.
18/4/13 下午8:20:47.746 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:20:47.780 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:20:47.814 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:20:47.849 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:20:47.866 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:20:47.867 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:20:47.925 ShadowsocksX-NG[371]: pac proxy set to global
18/4/13 下午8:20:48.815 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:21:20.235 ShadowsocksX-NG[371]: Stop ss-local succeeded.
18/4/13 下午8:21:20.307 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:21:20.375 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:21:20.375 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:21:20.448 ShadowsocksX-NG[371]: pac proxy set to off
18/4/13 下午8:21:27.950 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:21:28.020 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:21:28.088 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:21:28.089 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:21:28.137 ShadowsocksX-NG[371]: pac proxy set to global
18/4/13 下午8:21:36.872 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:21:36.944 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:21:37.011 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:21:37.011 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:21:37.058 ShadowsocksX-NG[371]: pac proxy set to auto
18/4/13 下午8:21:39.272 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:21:39.343 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:21:39.411 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:21:39.411 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:21:39.458 ShadowsocksX-NG[371]: pac proxy set to global
18/4/13 下午8:21:41.175 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:21:41.246 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:21:41.315 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:21:41.315 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:21:41.375 ShadowsocksX-NG[371]: pac proxy set to off
18/4/13 下午8:21:44.511 ShadowsocksX-NG[371]: bind profile 0
18/4/13 下午8:21:54.249 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:21:54.285 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:21:54.302 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:21:54.303 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:21:54.353 ShadowsocksX-NG[371]: pac proxy set to global
18/4/13 下午8:27:11.201 ShadowsocksX-NG[371]: Call SMLoginItemSetEnabled with [1] success
18/4/13 下午8:27:16.245 ShadowsocksX-NG[371]: Stop ss-local succeeded.
18/4/13 下午8:27:16.316 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:27:16.385 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:27:16.457 ShadowsocksX-NG[371]: Start ss-local succeeded.
18/4/13 下午8:27:16.528 ShadowsocksX-NG[371]: Start privoxy succeeded.
18/4/13 下午8:27:16.599 ShadowsocksX-NG[371]: Stop kcptun succeeded.
18/4/13 下午8:27:16.599 ShadowsocksX-NG[371]: run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
18/4/13 下午8:27:16.662 ShadowsocksX-NG[371]: pac proxy set to global
18/4/13 下午8:27:17.359 ShadowsocksX-NG[371]: Start ss-local succeeded.

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by abbottjlu** [comment]
我也遇到同样的问题。下载这里最新的版本。 无法使用。 启动运行看上去都OK。 就是无法代理。 
但是使用老旧的shadowsocksX就一切正常。

**Comment by yangfeicheung** [comment]
Hi, you guys can try the latest version of ShadowsocksX, the latest version is here:

[Latest SSX](https://github.com/yangfeicheung/Shadowsocks-Xl)

it sets up things automatically, if you have any issue, you can reach us via email.

**Comment by abbottjlu** [comment]
@yangfeicheung This link does not work. https://github.com/yangfeicheung/Shadowsocks-Xl. But this site is good, https://www.sednax.com/.

**Comment by yangfeicheung** [comment]
@abbottjlu  sorry, my bad, I've updated the link
