### ISSUE TITLE
当我把用户目录挂载到另一个分区上时，无法正常运作

### ISSUE THREAD

**Issue by FingersKey** [shadowsocks/ShadowsocksX-NG#791]
Shadowsocksx-NG version: 1.7.1 

macOS 10.13.4 

日志如下：
Apr 14 22:34:21 dengliaquansMBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): Caller specified a plist with bad ownership/permissions: path = /Volumes/OSExtends/Users/yuequan/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.http.plist, caller = launchctl.757
Apr 14 22:34:22 dengliaquansMBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): Caller specified a plist with bad ownership/permissions: path = /Volumes/OSExtends/Users/yuequan/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist, caller = launchctl.766
Apr 14 22:34:22 dengliaquansMBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): Caller specified a plist with bad ownership/permissions: path = /Volumes/OSExtends/Users/yuequan/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.http.plist, caller = launchctl.770
Apr 14 22:36:01 dengliaquansMBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100008.Aqua): Caller specified a plist with bad ownership/permissions: path = /Volumes/OSExtends/Users/yuequan/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.http.plist, caller = launchctl.788

**Comment by qiuyuzhou** [comment]
目录权限问题
