### ISSUE TITLE
Cannot scan qrcode to read ss address

### ISSUE THREAD

**Issue by yunogi** [shadowsocks/ShadowsocksX-NG#792]
**System and Shadowsocksx-NG version:**

- macOS 10.13.4
- Shadowsocksx-NG 1.7.1

**Expected behavior:**
Read server preference same as manually input

**Actual behavior:**
Notification with invalid qrcode

**Steps to reproduce:**
option 1. generate qrcode with ss address like "ss://Y2hhY2hhMjA6ZG91Yi5pby9zc3poZngvKmRvdWIud3Mvc3N6aGZ4Lyo1OTA5QDY0LjEzNy4yNDYuNjE6NTkwOQ"

or
option 2. just open the address with X-NG

**How often does this happen?**
Always

**Comment by yangfeicheung** [comment]
The address might be invalid, you can check this version to see if this works:
[reinstall](https://www.sednax.com/faq-0.php)

**Comment by qiuyuzhou** [comment]
Won't fix.

The NG implement has some tiny difference with other app when encoding/decoding legacy url format. Don't use symbol in password or use new `SIP002` format  qrcode.
