### ISSUE TITLE
访问失败

### ISSUE THREAD

**Issue by xixi9527** [shadowsocks/ShadowsocksX-NG#794]
之前的还可以翻墙,现在就不行了

**Comment by yangfeicheung** [comment]
Try this version:
[ssx](https://github.com/yangfeicheung/Shadowsocks-X)

**Comment by xixi9527** [comment]
我忘记如何配置文件了,  之前的完整教程是在哪个地方去了,是不是那些服务器出问题了?

**Comment by yangfeicheung** [comment]
@xixi9527 
You mean you don't know how to use it, or how to set up servers?

**Comment by xixi9527** [comment]
我用的是 ShadowsocksX-NG 1.5.1  之前还可以用谷歌 

  上个星期就发现 不能够用了 配置文件 之前都配置好了的

**Comment by yangfeicheung** [comment]
@xixi9527 
Did you try the version I told you?
