### ISSUE TITLE
我刚开源了一款 iOS 下的连接 Shadowsocks 的应用，可以隐藏 VPN 图标，支持 PAC，放在这里给大家验验货

### ISSUE THREAD

**Issue by sheng** [shadowsocks/ShadowsocksX-NG#796]
项目地址：[sheng/ladder-ios](https://github.com/sheng/ladder-ios)

这款应用的开发主要是为了实现我自己提出来的一个理念：[沉浸式无墙体验](https://aofei.org/posts/2018-04-05-immersive-wallless-experience)。

有条件的（主要是需要一个苹果开发者的身份）可以考虑一下自己编译和安装，这样可以避免掉那些 App Store 上的比如 ShadowRocket 之类的应用可能存在“后门”的问题，毕竟这种能接管系统所有网络请求的应用还是开源出来比较好，也算是让大家放个心吧。

另外有心人也可以 Fork 它用来作为一个模子，然后开发出别的更方便大家使用的应用，毕竟这款应用是按照我自己的喜好来开发的，比如我不喜欢很多台服务器切换着用，因为我有一台很快的只有我一个人在用的服务器，所以这款应用就不支持多节点切换的功能。

不知道发在这里违不违反 ShadowsocksX-NG 的条例，如果违反了麻烦告知一声，我好主动关闭 Issue。

**Comment by zhiqiang21** [comment]
已赞

**Comment by hongdong** [comment]
已fork

**Comment by thincamel** [comment]
编译安装后VPN无法开启...
