### ISSUE TITLE
有没有这么巧？每次Mac版都这样？

### ISSUE THREAD

**Issue by 0ChristianTam0** [shadowsocks/ShadowsocksX-NG#799]
**System and Shadowsocksx-NG 1.7
两次了，windows版用得好好地，每次在mac版输入服务器地址端口密码，使用不到两分钟，立马失效，服务器立马被墙了，我想知道为什么会这么巧？谁能给个解释啊？每次都是，win版稳定使用几个月，一到mac版登陆立马失效！

**Comment by 0ChristianTam0** [comment]
服务器地址绝对没有在其他地方转发过，看着windows，手动在mac上敲的

**Comment by yangfeicheung** [comment]
You guys can try this version here, you can reach me via my email if you have any issues:

[windows version](https://www.sednax.com/faq-10-cn.php)

[mac version](https://www.sednax.com/faq-0-cn.php)

**Comment by qiuyuzhou** [comment]
请用官网下载的版本
