### ISSUE TITLE
safari PAC模式无效，同时chrome会闪断

### ISSUE THREAD

**Issue by jeehou** [shadowsocks/ShadowsocksX-NG#80]
shadowsocks-NG 在最新的macos中 safari PAC模式无效 全局OK 同系统的chrome都ok 但是经常都会出现“您的链接已经更改”，之后又自动跳转。

**Comment by Siceberg** [comment]
我遇到同样的问题

**Comment by interchen** [comment]
我也遇到这个问题了，关注

**Comment by C7C7** [comment]
遇到了同样的问题

**Comment by qinyuhang** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/pull/44 这个已经merge 可以等待打包好的二进制文件发布，或者下载PR来源的，或者自行打包。

**Comment by Siceberg** [comment]
请问什么时候会有新版本发布？谢谢

**Comment by nanacheung** [comment]
同样的问题🙋举手！
之前有两版好像safari可以正常使用Google和twitter但是1.2之后又不行了😭

**Comment by heartinfei** [comment]
我也遇到了 同样的问题！

**Comment by Siceberg** [comment]
[https://github.com/qinyuhang/ShadowsocksX-NG/files/432302/ShadowsocksX-NG.app-Fix.zip](url)

下载上面这个包

**Comment by qinyuhang** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/issues/30

**Comment by luis-allan** [comment]
@Siceberg 您的这个下载连接好像有些问题呢
