### ISSUE TITLE
ssx-ng does not work on my mac, ssx works

### ISSUE THREAD

**Issue by ryanking8215** [shadowsocks/ShadowsocksX-NG#805]
**System and Shadowsocksx-NG version:**

- macOS 10.12.6 (16E59)
- Shadowsocksx-NG 1.7.1

**Expected behavior:**
ssx-ng works

**Actual behavior:**
ssx-ng doesn't work. socks5 is not listenning.

```
tcp6       0      0  ::1.1089               *.*                    LISTEN
tcp4       0      0  127.0.0.1.1089         *.*                    LISTEN
tcp4       0      0  127.0.0.1.1087         *.*                    LISTEN
```

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**
always
(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

No data generatered in ss-local.log. I confirmed the Verbose Mode is enabled.

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

```
默认	20:55:14.700362 +0800	ShadowsocksX-NG	TIC TLS Trust Result [1:0x6080001930b0]: 0
默认	20:55:14.791147 +0800	ShadowsocksX-NG	TIC TLS Event [1:0x6080001930b0]: 20, Pending(0)
默认	20:55:14.791779 +0800	ShadowsocksX-NG	TIC TCP Conn Event [1:0x6080001930b0]: 8 Err(0)
默认	20:55:14.791817 +0800	ShadowsocksX-NG	TIC TLS Handshake Complete [1:0x6080001930b0]
默认	20:55:49.641327 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [1] success
默认	20:55:58.572892 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	20:55:58.630037 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	20:55:58.697294 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	20:55:58.764759 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	20:55:58.832102 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	20:55:58.898400 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
默认	20:55:58.899226 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	20:55:58.909088 +0800	ShadowsocksX-NG	/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper: unrecognized option `-x'
默认	20:56:14.794843 +0800	ShadowsocksX-NG	TIC TCP Conn Cancel [1:0x6080001930b0]

```

**Crash Log**
No crash log.

It seems not the OTA problem. I didn't enable OTA which is departed. ss-local is successful.

**Comment by ryanking8215** [comment]
Issue solved.

```
ShadowsocksX-NG	/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper: unrecognized option `-x'
```
I don't know why `proxy_conf_helper` here is different from the file inside of ShadowsocksX-NG.

I just copy the file to the /Library/Application Support/ShadowsocksX-NG/
The problem is solved.

**Comment by alfiewm** [comment]
Thanks, saved my day!  I just removed the `/Library/Application Support/ShadowsocksX-NG/` folder and reinstalled ss-ng, also works.
