### ISSUE TITLE
订阅功能能否添加保留备注功能

### ISSUE THREAD

**Issue by flyingwhitewhale** [shadowsocks/ShadowsocksX-NG#806]
刚试了下，新版本个性化排序后再更新订阅，已经可以保留个性化排序。赞

Quantumult订阅有个很好的功能，对于更新后参数网址未改变的节点，可以设定keep local server name when update。
希望能添加上述功能，这样对于习惯于个性化节点备注的机场用户来说，就完美了。
再次感谢大佬的幕后辛苦工作！

**Comment by qiuyuzhou** [comment]
你使用的是服务商开发的衍生版本。
这里的项目从未实现订阅功能。
