### ISSUE TITLE
shadowsocks-ng 内置kcptun 设置后没有效果

### ISSUE THREAD

**Issue by snailedMan** [shadowsocks/ShadowsocksX-NG#811]
Mac OS 10.13.4    shadowsocks-ng 1.7.1
为什么我设置了内置的kcptun 加速没有任何效果，反而感觉更慢了。这个东西该如何设置啊？有没有成功的告知一下

**Comment by qiuyuzhou** [comment]
kcptun 的问题请到kcptun的项目询问，或google解决。
