### ISSUE TITLE
用户自定义规则和gfwlist冲突

### ISSUE THREAD

**Issue by kongwu-** [shadowsocks/ShadowsocksX-NG#814]
gfwlist内有@@||qq.com的白名单，但是我需要qq.com也走代理，就没办法配置了。希望作者可以优化一下，自定义规则的权重>gfwlist

**Comment by zepinglee** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/issues/335#issuecomment-326466234 :
> According to the ABP Filter implementation, whitelists always have higher priority than blacklists. It has nothing to do with the order of rules.
GFW List rules and User Rules are combined into a single ABP Filter, so as long as GFW List whitelists fonts.googleapis.com, it will ignore other blacklist about that url and always bypasses the proxy.

**Comment by chiseller** [comment]
@kongwu- 我测试加入qq.com好像也是无效的，后来是怎么解决的？

**Comment by kongwu-** [comment]
> @kongwu- 我测试加入qq.com好像也是无效的，后来是怎么解决的？
复制一份gfwlist，自己修改，然后push到github....最后引用自己修改的版本
https://github.com/kongwu-/gfwlist

**Comment by chiseller** [comment]
@kongwu- 谢谢  我去试试
