### ISSUE TITLE
another usefull client shadowsocks-iOS

### ISSUE THREAD

**Issue by LZY-fangqian** [shadowsocks/ShadowsocksX-NG#817]
the client "ShadowsocksX-NG" is useless on my mac
and I used another instead 
https://github.com/shadowsocks/shadowsocks-iOS/releases

**Comment by qiuyuzhou** [comment]
Take a look the [README](https://github.com/shadowsocks/ShadowsocksX-NG/blob/develop/README.md) of shadowsocks-ng.
