### ISSUE TITLE
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/c-ares/lib/libcares.2.dylib

### ISSUE THREAD

**Issue by debugly** [shadowsocks/ShadowsocksX-NG#818]
when I run the project encounter this problem，why ?

dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/c-ares/lib/libcares.2.dylib   Referenced from: /Users/xuqianlong/Library/Developer/Xcode/DerivedData/ShadowsocksX-NG-gcrhgimfsbihsweuqxyokzbqgzty/Build/Products/Debug/ShadowsocksX-NG.app/Contents/MacOS/ShadowsocksX-NG   Reason: image not found

**Comment by nemo316** [comment]
me too

**Comment by oliverhu** [comment]
+1

**Comment by oliverhu** [comment]
Found that you need to install latest c-ares `brew install c-ares`

**Comment by debugly** [comment]
Thanks， @oliverhu ！

**Comment by Withpassionalltime** [comment]
it also shows this crash when i "brew install c-ares",  what happened?
