### ISSUE TITLE
希望加入从gui-config.json导入SS服务器的功能

### ISSUE THREAD

**Issue by chengzhoukun** [shadowsocks/ShadowsocksX-NG#82]
目前在macOS上使用的SS客户端是ss-qt5，它可以导出所有SS服务器到JSON文件，希望SSX-NG能加入一键导入功能。

**Comment by qinyuhang** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/pull/58

Geek Cheng <notifications@github.com>于2016年10月9日 周日10:17写道：
