### ISSUE TITLE
socks5代理成功了， 端口也up了，但就是翻不出去。。。

### ISSUE THREAD

**Issue by eldenchang** [shadowsocks/ShadowsocksX-NG#821]
**System and Shadowsocksx-NG version:**

- macOS 10.13.4
- Shadowsocksx-NG 1.7.1?

**Expected behavior:**
手机上用wingy可以翻出去

**Actual behavior:**

但mac上就是翻不出去

**Steps to reproduce:**
端口开着：
<img width="821" alt="screen shot 2018-05-22 at 5 41 45 pm" src="https://user-images.githubusercontent.com/9343055/40354892-922926e4-5de7-11e8-89cd-b826dbf0de5c.png">
socks5也代理成功
<img width="480" alt="screen shot 2018-05-22 at 5 38 21 pm" src="https://user-images.githubusercontent.com/9343055/40354978-d58d720a-5de7-11e8-825a-fa5a57514467.png">
ShadowsocksX 显示连接也成功了
<img width="1022" alt="screen shot 2018-05-22 at 5 46 00 pm" src="https://user-images.githubusercontent.com/9343055/40355090-1b77eeee-5de8-11e8-9f1c-4657d3a1885a.png">
8388口也是通的啊
<img width="555" alt="screen shot 2018-05-23 at 12 10 58 am" src="https://user-images.githubusercontent.com/9343055/40375432-243a127e-5e1e-11e8-9aee-909c8bce54d0.png">

但是本地的ss-local却好像一直在用随机的端口数
<img width="1224" alt="screen shot 2018-05-22 at 3 43 41 pm" src="https://user-images.githubusercontent.com/9343055/40355146-3dc70cb4-5de8-11e8-89da-9f78aa8f9d60.png">
为什么。。。。？
补一条，lsof的时候显示很多不知道为什么会出来这些其他端口的信息。不知道有没有关系。
<img width="1073" alt="screen shot 2018-05-22 at 9 14 20 pm" src="https://user-images.githubusercontent.com/9343055/40364621-65266882-5e05-11e8-8e3d-28f06e266562.png">

**How often does this happen?**

隔了一年没有用ss。不过现在用的是一台新电脑， ss是新装的，装上之后还没有chen成功翻出去过。

**ss-local.log**
[ss-local.log](https://github.com/shadowsocks/ShadowsocksX-NG/files/2026057/ss-local.log)
**Application log**

> default	20:19:18.342561 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [922] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [936] (3,0)
> default	20:19:18.361126 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [922] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [936] (3,0)
> default	20:19:18.363681 +0800	ShadowsocksX-NG	pac proxy set to global
> default	20:20:00.011958 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
> default	20:20:00.081516 +0800	ShadowsocksX-NG	Start privoxy succeeded.
> default	20:20:00.134126 +0800	ShadowsocksX-NG	Stop kcptun succeeded.
> default	20:20:00.134894 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
> default	20:20:00.256912 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [960] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [959] (3,0)
> default	20:20:00.279790 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [960] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [959] (3,0)
> default	20:20:00.301748 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [960] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [959] (3,0)
> default	20:20:00.321546 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [960] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [959] (3,0)
> default	20:20:00.324316 +0800	ShadowsocksX-NG	pac proxy set to off
> 
> 

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by l5ee** [comment]
我也用不起了，怎么搞啊，不太懂，好像我们情况一样

**Comment by txdywy** [comment]
浏览器代理设置成sock5 1080或者http的

mac的safari应该走系统默认代理吧。你的curl已经翻出去了呀

**Comment by eldenchang** [comment]
@l5ee 也是macos么？会不会是系统里的什么新设置？（神伤。。）

**Comment by l5ee** [comment]
@eldenchang  是macOS，我也是这两天突然用不起了。。。 手机可以用，所以应该不是配置的原因，应该是客户端有什么问题。。。

**Comment by eldenchang** [comment]
@txdywy 一直忘了试safari，刚刚试了一下safari居然已经翻出去了，但是以前只要shadowsocks通了，整个系统就翻出去了，但是现在连Google都ping不通。这会是什么问题啊。我也试了chrome上用proxyOmega也不行。而且terminal也没有出去。。。

**Comment by eldenchang** [comment]
@l5ee  那你terminal里可以ping通Google么？

**Comment by l5ee** [comment]
@eldenchang 我Safari也可以居然。。。 terminal怎么ping，我不太会。。。

**Comment by txdywy** [comment]
chrome就是代理没有设置对，多试试，重启一下。mac按里说最新版terminal是走系统代理的，除了系统默认的curl。要想保证去安装proxychain

另外ping不走代理，协议的原因，这个不是vpn，只是提供了本地的socks或http代理



2018-05-23 10:21 GMT+08:00 Qifan Chang <notifications@github.com>:

**Comment by l5ee** [comment]
我一解决，我发现是我有其它VPN，在chrome代理设置中，我停用了，然后就好了

**Comment by eldenchang** [comment]
@txdywy 多谢多谢，我已经解决。居然是chrome上unblock youku这个插件的锅，因为不知道ping不走代理所以一直没有考虑是chrome里的问题。涨姿势了

**Comment by yangfeicheung** [comment]
check this, some of chrome extensions conflicts with app, so you need to stop those extensions first:

https://www.sednax.com/faq-1.php
