### ISSUE TITLE
macos 打开shadowsocks不能访问

### ISSUE THREAD

**Issue by ouyangluwei** [shadowsocks/ShadowsocksX-NG#822]
默认	21:45:46.679294 +0800	signpost_notificationd	Invalid Connection ID 0
错误	21:45:46.679961 +0800	signpost_notificationd	0 is not a valid connection ID.
默认	21:45:46.680015 +0800	signpost_notificationd	Invalid Connection ID 0
错误	21:45:46.681353 +0800	signpost_notificationd	0 is not a valid connection ID.
默认	21:45:46.681771 +0800	signpost_notificationd	Invalid Connection ID 0
错误	21:45:46.750506 +0800	signpost_notificationd	0 is not a valid connection ID.
默认	21:45:46.750564 +0800	signpost_notificationd	Invalid Connection ID 0
错误	21:45:46.750703 +0800	signpost_notificationd	0 is not a valid connection ID.
默认	21:45:46.750754 +0800	signpost_notificationd	Invalid Connection ID 0
错误	21:45:46.778226 +0800	signpost_notificationd	0 is not a valid connection ID.
默认	21:45:46.778286 +0800	signpost_notificationd	Invalid Connection ID 0
错误	21:45:46.778385 +0800	signpost_notificationd	0 is not a valid connection ID.
默认	21:45:46.778424 +0800	signpost_notificationd	Invalid Connection ID 0

**Comment by ouyangluwei** [comment]
错误	21:45:59.172890 +0800	wirelessproxd	Error starting advertising - Unknown error.
默认	21:45:59.172948 +0800	wirelessproxd	Started to advertise for type 12 with error Unknown error.
错误	21:45:59.172997 +0800	wirelessproxd	Advertising failed to start for client identityservicesd type 12 with error: Unknown error.
默认	21:45:59.173107 +0800	wirelessproxd	Started to advertise for type 16 with error Unknown error.
错误	21:45:59.173158 +0800	wirelessproxd	Advertising failed to start for client sharingd type 16 with error: Unknown error.
错误	21:45:59.173270 +0800	identityservicesd	Continuity advertising failed to start of type: 12 with error: Unknown error.
错误	21:45:59.173413 +0800	sharingd	Nearby advertising failed to start of type: 16 with error: Unknown error.
默认	21:45:59.173442 +0800	identityservicesd	calling continuityDidFailToStartAdvertisingOfType:Activity withError:<private>
默认	21:45:59.173676 +0800	sharingd	### Bluetooth advertise failed: Error Domain=CBErrorDomain Code=0 "Unknown error." UserInfo={NSLocalizedDescription=Unknown error.}
错误	21:45:59.173376 +0800	wirelessproxd	Error starting advertising - Unknown error.
错误	21:45:59.174290 +0800	identityservicesd	Continuity advertising failed to start of type: 12 with error: Unknown error.
错误	21:45:59.174586 +0800	sharingd	Nearby advertising failed to start of type: 16 with error: Unknown error.
默认	21:45:59.173905 +0800	wirelessproxd	Started to advertise for type 12 with error Unknown error.

**Comment by wjingkunwang** [comment]
楼主的问题解决没，麻烦问下你的mac那个版本

**Comment by ouyangluwei** [comment]
10.13.4

**Comment by yangfeicheung** [comment]
Bro, try this version:

https://github.com/yangfeicheung/Shadowsocks-X/releases
