### ISSUE TITLE
pac 文件的路径在哪？

### ISSUE THREAD

**Issue by consatan** [shadowsocks/ShadowsocksX-NG#825]
有个 ssh 代理是可以访问公司特定网站的（限定了只允许公司 ip 访问）

想给 pac 文件增加判断，当请求的 url 是 指定特定网址时，使用这个 ssh 代理

编辑好了，测试也 ok 了，但突然发现不知道该把这 pac 文件放哪里才能在下次 shadowsocksx-ng 启动时自动使用这个 pac 文件

**Comment by halftrue** [comment]
Use `user-rule` to support that.
By the way, the PAC file is located in `~/.ShadowsocksX-NG/`.
