### ISSUE TITLE
服务器端升级shadowsocks-libev为最新的3.2.0版本后，MAC版Shadowsocks-NG开启之后不能科学上网

### ISSUE THREAD

**Issue by siriusfinex** [shadowsocks/ShadowsocksX-NG#828]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by vincenthou2016** [comment]
楼上怎么解决的？我的也是最新不能用了。

**Comment by oynix** [comment]
楼上的楼上怎么解决的？我的也不能了 我是Mac

**Comment by zhouxl** [comment]
楼上的楼上怎么解决的？我的也不能了 我是Mac

**Comment by oynix** [comment]
至今未解决，我提了一个新问题 #830 @zhouxl

**Comment by iROCKBUNNY** [comment]
@siriusfinex 请问您是怎么解决的？

**Comment by iROCKBUNNY** [comment]
@qiuyuzhou Hi! This issue is quite critical. Could you please show up to make a quick patch for this?

**Comment by qiuyuzhou** [comment]
The version 3.2 of shadowsocks-libev is too sensitive to block the ip which has failed connection from. 
You could try to add your ip or all ip 0.0.0.0/0 in white list by --acl option on server side.

**Comment by iROCKBUNNY** [comment]
Thanks for you reply! @qiuyuzhou 
`3.1.3` worked. However, after upgrading to `3.2.0`, **shadowsocks-libev** has kept raising those annoying `Invalid argument` errors. My server is using Ubuntu 16.04 LTS with no ufw configured. Could you please show me how to **add my ip or all ip 0.0.0.0/0 in white list by --acl option on server side** specifically?

**Comment by iROCKBUNNY** [comment]
@qiuyuzhou Hi! I've solved the issue. It turns out that **shadowsocks-libev** has upgraded its `config.json` file since `3.2.0`. I will open another issue to address the work-around there.

**Comment by iROCKBUNNY** [comment]
Hi @vincenthou2016 @oynix @zhouxl @qiuyuzhou , the work-around is here #831 , which works perfect for me.

**Comment by zhouyong1d1** [comment]
@iROCKBUNNY 楼主，我这个问题很大，一直无法解决，你可以给我点指导吗，邮箱705195127@qq.com

**Comment by iROCKBUNNY** [comment]
@zhouyong1d1 Sorry, I am not capable of fixing more specific issues other than this.

**Comment by Zhang-Jack** [comment]
after upgraded to ss version 3.2.0, you need to 
remove line 
"local_address":"127.0.0.1",
in /etc/shadowsocks/config.json 
then the ss will work
I don't know why but just this can establish the connection
