### ISSUE TITLE
Mac上的client自动映射到127.0.0.1:1080，是否可以映射到0.0.0.0:1080？

### ISSUE THREAD

**Issue by bannyle** [shadowsocks/ShadowsocksX-NG#83]
这样的话，client启动以后，在本机启动的container就可以借助于本机IP和1080端口访问Google等地址？也许我的问题有很多人问了，只是我目前还不知道在Mac的client上如何做这样的设置？如果你能帮忙回答，非常非常感谢

**Comment by qinyuhang** [comment]
就在高级设置里面就有的呀？

bannyle <notifications@github.com>于2016年10月9日 周日18:13写道：

**Comment by bannyle** [comment]
我直接下载的是GUI版本的，看不到高级设置的选项。。。抱歉这么愚蠢的问题

**Comment by qinyuhang** [comment]
[img](https://cloud.githubusercontent.com/assets/6239057/19219695/3d79927a-8e4d-11e6-95a2-ff8e14e5a6c9.png)

**Comment by bannyle** [comment]
多谢多谢，我从https://portal.shadowsocks.com/clientarea.php这里下载的版本不对，没有这个功能，下载了新的试试，太感谢了

**Comment by 0xdatou** [comment]
@qinyuhang 你好,注意到你img中有检测服务器ping的功能,能告诉下你使用的版本吗?

**Comment by qinyuhang** [comment]
是ssr版本。 http://github.com/shadowsocksr/shadowsocksx-ng <http://github.com/shadowsocksr/shadowsocksx-ng>
