### ISSUE TITLE
Please update your `config.json` file on server side after upgrading shadowsocks-libev to 3.2.0

### ISSUE THREAD

**Issue by iROCKBUNNY** [shadowsocks/ShadowsocksX-NG#831]
> Well, ironically, this is not a **ShadowsocksX-NG** issue, but it is a **critical** one! So I opened this issue to provide a simple work-around on Ubuntu 16.04 LTS.

After upgrading **shadowsocks-libev** to `3.2.0` on your server side, you might as well update your `config.json` file. 

On Ubuntu 16.04 LTS, it is usually located at `/etc/shadowsocks-libev/config.json`. If you have a previous version installed, like `3.1.3`, the `config.json` file would not update, thus causing your **shadowsocks-libev** connection invalid argument errors. 

The work-around is simple, just replace your `config.json` file as folllows:

```
{
    "server": "your.server.i.p",
    "server_port": port_number_like_8388,
    "local_port": 1080,
    "password": "some_password_nobody_knows",
    "timeout": 60,
    "method": "chacha20-ietf-poly1305"
}
```

Good luck!

**Comment by iROCKBUNNY** [comment]
@qiuyuzhou It came with an additional `local` key in the json dict, in the `3.1.3` release.

**Comment by qiuyuzhou** [comment]
Do you mean `local_port` is a required key?

**Comment by iROCKBUNNY** [comment]
It looks like this in the `3.1.3` configuration file.

```
{
    "server": "your.server.i.p",
    "server_port": port_number_like_8388,
    "local": "your.local.i.p",
    "local_port": 1080,
    "password": "some_password_nobody_knows",
    "timeout": 300,
    "method": "chacha20-ietf-poly1305",
    "fast_open": false
}
```

**Comment by qiuyuzhou** [comment]
You mean remove the `local` key-value in config then it is work?

**Comment by zhouxl** [comment]
{
    "server":"0.0.0.0",
    "server_port":443,
    "password":"",
    "method":"chacha20-ietf-poly1305",
    "timeout":1800,
    "udp_timeout":1800,
    "plugin":"obfs-server",
    "plugin_opts":"obfs=tls;fast-open;failover=mzstatic.com:443",
    "fast_open":true,
    "reuse_port":true,
    "nofile":512000,
    "nameserver":"8.8.8.8,8.8.4.4",
    "dscp":"EF",
    "mode":"tcp_and_udp",
    "mtu":1500,
    "mptcp":false,
    "ipv6_first":false,
    "use_syslog":true,
    "no_delay":true,
}

but it not work

**Comment by tkisme** [comment]
now mac `--fast-open` make sense?

**Comment by qiuyuzhou** [comment]
@tkisme As I known, `--fast-open` is dependent on the feature of linux kernel.

**Comment by qiuyuzhou** [comment]
@zhouxl Please try without plugin first.

**Comment by zhouxl** [comment]
@qiuyuzhou I need the plugin, I notice in 1.8.0 will install plugin，when release it.

**Comment by zhouyong1d1** [comment]
@iROCKBUNNY 楼主咋搞

**Comment by iROCKBUNNY** [comment]
@zhouyong1d1 Please follow the instructions described above. Good luck.

**Comment by zhouyong1d1** [comment]
@iROCKBUNNY I will pay your time value.Only solve the problem.My computer is Mac,not Ubuntu
