### ISSUE TITLE
Please add ShadowsocksR support

### ISSUE THREAD

**Issue by 45gfg9** [shadowsocks/ShadowsocksX-NG#833]
I got a ShadowsocksR QRCode from my friend
However ShadowsocksX-NG doesn't distinguish it
It says "Not found valid qrcode of shadowsocks profile."
Really annoying when it supports only ss but not ssr

**Comment by mori-honest** [comment]
Same problem here!
can anybody explain how they are different?

**Comment by qiuyuzhou** [comment]
Won't support ssr.
