### ISSUE TITLE
版本 1.7.1 (1) 服务器订阅功能取消了吗？

### ISSUE THREAD

**Issue by jigme123** [shadowsocks/ShadowsocksX-NG#839]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by yangfeicheung** [comment]
ShadowsocksX-NG本身沒有訂閱功能，如果需要訂閱，可以參考下面這個版本：

https://github.com/yangfeicheung/Shadowsocks-X
