### ISSUE TITLE
系统10.13.5 MenuBar无法显示图标

### ISSUE THREAD

**Issue by Guo-Zhang** [shadowsocks/ShadowsocksX-NG#840]
先升级系统到10.13.5，发现Star VPN无法显示到MenuBar上，下载安装此软件，发现也无法显示到MenuBar上，现在Star VPN已经能显示并且使用。后台进程中有此应用，无任何log文件。

**Comment by zhangzizhao404** [comment]
问一下10.13版本怎么安装这个   1.7.1和1.5.1版本都不能打开
