### ISSUE TITLE
请问有可在MAC OS X 10.09系统上运行的旧版本吗

### ISSUE THREAD

**Issue by westmylove** [shadowsocks/ShadowsocksX-NG#841]
**Describe the bug**
你好，我的电脑系统是10.09版本的，从该网站上下载的shadowsocketsX-NG 提示需要10.10以上版本才能运行。

请问，是否还有旧版本的shadowsockets可以下载吗？

**Comment by yangfeicheung** [comment]
Try this one, it support os 10.9:

https://github.com/yangfeicheung/Shadowsocks-X

**Comment by qiuyuzhou** [comment]
The legacy project https://github.com/shadowsocks/shadowsocks-iOS
