### ISSUE TITLE
为啥我的手机能连接，使用咱们这个客户端就不行呢，求帮助啊。。。

### ISSUE THREAD

**Issue by sunfan666** [shadowsocks/ShadowsocksX-NG#842]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by JohnTian** [comment]
same issue.

**Comment by hunao0221** [comment]
same issue

**Comment by yangfeicheung** [comment]
Try this:
https://github.com/yangfeicheung/Shadowsocks-X

**Comment by YoleYu** [comment]
same issue

**Comment by YAOYYQ** [comment]
same issue

**Comment by johnwu89** [comment]
+1 repro

**Comment by MingrenChen** [comment]
found out why - try turn off unblock youku

**Comment by yangfeicheung** [comment]
@MingrenChen
not just unblock youku, some other extensions might stop it from working as well
https://www.sednax.com/faq-1.php

**Comment by YoleYu** [comment]
@yangfeicheung  your version can't support obfs

**Comment by YoleYu** [comment]
@sunfan666  have you find any solution?
