### ISSUE TITLE
Advertising failed to start for client sharingd type 16 with error: Unknown error.

### ISSUE THREAD

**Issue by wzqjava** [shadowsocks/ShadowsocksX-NG#844]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**
如何恢复默认设置?
我修改了 Advance Preferences 后, 无法连接, 应该是我修改错了, 但是无法回到默认设置状态

**Comment by wzqjava** [comment]
这个是错误日志:default	08:48:28.201454 +0800	CFNetworkAgent	PAC fetch end for <private>. data 0x0 response 0x0 statusCode 0 error 0x7f97d8d01ef0
error	08:48:28.201484 +0800	CFNetworkAgent	PAC Fetch failed with error [NSURLErrorDomain:-1001]
default	08:48:28.201580 +0800	CFNetworkAgent	PAC query complete list=(null), error=<private>
default	08:48:28.201645 +0800	CFNetworkAgent	[1 <private> stream, pid: 287, url: http://69.49.222.138:8090/proxy.pac] cancelled. Events:
default	08:48:28.201722 +0800	QQLive	Received CFNA PAC response
default	08:48:28.201648 +0800	CFNetworkAgent	PAC query complete list=(null), error=<private>
default	08:48:28.201710 +0800	CFNetworkAgent	0.000s [1 A4F2E371-5543-4542-80A4-935FA352A5C1 192.168.1.109:50361-><private> socket-flow] path:start
default	08:48:28.201856 +0800	CFNetworkAgent	0.000s [1 A4F2E371-5543-4542-80A4-935FA352A5C1 192.168.1.109:50361-><private> socket-flow] path:satisfied
default	08:48:28.201899 +0800	CFNetworkAgent	0.000s [1 A4F2E371-5543-4542-80A4-935FA352A5C1 192.168.1.109:50361-><private> socket-flow] flow:start_connect
default	08:48:28.201932 +0800	CFNetworkAgent	60.010s [1] path:cancel
default	08:48:28.202034 +0800	CalendarAgent	Received CFNA PAC response
error	08:48:28.202069 +0800	CFNetworkAgent	Task <5B7740B5-9EE3-49C7-8767-3C40B594F7F7>.<1> HTTP load failed (error code: -999 [1:89])
default	08:48:28.202269 +0800	CFNetworkAgent	TIC TCP Conn Destroyed [1:0x7f97d8e0a450]
default	08:48:28.822563 +0800	WindowServer	CoreAnimation: Context is a zombie!
default	08:48:28.903084 +0800	sharingd	Nearby stop advertising of type: 16
default	08:48:28.903214 +0800	sharingd	Nearby start advertising with data: Advertising request of type 16, priority 1, UseFG 432 (270.00 ms), data <0b00>, connectable 1, options {
} priority 0 mode 432 options (null)
default	08:48:28.903607 +0800	wirelessproxd	Stop advertising for process sharingd (320) of type 16
default	08:48:28.904359 +0800	wirelessproxd	Nothing left to advertise, stopping
default	08:48:28.905407 +0800	wirelessproxd	Start advertising for process sharingd (320) of type 16 with advertising interval 432 (270.00 ms)
default	08:48:28.905531 +0800	wirelessproxd	advertisingRulesOSX - advertisements: (
        {
        kCBAdvAppleMfgTypeKey = 16;
        kCBAdvDataAppleMfgData = <07ff4c00 10020b00>;
        kCBAdvOptionUseFGInterval = 0;
    }
)
default	08:48:28.905641 +0800	wirelessproxd	Requesting to start advertising for clients 16  with (
        {
        kCBAdditionalAppleMfgAdvertisements =         (
        );
        kCBAdvDataAppleMfgData = <07ff4c00 10020b00>;
        kCBAdvOptionUseFGInterval = 0;
        kCBMsgArgIsPrivilegedDaemon = 1;
    }
)
error	08:48:28.907380 +0800	sharingd	Nearby advertising failed to start of type: 16 with error: Unknown error.
error	08:48:28.906951 +0800	wirelessproxd	Error starting advertising - Unknown error.
default	08:48:28.907471 +0800	sharingd	### Bluetooth advertise failed: Error Domain=CBErrorDomain Code=0 "Unknown error." UserInfo={NSLocalizedDescription=Unknown error.}
default	08:48:28.907008 +0800	wirelessproxd	Started to advertise for type 16 with error Unknown error.
error	08:48:28.907072 +0800	wirelessproxd	Advertising failed to start for client sharingd type 16 with error: Unknown error.
error	08:48:29.110224 +0800	Microsoft Word	database corruption at line 68652 of [2b0954060f]
error	08:48:31.755847 +0800	Microsoft Word	database corruption at line 68652 of [2b0954060f]
default	08:48:32.173807 +0800	sharingd	Nearby stop advertising of type: 16
default	08:48:32.174007 +0800	sharingd	Nearby start advertising with data: Advertising request of type 16, priority 1, UseFG 432 (270.00 ms), data <0b00>, connectable 1, options {
} priority 0 mode 432 options (null)
default	08:48:32.174328 +0800	wirelessproxd	Stop advertising for process sharingd (320) of type 16
default	08:48:32.174451 +0800	wirelessproxd	Nothing left to advertise, stopping
default	08:48:32.175414 +0800	wirelessproxd	Start advertising for process sharingd (320) of type 16 with advertising interval 432 (270.00 ms)
default	08:48:32.175544 +0800	wirelessproxd	advertisingRulesOSX - advertisements: (
        {
        kCBAdvAppleMfgTypeKey = 16;
        kCBAdvDataAppleMfgData = <07ff4c00 10020b00>;
        kCBAdvOptionUseFGInterval = 0;
    }
)
default	08:48:32.175650 +0800	wirelessproxd	Requesting to start advertising for clients 16  with (
        {
        kCBAdditionalAppleMfgAdvertisements =         (
        );
        kCBAdvDataAppleMfgData = <07ff4c00 10020b00>;
        kCBAdvOptionUseFGInterval = 0;
        kCBMsgArgIsPrivilegedDaemon = 1;
    }
)
error	08:48:32.177990 +0800	sharingd	Nearby advertising failed to start of type: 16 with error: Unknown error.
error	08:48:32.177557 +0800	wirelessproxd	Error starting advertising - Unknown error.
default	08:48:32.178084 +0800	sharingd	### Bluetooth advertise failed: Error Domain=CBErrorDomain Code=0 "Unknown error." UserInfo={NSLocalizedDescription=Unknown error.}
default	08:48:32.177670 +0800	wirelessproxd	Started to advertise for type 16 with error Unknown error.
error	08:48:32.177712 +0800	wirelessproxd	Advertising failed to start for client sharingd type 16 with error: Unknown error.
default	08:48:33.903438 +0800	sharingd	Nearby stop advertising of type: 16
default	08:48:33.903720 +0800	sharingd	Nearby start advertising with data: Advertising request of type 16, priority 1, UseFG 432 (270.00 ms), data <0b00>, connectable 1, options {
} priority 0 mode 432 options (null)
default	08:48:33.904015 +0800	wirelessproxd	Stop advertising for process sharingd (320) of type 16
default	08:48:33.904302 +0800	wirelessproxd	Nothing left to advertise, stopping
default	08:48:33.905538 +0800	wirelessproxd	Start advertising for process sharingd (320) of type 16 with advertising interval 432 (270.00 ms)
default	08:48:33.905685 +0800	wirelessproxd	advertisingRulesOSX - advertisements: (
        {
        kCBAdvAppleMfgTypeKey = 16;
        kCBAdvDataAppleMfgData = <07ff4c00 10020b00>;
        kCBAdvOptionUseFGInterval = 0;
    }
)
default	08:48:33.905843 +0800	wirelessproxd	Requesting to start advertising for clients 16  with (
        {
        kCBAdditionalAppleMfgAdvertisements =         (
        );
        kCBAdvDataAppleMfgData = <07ff4c00 10020b00>;
        kCBAdvOptionUseFGInterval = 0;
        kCBMsgArgIsPrivilegedDaemon = 1;
    }
)
error	08:48:33.907335 +0800	wirelessproxd	Error starting advertising - Unknown error.
default	08:48:33.907480 +0800	wirelessproxd	Started to advertise for type 16 with error Unknown error.
error	08:48:33.907956 +0800	sharingd	Nearby advertising failed to start of type: 16 with error: Unknown error.
default	08:48:33.908076 +0800	sharingd	### Bluetooth advertise failed: Error Domain=CBErrorDomain Code=0 "Unknown error." UserInfo={NSLocalizedDescription=Unknown error.}
error	08:48:33.907619 +0800	wirelessproxd	Advertising failed to start for client sharingd type 16 with error: Unknown error.
error	08:48:34.110487 +0800	Microsoft Word	database corruption at line 68652 of [2b0954060f]
default	08:48:34.253059 +0800	taskgated	MacOS error: -67062
default	08:48:34.289255 +0800	taskgated	MacOS error: -67062
default	08:48:35.408176 +0800	useractivityd	[PBOARD CONTROLLER] Remove Local Types Fired
default	08:48:35.436279 +0800	useractivityd	DETERMINE: FA9DA559-CCC0-48F1-B01F-D18DABFD2AEC/<private> as the current item-to-advertise.
error	08:48:36.610391 +0800	Microsoft Word	database corruption at line 68652 of [2b0954060f]
default	08:48:36.652964 +0800	com.apple.WebKit.WebContent	Current memory footprint: 30 MB

**Comment by qiuyuzhou** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/wiki/FAQ#how-to-reset-all-preference-to-defaulthow-to-delete-preference-file
