### ISSUE TITLE
Global mode setting http/https proxy will better（OS X）

### ISSUE THREAD

**Issue by gshmu** [shadowsocks/ShadowsocksX-NG#852]
when http proxy enable, global proxy model should setting http/http proxy too

**Comment by qiuyuzhou** [comment]
The embed `privoxy` has bugs. Sometime it return error. So I choose to use sock5 as main proxy, the http proxy in order to been use by command line tools.

**Comment by gshmu** [comment]
eg: Google backup and sync will not work via Global mode.
but add http proxy, it will work well

**Comment by ouyanmao** [comment]
> eg: Google backup and sync will not work via Global mode.
> but add http proxy, it will work well

你好，同学，请教下怎么利用这个自带privoxy设置http转发功能，让Google backup and sync可以使用？谢谢。我是mac HighSeirra 10.13.6
我编辑 ~/Library/Application Support/ShadowsocksX-NG/privoxy.config 
加入以下：
forward-socks5  *.google.com:443        127.0.0.1:1086 .
依旧失败...
请问你是怎么设置的？谢谢指教。

**Comment by gshmu** [comment]
@ouyanmao  MAC OS X设置http/https代理

首先启用http转发功能，也可以使用`polipo`自己转发，然后设置为相应的http(s)代理。
https 代理可以设置http的代理
