### ISSUE TITLE
于 macOS 10.14(Beta) Mojave 中无法使用.

### ISSUE THREAD

**Issue by N0rthzae** [shadowsocks/ShadowsocksX-NG#854]

**Comment by ZTfer** [comment]
10.14 无法使用

**Comment by yangfeicheung** [comment]
try this one:

https://github.com/yangfeicheung/Shadowsocks-X/releases

**Comment by niu-niu** [comment]
同上

**Comment by JiangYongKang** [comment]
同上

**Comment by Yanjianghua** [comment]
同上

**Comment by ZTfer** [comment]
正式版没问题，可以用

**Comment by Yanjianghua** [comment]
> 正式版没问题，可以用

用的什么版本的？

**Comment by ZTfer** [comment]
> > 正式版没问题，可以用
> 
> 用的什么版本的？

Mojave 正式版，10.14；ss：git上的最新版本

**Comment by earthday** [comment]
> 
> 
> > > 正式版没问题，可以用
> > 
> > 
> > 用的什么版本的？
> 
> Mojave 正式版，10.14；ss：git上的最新版本

具体些，哪个版本可以？谢谢。。

**Comment by ZTfer** [comment]
> > > > 正式版没问题，可以用
> > > 
> > > 
> > > 用的什么版本的？
> > 
> > 
> > Mojave 正式版，10.14；ss：git上的最新版本
> 
> 具体些，哪个版本可以？谢谢。。

ShadowsocksX-NG
版本 1.7.1 (1)

**Comment by ZTfer** [comment]
> > > > 正式版没问题，可以用
> > > 
> > > 
> > > 用的什么版本的？
> > 
> > 
> > Mojave 正式版，10.14；ss：git上的最新版本
> 
> 具体些，哪个版本可以？谢谢。。

这个版本也可以
ShadowsocksX-NG
版本 1.8.1
ss-local v3.2.0
kcptun v20170718
simple-obfs v0.0.5
privoxy v3.0.26

**Comment by earthday** [comment]
@zhfish 谢了

我参考了一下，https://github.com/shadowsocks/ShadowsocksX-NG/issues/852
删除了app，删除了用户下的和系统下的这些文件夹，然后重新安装就好了。
```
rm -rf /Users/chenbr/Library/Application Support/ShadowsocksX-NG
sudo rm -rf /Library/Application\ Support/ShadowsocksX-NG
```

**Comment by JiangYongKang** [comment]
同样的服务器配置文件，win 上面可以用，mac 上失效，求大佬指教

**Comment by cloudyan** [comment]
亲测可用 https://github.com/shadowsocks/ShadowsocksX-NG/issues/939#issuecomment-435569249

**Comment by jingchaocheng** [comment]
用 AppCleaner 删除后，重启下电脑好了。

**Comment by sanpi0205** [comment]
换一个IP地址的端口就可以了，1.8.2版本可用，mac os 版本 10.14.3
