### ISSUE TITLE
macOs 10.13.6 后报错

### ISSUE THREAD

**Issue by lincome** [shadowsocks/ShadowsocksX-NG#858]
macOs升级到10.13.6后报错：
failed to read /System/Library/Preferences/Logging/Subsystems/com.apple.launchservices.plist: [1: Operation not permitted]

**Comment by kwdd** [comment]
现在解决了吗

**Comment by kmlixh** [comment]
com.qiuyuzhou.shadowsocksX-NG.kcptun.plist: Could not find specified service

**Comment by yangfeicheung** [comment]
guys, try this one first, it works with 10.13.6
https://github.com/yangfeicheung/Shadowsocks-X/releases

**Comment by miya2017** [comment]
> com.qiuyuzhou.shadowsocksX-NG.kcptun.plist: Could not find specified service


我的配置：Mac OS  10.13,  shadowsocks-ng-r8 1.4.3,
拖到terminal 运行也是报错找不到服务，
你的这个运行问题解决了吗？有什么好的建议？

**Comment by miya2017** [comment]
@kmlixh

**Comment by miya2017** [comment]
/Users/moon/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist: Could not find specified service
