### ISSUE TITLE
https://github.com/shadowsocks/ShadowsocksX-NG/wiki/SIP003-Plugin

### ISSUE THREAD

**Issue by jibon57** [shadowsocks/ShadowsocksX-NG#859]
Spelling mistake:

It should be `simple-obfs` but in that wiki it's `simple-ofbs`

**Comment by qiuyuzhou** [comment]
Thanks，I have fixed the typo.

Jibon L. Costa <notifications@github.com>于2018年7月25日 周三上午1:30写道：

**Comment by jibon57** [comment]
@qiuyuzhou any ETA to publish version 1.8.0? Currently I am using by building your repo
