### ISSUE TITLE
shadowsocks.to客服不解决问题说假话.shadowsocks.la shadowsocks.com

### ISSUE THREAD

**Issue by wentingg** [shadowsocks/ShadowsocksX-NG#866]
看到留言后更新：恩恩 之前正文里没有说清楚，还以为分清区别早就是不言自明的事情了。有人会觉得是没有分清区别才发的。再叙述一下：这个服务商域名取的相当混淆。shadowsocks.org是官网。而.to .la .com一类全都是这家不负责任的服务商。

去年7月购买服务，10月份出现的问题，当时通过网站工单系统反映了，回复中没给出解决办法及恢复期限，后来发现连网站也登不上去了，而且他们是不予邮件联系的，就只能不了了之。今年7月突然收到这家网站的续费提醒，才知道换了地址。我就追究出问题换地址没有告知我，所以要求退款。

当时讨论了一些点，问题就集中在通知没通知我，因为他的说法超过半年不能退款（虽然他们也根本没写明退款时效），但是按那个半年的说法谁造成这个延误就很重要了，客服声称恢复后马上就向所有用户发了邮件，声称不排除邮件在垃圾箱。其实马上就知道他是拍脑袋就编了个理由。

我也没有说破而是又说了一些话要求考虑用户立场，接着客服暴走明说了不管，说你可以选择不续费就好（伪选项.因他也知道根本不用这样说，但还是故意这样说）并又重复关于邮件的谎言并表示将关闭工单。

那么这个关键邮件谎言，我真的不知道他为什么要抓住这个，因为太明显的就是他们账户那里的下拉菜单就直接有发送email的记录····从我去年7月最初注册时的注册欢迎邮件全都有记录，就是没有他所说的通知邮件。

吐槽的同时也希望有可能有shadowsocks.to的其他同事看到，能越过工单系统反映一下最好，因为从那里看来是解决不了了。Eila Juutilainen这个是客服具体的名字吗 可以问下他（已经很多天了，无需在意上面这句）

**Comment by 1900forever** [comment]
你跑这来说这个干啥？这只是个客户端软件……

**Comment by wentingg** [comment]
出门右转，赶紧去 他们最喜欢新来的了

**Comment by skysr** [comment]
你又在这说这个问题干什么呢?事实很明白了不是吗?shadowsocks.org是个软件的官网,不是服务商官网.这点希望你清楚

**Comment by wentingg** [comment]
为什么就是非要想象“别人不清楚”这个事实呢，都已经说了5，6遍了在最明显的位置  为什么必须抓住此个幻想。也罢 问新地址的也有，也不奇怪

**Comment by skysr** [comment]
你又是否清楚你被某个服务商坑了之后,在这发泄~会导致成千上万并没有关系的人而收到你在这发的消息的邮件?这点你这边是否清楚呢?我做个比喻 就好像你在商场某家店买了件假货.而你不去维权,跑到商场的大门拿着个大喇叭在喊"某某商家卖假货,制造噪音扰民" 就好像这种行径.这点你了解吗?

**Comment by skysr** [comment]
就像你所说的,是会有些人在这问那些坑人的商家,但是基本上都是不了解情况的.但是像你这样了解事情原委的.还开了三个issues来说这个事情的,你还是第一个.这点也希望你能明白
