### ISSUE TITLE
iPad可以出去 但是 iPhone出不去

### ISSUE THREAD

**Issue by gaoweihua** [shadowsocks/ShadowsocksX-NG#867]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by gaoweihua** [comment]
谁能帮忙解释下这个问题

**Comment by qiuyuzhou** [comment]
这是macos软件，关ipad、iphone什么事？
