### ISSUE TITLE
在 macOS 10.14 Mojave 中失效

### ISSUE THREAD

**Issue by N0rthzae** [shadowsocks/ShadowsocksX-NG#869]
**Describe the bug**
如题目，在 Mojave 中启用 ShadowsocksX-NG 后所有网络无法访问，Safari 显示无法连接到服务器
**To Reproduce**
Steps to reproduce the behavior
打开 ShadowsocksX-NG 后问题直接可见
**Expected behavior**
是否会更新软件？
**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1] macOS 10.14 Mojave Developer Beta 6
 - Version [e.g. 22] ShadowsocksX-NG 1.7.1(1)

**ss-local.log**
dyld: Library not loaded: @@HOMEBREW_PREFIX@@/opt/mbedtls/lib/libmbedcrypto.0.dylib
  Referenced from: /Users/USERNAME/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
  Reason: image not found

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by loverto** [comment]
Unable to load Info.plist exceptions (eGPUOverrides)

**Comment by xiaoguiSniper** [comment]
macOS 10.14 Mojave 正式版
ShadowsocksX-NG 1.8.1
也无法使用

**Comment by TinkoLiu** [comment]
10.14正式版
严格来说，这个问题并不局限于ssxng
目前我遇到这个bug的地方包括了系统偏好设置-安全-隐私-辅助功能列表完全失效，Steam打不开，Alfred和Synergy无法操控系统，以及其它一系列玄学问题
这个bug实际是由LaunchServices抛出的
我的电脑并没有外置显卡，但是是14年中的带N卡750M，不知道是不是eGPU误识别的问题
我联系了苹果客服，对方尚未有任何方案
覆盖安装数次没有任何好转

**Comment by JayceCao** [comment]
我的 Mac 现在用的是正式版 Mojave，ShadowsocksX-NG 是 1.7.1，能正常使用没有问题。

**Comment by FeLiX-LiM** [comment]
> 我的 Mac 现在用的是正式版 Mojave，ShadowsocksX-NG 是 1.7.1，能正常使用没有问题。

可以用了 需要卸载掉重装 重新输管理密码 可能是升级后权限问题

**Comment by JiangYongKang** [comment]
同样的配置在 win 下能正常使用，mac 10.14 下报错日志：
```
 2018-10-10 09:30:10 INFO: listening at 127.0.0.1:1086
 2018-10-10 09:30:15 INFO: initializing ciphers... none
 2018-10-10 09:30:15 ERROR: invalid cipher name: none
 2018-10-10 09:30:15 ERROR: failed to initialize ciphers
 2018-10-10 09:30:26 INFO: initializing ciphers... none
 2018-10-10 09:30:26 ERROR: invalid cipher name: none
 2018-10-10 09:30:26 ERROR: failed to initialize ciphers
 2018-10-10 09:30:39 INFO: initializing ciphers... none
 2018-10-10 09:30:39 ERROR: invalid cipher name: none
 2018-10-10 09:30:39 ERROR: failed to initialize ciphers
 2018-10-10 09:30:49 INFO: initializing ciphers... none
 2018-10-10 09:30:49 ERROR: invalid cipher name: none
 2018-10-10 09:30:49 ERROR: failed to initialize ciphers
```

**Comment by forrestcn** [comment]
> > 我的 Mac 现在用的是正式版 Mojave，ShadowsocksX-NG 是 1.7.1，能正常使用没有问题。
> 
> 可以用了 需要卸载掉重装 重新输管理密码 可能是升级后权限问题

请问：“卸载重装”是指什么操作？ 我这里，重新下压缩包，将app拷贝到应用程序即可。没有任何步骤提示“输管理密码”呀？

**Comment by FeLiX-LiM** [comment]
@forrestcn 我是使用cleanMyMac卸载删除掉APP 然后重新安装的

**Comment by forrestcn** [comment]
> @forrestcn 我是使用cleanMyMac卸载删除掉APP 然后重新安装的

谢谢！ 问题是，重新安装也不需要输入密码呀？ 你不是下载压缩包，然后直接拷贝app吗？

**Comment by xiaoguiSniper** [comment]
> @forrestcn 我是使用cleanMyMac卸载删除掉APP 然后重新安装的

卸载重装也重新输入了管理密码，配置的SS还是没有办法正常使用

**Comment by forrestcn** [comment]
是的，到目前为止，我还是不能用。我已经用了下面两种方法：
(1)使用1.7.1版本；（2）使用1.8.2版本

**Comment by xiaoguiSniper** [comment]
> 我也是折腾了好久，最后在AppStore上搜了一个ShadowTunnel，可以用

额 尝试了 还是不能用

**Comment by forrestcn** [comment]
报告一下，我现在1.8.2可以用。 原来不能使用，是因为我配置错了（😓）

**Comment by xiaoguiSniper** [comment]
> 报告一下，我现在1.8.2可以用。 原来不能使用，是因为我配置错了（😓）

哎 我的应该没错啊 windows就能正常用 换到mac就不能，我用上面朋友推荐的ShadowTunnel，现在基本能正常实现。

**Comment by JiangYongKang** [comment]
@xiaoguiSniper 我感觉像是这次系统升级导致，因为我使用 ShadowTunnel 也无法访问，而且我也是同样的配置在 win 上能用。

**Comment by N0rthzae** [comment]
用 CleanMyMac 删干净，重新安装，会要求输入密码，然后就好了。

**Comment by xiaoguiSniper** [comment]
> @xiaoguiSniper 我感觉像是这次系统升级导致，因为我使用 ShadowTunnel 也无法访问，而且我也是同样的配置在 win 上能用。

你检查下你的shadowtunnel是不是没有配置好，我现在能用了，前面是软件使用的问题，SS仍然不能正常使用。用cleanMyMac清除干净 重新安装输入密码，也没法解决

**Comment by JiangYongKang** [comment]
@xiaoguiSniper 
> 你检查下你的shadowtunnel是不是没有配置好，我现在能用了，前面是软件使用的问题，SS仍然不能正常使用。用cleanMyMac清除干净 重新安装输入密码，也没法解决
我使用 shadowtunnel 之后出现以下页面
<img width="1406" alt="20181012190216" src="https://user-images.githubusercontent.com/19708877/46934441-5da5a080-d08a-11e8-87e6-edec5580c31e.png">
你有遇到过这个情况吗？

**Comment by xiaoguiSniper** [comment]
@JiangYongKang 抱歉没有，我就是单纯的使用错误。

**Comment by JiangYongKang** [comment]
@xiaoguiSniper 伤心。。。。已经很久没有呼吸到墙外的空气了

**Comment by xiaoguiSniper** [comment]
@icemanjin 感谢，前面确实是我自己使用软件的问题，现在已经能用了。

**Comment by JiangYongKang** [comment]
@icemanjin 好的，我试试

**Comment by dixieboy** [comment]
我的配置跟朋友一模一样，尝试过卸载重新安装，还是不行。。

**Comment by cloudyan** [comment]
亲测可用 https://github.com/shadowsocks/ShadowsocksX-NG/issues/939#issuecomment-435569249
