### ISSUE TITLE
PAC用户自定义规则

### ISSUE THREAD

**Issue by 2007lf** [shadowsocks/ShadowsocksX-NG#870]
**System and Shadowsocksx-NG version:**

- macOS 10.13.5
- Shadowsocksx-NG 1.7.1

PAC用户自定义规则，无论怎么设置，尝试各种办法，都不能生效，求帮助，谢谢！

**Comment by pinylin** [comment]
跟你一样的问题，我去配置文件看了下是这样的
`
"".julialang.org",",
""||julialang.org",",
`
是应为在user-rules 多加了, 和"".去掉就好了
`
.julialang.org
||julialang.org
`

**Comment by 2007lf** [comment]
@pinylin 亲测无用，还是感谢回复

**Comment by qiuyuzhou** [comment]
保存新规则后，需要浏览器开新标签页才会去重新加载pac文件，在原来的标签页里刷新是没有用的。

**Comment by 2007lf** [comment]
@qiuyuzhou 不行的老大，以这个网站为例，你能不能写个确定是能生效的规则，我在测试下https://whatismyipaddress.com

我是这样写的
||whatismyipaddress.com

**Comment by 2007lf** [comment]
@qiuyuzhou 谢谢了

**Comment by 2007lf** [comment]
@qiuyuzhou 我发现网络代理配置里这个http://127.0.0.1:1089/proxy.pac文件是没有加入我添加到pac规则里的，是不是可能是这个问题，该怎么解决？

**Comment by 2007lf** [comment]
@qiuyuzhou 重启了下mac，现在工作了，但是每次修改规则后，需要把SS关闭在打开，才会生效😏
