### ISSUE TITLE
Mac无法翻墙

### ISSUE THREAD

**Issue by Eden-Lin** [shadowsocks/ShadowsocksX-NG#871]
Mac系统版本：10.13.6
shadowsocks版本：1.7.1
之前是老版本0.3左右的可以用，更新到最新版后就不行了。。。
是为什么呢？

**Comment by qiuyuzhou** [comment]
本软件没有0.3版。

**Comment by Eden-Lin** [comment]
@qiuyuzhou 已解决，原来是因为我用的是ssr，应该下载ng-r而不是这个只能用ss的ng。。。谢谢回复！
