### ISSUE TITLE
希望可以增加Android的SS那样的绕过局域网、绕过中国ip这样的选项

### ISSUE THREAD

**Issue by wyfang** [shadowsocks/ShadowsocksX-NG#872]
黑名单太麻烦了，很多软件根本不知道用了什么域名，导致每次使用都要开全局。也顺便问下手动模式是什么意思？

如果可以有android那样的绕过中国ip，那会非常方便对于我而言。
或者有白名单的方法吗？

**Comment by qiuyuzhou** [comment]
macos上因实行方式原因，不方便通过ip过滤。

**Comment by peakio** [comment]
真的加不了吗？
