### ISSUE TITLE
还有这样管理的？

### ISSUE THREAD

**Issue by wentingg** [shadowsocks/ShadowsocksX-NG#874]
![snip20180814_1](https://user-images.githubusercontent.com/42066405/44084891-8e9e4014-9fea-11e8-921c-b987cb5b3124.png)

这和发泄没关系，完全是你们只站在自己的角度的解读。发之前我搜了一些关键字，几个issue都是被说和官网混淆，所以我的正文一上来就澄清和官网无关。但是我并不知道这网站发issue后邮件通知系统的具体情况。所以在我的角度完全与“发泄”或“想引起关注”无关，我只是因为看很多用户也有用这个网站就在三个人比较多的仓库里发了issue。

而且你那句“在商场门口喊商品不好”暴露了这里的本质，这里根本就是一个服务商大本营。当时我根本不知道这一点，我的角度，这里就是一个“用户不少，更多的是自己搭梯子的人”的这么一个地方。 

所以我当时根本不知道这是一个“商场”，也就不存在意图“站在商场门口”做什么的想法。

**Comment by qiuyuzhou** [comment]
吵架的issue当然关掉
