### ISSUE TITLE
can not work on macos 10.13.6

### ISSUE THREAD

**Issue by jasonkylelol** [shadowsocks/ShadowsocksX-NG#877]
**Describe the bug**

just can not connect my ss-server

**Application log**

com.apple.launchservices
LSExceptions shared instance invalidated for timeout.

**Comment by xuxiong** [comment]
I have the same problem

**Comment by wangmeijian** [comment]
I have the same problem

**Comment by hiblacker** [comment]
me too，it looks like  a common problem

**Comment by EverCurse** [comment]
+1

**Comment by Eliza0512** [comment]
+1

**Comment by wangruocong** [comment]
same problem

**Comment by oykhaha** [comment]
+1

**Comment by sillykelvin** [comment]
我也出现过这个错误，服务器明明是好的，最后发现DNS有问题，在设置->网络->DNS里面改成四个8就可以了。
