### ISSUE TITLE
【Bug report】在 Server Preferences 中, Address 不支持含下划线的服务器地址

### ISSUE THREAD

**Issue by foobarjohnny** [shadowsocks/ShadowsocksX-NG#878]
**Describe the bug**
在 Server Preferences 中, 修改 Address 中的服务器地址, 如果含下划线(例如, a_b.com), 则点击OK 无效.

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 10.13.6]
 - Version 1.7.0

**Comment by qiuyuzhou** [comment]
Won't support.
域名中下划线是不规范的，很多系统都不支持。不符合RFC952、RFC1034.
https://blog.delphij.net/2008/02/post-524.html
