### ISSUE TITLE
Mac 10.13.6无法打开问题

### ISSUE THREAD

**Issue by zhangzizhao404** [shadowsocks/ShadowsocksX-NG#879]
如图
![image](https://user-images.githubusercontent.com/30070390/44305656-8291d600-a3af-11e8-813c-2976cf9facf0.png)

**Comment by rlin1995** [comment]
我的两台版本都是10.13.6，其中一台可以，另外一台显示已经打开服务，但是在浏览器里一直上不去。 检查了浏览器，配置是对的。

**Comment by MrChenyao** [comment]
10.13.6确实有问题，还是用1.6.1吧
