### ISSUE TITLE
系统升级到10.12之后，PAC模式不能用了，全局模式没有问题

### ISSUE THREAD

**Issue by luis-allan** [shadowsocks/ShadowsocksX-NG#88]
系统升级到10.12之后，PAC模式不能用了，全局模式没有问题

**Comment by freedom0622** [comment]
+1

**Comment by hellorocky** [comment]
可以吧,我的就是10.12

**Comment by luis-allan** [comment]
@hellorocky sorry， 我用Safari有问题，看到你的回复之后我用Chrome试了一下是没问题的。那就是我的设置问题了，我去排查下Safari的设置问题吧。谢谢

**Comment by qinyuhang** [comment]
https://github.com/shadowsocks/ShadowsocksX-NG/issues/30
