### ISSUE TITLE
Is it possible to use simple-obfs with shadowsocksX-NG?

### ISSUE THREAD

**Issue by ChikoritaPiplup** [shadowsocks/ShadowsocksX-NG#884]
I use `brew install simple-obfs` and then I don't know what to do with it.
Could I modify config file to add simple-obfs to ssX-NG?
If possible, what should I do as well as where is the config file?
I  am too like shadowsocksX-NG, AEAD:GCM is excellent! I don't want to change it.
Please help me, thanks :)

**Comment by hguandl** [comment]
In branch https://github.com/shadowsocks/ShadowsocksX-NG/tree/release/v1.8.0 it has been implemented though the maintainer has not released it yet. You can compile it yourself. Or you can try my fork https://github.com/hguandl/ShadowsocksX-NG/releases.

**Comment by ChikoritaPiplup** [comment]
@hguandl Solved big trouble. Thanks a lot.😁
