### ISSUE TITLE
如何恢复初始设置？

### ISSUE THREAD

**Issue by aisouth** [shadowsocks/ShadowsocksX-NG#889]
**Describe the bug**
在server preference里添加了一个新地址，发现无法使用之后删除了这个地址，但是preference中很多选项没有复原。已经尝试了删除shadowsocks应用和application.support里面对应的文件夹，发现选项仍然没有复原。

**Expected behavior**
希望能有办法恢复初始设置。

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.
log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by qiuyuzhou** [comment]
```
rm -f ~/Library/Preferences/com.qiuyuzhou.ShadowsocksX-NG.plist
```
