### ISSUE TITLE
1.8.0 Remove feature Export/Import configure file ?

### ISSUE THREAD

**Issue by tomhjx** [shadowsocks/ShadowsocksX-NG#896]
`Remove feature Export/Import configure file.`

想了解下为什么要去掉配置的导出导入呢？

**Comment by tomhjx** [comment]
并且想了解有否通过修改配置或者命令行工具来添加服务器呢？

**Comment by tomhjx** [comment]
然后，想再了解下，能否通过修改配置或执行命令行来添加服务器呢？

**Comment by qiuyuzhou** [comment]
以前的导入导出实现是其他人贡献，缺少维护。在前面的版本已经有报告某些情况下会crash。

我猜想其配置文件格式应该是来自windows版本，以前也只实现了部分配置字段（主要是服务器配置部分），配置模板中的全局配置都不支持，有误导用户的可能。维护格式与windows版同步也很麻烦。用起来易错。

如果需要批量导入导出服务器配置，可以使用新实现的`分享窗口`通过复制服务器配置的URL链接的方式进行。
* 分享服务器配置-> 复制所有服务器链接/保存所有服务器链接到文件
* 将链接文本或文件发送到其他机器
* 从剪贴板导入服务器链接

ss服务器url链接的格式是标准化的，用来作为交换格式更合适

> 然后，想再了解下，能否通过修改配置或执行命令行来添加服务器呢？

以后可能merge #895

**Comment by tomhjx** [comment]
Thx~

**Comment by wentmac** [comment]
移除了导入配置文件，真的是太不方便了，gui-config.json文件中有几十个，现在让我一个个手动添加更新，而且扫描二维码还没有了备注名称。累觉不爱了。

**Comment by qiuyuzhou** [comment]
现在sip002标准的二维码是支持备注的

**Comment by Great-Li-Xin** [comment]
@qiuyuzhou 还是希望能够保留配置文件的导入导出作为备用接口。新实现的接口真的比较难用。。。谢谢

**Comment by elanpang** [comment]
url feed功能也没了？实在是变得超级麻烦 = =！

**Comment by elanpang** [comment]
而且扫描二维码添加也没有去重功能

**Comment by magnetron** [comment]
I'm also missing the bulk import function from previous version. Never had any problems with it, so not quite sure why you've chosen to remove it?

**Comment by elanpang** [comment]
导入导出功能真的很棒，如果有问题可以开个issue来解决issue，没必要关掉吧。
