### ISSUE TITLE
能否添加自己的服务器？有个阿里云的服务器，但是需要用户名密码登陆，是否支持添加这样的服务器？

### ISSUE THREAD

**Issue by dongzideas** [shadowsocks/ShadowsocksX-NG#897]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by giveup** [comment]
可以添加自己的服务器，前提是已经部署相关服务在服务器上，和你服务器提供商以及服务器本身是否需要密码没有关系。
