### ISSUE TITLE
1.8.0 没有内置kcptun插件

### ISSUE THREAD

**Issue by xpader** [shadowsocks/ShadowsocksX-NG#899]
我设置了 kcptun 参数无论如何都不成功，后面我发现是 ~/Library/Application\ Support/ShadowsocksX-NG/plugins 中并没有 kcptun 文件，只有 simple-obfs。

我把自己机器上之前的 kcptun 软链过去才成功了。

**Comment by qiuyuzhou** [comment]
Fixed in 6b557c1d6c2fed68077655eb73866d62fab65eac
