### ISSUE TITLE
新客户端结合老服务不可用

### ISSUE THREAD

**Issue by CoderAFI** [shadowsocks/ShadowsocksX-NG#90]
我在一台 VPS 上搭了 Shadowsocks 服务，用 Shadowsocks-iOS 的客户端上代理是没问题的，但是用了 Shadowsokcsx-NG 客户端就不可以，是必须要再配 Privoxy 吗?

**Comment by ykqmain** [comment]
@CoderAFI 

服务器设置中 是否 `启用OTA`

不要 使用OTA，重启再连接

**Comment by klaek** [comment]
Its a small bug. when you scan a qrcode, somethings you get the encrytion is Capital, maybe looks like AES-256-CFB, pls manully change it to aes-256-cfb. little trick n works.
你是不是扫描二维码方式添加的，改一下。
