### ISSUE TITLE
1.8.0 自动代理配置错误，每次启动后都要手动修改

### ISSUE THREAD

**Issue by satywt** [shadowsocks/ShadowsocksX-NG#900]
**System and Shadowsocksx-NG version:**

- macOS 10.13.4 (17E202)
- Shadowsocksx-NG 1.8.0 (1)

**Actual behavior:**

启动后，自动配置协议为「自动代理配置」，URL: http://127.0.0.1:0/proxy.pac，无法正常使用。
<img width="780" alt="2018-09-21 10 07 40" src="https://user-images.githubusercontent.com/6372607/45856675-0876b780-bd88-11e8-81b7-5792c2ee0fc9.png">
需手动将协议修改为 socks5，并且手动输入 127.0.0.1:1080 才可以正常使用。
偏好设置中 socks5 和 http 监听地址均为默认的 127.0.0.1:1080。

**How often does this happen?**

每次启动时

**ss-local.log**

 2018-09-21 10:11:13 INFO: initializing ciphers... rc4-md5
 2018-09-21 10:11:13 INFO: listening at 127.0.0.1:1080
 2018-09-21 10:11:13 INFO: tcp port reuse enabled
 2018-09-21 10:11:13 ERROR: bind: Address already in use
 2018-09-21 10:11:13 ERROR: bind() error

**Application log**

默认	10:11:13.249598 +0800	ShadowsocksX-NG	Start ss-local succeeded.
默认	10:11:13.316819 +0800	ShadowsocksX-NG	Start privoxy succeeded.
默认	10:11:13.317283 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
默认	10:11:13.430213 +0800	ShadowsocksX-NG	pac proxy set to auto

**Comment by qiuyuzhou** [comment]
你的`本地PAC服务监听端口`应该配置错了，你现在的设置好像是0
![2018-09-26 1 05 43](https://user-images.githubusercontent.com/2310221/46058297-039d7380-c18d-11e8-9319-ad58b3136263.png)
