### ISSUE TITLE
1.8.0 如何使用 kcptun ？

### ISSUE THREAD

**Issue by wyfang** [shadowsocks/ShadowsocksX-NG#901]
![qq20180921-113411](https://user-images.githubusercontent.com/17900420/45858926-47116f80-bd92-11e8-8120-351ff5993e54.png)
是像Andorid手机这样吗？可是好像这样的话直接没法用了。

**Comment by qiuyuzhou** [comment]
Duplicated to #899

**Comment by fifman** [comment]
插件选项怎么填啊？我找不到说明

**Comment by wyfang** [comment]
我是参考android系统的直接输入就可以。
