### ISSUE TITLE
优化建议，pac模式的url是否可改成动态配置

### ISSUE THREAD

**Issue by guoxu0514** [shadowsocks/ShadowsocksX-NG#905]
+ (NSString*)getHttpPACUrl {
    NSString * routerPath = @"/proxy.pac";
    
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];

    NSString * address = @"127.0.0.1";
    int port = (short)[defaults integerForKey:@"PacServer.ListenPort"];
    
    return [NSString stringWithFormat:@"%@%@:%d%@",@"http://",address,port,routerPath];
}

优化建议，pac模式的url是否可改成动态配置
不要写死成127.0.0.1呢？ 比如我局域网的手机想共用电脑上的pac地址。

**Comment by qiuyuzhou** [comment]
PR #1056
