### ISSUE TITLE
SIP0003 kcptun update

### ISSUE THREAD

**Issue by alexlee728** [shadowsocks/ShadowsocksX-NG#909]
can not update from https://github.com/xtaci/kcptun
https://github.com/shadowsocks/kcptun version too old

**Comment by iugo** [comment]
I don't need extra configuration when I'm using it. kcptun is just running.

<img width="402" alt="2018-10-08 11 51 45" src="https://user-images.githubusercontent.com/499364/46591902-97a5fe00-caf0-11e8-9e7e-f7a18ed09364.png">

**Comment by qiuyuzhou** [comment]
Already upgrade. Release new version soon.
