### ISSUE TITLE
ver 1.3 not work

### ISSUE THREAD

**Issue by ruchee** [shadowsocks/ShadowsocksX-NG#91]
1.3版本没能正常启动，1.2版本可以

MacOS：10.12

**Comment by Shadowlong** [comment]
ShadowsocksX-NG-1.3.dmg 无法启动(没有报任何错误信息), 之前用的 shadowsocks x 版本.  

Mac 系统也是 10.12

**Comment by golmic** [comment]
1.3版本打开之后没任何反应，无报错信息，之前用的shadowsocks x ，系统版本10.12 (16A323)

**Comment by CoderAFI** [comment]
在装 1.3 之前，先安装一遍 1.2 就可以了。

**Comment by qiuyuzhou** [comment]
#89
