### ISSUE TITLE
Cannot proxy in MacOS 10.14

### ISSUE THREAD

**Issue by a2232189** [shadowsocks/ShadowsocksX-NG#910]
**Describe the bug**
After upgrade to MacOS 10.14, Shadowsocks-NG cannot work properly, not even one line in ss-local.log 

**To Reproduce**
Steps to reproduce the behavior
 

Upgrade to MacOS 10.14
Download ShadowsocksX-NG 1.8.1
Run it

  

1. 

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by a2232189** [comment]
Sep 30 22:10:28 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7391]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:10:28 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7391]): Service exited with abnormal code: 78
Sep 30 22:10:42 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7416]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:10:42 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7416]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:10:42 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7416]): Service exited with abnormal code: 78
Sep 30 22:12:33 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7559]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:12:33 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7559]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:12:33 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7559]): Service exited with abnormal code: 78
Sep 30 22:13:36 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[7302]): Service exited with abnormal code: 15
Sep 30 22:15:44 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7799]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:15:44 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7799]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:15:44 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[7799]): Service exited with abnormal code: 78
Sep 30 22:16:27 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[7668]): Service exited with abnormal code: 15
Sep 30 22:20:59 B000000126607L ShadowsocksX-NG[8058]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 30 22:21:05 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8108]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:21:05 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8108]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:21:05 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8108]): Service exited with abnormal code: 78
Sep 30 22:21:19 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[8102]): Service exited with abnormal code: 15
Sep 30 22:22:01 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8197]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:22:01 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8197]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:22:01 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8197]): Service exited with abnormal code: 78
Sep 30 22:22:05 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8219]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:22:05 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8219]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:22:05 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8219]): Service exited with abnormal code: 78
Sep 30 22:22:08 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8239]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:22:08 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8239]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:22:08 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8239]): Service exited with abnormal code: 78
Sep 30 22:22:30 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[8145]): Service exited with abnormal code: 15
Sep 30 22:22:32 B000000126607L ShadowsocksX-NG[8259]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 30 22:22:38 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8307]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:22:38 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8307]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:22:38 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8307]): Service exited with abnormal code: 78
Sep 30 22:26:02 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[8302]): Service exited with abnormal code: 15
Sep 30 22:26:25 B000000126607L ShadowsocksX-NG[8465]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 30 22:26:30 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8513]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:26:30 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8513]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:26:30 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8513]): Service exited with abnormal code: 78
Sep 30 22:32:44 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[8508]): Service exited with abnormal code: 15
Sep 30 22:33:00 B000000126607L ShadowsocksX-NG[8680]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 30 22:33:06 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8714]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:33:06 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8714]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:33:06 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8714]): Service exited with abnormal code: 78
Sep 30 22:33:15 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8737]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:33:15 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8737]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:33:15 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8737]): Service exited with abnormal code: 78
Sep 30 22:34:25 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[8703]): Service exited with abnormal code: 15
Sep 30 22:34:25 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8805]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:34:25 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8805]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:34:25 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8805]): Service exited with abnormal code: 78
Sep 30 22:34:34 B000000126607L ShadowsocksX-NG[8831]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 30 22:37:20 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[8810]): Service exited with abnormal code: 15
Sep 30 22:37:25 B000000126607L ShadowsocksX-NG[8938]: DEPRECATED USE in libdispatch client: dispatch source activated with no event handler set; set a breakpoint on _dispatch_bug_deprecated to debug
Sep 30 22:37:26 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8976]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:37:26 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8976]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:37:26 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8976]): Service exited with abnormal code: 78
Sep 30 22:37:45 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8992]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:37:45 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8992]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:37:45 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[8992]): Service exited with abnormal code: 78
Sep 30 22:38:04 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[9014]): Could not find and/or execute program specified by service: 2: No such file or directory: /Users/guojiahao/Library/Application Support/ShadowsocksX-NG/ss-local-latest/ss-local
Sep 30 22:38:04 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[9014]): Service setup event to handle failure and will not launch until it fires.
Sep 30 22:38:04 B000000126607L com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.local[9014]): Service exited with abnormal code: 78

**Comment by spartajet** [comment]
1.7.1 is ok

**Comment by a2232189** [comment]
1.8.2 work well
