### ISSUE TITLE
PAC下 Youtube 打开十分缓慢，别的比如Google就很快。全局模式就不会这样的情况

### ISSUE THREAD

**Issue by ChaunceyDong** [shadowsocks/ShadowsocksX-NG#915]
问题如题，设置如下图，
![image](https://user-images.githubusercontent.com/33920326/46344298-4f5f8980-c673-11e8-8d3e-c98c986703a7.png)
![image](https://user-images.githubusercontent.com/33920326/46344303-54243d80-c673-11e8-9d90-89850753966e.png)
![image](https://user-images.githubusercontent.com/33920326/46344307-58505b00-c673-11e8-88c1-125c8abefc1f.png)
![image](https://user-images.githubusercontent.com/33920326/46344317-5e463c00-c673-11e8-87d6-4bd99e8a9371.png)

**Comment by lxhlxhlxh555** [comment]
可以这样试试：打开chrome的调试工具，刷新页面，看看哪些文件加载得慢，将它们的URLs添加到自定义规则中。

默认的gfwlist里设置了黑白名单，但有些白名单的URLs可能又被限制了，导致它们在pac模式下没走代理，影响了页面加载。需要注意：有些URLs在gfwlist的白名单中，自定义规则会被它们覆盖，因此可能要自己修改pac文件~

**Comment by ChaunceyDong** [comment]
> 可以这样试试：打开chrome的调试工具，刷新页面，看看哪些文件加载得慢，将它们的URLs添加到自定义规则中。
> 
> 默认的gfwlist里设置了黑白名单，但有些白名单的URLs可能又被限制了，导致它们在pac模式下没走代理，影响了页面加载。需要注意：有些URLs在gfwlist的白名单中，自定义规则会被它们覆盖，因此可能要自己修改pac文件~

太感谢了！好使～
谢谢你！
