### ISSUE TITLE
升级到macOS Mojave后，ShadowsocksX-NG无法显示图形界面

### ISSUE THREAD

**Issue by yunkai** [shadowsocks/ShadowsocksX-NG#917]
**Describe the bug**
ShadowsocksX-NG在升级到macOS Mojave后无法显示图形界面。

在启动ShadowsocksX-NG后找不到图形界面，状态栏也找不到图标，但使用Activity Monitor可以查看到它在后台运行。

测了最新版的1.8.2，问题依旧。应该是图形界面与macOS Mojave的兼容性问题。

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 10.14
 - Version 1.8.2

**ss-local.log**
yunkai@taobao: Logs$ tail -f ./ss-local.log
 2018-10-04 09:01:22 INFO: initializing ciphers... aes-128-cfb
 2018-10-04 09:01:22 INFO: listening at 127.0.0.1:1086
 2018-10-04 09:01:22 INFO: tcp port reuse enabled

**Application log**
在启动过程，发现了唯一的一个错误提示：
Unable to load Info.plist exceptions (eGPUOverrides)

**Comment by yunkai** [comment]
重启macOS后，又可以了，打扰了。

**Comment by ghost** [comment]
我在 mac 10.14 安装 X-NG 1.9.2 ，无法启动图形界面。重启电脑也是。

**Comment by queenfreeli** [comment]
解决了吗？
