### ISSUE TITLE
kcptun does not pay attention to environment variables

### ISSUE THREAD

**Issue by staticfloat** [shadowsocks/ShadowsocksX-NG#920]
**Describe the bug**
It appears that `kcptun` does not pay attention to the SSIP003 environment variables that would allow it to receive information from `ss-local`.  This may be a bug with `kcptun`, I don't know.

**To Reproduce**
Setup a server configuration with `kcptun` as a plugin.  Here is an example generated `ss-local-config.json`:

```
{
  "plugin" : "plugins\/kcptun",
  "local_address" : "127.0.0.1",
  "server" : "****",
  "password" : "****",
  "local_port" : 1086,
  "server_port" : 29900,
  "plugin_opts" : "--key **** --crypt aes --mode fast --nocomp",
  "method" : "chacha20-ietf-poly1305",
  "timeout" : 60
}
```

With this configuration, looking at `ss-local.log`, when `kcptun` starts up it seems to use `vps:29900` as the remote address to try and connect to.  Looking at the [`kcptun` source code](https://github.com/xtaci/kcptun/blob/22893775cca0f8670c4403cd8626271e4ab74f76/client/main.go#L114) this appears to be the default value.  Looking through the rest of the source code, I realized that `kcptun` doesn't actually try and read in from the `SS_REMOTE_SERVER`/`SS_REMOTE_PORT` environment variables, which is how `ss-local` tries to communicate information to `kcptun`.

**Expected behavior**
I expect `kcptun` to be able to receive the information from `ss-local`.

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: `10.13.6`
 - ShadowsocksX-NG Version: `1.8.1 (1)`

**Possible Fix:**

I have worked around this by replacing `~/Library/Application Support/ShadowsocksX-NG/plugins/kcptun` with the following `bash` wrapper script:

```bash
#!/bin/bash

echo "Starting kcptun through wrapper script..."
KCPTUN="$(dirname "${BASH_SOURCE[0]}")/../kcptun_v20170718/kcptun_client"
"$KCPTUN" -r "${SS_REMOTE_HOST}:${SS_REMOTE_PORT}" -l "${SS_LOCAL_HOST}:${SS_LOCAL_PORT}" ${SS_PLUGIN_OPTIONS}
```

This basically translates the environment variables into command-line arguments, and it works great for me.

**Comment by qiuyuzhou** [comment]
The origin kcptun [https://github.com/xtaci/kcptun](https://github.com/xtaci/kcptun) not support the SIP003 of ss. Try this [https://github.com/shadowsocks/kcptun](https://github.com/shadowsocks/kcptun), but there is not a new release in long time.

**Comment by qiuyuzhou** [comment]
I have upgraded the `kcptun` to latest version by your approach. dc38694ffa2e9ed47445c5f8b6c7e846517b0508
Thanks for the idea.

**Comment by staticfloat** [comment]
Awesome, thanks Qiu!
