### ISSUE TITLE
1.8.2 kcptun 自带的和1.7.1不同，如何打开kcptun

### ISSUE THREAD

**Issue by ysmintor** [shadowsocks/ShadowsocksX-NG#926]
新版本好像没有打开kcptun插件，不知道新版本要怎么设置kcptun，下图中新版中插件和插件选项不知道怎么来打开kcptun

<img width="670" alt="2018-10-10 8 03 18" src="https://user-images.githubusercontent.com/7165048/46705643-ff7c5600-cc62-11e8-88d2-d1f03075a2bf.png">

**Comment by 907064772** [comment]
一样打不开，求问该怎么办

**Comment by ysmintor** [comment]
不知道是新版更新了使用kcptun的办法还是代码没有启用kcptun 的功能，作者能够解答下吗？

**Comment by bingoku** [comment]
同问如何上设置呀？

**Comment by Xbigfat** [comment]
请使用如下参数设置：
key=very fast;crypt=aes;mode=fast2;mtu=1350;sndwnd=512;rcvwnd=512;datashard=10;parityshard=3;dscp=0

**Comment by xiebruce** [comment]
@qiuyuzhou 你好，这个设置kcptun问题，可以说清楚一点吗？好多人都不知道怎么设置，点旁边的问号，说把kcptun插件放在『~/Library/Application Support/ShadowsocksX-NG/plugins』里，我去看了，它本身就有，所以我就不用放了，但是参数的写法，以前的参数是这样的：
![57536876](https://user-images.githubusercontent.com/13575500/46860039-10cf8900-ce42-11e8-850f-8bd6994a620f.png)
根据 @Xbigfat 的说法，我使用了并不会自动启动kcptun，是否需要手动？因为以前的shadowsocks-NG的偏好设置里，是可以配置kcptun的监听地址和端口的：
<img width="431" alt="xnip2018-10-12_18-36-43" src="https://user-images.githubusercontent.com/13575500/46865030-a7a24280-ce4e-11e8-9dcd-3a195b3ff589.png">
而现在却没有地方配置监听IP和端口，所以不知道怎么启动，希望在README里面说明一下，谢谢！

**Comment by Xbigfat** [comment]
作者可能比较忙，我再次回复一下帮助各位。
1.遵从 SIP003 插件化协议，该协议写明了 option 的格式如下：
`key=value;key=value;`
2.新版本和旧版本不兼容（我认为不兼容）
3.只需填写 `kcptun` 即可，在 macOS 本地的 log 中可以看到当前使用的参数。
4.端口填写 服务器端 kcptun 配置端口。
5.无需设置 kcp 本地监听

![image](https://user-images.githubusercontent.com/31509466/46867179-a7a64080-ce56-11e8-8f2d-10ba867e0b5f.png)

![image](https://user-images.githubusercontent.com/31509466/46867200-bf7dc480-ce56-11e8-8224-d395d6bba678.png)

**Comment by xiebruce** [comment]
@Xbigfat 谢谢，已经可以了，不过不知道为什么我的开了又关（我这个是kcp服务器端log），一会还broken，是什么参数设置的不对？我是洛杉矶的服务器
<img width="415" alt="xnip2018-10-12_23-45-55" src="https://user-images.githubusercontent.com/13575500/46879665-31670580-ce79-11e8-9f60-dad9ebcb8f80.png">

**Comment by ZevveZ** [comment]
@xiebruce 我也出现同样的问题，在macos本地的日志中发现没有@Xbigfat日志中关于kcptun的日志，怀疑kcptun没有启动

**Comment by Bryant-Yang** [comment]
反复折腾了一把，读了macos客户端和kcp改动客户端go的源码，主要就是插件参数语法而已，不需要远程地址和本地地址，只需要key, crypt, mode这三个参数。已经设置成功。

**Comment by songguohfut** [comment]
> 作者可能比较忙，我再次回复一下帮助各位。
> 1.遵从 SIP003 插件化协议，该协议写明了 option 的格式如下：
> `key=value;key=value;`
> 2.新版本和旧版本不兼容（我认为不兼容）
> 3.只需填写 `kcptun` 即可，在 macOS 本地的 log 中可以看到当前使用的参数。
> 4.端口填写 服务器端 kcptun 配置端口。
> 5.无需设置 kcp 本地监听
> 
> ![image](https://user-images.githubusercontent.com/31509466/46867179-a7a64080-ce56-11e8-8f2d-10ba867e0b5f.png)
> 
> ![image](https://user-images.githubusercontent.com/31509466/46867200-bf7dc480-ce56-11e8-8224-d395d6bba678.png)

**感谢细心指导，验证可行。**

1.   IP、加密方法、密码为ssr服务端配置的信息
2.  端口为kcptun服务端配置的信息
3.  插件即 kcptun，插件选项为kcptun服务端配置，如果用一键脚本配置的服务端，最终会有提示
4.  配置后需要关注`plugins/kcptun`进程是否启动

**Comment by ZevveZ** [comment]
划重点，之前将密码配置为kcptun的key了

>1.  IP、加密方法、密码为ssr服务端配置的信息

**Comment by JimLee1996** [comment]
遵从SIP003真是捡了芝麻丢了西瓜

**Comment by xiebruce** [comment]
@JimLee1996 这个样做简单哈哈，不过确实很多人不知道怎么配置，我开始也不知道，文档也没有写

**Comment by rogershieh** [comment]
你们怎么解决的？透过kcp没法上网
SSX-NG:
```
 2018-12-03 22:01:02 INFO: plugin "plugins/kcptun" enabled
 2018-12-03 22:01:02 INFO: initializing ciphers... xchacha20-ietf-poly1305
 2018-12-03 22:01:02 INFO: listening at 127.0.0.1:1086
 2018-12-03 22:01:02 INFO: tcp port reuse enabled
 2018-12-03 22:01:02 INFO: udprelay enabled
 2018-12-03 22:01:02 INFO: udp port reuse enabled
test2018/12/03 22:01:03 version: 20170718
2018/12/03 22:01:03 listening on: 127.0.0.1:63294
2018/12/03 22:01:03 encryption: aes
2018/12/03 22:01:03 nodelay parameters: 1 20 2 1
2018/12/03 22:01:03 remote address: XXXXXXXXXXXXXXXXXX
2018/12/03 22:01:03 sndwnd: 128 rcvwnd: 512
2018/12/03 22:01:03 compression: true
2018/12/03 22:01:03 mtu: 1350
2018/12/03 22:01:03 datashard: 10 parityshard: 3
2018/12/03 22:01:03 acknodelay: false
2018/12/03 22:01:03 dscp: 0
2018/12/03 22:01:03 sockbuf: 4194304
2018/12/03 22:01:03 keepalive: 10
2018/12/03 22:01:03 conn: 1
2018/12/03 22:01:03 autoexpire: 60
2018/12/03 22:01:03 scavengettl: 600
2018/12/03 22:01:03 snmplog: 
2018/12/03 22:01:03 snmpperiod: 60
2018/12/03 22:01:03 connection: XXXXXXXXXXXXXXXXXX
2018/12/03 22:01:05 stream opened
2018/12/03 22:01:06 stream opened
2018/12/03 22:01:07 stream closed
2018/12/03 22:01:08 stream opened
2018/12/03 22:01:09 stream opened
2018/12/03 22:01:27 stream opened
2018/12/03 22:01:41 stream closed
2018/12/03 22:01:41 stream opened
2018/12/03 22:01:42 stream closed
2018/12/03 22:01:42 stream opened
```
Server:
```
2018/12/03 14:00:43 version: 20181114
2018/12/03 14:00:43 initiating key derivation
2018/12/03 14:00:43 listening on: [::]:XXXX
2018/12/03 14:00:43 target: XXXXXXXXXXXXXXXXXX
2018/12/03 14:00:43 encryption: aes
2018/12/03 14:00:43 nodelay parameters: 1 20 2 1
2018/12/03 14:00:43 sndwnd: 1024 rcvwnd: 1024
2018/12/03 14:00:43 compression: true
2018/12/03 14:00:43 mtu: 1350
2018/12/03 14:00:43 datashard: 10 parityshard: 3
2018/12/03 14:00:43 acknodelay: false
2018/12/03 14:00:43 dscp: 0
2018/12/03 14:00:43 sockbuf: 4194304
2018/12/03 14:00:43 keepalive: 10
2018/12/03 14:00:43 snmplog: 
2018/12/03 14:00:43 snmpperiod: 60
2018/12/03 14:00:43 pprof: false
2018/12/03 14:00:43 quiet: false
2018/12/03 14:01:08 remote address: XXXXXXXXXXXXXXXXXX
2018/12/03 14:01:13 stream opened
2018/12/03 14:01:13 stream opened
2018/12/03 14:01:13 stream closed
2018/12/03 14:01:13 stream opened
2018/12/03 14:01:13 stream opened
2018/12/03 14:01:31 stream opened
2018/12/03 14:01:42 stream closed
2018/12/03 14:01:42 stream opened
```

**Comment by Tang-RoseChild** [comment]
开源的啊，兄弟们，有问题的话，wiki上开个说明页啊

**Comment by Tang-RoseChild** [comment]
然后就可以吹牛逼，说给上万star的项目提过issue，美滋滋

**Comment by JimLee1996** [comment]
> 然后就可以吹牛逼，说给上万star的项目提过issue，美滋滋

然后就可以申清华特奖和约threesome了hhhh

**Comment by sh4wn** [comment]
对kcptun的server端版本有要求吗

**Comment by Kevin-Winehouse** [comment]
我觉得对于服务器端的kcptun版本没有要求吧？
今天刚把服务器上的kcptun更新了一下，v20181226的，现在按照SIP003的格式输入参数，就直接连上了。非常快，这才是开了kcptun的速度

**Comment by cocobear** [comment]
确实应该把这个`issue`作为一页`wiki`

**Comment by zhanhb** [comment]
密码中如果有\或者; 需要转义成 \\ 或 \; 感觉这个需要强调一下

**Comment by jwang0512** [comment]
这是开倒车，这种配置方式明显很不人性化

**Comment by jearton** [comment]
在哪里看macos的本地日志啊？插件选项并没有起作用

**Comment by zhanhb** [comment]
![image](https://user-images.githubusercontent.com/6323014/52564248-a4d84e00-2e3e-11e9-8375-5ede199a87aa.png)
![image](https://user-images.githubusercontent.com/6323014/52564267-b3266a00-2e3e-11e9-80d3-d9ff19dc6dc8.png)

**Comment by alanban** [comment]
> > 作者可能比较忙，我再次回复一下帮助各位。
> > 1.遵从 SIP003 插件化协议，该协议写明了 option 的格式如下：
> > `key=value;key=value;`
> > 2.新版本和旧版本不兼容（我认为不兼容）
> > 3.只需填写 `kcptun` 即可，在 macOS 本地的 log 中可以看到当前使用的参数。
> > 4.端口填写 服务器端 kcptun 配置端口。
> > 5.无需设置 kcp 本地监听
> > ![image](https://user-images.githubusercontent.com/31509466/46867179-a7a64080-ce56-11e8-8f2d-10ba867e0b5f.png)
> > ![image](https://user-images.githubusercontent.com/31509466/46867200-bf7dc480-ce56-11e8-8224-d395d6bba678.png)
> 
> **感谢细心指导，验证可行。**
> 
> 1. IP、加密方法、密码为ssr服务端配置的信息
> 2. 端口为kcptun服务端配置的信息
> 3. 插件即 kcptun，插件选项为kcptun服务端配置，如果用一键脚本配置的服务端，最终会有提示
> 4. 配置后需要关注`plugins/kcptun`进程是否启动

谢谢  应该写个wiki呀

**Comment by Kyoloro** [comment]
如果是vps，暴露端口注意区分 udp 和 tcp

kcptun 是udp

**Comment by samstar** [comment]
> 如果是vps，暴露端口注意区分 udp 和 tcp
> 
> kcptun 是udp

正解，阿里云香港就是没有注意这里，找了很久才发现问题！

**Comment by forestfsl** [comment]
搬瓦工的vps怎么暴露UDP接口呀，我的已开启kcptun就上不了google

**Comment by waning007** [comment]
> @Xbigfat 谢谢，已经可以了，不过不知道为什么我的开了又关（我这个是kcp服务器端log），一会还broken，是什么参数设置的不对？我是洛杉矶的服务器
> <img alt="xnip2018-10-12_23-45-55" width="415" src="https://user-images.githubusercontent.com/13575500/46879665-31670580-ce79-11e8-9f60-dad9ebcb8f80.png">

我这边也这样，一会开一会关 不知道怎么解决？

**Comment by fwilyair** [comment]
求问一下大佬 为什么我的服务器好好的 在windows上用kcptun客户端都能正常加速 但是mac上就经常用不了呢 不用kcptun就正常
