### ISSUE TITLE
编译 各种崩溃

### ISSUE THREAD

**Issue by juvham** [shadowsocks/ShadowsocksX-NG#93]
编译 各种崩溃

**Comment by qinyuhang** [comment]
是这个原因造成的嘛？ https://github.com/qinyuhang/ShadowsocksX-NG/issues/17

**Comment by juvham** [comment]
不是 崩溃代码在  appdelegate  388 行 
```
 var serverMenuText = "Servers".localized
        for v in defaults.array(forKey: "ServerProfiles")! {   // <=========
```

貌似是 强制解包的崩溃  ，这一条改完之后 还 有 其他的 崩溃  就没忍心再调下去了
release 1.3 下载下来 也是  无限闪退的

**Comment by qinyuhang** [comment]
这个问题在最近的commit已经修复，请再pull一下，尝试重新编译一下吧。

**Comment by qiuyuzhou** [comment]
#89
