### ISSUE TITLE
Shadowsocksx does not work on maxos

### ISSUE THREAD

**Issue by xbtlin** [shadowsocks/ShadowsocksX-NG#941]
I tried the same config on my iphone and it works! So the problem is definitively on the mac client.
**System and Shadowsocksx-NG version: 1.8.2**

- macOS 10.12.3 (16D30)
- Shadowsocksx-NG 1.8.2

**Expected behavior:**
Work in Global Mode

**Actual behavior:**
<img width="630" alt="safrai" src="https://user-images.githubusercontent.com/6993203/48040868-b8c44200-e1b5-11e8-85fb-6f710d8de9f4.png">
<img width="389" alt="chrome2" src="https://user-images.githubusercontent.com/6993203/48040869-b8c44200-e1b5-11e8-9428-0b3a425bf014.png">
<img width="850" alt="chrome1" src="https://user-images.githubusercontent.com/6993203/48040870-b95cd880-e1b5-11e8-82f9-725a25a4978e.png">

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**
Always
(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)
It seems that the ss-local.log file does not increase from one day ago even I enable Verbose Mode and run the Shadowsocksx-NG。 The history log is as following:
[ss-local.log.zip](https://github.com/shadowsocks/ShadowsocksX-NG/files/2551497/ss-local.log.zip)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here :
`default	11:27:26.968842 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
default	11:27:27.033684 +0800	ShadowsocksX-NG	Stop privoxy succeeded.
default	11:27:27.034092 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	11:27:27.071702 +0800	proxy_conf_helper	subsystem: com.apple.SystemConfiguration, category: SCPreferences, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
default	11:27:27.087409 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38161] (3,0)
default	11:27:27.090593 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38161] (3,0)
default	11:27:27.095540 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38161] (3,0)
default	11:27:27.096633 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38161] (3,0)
default	11:27:27.100623 +0800	ShadowsocksX-NG	pac proxy set to off
default	11:27:37.539914 +0800	lsd	SecTranslocateCreateSecureDirectoryForURL: created /private/var/folders/tk/v9nks16x3gn6jlfl4qm7s4lr0000gn/T/AppTranslocation/100F7629-132B-4C62-B418-C4BB8C9A9FA0/d/ShadowsocksX-NG 2.app
default	11:27:38.196900 +0800	ShadowsocksX-NG	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	11:27:38.457436 +0800	ShadowsocksX-NG	Call SMLoginItemSetEnabled with [0] success
default	11:27:38.602329 +0800	ShadowsocksX-NG	Install ss-local succeeded.
default	11:27:38.667369 +0800	ShadowsocksX-NG	Install kcptun succeeded.
default	11:27:38.796397 +0800	ShadowsocksX-NG	generateSSLocalLauchAgentPlist - File has not been changed.
default	11:27:38.798938 +0800	ShadowsocksX-NG	writeSSLocalConfFile - File has been changed.
default	11:27:38.867335 +0800	ShadowsocksX-NG	Stop ss-local succeeded.
default	11:27:38.936220 +0800	ShadowsocksX-NG	Start privoxy succeeded.
default	11:27:38.936445 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	11:27:38.969770 +0800	proxy_conf_helper	subsystem: com.apple.SystemConfiguration, category: SCPreferences, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
default	11:27:38.972231 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38202] (3,0)
default	11:27:38.974527 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38202] (3,0)
default	11:27:38.978822 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38202] (3,0)
default	11:27:38.979951 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38202] (3,0)
default	11:27:38.982969 +0800	ShadowsocksX-NG	pac proxy set to global
default	11:27:39.932869 +0800	ShadowsocksX-NG	Start ss-local succeeded.
default	11:28:06.051162 +0800	ShadowsocksX-NG	generateSSLocalLauchAgentPlist - File has not been changed.
default	11:28:06.053521 +0800	ShadowsocksX-NG	writeSSLocalConfFile - File has not been changed.
default	11:28:06.121837 +0800	ShadowsocksX-NG	Start ss-local succeeded.
default	11:28:06.190422 +0800	ShadowsocksX-NG	Start privoxy succeeded.
default	11:28:06.195011 +0800	ShadowsocksX-NG	run shadowsocks helper: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper
default	11:28:06.227105 +0800	proxy_conf_helper	subsystem: com.apple.SystemConfiguration, category: SCPreferences, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 2, enable_private_data: 0
default	11:28:06.229302 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38232] (3,0)
default	11:28:06.230937 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38232] (3,0)
default	11:28:06.234033 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38232] (3,0)
default	11:28:06.235038 +0800	authd	Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [38162] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [38232] (3,0)
default	11:28:06.237564 +0800	ShadowsocksX-NG	pac proxy set to auto
`

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by xbtlin** [comment]
I reinstall the Shadowsocks and get the following info from ss-local: 

>  2018-11-06 17:50:53 INFO: listening at 127.0.0.1:1080
>  2018-11-06 17:50:53 INFO: tcp port reuse enabled
>  2018-11-06 17:50:53 ERROR: bind: Address already in use

Then I change the Preferences-> Advanced -> Local Socks Listen Port to 1099 and the problem solved!

**Comment by pesowen** [comment]
Thank you for comment. It is very helpful

**Comment by cloudyan** [comment]
look https://github.com/shadowsocks/ShadowsocksX-NG/issues/939#issuecomment-435569249
