### ISSUE TITLE
shadowsocksX-NG 1.8.2 无法开机自启，且忽略代理设置不生效

### ISSUE THREAD

**Issue by zhengyongtao** [shadowsocks/ShadowsocksX-NG#942]
使用过程中发现了以下两个问题：
1.shadowsocksX-NG 1.8.2在macos mojave下设置了开机启动但是不生效，目前已知的解决方案是先安装1.7版本，再用1.8版本覆盖
2.
![image](https://user-images.githubusercontent.com/23188362/48180021-c536cf00-e35c-11e8-96c1-07e3a824df03.png)
当我在网络接口-忽略这些主机与域的代理设置中，配置想要忽略代理的域名后，并不生效，依旧会根据pac文件来执行代理，无法忽略

**Comment by xyvpn** [comment]
请问，第二个问题解决没？
