### ISSUE TITLE
1.8.2无法上网

### ISSUE THREAD

**Issue by wangduokai** [shadowsocks/ShadowsocksX-NG#945]
我对版本原本是1.7.1 ，昨天升级1.8.2无法上网，回退到1.7.1依然无法上网，请问有什么版本可以解决这个问题？ https://github.com/shadowsocks/ShadowsocksX-NG/issues/531 按照这个操作试过还是不行。

**Comment by wangduokai** [comment]
已经解决，我按照进程里所涉及的所有有关的文件都给删除了。

**Comment by ShikiSuen** [comment]
@wangduokai 請說明您說的進程是哪個進程、要刪掉那些檔案？
