### ISSUE TITLE
ShadowsocksX-NG 版本1.6.1（1）无法用chrome翻墙了

### ISSUE THREAD

**Issue by zongmingwei** [shadowsocks/ShadowsocksX-NG#948]
下午突然就无法用1.6.1（1）版本的客户端翻墙了
浏览器用的是chrome，下载了那个插件
想问下如何解决- -如何排查是什么问题？？？
shadowsocks官网也上不去。。。。。。
小白很急。。。。。。

**Comment by kwame998** [comment]
是不是你系统 升级了

**Comment by zongmingwei** [comment]
> 是不是你系统 升级了

我的系统还是high sierra，我什么都没干就不能科学上网了。。。。。。就想知道到底是什么问题？？难道是dns的问题？？？？？

**Comment by DNrover** [comment]
检查自己的代理地址是否还有效，shadowsocks一系列客户端都不会提供任何可连接的代理节点

**Comment by cloudyan** [comment]
> > 是不是你系统 升级了
> 
> 我的系统还是high sierra，我什么都没干就不能科学上网了。。。。。。就想知道到底是什么问题？？难道是dns的问题？？？？？

使用这个方法 https://github.com/shadowsocks/ShadowsocksX-NG/issues/939#issuecomment-435569249

**Comment by smartlibo** [comment]
我也不行，解决了吗？如何解决的

**Comment by zongmingwei** [comment]
我解决了= =好像是官方把我的账号关了emmm

**Comment by smartlibo** [comment]
怎么操作解决的呢

----------

该邮件从移动设备发送




















--------------原始邮件--------------
发件人："Mune "<notifications@github.com>;
发送时间：2018年12月5日(星期三) 晚上9:35
收件人："shadowsocks/ShadowsocksX-NG" <ShadowsocksX-NG@noreply.github.com>;
抄送："TigerLI-NEWBetter "<tiger.li@newbetter.cn>;"Comment "<comment@noreply.github.com>;
主题：Re: [shadowsocks/ShadowsocksX-NG] ShadowsocksX-NG 版本1.6.1（1）无法用chrome翻墙了 (#948)
-----------------------------------

 
我解决了= =好像是官方把我的账号关了emmm
