### ISSUE TITLE
突然无法使用ShadowsocksX-NG 了

### ISSUE THREAD

**Issue by smartlibo** [shadowsocks/ShadowsocksX-NG#955]
**Describe the bug**
1.6.1(1)版本，以前一直好好的，好像是前天就无法通过这个访问外网了，请问是啥原因？
谷歌浏览器显示说：
www.gmail.com 意外终止了连接。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
ERR_CONNECTION_CLOSED

**Comment by chengjs** [comment]
我直接使用软件扫描二维码设置上翻墙，就是连不上

**Comment by superlbr** [comment]
长。城。升级2.0了。。

**Comment by yanue** [comment]
欢迎使用: https://github.com/yanue/V2rayU 支持ss,支持v2ray(可伪装,防长城检测)

**Comment by smartlibo** [comment]
这个好像没有找到MAC的安装文件吧？请问在哪里下载安装呢？
谢谢
 
 
 
------------------ Original ------------------

**Comment by yanue** [comment]
https://github.com/yanue/V2rayU/releases 下载dmg文件进行安装

> 这个好像没有找到MAC的安装文件吧？请问在哪里下载安装呢？ 谢谢
> […](#)
> ------------------ Original ------------------ From: "yanue"<notifications@github.com>; Date: Thu, Dec 20, 2018 11:21 PM To: "shadowsocks/ShadowsocksX-NG"<ShadowsocksX-NG@noreply.github.com>; Cc: "TigerLI-NEWBetter"<tiger.li@newbetter.cn>; "Author"<author@noreply.github.com>; Subject: Re: [shadowsocks/ShadowsocksX-NG] 突然无法使用ShadowsocksX-NG 了 (#955) 欢迎使用: https://github.com/yanue/V2rayU 支持ss,支持v2ray(可伪装,防长城检测) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

https://github.com/yanue/V2rayU/releases 下载dmg文件进行安装

**Comment by smartlibo** [comment]
非常感谢！


 
 
 
------------------ Original ------------------

**Comment by smartlibo** [comment]
你好，
下载完毕后安装完，然后运行后，想选择“turn V2ray-core on”的时候，显示：v2ray config not found
请问如何解决？谢谢







 
------------------ Original ------------------

**Comment by yanue** [comment]
需要配置as或者v2ray

发自我的 iPhone

在 2018年12月21日，18:42，smartlibo <notifications@github.com<mailto:notifications@github.com>> 写道：

你好，
下载完毕后安装完，然后运行后，想选择“turn V2ray-core on”的时候，显示：v2ray config not found
请问如何解决？谢谢








------------------ Original ------------------

**Comment by plotworld** [comment]
> 你好， 下载完毕后安装完，然后运行后，想选择“turn V2ray-core on”的时候，显示：v2ray config not found 请问如何解决？谢谢
> […](#)
> ------------------ Original ------------------ From: "yanue"<notifications@github.com>; Date: Fri, Dec 21, 2018 05:46 PM To: "shadowsocks/ShadowsocksX-NG"<ShadowsocksX-NG@noreply.github.com>; Cc: "TigerLI-NEWBetter"<tiger.li@newbetter.cn>; "Author"<author@noreply.github.com>; Subject: Re: [shadowsocks/ShadowsocksX-NG] 突然无法使用ShadowsocksX-NG 了 (#955) https://github.com/yanue/V2rayU/releases 下载dmg文件进行安装 这个好像没有找到MAC的安装文件吧？请问在哪里下载安装呢？ 谢谢 … ------------------ Original ------------------ From: "yanue"notifications@github.com; Date: Thu, Dec 20, 2018 11:21 PM To: "shadowsocks/ShadowsocksX-NG"ShadowsocksX-NG@noreply.github.com; Cc: "TigerLI-NEWBetter"tiger.li@newbetter.cn; "Author"author@noreply.github.com; Subject: Re: [shadowsocks/ShadowsocksX-NG] 突然无法使用ShadowsocksX-NG 了 (#955) 欢迎使用: https://github.com/yanue/V2rayU 支持ss,支持v2ray(可伪装,防长城检测) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread. https://github.com/yanue/V2rayU/releases 下载dmg文件进行安装 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

可以用终端brew安装
