### ISSUE TITLE
Chain multiple plugins (kcptun + obfs-local)

### ISSUE THREAD

**Issue by rogershieh** [shadowsocks/ShadowsocksX-NG#957]
**Is your feature request related to a problem? Please describe.**
I currently have a ss-libev server I want to be able to access both via kcp and normally/obfs. I cannot switch simply on the client side currently with SSXNG as only a single plugin can be used at any time and I have to go to the server, disable obfs and enable kcp.

**Describe the solution you'd like**
I was wondering if it's possible to chain plugins together without rewriting a new plugin?
ss-local -> obfs-local -> kcptun-client -> kcp-server -> obfs-server -> ss->server

**Describe alternatives you've considered**
I'm trying to see if I can run a kcptun client separately and have ssxng configured for obfs, but that would be quite a bit less convenient, still need to check if that works at all.

**Additional context**
None

**Comment by jibon57** [comment]
@rogershieh the only way to run separate script for `kcptun`.

**Comment by rogershieh** [comment]
yeah, I now run a separate instance of ss for kcp, gonna close the issue
