### ISSUE TITLE
ShadowsocksX-NG 在搬瓦工的IP不能连接而在vultr的IP可以连接，为什么

### ISSUE THREAD

**Issue by bestaild** [shadowsocks/ShadowsocksX-NG#959]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by littlegrayss** [comment]
为什么我在vultr的IP不可以连接😂

**Comment by linonetwo** [comment]
这是服务器的问题吧
