### ISSUE TITLE
Let us have some fun! (New design of ShadowsocksX-NG)

### ISSUE THREAD

**Issue by NobelLiu** [shadowsocks/ShadowsocksX-NG#964]
![ShadowsocksX-NG new design](https://user-images.githubusercontent.com/10796646/50222985-e4516380-03d4-11e9-80bd-698c85b35d21.png)

The new design was originally post in [Gitter](https://gitter.im/ShadowsocksX-NG/Lobby), and I was very happy to see that @rizwankce stood out and hoped to implement this new design.

![Gitter screenshot](https://user-images.githubusercontent.com/10796646/50223421-229b5280-03d6-11e9-8a3a-9edc226b7fe6.png)

But unfortunately I missed that message. Recently I made some changes and posted it here, let's give tool we <3 ShadowsocksX-NG a new look. 🤟

Feel free to contact me for design spec if you want to achieve it.

**Comment by LipYoung** [comment]
This design is cool, I've ever seen VPN software.
