### ISSUE TITLE
SS does not correctly configure proxy preference on macOS.

### ISSUE THREAD

**Issue by NeapolitanIcecream** [shadowsocks/ShadowsocksX-NG#965]
macOS High Sierra 10.13.6, ShadowsocksX-NG 1.8.2.

When I switch to global proxy, SS doesn't work on browser.
I found the configuration of http proxy is missing. I tried to specify it manually but SS still covered it.

**Comment by NeapolitanIcecream** [comment]
> macOS High Sierra 10.13.6, ShadowsocksX-NG 1.8.2.
> 
> When I switch to global proxy, SS doesn't work on browser.
> I found the configuration of http proxy is missing. I tried to specify it manually but SS still covered it.

Nine days ago I found it not working on Firefox and http proxy in system missing. But today I realize it works fine except Firefox. Temporarily I have no idea what it is going on. Please close this issue.

**Comment by PPPang** [comment]
``
