### ISSUE TITLE
如何更新 kcptun client (嘗試更新後無法訪問)

### ISSUE THREAD

**Issue by xareelee** [shadowsocks/ShadowsocksX-NG#967]
你好，我剛搭建起來：

* Server (CentOS 7 with 4.18 kernel): 
    - shadowsocks-libev (v3.2.3)
    - kcptun-server `20181226` 版本
* Client (MacOS 10.13):
    - ShadowsocksX-NG 1.8.2
    - kcptun (ShadowsocksX-NG 自攜帶版本 v20170718，soft link 到 `~/Library/Application\ Support/ShadowsocksX-NG/kcptun_v20170718/kcptun_client`) 

服務端 shadowsocks 配置：

```
{
  "server":["[::0]","0.0.0.0"],
  "server_port": ${SS_PORT},
  "password": "${SS_PASSWORD}",
  "method": "${SS_METHOD}",
  "mode": "tcp_and_udp",
  "timeout": 600,
  "fast_open": false
}
```

服務端 kcptun 配置：

```
{
  "listen": ":${KCPTUN_PORT}",
  "target": "127.0.0.1:${SS_PORT}",
  "key": "${KCPTUN_PASSWORD}",
  "crypt": "aes-192",
  "mode": "fast3"
}
```

我在 Mac 上的 ShadowsocksX-NG 設置兩種配置 (不贅述，依照服務端設置進行配置)：

- 純 shadowsocks：使用 shadowsocks-libev-server 監聽端口
- shadowsocks + kcptun：使用 kcptun-server 監聽端口，外加 plugin 的配置

上面兩者都能科學上網，但...

## 問題一：使用 kcptun 下載反而變慢

在 [http://fast.com](http://fast.com) 使用 kcptun 時下載反而比較慢、latency 也比較長 (使用另外一個測速的服務也是如此 http://www.speedtest.net)：

 翻牆方式   | download (Mbps) | latency: unloaded (ms)  | latency: loaded (ms) | upload (Mbps)
----|:----:|:----:|:----:|:----:
純 SS | 9.5 | 94 | 154 | 8.7
SS+kcptun | 4.5 | 109 | 3000 | 12

問題：是兩者 speed test 比較方式不恰當，或是配置的問題，還是說大家使用 kcptun 真的反而下載比較慢呢？

## 問題二：嘗試更新 kcptun client，卻導致無法訪問

我嘗試下載跟服務端同一個版本的 kcptun Mac client (`client_darwin_amd64`, 20181226 版本)，並將 `plugins` 下的 kcptun 重新 soft link 到該新版的路徑上，反而導致 Shadowsocks 無法再透過 kcptun 科學上網 (ShadowsocksX-NG 的配置都一樣，重開機也還是無法訪問)：

```
ln -s ${path_to_latest_kcptun}/kcptun-20181226/client_darwin_amd64 ~/Library/Application\ Support/ShadowsocksX-NG/plugins/kcptun
```

問題：Mac 客戶端要如何更新 kcptun？

> 順帶一問，如何更新 shadowsocks-libev client (`ss-local`?)

**Comment by alphayan** [comment]
更新kcptun client需要将[shadowsocks/kcptun](https://github.com/shadowsocks/kcptun/commit/84176a9ecb2011c270c91cbf3fdd9aa477de2e41)里面关于SIP300的提交合并到[xatic/kcptun](https://github.com/xtaci/kcptun/tree/master/client),然后使用`go build  client/*.go`重新构建程序

**Comment by luluman** [comment]
我根据你的方法确实可以使用最新的kcptun客户端，感谢你提供的方法。 @alphayan

**Comment by tkisme** [comment]
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import subprocess

print(os.environ)
env = os.environ
#kwg = [ii for i in env["SS_PLUGIN_OPTIONS"].split(';') for ii in i.split('=')]
kwg = []
for i in env["SS_PLUGIN_OPTIONS"].split(';'):
    ii=i.split('=')
    kwg.append('-'+ii[0])
    kwg.append(ii[1])

#os.execv("kcptun_v20170718/client_darwin_amd64","-l","")
print(kwg)
subprocess.call([
    "kcptun_v20170718/client_darwin_amd64",
    "-l",env["SS_LOCAL_HOST"]+":"+env["SS_LOCAL_PORT"],
    "-r",env["SS_REMOTE_HOST"]+":"+env["SS_REMOTE_PORT"],
    ]+kwg)
```

取名为kcptun_client,在kcptun_v20170718目录下，下载解压xtaci版本的kcptun文件，二进制文件名为client_darwin_amd64

```
chmod +x kcptun_client client_darwin_amd64
```

**Comment by yuki-xin** [comment]
@luluman 可以分享一下重新构建的客户端吗

**Comment by yuki-xin** [comment]
@tkisme 厉害了

**Comment by zyuyou** [comment]
@tkisme 牛逼!!

**Comment by huanglins** [comment]
@tkisme 请问下，这个新编辑的文件放在哪个位置呀

**Comment by tkisme** [comment]
@huanglins ~/library/Application Support/ShadowsocksX-NG/kcptun_v20170718目录下

**Comment by sjnhnp** [comment]
@tkisme 你好，我按照你的方法，但是我不能使用，log：

 2019-03-19 16:09:15 INFO: tcp port reuse enabled
 2019-03-19 16:09:15 INFO: udprelay enabled
 2019-03-19 16:09:15 INFO: udp port reuse enabled
plugins/kcptun: line 1: {rtf1ansiansicpg936cocoartf1671cocoasubrtf200: command not found
plugins/kcptun: line 2: syntax error near unexpected token `}'
plugins/kcptun: line 2: `{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}'
 2019-03-19 16:09:15 ERROR: plugin service exit unexpectedly

**Comment by Buffer2Disk** [comment]
> 更新kcptun client需要将[shadowsocks/kcptun](https://github.com/shadowsocks/kcptun/commit/84176a9ecb2011c270c91cbf3fdd9aa477de2e41)里面关于SIP300的提交合并到[xatic/kcptun](https://github.com/xtaci/kcptun/tree/master/client),然后使用`go build client/*.go`重新构建程序

请问直接使用https://github.com/shadowsocks/kcptun 来编译可以嘛？
为啥一定要合并到https://github.com/xtaci/kcptun/tree/master/client 里面来编译
