### ISSUE TITLE
更新gfwlist.txt无法访问github

### ISSUE THREAD

**Issue by coooliang** [shadowsocks/ShadowsocksX-NG#972]
使用https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
无法访问github

**Comment by wonder566** [comment]
+1，需要打开全局模式

**Comment by YYAppleFan** [comment]
-1，可以用啊，楼上清一波DNS缓存试试。

**Comment by pizzamx** [comment]
疑似同样问题，只能全局，但换了几个 gfwlist 都没用

**Comment by zhangchenkai** [comment]
> 不是有几个模式吗，全局、白名单、PAC、ACL

哪里有ACL模式？我的点右键只有pac和全局啊

**Comment by pizzamx** [comment]
> > 不是有几个模式吗，全局、白名单、PAC、ACL
> 
> 哪里有ACL模式？我的点右键只有pac和全局啊

我用的是一个分支，你可以看看：https://github.com/qinyuhang/ShadowsocksX-NG-R/releases
