### ISSUE TITLE
没有找到有效的shadowsocks配置二维码和链接（No valid shadowsocks configuration fof 2-D code and links were found）

### ISSUE THREAD

**Issue by xixiaoyou** [shadowsocks/ShadowsocksX-NG#973]
如题，屏幕上有高清的二维码或者是链接，总是会出现这个错误提醒，是什么原因？
if there are high-definition two-dimensional codes or links on the screen, there will always be such error. Why?

**Comment by xixiaoyou** [comment]
MacOS版本是10.13.2
The MacOS version is 10.13.2

**Comment by huangxiangrongphper** [comment]
你需要重新关闭软件,重新启动才行

**Comment by liangchen55** [comment]
> 你需要重新关闭软件，重新启动才行
重启软件也不行～～～oh，不知道是哪里除了问题

**Comment by huangxiangrongphper** [comment]
你可以加我微信 我可以帮你解决  HXR_DSG

**Comment by liangchen55** [comment]
> HXR_DSG

已加好友

**Comment by RunningShadow-007** [comment]
遇到同样的问题  楼主最后怎么解决的？在mbp上没问题，在imac上就出现这个问题了

**Comment by wgy6055** [comment]
同遇到这个问题，Mac mini

**Comment by HoZanDung** [comment]
同样遇到这个问题 怎么解决的
