### ISSUE TITLE
怎么才能指定特定的一组域名强制走vpn呢？

### ISSUE THREAD

**Issue by hancc** [shadowsocks/ShadowsocksX-NG#974]
怎么才能指定特定的一组域名强制走vpn呢？

**Comment by hancc** [comment]
或者全局模式下，指定GFW List+自定义列表不走vpn

**Comment by luvvien** [comment]
自定义pac吧

**Comment by hancc** [comment]
才知道，原来SS本身PAC模式就支持
![image](https://user-images.githubusercontent.com/4936114/58618220-a26a0900-82f4-11e9-85ce-f5576004c070.png)
![image](https://user-images.githubusercontent.com/4936114/58618248-b281e880-82f4-11e9-9e33-7079f5daffee.png)

> 经过代理：||example.com
绕过代理：@@||example.com

具体请参照：https://adblockplus.org/filter-cheatsheet
