### ISSUE TITLE
ping 服务去哪里了呢？希望能够增加一个ping功能，要不然无法判定节点是否有效

### ISSUE THREAD

**Issue by zhangweijie666** [shadowsocks/ShadowsocksX-NG#979]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by luvvien** [comment]
有ping功能啊 [一键ss/ssr](https://vien.tech/article/122) 这篇文章底部的下载链接下载的，
![ping](https://user-images.githubusercontent.com/18453820/54580116-a13d7580-4a41-11e9-9cb6-525a043b4e4a.png)

**Comment by qiuyuzhou** [comment]
以前实现的ping 功能有概率会造成crash，已经去掉了
