### ISSUE TITLE
maxos 10.14 无法打开

### ISSUE THREAD

**Issue by lovingcodesk** [shadowsocks/ShadowsocksX-NG#981]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: [e.g. 10.13.1]

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Additional context**

**Comment by imxintian** [comment]
+1,mac10.14无反应，没发使用

**Comment by OBKoro1** [comment]
mac10.14 各选项都填了，下面框框抖动一下，就没有反应了。 
![image](https://user-images.githubusercontent.com/24698201/51533485-f9ab2900-1e7d-11e9-8b80-c763fdbc54df.png)

**Comment by huokailihappy** [comment]
+2,mac10.14无反应，无法使用

**Comment by fatezeronight** [comment]
10.14.3连不上，ios和windows都可以

**Comment by zhaolion** [comment]
老款 MBP(10.12)  使用相同的版本和服务器配置下面可以工作，但是新 iMAC 在 10.14 下面任何模式都不工作

**Comment by BertieJim** [comment]
> the same
> here is my log:
> 2019-01-27 23:00:43 INFO: listening at 127.0.0.1:1086
> 2019-01-27 23:14:13 INFO: initializing ciphers... aes-256-cfb
> 2019-01-27 23:14:13 INFO: listening at 127.0.0.1:1086
> 2019-01-27 23:14:17 ERROR: getpeername: Invalid argument
> 2019-01-27 23:14:18 ERROR: getpeername: Invalid argument
> 2019-01-27 23:14:18 ERROR: getpeername: Invalid argument
> 2019-01-27 23:14:18 ERROR: getpeername: Invalid argument

搞定了 改了端口

**Comment by JinPengCN** [comment]
> > the same
> > here is my log:
> > 2019-01-27 23:00:43 INFO: listening at 127.0.0.1:1086
> > 2019-01-27 23:14:13 INFO: initializing ciphers... aes-256-cfb
> > 2019-01-27 23:14:13 INFO: listening at 127.0.0.1:1086
> > 2019-01-27 23:14:17 ERROR: getpeername: Invalid argument
> > 2019-01-27 23:14:18 ERROR: getpeername: Invalid argument
> > 2019-01-27 23:14:18 ERROR: getpeername: Invalid argument
> > 2019-01-27 23:14:18 ERROR: getpeername: Invalid argument
> 
> 搞定了 改了端口

怎么改？求教

**Comment by frankli0324** [comment]
worked out, nevermind系列

**Comment by BertieJim** [comment]
统一回复...就是随便换了个端口
