### ISSUE TITLE
频繁提示：“proxy_conf_helper”正在尝试修改系统网络配置

### ISSUE THREAD

**Issue by TothingWay** [shadowsocks/ShadowsocksX-NG#983]
**Describe the bug**
频繁提示：“proxy_conf_helper”正在尝试修改系统网络配置

**To Reproduce**
软件启动/退出、打开/关闭ShadowSocks、切换状态等操作都会弹出输入密码的窗口

**Expected behavior**
不弹出输入密码窗口

**Screenshots**
![e9061ae6-c50b-49f3-8261-98a8d52dad65](https://user-images.githubusercontent.com/15687309/51811778-955af000-22e9-11e9-86d0-76994f708fe4.png)

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 10.14.2
 - Version 1.8.2 (1)

**Comment by kcilcarus** [comment]
我也遇到这个问题，查了下日志。
`Succeeded authorizing right 'system.services.systemconfiguration.network' by client '/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/Helpers/SCHelper' [1373] for authorization created by '/Library/Application Support/ShadowsocksX-NG/proxy_conf_helper' [1372] (3,0) (engine 87)`

把这个目录删了 重启应用就好了/Library/Application Support/ShadowsocksX-NG/

猜测是迁移系统的时候出的问题

**Comment by TothingWay** [comment]
我更新了一次版本，解决了

**Comment by gigamzus** [comment]
我用的是ShadowsocksX-NG-R8, 我迁移过系统, 出了同样问题, 但删了 /Library/Application Support/ShadowsocksX-NG/, 也不解决问题. 迁移前没有问题. 

我现在用ShadowsocksX-NG Version 1.8.2 (1). 没问题. 但需要混淆的SSR用不了了. 

求救 ShadowsocksX-NG-R8 咋办?

**Comment by muchild** [comment]
mac上
rm -rf /Library/Application\ Support/ShadowsocksX-NG
亲测，可以解决问题

**Comment by BryanSharp** [comment]
> mac上
> rm -rf /Library/Application\ Support/ShadowsocksX-NG
> 亲测，可以解决问题

多谢 解决了 原理是什么？

**Comment by kinzun** [comment]
我也是迁移后出现的。
删除家目录下的 .ShadowsocksX-NG/ 隐藏文件夹
`rm -rf .ShadowsocksX-NG/`

**Comment by weidongjian** [comment]
> mac上
> rm -rf /Library/Application\ Support/ShadowsocksX-NG
> 亲测，可以解决问题

rm -rf /Library/Application\ Support/ShadowsocksX-NG
rm: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper: Permission denied
rm: /Library/Application Support/ShadowsocksX-NG: Permission denied
提示没权限，怎么处理

**Comment by austin615** [comment]
> > mac上
> > rm -rf /Library/Application\ Support/ShadowsocksX-NG
> > 亲测，可以解决问题
> 
> rm -rf /Library/Application\ Support/ShadowsocksX-NG
> rm: /Library/Application Support/ShadowsocksX-NG/proxy_conf_helper: Permission denied
> rm: /Library/Application Support/ShadowsocksX-NG: Permission denied
> 提示没权限，怎么处理

加sudo
sudo rm -rf /Library/Application\ Support/ShadowsocksX-NG

**Comment by panol** [comment]
之前用了cleanMyMac,后面就一直有这个问题.
按照如上方法删除没用(我用的是vilavpn)
用cleanMyMac写在了vilavpn之后再重装就可以

**Comment by VVangyingqi** [comment]
> 之前用了cleanMyMac,后面就一直有这个问题. 按照如上方法删除没用(我用的是vilavpn) 用cleanMyMac写在了vilavpn之后再重装就可以

大佬你好!!我也是用了cleanMyMac之后就这样了，每次挂、改VPN节点都会要输入密码。能细说一下具体操作吗，拜托！🙏🏻

**Comment by VVangyingqi** [comment]
> sudo rm -rf /Library/Application\ Support/ShadowsocksX-NG



> 之前用了cleanMyMac,后面就一直有这个问题. 按照如上方法删除没用(我用的是vilavpn) 用cleanMyMac写在了vilavpn之后再重装就可以

按你的方法已解决，感谢！
