### ISSUE TITLE
release上只有单个应用程序没有dmg安装程序怎么安装？

### ISSUE THREAD

**Issue by cyk9944** [shadowsocks/ShadowsocksX-NG#984]
https://github.com/shadowsocks/ShadowsocksX-NG/releases/    比如mac上应该是通过dmg安装程序，但这里下载直接打开就一个1.8.2版本的25m的应用程序，

win下https://github.com/shadowsocks/shadowsocks-windows/releases 也应该是一个安装程序，但这也只是个4.1.4的exe单文件， 

电脑上客户端实际安装程序该怎么下载啊？不好意思懵逼了，以前我记得下载是个完整的应用程序进行安装的。。。然后今天vultr 日本机房上不去了，ping通的，有大神知道该怎么办吗

**Comment by cyk9944** [comment]
已解决。。。单文件下载就能用了

**Comment by oyb001** [comment]
楼上的同学，mac os系统没有dmg文件，你是如何安装的，难道是自己编译一个dmg文件吗？

**Comment by jkpang** [comment]
> 楼上的同学，mac os系统没有dmg文件，你是如何安装的，难道是自己编译一个dmg文件吗？

下载后直接解压，然后移动至“应用程序”文件夹就行了 @oyb001 

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by oyb001** [comment]
@jkpang ,还是不行呀，我把解压的文件移动至应用程序目录/Applications/ShadowsocksX-NG-1.8.2/ShadowsocksX-NG，然后安装，但是无法允许，也不知道是在哪里配置vpn连接信息的。
szitdembp-oyb:ShadowsocksX-NG ouyangbin$ sh install_
install_helper.sh    install_privoxy.sh   install_ss_local.sh  
szitdembp-oyb:ShadowsocksX-NG ouyangbin$ sh install_ss_local.sh 
ngdir: /Users/ouyangbin/Library/Application Support/ShadowsocksX-NG
done
szitdembp-oyb:ShadowsocksX-NG ouyangbin$ sh start_ss_local.sh 
chmod: /Users/ouyangbin/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist: No such file or directory
/Users/ouyangbin/Library/LaunchAgents/com.qiuyuzhou.shadowsocksX-NG.local.plist: No such file or directory
