### ISSUE TITLE
Mac ios都不能用

### ISSUE THREAD

**Issue by annie983284450** [shadowsocks/ShadowsocksX-NG#985]

**Comment by helloMike** [comment]
我也是一样啊!

**Comment by nepaul** [comment]
![wechatimg77](https://user-images.githubusercontent.com/1112181/52478537-9db40480-2be0-11e9-89c9-603386b396a1.jpeg)
mac 无法使用，报错MacOS error: -67062

**Comment by plotworld** [comment]
我的 版本 1.6.1 (1) ，可以链接，单无法访问google.com等这些网站。

**Comment by plotworld** [comment]
据说厂城升级了

**Comment by ganl** [comment]
使用正常

**Comment by zhoujingchao** [comment]
过年这段时间突然用不了了？？

**Comment by liaobamboo** [comment]
一样。
过年之前开始用不了，两台Mac，一台10.13.6，一台10.14.3都不能用。ShadowsocksX-NG +  Chrome, 之前一直好好用的。
安卓手机目前无问题。

**Comment by diong** [comment]
macOS 10.14.2 + ShadowsocksX-NG 1.8.2， 一样不能使用

**Comment by diong** [comment]
我换个端口就可以了，大家可以试试

**Comment by sd1435728** [comment]
不能用，好头疼

**Comment by jackhmy** [comment]
我这里443端口不行，换一个可以了

**Comment by Yanphet** [comment]
> 我换个端口就可以了，大家可以试试

请问你换的是ss的端口吗？

**Comment by zhoujingchao** [comment]
> > 我换个端口就可以了，大家可以试试
> 
> 请问你换的是ss的端口吗？

服务器端口默认443和444，换掉后，ss端口也跟着换掉就好了

**Comment by jackhmy** [comment]
> > 我换个端口就可以了，大家可以试试
> 
> 请问你换的是ss的端口吗？

是的

**Comment by hwy1782** [comment]
> 我换个端口就可以了，大家可以试试

我切换端口号之后也可以了

**Comment by AndrewLaBabies** [comment]
请问哪里改端口？
ShadowsocksX-NG的Preferences -> Advanced, 或者Preferences -> HTTP里改？

**Comment by Thyiad** [comment]
@hwy1782 请问你是怎么换端口的呀？我的服务端是用mritd/shadowsocks这个docker镜像搭的。。

**Comment by lhuafmaof** [comment]
怎么换端口
