### ISSUE TITLE
突然无法连上vpn了

### ISSUE THREAD

**Issue by koudai8** [shadowsocks/ShadowsocksX-NG#987]
今天打开shadowsocksX-NG 之后就无法连上vpn。日志如下：

默认	22:01:32.161232 +0800	useractivityd	DETERMINE: E59A2936-BA3C-49DE-9462-F7C5FA9B1601/<private> as the current item-to-advertise.
默认	22:01:39.118549 +0800	coreduetd	Location unknown
默认	22:01:39.118718 +0800	coreduetd	Not requesting location (2, <private>)
默认	22:01:39.118761 +0800	coreduetd	Saving new values: <private>
默认	22:01:39.440093 +0800	coreaudiod	gPTPClockStatistics for 0x39c986213d580000
默认	22:01:39.440150 +0800	coreaudiod	Grandmaster Identity: 0x39c986213d580000
默认	22:01:39.440173 +0800	coreaudiod	Clock lock state: Locked
默认	22:01:39.440216 +0800	coreaudiod	0x39c986213d580000: First Sync 2199023255552,2199023255552,45632118327,45632118327,0x39c986213d580000,0
默认	22:01:39.440250 +0800	coreaudiod	Rate Ratio: 2199023255552/2199023255552 (1.000000000000)
默认	22:01:39.440268 +0800	coreaudiod	Anchors: 45632118327, 45632118327
默认	22:01:39.440285 +0800	coreaudiod	Sync Identity: 0x39c986213d580000.0
默认	22:01:40.337036 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.
默认	22:01:43.896555 +0800	com.apple.WebKit.WebContent	Current memory footprint: 153 MB
默认	22:01:45.752390 +0800	WindowServer	pid 519 failed to act on a ping it dequeued before timing out.
默认	22:01:47.975018 +0800	useractivityd	-- Demoting self.advertisingProcess to nil (was UserActivityClient(pid=436/com.google.Chrome uuids={E59A2936-BA3C-49DE-9462-F7C5FA9B1601 })) and trigger pickNewAdvertisement because the previous advertisingProcess had a current activity.
默认	22:01:48.001157 +0800	useractivityd	DETERMINE: No item is being advertised, so removing any previously set of advertised items.
默认	22:01:55.235249 +0800	trustd	could not enable test hierarchy: no UAT pinning preferences set
默认	22:01:55.754820 +0800	WindowServer	pid 519 failed to act on a ping it dequeued before timing out.
默认	22:01:57.964416 +0800	ShadowsocksX-NG	LSExceptions shared instance invalidated for timeout.
默认	22:01:58.012435 +0800	MacKeeper	0x7fa54dcc1de0 - PerformanceMonitor::measureCPUUsageInActivityState: Process is using 0.0% CPU in state: VisibleNonActive
默认	22:02:01.379302 +0800	MacKeeper Helper	TIC TCP Conn Cancel [133:0x7f800f66df70]
默认	22:02:01.379477 +0800	MacKeeper Helper	[146 <private> stream, pid: 618, url: https://gw-zdt.zoomsupport.com/v4/notifications/token/eb944178ded8c07c17c46d36bf1f2ae535e67078ae34e19e6a9cd978eef419c2, tls] cancelled
	[146.1 342D896F-3BEC-400E-878A-186228F6CAC5 <private>.57896<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 62.289s, DNS @0.000s took 0.006s, TCP @0.007s took 0.421s, TLS took 0.870s
	bytes in/out: 5474/730, packets in/out: 6/3, rtt: 0.423s, retransmitted packets: 0, out-of-order packets: 2
默认	22:02:05.757628 +0800	WindowServer	pid 519 failed to act on a ping it dequeued before timing out.
默认	22:02:14.755653 +0800	trustd	could not disable pinning: not an internal release
默认	22:02:15.760308 +0800	WindowServer	pid 519 failed to act on a ping it dequeued before timing out.
默认	22:02:16.899856 +0800	com.apple.WebKit.WebContent	Current memory footprint: 153 MB

**Comment by liaobamboo** [comment]
Same happened here.

**Comment by zhangslob** [comment]
+1

**Comment by qq291462491** [comment]
+1

**Comment by youngcy** [comment]
PC客户端打开kcptun可使用，手机上为止，貌似移动网络是可以的，但是Wi-Fi不行

**Comment by xiong-it** [comment]
更换服务ip即可解决，亲测有效。

**Comment by luvvien** [comment]
现在封端口封ip，用[vultr](https://vien.tech/article/114)，随时可以删机器重新建，就能随时换ip
