### ISSUE TITLE
ShadowsocksX-NG 不能使用，找不到原因，求解答

### ISSUE THREAD

**Issue by 798475323** [shadowsocks/ShadowsocksX-NG#988]
突然登陆不上去，然后又不太懂这方面的知识，自己乱捣鼓，很多设置可能设置错了，有懂这方面知识的大神可以帮忙解答一下吗？急

**Comment by 798475323** [comment]
Unable to load Info.plist exceptions (eGPUOverrides)

**Comment by liaobamboo** [comment]
我也是.
两台Mac同时发生。
手机端安卓的，正常使用。
Mac的是ssX-NG + chrome with SwitchyOmega

**Comment by 798475323** [comment]
我下载了AppCleaner,卸载了ss,试了下用Safari可以用了，但是chrome还是不能正常访问

**Comment by 798475323** [comment]
因为chrome插件的原因，把插件禁用就可以了

**Comment by Thyiad** [comment]
@798475323 什么插件禁用？

**Comment by 798475323** [comment]
> @ 798475323什么插件禁用？
我把采集图片的插件禁用了，我看其他人的经验，并不是某一个插件的原因，只要把chrome的插件禁用就可以了。我重新下载最新版本的插件后，插件也可以正常使用。有可能是插件没更新的原因

**Comment by luvvien** [comment]
[Outline](https://vien.tech/article/93)
[一键ss/ssr](https://vien.tech/article/122)
文章后面链接下载的没问题
