### ISSUE TITLE
点击应用后，应用未启动。

### ISSUE THREAD

**Issue by KIDJourney** [shadowsocks/ShadowsocksX-NG#99]
系统版本
MacOs Sierra 10.12(16A323)
应用版本
v1.3

尝试在应用程序打开 ShadowsocksX-NG后，ps -A中没有进程，活动监视器中没有启动记录。

直接在application/content 中启动会出现

      92290 illegal hardware instruction

如果还有什么需要我提供的信息，往告知。

日志文件
[log.txt](https://github.com/shadowsocks/ShadowsocksX-NG/files/538109/log.txt)

**Comment by KIDJourney** [comment]
这里是日志

**Comment by qiuyuzhou** [comment]
#89
