### ISSUE TITLE
portal.shadowsocks.nu无法访问

### ISSUE THREAD

**Issue by hanxiaofeng** [shadowsocks/ShadowsocksX-NG#991]
无法访问此网站 portal.shadowsocks.nu 的响应时间过长。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_CONNECTION_TIMED_OUT

**Comment by BulldogX** [comment]
使用全局模式可以正常打开的；
另外他们更换了地址：https://secure.shadowsocks.nu ，试下这个

**Comment by hanxiaofeng** [comment]
@BulldogX 多谢
