### ISSUE TITLE
ss-netconfig频繁提示

### ISSUE THREAD

**Issue by jiexingtianxia** [shadowsocks/ShadowsocksX-NG#992]
**Describe the bug**
ss-netconfig频繁提示，每次输入好几次密码

**Screenshots**
<img width="435" alt="2019-02-12 13 23 21" src="https://user-images.githubusercontent.com/12974992/52614496-ce3fbb00-2ecc-11e9-8218-80b6044fa37a.png">

**Comment by qiuyuzhou** [comment]
这不是这个软件
