### ISSUE TITLE
kcptun插件选项不生效

### ISSUE THREAD

**Issue by sanlengjingvv** [shadowsocks/ShadowsocksX-NG#993]
**Describe the bug**
设置的 kcptun 插件选项 ，和日志里的不一致

**To Reproduce**
1. 升级到 ShadowsocksX-NG 1.8.2
2. 下载 kcptun-darwin-amd64-20190109 替换  `~/Library/Application Support/ShadowsocksX-NG/plugins` 里的文件
3. 配置服务器后启动
插件：kcptun
插件选项： key=flewover1984;crypt=aes;mode=fast;mtu=1350;sndwnd=512;rcvwnd=512;datashard=10;parityshard=3;dscp=0;nocomp

**Expected behavior**
无法打开google，日志里的kcptun设置不对

**Screenshots**
![2019-02-13 12 02 26](https://user-images.githubusercontent.com/6478615/52687421-cfd0b800-2f8c-11e9-9be0-be2129a266b3.jpg)

**System and Shadowsocksx-NG version: (please complete the following information):**
 - OS Version: 10.13.6
 - Version 1.8.2

**ss-local.log**
> 2019/02/13 11:58:06 connection: 10.23.170.165:58518 -> 223.223.223.223:13445
2019/02/13 11:58:06 stream opened
2019/02/13 11:58:06 session normally closed
 2019-02-13 11:59:44 INFO: plugin "plugins/kcptun" enabled
 2019-02-13 11:59:44 INFO: initializing ciphers... aes-256-cfb
 2019-02-13 11:59:44 INFO: listening at 127.0.0.1:1086
 2019-02-13 11:59:44 INFO: tcp port reuse enabled
2019/02/13 11:59:44 version: 20190109
2019/02/13 11:59:44 initiating key derivation
2019/02/13 11:59:44 listening on: [::]:12948
2019/02/13 11:59:44 encryption: aes
2019/02/13 11:59:44 nodelay parameters: 0 30 2 1
2019/02/13 11:59:44 remote address: vps:29900
2019/02/13 11:59:44 sndwnd: 128 rcvwnd: 512
2019/02/13 11:59:44 compression: true
2019/02/13 11:59:44 mtu: 1350
2019/02/13 11:59:44 datashard: 10 parityshard: 3
2019/02/13 11:59:44 acknodelay: false
2019/02/13 11:59:44 dscp: 0
2019/02/13 11:59:44 sockbuf: 4194304
2019/02/13 11:59:44 keepalive: 10
2019/02/13 11:59:44 conn: 1
2019/02/13 11:59:44 autoexpire: 0
2019/02/13 11:59:44 scavengettl: 600
2019/02/13 11:59:44 snmplog: 
2019/02/13 11:59:44 snmpperiod: 60
2019/02/13 11:59:44 quiet: false
2019/02/13 11:59:45 re-connecting: createConn(): net.ResolveUDPAddr: lookup vps on 10.23.194.203:53: server misbehaving

**Comment by Hmyy** [comment]
你用的是两个不同分支的kcptun，下载的这个版本不支持从插件选项里面读参数

**Comment by tkisme** [comment]
#967 可以看看

**Comment by hugepower** [comment]
似乎目前只支持到 kcptun 的 2017 版本 https://github.com/shadowsocks/kcptun/releases

**Comment by qiuyuzhou** [comment]
Already upgrade. Release new version soon.
