### ISSUE TITLE
ShadowsocksX-NG 连接上但是无法上网问题

### ISSUE THREAD

**Issue by sunday2** [shadowsocks/ShadowsocksX-NG#994]
**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
10.12.6 
- Shadowsocksx-NG 
11.8.1

shadowsocksx-NG能连接上，但是翻不了墙.

部分日志如下：
Feb 13 14:06:52 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.Plugin.64): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:06:52 localhost com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.WebContent.6927): Path not allowed in target domain: type = pid, path = /System/Library/StagedFrameworks/Safari/SafariShared.framework/Versions/A/XPCServices/com.apple.Safari.ImageDecoder.xpc/Contents/MacOS/com.apple.Safari.ImageDecoder error = 147: The specified service did not ship in the requestor's bundle, origin = /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc
Feb 13 14:06:52 localhost com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.WebContent.6927): Path not allowed in target domain: type = pid, path = /System/Library/StagedFrameworks/Safari/SafariShared.framework/Versions/A/XPCServices/com.apple.Safari.SearchHelper.xpc/Contents/MacOS/com.apple.Safari.SearchHelper error = 147: The specified service did not ship in the requestor's bundle, origin = /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc
Feb 13 14:06:53 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.WebContent.Development): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:06:53 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.Plugin.32): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:06:53 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.WebContent): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:06:53 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.Plugin.64): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:06:53 localhost com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.WebContent.6928): Path not allowed in target domain: type = pid, path = /System/Library/StagedFrameworks/Safari/SafariShared.framework/Versions/A/XPCServices/com.apple.Safari.ImageDecoder.xpc/Contents/MacOS/com.apple.Safari.ImageDecoder error = 147: The specified service did not ship in the requestor's bundle, origin = /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc
Feb 13 14:06:53 localhost com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.WebContent.6928): Path not allowed in target domain: type = pid, path = /System/Library/StagedFrameworks/Safari/SafariShared.framework/Versions/A/XPCServices/com.apple.Safari.SearchHelper.xpc/Contents/MacOS/com.apple.Safari.SearchHelper error = 147: The specified service did not ship in the requestor's bundle, origin = /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc
Feb 13 14:06:56 localhost SCIM_Extension[1378]: notify name "KSTextReplacementDidChangeNotification" has been registered 20 times - this may be a leak
Feb 13 14:07:27 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.WebContent.Development): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:07:27 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.Plugin.32): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:07:27 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.WebContent): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:07:27 localhost com.apple.xpc.launchd[1] (com.apple.WebKit.Plugin.64): Unknown key for Boolean: _HighBitsASLR
Feb 13 14:07:27 localhost com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.WebContent.6932): Path not allowed in target domain: type = pid, path = /System/Library/StagedFrameworks/Safari/SafariShared.framework/Versions/A/XPCServices/com.apple.Safari.ImageDecoder.xpc/Contents/MacOS/com.apple.Safari.ImageDecoder error = 147: The specified service did not ship in the requestor's bundle, origin = /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc
Feb 13 14:07:27 localhost com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.WebContent.6932): Path not allowed in target domain: type = pid, path = /System/Library/StagedFrameworks/Safari/SafariShared.framework/Versions/A/XPCServices/com.apple.Safari.SearchHelper.xpc/Contents/MacOS/com.apple.Safari.SearchHelper error = 147: The specified service did not ship in the requestor's bundle, origin = /System/Library/StagedFrameworks/Safari/WebKit.framework/Versions/A/XPCServices/com.apple.WebKit.WebContent.xpc
Feb 13 14:09:33 localhost com.apple.xpc.launchd[1] (com.apple.quicklook[6942]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Feb 13 14:10:24 localhost UserEventAgent[39]: assertion failed: 16G29: com.apple.telemetry + 58408 [165E935B-9099-32D4-945F-270EC2E89A29]: 0x5
Feb 13 14:13:44 localhost com.apple.xpc.launchd[1] (com.apple.quicklook[6967]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Feb 13 14:14:14 localhost com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Feb 13 14:14:44 --- last message repeated 1 time ---
Feb 13 14:14:54 localhost com.apple.xpc.launchd[1] (com.apple.quicklook[7037]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Feb 13 14:15:35 localhost syslogd[38]: ASL Sender Statistics
Feb 13 14:18:56 localhost diagnosticd[5633]: System mode client started - Console (7087) - mode: 0x8
Feb 13 14:18:58 localhost Console[7087]: BUG in libdispatch client: kevent[EVFILT_VNODE] monitored resource vanished before the source cancel handler was invoked
Feb 13 14:19:05 localhost com.apple.xpc.launchd[1] (com.apple.quicklook[7088]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Feb 13 14:20:24 localhost UserEventAgent[39]: assertion failed: 16G29: com.apple.telemetry + 58408 [165E935B-9099-32D4-945F-270EC2E89A29]: 0x5
Feb 13 14:22:28 localhost com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[7004]): Service exited with abnormal code: 15
Feb 13 14:23:15 localhost com.apple.xpc.launchd[1] (com.apple.quicklook[7163]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Feb 13 14:24:17 localhost com.apple.xpc.launchd[1] (com.qiuyuzhou.shadowsocksX-NG.http[7122]): Service exited with abnormal code: 15
Feb 13 14:26:06 localhost syslogd[38]: ASL Sender Statistics
Feb 13 14:27:26 localhost com.apple.xpc.launchd[1] (com.apple.quicklook[7238]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Feb 13 14:30:16 localhost com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Feb 13 14:30:24 --- last message repeated 2 times ---
Feb 13 14:30:24 localhost UserEventAgent[39]: assertion failed: 16G29: com.apple.telemetry + 58408 [165E935B-9099-32D4-945F-270EC2E89A29]: 0x5
Feb 13 14:31:36 localhost com.apple.xpc.launchd[1] (com.apple.quicklook[7285]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.quicklook
Feb 13 14:33:34 localhost com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit

**Comment by jamesiter** [comment]
建议研究源码。很怀疑源码里面做了手脚。

**Comment by 823844596** [comment]
可以多换几个端口号试试。

**Comment by liuhill** [comment]
MACOS: 10.14.3
SSX-NG: 1.8.2(1)

ss-local.log
```
2019-02-15 23:40:12 INFO: tcp port reuse enabled
 2019-02-15 23:42:27 INFO: initializing ciphers... aes-256-ctr
 2019-02-15 23:42:27 INFO: listening at 127.0.0.1:1086
 2019-02-15 23:42:27 INFO: tcp port reuse enabled
 2019-02-15 23:52:13 INFO: initializing ciphers... aes-256-ctr
 2019-02-15 23:52:13 INFO: listening at 127.0.0.1:1086
 2019-02-15 23:52:13 INFO: tcp port reuse enabled
 2019-02-16 00:31:27 ERROR: Invalid config path.
 2019-02-16 00:31:41 INFO: initializing ciphers... aes-256-ctr
 2019-02-16 00:31:41 INFO: listening at 127.0.0.1:1086
 2019-02-16 00:31:41 INFO: tcp port reuse enabled
```

server 
```
[root@host ~]# tail -f /var/log/shadowsocks.log 
2019-02-15 11:36:51 INFO     connecting clients1.googl?N?15285 from 222.128.179.61:52714
2019-02-15 11:36:51 ERROR    invalid hostname: clients1.googl?N?when handling connection from 222.128.179.61:52714
2019-02-15 11:36:52 INFO     connecting clients1.googlo`?9:63411 from 222.128.179.61:52716
2019-02-15 11:36:52 ERROR    invalid hostname: clients1.googlo`?9 when handling connection from 222.128.179.61:52716
2019-02-15 11:37:22 INFO     connecting clients1.googl??
?}:52711 from 222.128.179.61:52718
2019-02-15 11:37:22 ERROR    invalid hostname: clients1.googl??
?} when handling connection from 222.128.179.61:52718
2019-02-15 11:37:22 INFO     connecting clients1.googl?????:12067 from 222.128.179.61:52720
2019-02-15 11:37:22 ERROR    invalid hostname: clients1.googl????? when handling connection from 222.128.179.61:52720

```

**Comment by zomliu** [comment]
@liuhill 
MACOS: 10.14.3 下，你这么解决不能用的问题了吗？
under MAC OS: 10.14.3, have you solved the not-work problem?  By deleting all ‘shadowsock’ files and re-installing

**Comment by jamesiter** [comment]
KcpTun 。多ss数据加一层封装，改变ss数据表的特征。

**Comment by liuhill** [comment]
@zomliu 
MacBook是这样解决了，
另外2个windows，通过更换端口号解决了。

> @liuhill
> MACOS: 10.14.3 下，你这么解决不能用的问题了吗？
> under MAC OS: 10.14.3, have you solved the not-work problem? By deleting all ‘shadowsock’ files and re-installing

**Comment by luvvien** [comment]
现在封端口封ip，可以用 [vultr](https://vien.tech/article/114) 封ip就换台机器，反正按时计费的。现在注册还送50刀
