### ISSUE TITLE
Integrate support for v2ray-plugin

### ISSUE THREAD

**Issue by zengxs** [shadowsocks/ShadowsocksX-NG#995]
<https://github.com/shadowsocks/v2ray-plugin>

**Comment by Mjollnirs** [comment]
You can download v2ray-plugin-darwin-amd64-8cea1a3.tar.gz

> tar -xvf v2ray-plugin-darwin-amd64-8cea1a3.tar.gz

Rename v2ray-plugin and copy to $HOME/Library/Application Support/ShadowsocksX-NG/plugins/.

**Comment by zengxs** [comment]
Now we can use homebrew to install it:
~~~
brew install v2ray-plugin
~~~

**Comment by Mjollnirs** [comment]
Already supported by https://github.com/shadowsocks/ShadowsocksX-NG/pull/1001

**Comment by norcm** [comment]
i  already installed the plugin, but how can i configurate the server configeration to use this plugin. windows can input the plugin name from here, how macOS?
![image](https://user-images.githubusercontent.com/24206966/59187101-2e0e5000-8ba7-11e9-8187-87f143280c2a.png)

**Comment by smart-z** [comment]
> 我已经安装了插件，但是如何配置服务器配置以使用此插件。Windows可以从这里输入插件名称，怎么用macOS？
> ![图片](https://user-images.githubusercontent.com/24206966/59187101-2e0e5000-8ba7-11e9-8187-87f143280c2a.png)

兄弟，你mac会用了吗？

**Comment by ericellis7** [comment]
> 我已经安装了插件，但是如何配置服务器配置以使用此插件。Windows可以从这里输入插件名称，怎么用macOS？
> ![图片](https://user-images.githubusercontent.com/24206966/59187101-2e0e5000-8ba7-11e9-8187-87f143280c2a.png)

你好，Mac这个该如何填写插件选项以及插件程序呢？
