### ISSUE TITLE
如何反向使用，只对大陆听歌软件使用？

### ISSUE THREAD

**Issue by NaiveVincent** [shadowsocks/ShadowsocksX-NG#997]
坐标海外，想只对网易云音乐走搭建的国内服务器，其他不走SS，该如何实现？

**Comment by NaiveVincent** [comment]
how to only apply on Chinese music applications ?

**Comment by nagatoism** [comment]
unblock youku

**Comment by ismejun** [comment]
自定义规则呗，把网易云音乐的域名或者ip加进去

**Comment by NaiveVincent** [comment]
> 自定义规则呗，把网易云音乐的域名或者ip加进去

谢谢。后来发现卡在了建立国内服务器上。谷歌云没有大陆节点。就没折腾了。
